sister_info = {'alb' : {'temp': 'ash', 'lwet': 'ash', 'rhum': 'ash', 'prcp': 'ash', 'wspd': 'ash', 'wdir': 'ash', 'srad': 'kno'},
'noa' : {'temp': 'som', 'lwet': 'som', 'rhum': 'som', 'prcp': 'som', 'wspd': 'som', 'wdir': 'som', 'srad': 'som'},
'soa' : {'temp': 'som', 'lwet': 'som', 'rhum': 'som', 'prcp': 'som', 'wspd': 'som', 'wdir': 'som', 'srad': 'som'},
'ark' : {'temp': 'kdsv', 'rhum': 'kdsv', 'prcp': 'kdsv'},
'arm' : {'temp': 'kdsv', 'lwet': 'way', 'rhum': 'kdsv', 'prcp': 'kdsv', 'wspd': 'kdsv', 'wdir': 'kdsv', 'srad': 'way'},
'ash' : {'temp': 'alb', 'lwet': 'alb', 'rhum': 'alb', 'prcp': 'alb', 'wspd': 'alb', 'wdir': 'alb', 'srad': 'kno'},
'aur' : {'temp': 'cu_gfr', 'rhum': 'cu_gfr', 'lwet': 'var', 'prcp': 'cu_gfr', 'wspd': 'cu_gfr', 'wdir': 'cu_gfr', 'srad': 'cu_gfr'},
'bal' : {'temp': 'ksyr', 'rhum': 'ksyr', 'prcp': 'ksyr', 'wspd': 'ksyr', 'wdir': 'ksyr', 'lwet': 'laf', 'srad': 'aur'},
'bla' : {'temp': 'bal', 'rhum': 'bal', 'prcp': 'bal', 'wspd': 'bal', 'wdir': 'bal', 'lwet': 'bal', 'srad': 'bal'},
'bar' : {'temp': 'pul', 'lwet': 'pul', 'prcp': 'pul'},
'bat' : {'temp': 'pav', 'lwet': 'alb', 'rhum': 'alb', 'prcp': 'pav', 'st4i': 'pav'},
'bra' : {'temp': 'pul', 'lwet': 'pul', 'rhum': 'pul', 'prcp': 'pul'},
'brh' : {'temp': 'khwv', 'rhum': 'khwv', 'prcp': 'khwv', 'wspd': 'khwv', 'wdir': 'khwv', 'lwet': 'riv', 'srad': 'riv'},
'bri' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'lwet': 'wmi', 'srad': 'cut'},
'but' : {'temp': 'bal', 'lwet': 'bal', 'rhum': 'bal', 'prcp': 'bal', 'wspd': 'bal', 'wdir': 'bal', 'srad': 'bal'},
'cas' : {'temp': 'kalb', 'rhum': 'kalb', 'prcp': 'kalb', 'wspd': 'kalb', 'wdir': 'kalb', 'srad': 'hud', 'lwet': 'hud'},
'cer' : {'temp': 'kelz', 'rhum': 'kelz', 'prcp': 'kelz', 'wspd': 'kelz', 'wdir': 'kelz'},
'chz' : {'temp': 'vso', 'rhum': 'vso', 'prcp': 'vso', 'wspd': 'vso', 'wdir': 'vso', 'lwet': 'vso', 'srad': 'vso'},
'czy' : {'temp': 'vso', 'rhum': 'vso', 'prcp': 'vso', 'wspd': 'vso', 'wdir': 'vso', 'lwet': 'vso', 'srad': 'vso'},
'cli' : {'temp': 'kalb', 'rhum': 'kalb', 'prcp': 'kalb', 'wspd': 'kalb', 'wdir': 'kalb', 'lwet': 'gui', 'srad': 'gui'},
'clw' : {'temp': 'cln', 'rhum': 'cln', 'prcp': 'cln', 'wspd': 'cln', 'wdir': 'cln', 'lwet': 'cln', 'srad': 'hig'},
'cln' : {'temp': 'clw', 'lwet': 'clw', 'rhum': 'clw', 'prcp': 'clw', 'wspd': 'clw', 'wdir': 'clw', 'srad': 'hig'},
'cro' : {'temp': 'vsh', 'rhum': 'vsh', 'prcp': 'vsh', 'wspd': 'vsh', 'wdir': 'vsh', 'srad': 'vsh', 'lwet': 'vsh'},
'cns' : {'temp': 'kfok', 'lwet': 'cut', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'srad': 'cut'},
'cut' : {'temp': 'kfok', 'lwet': 'mat', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'srad': 'cns'},
'dre' : {'temp': 'gen', 'lwet': 'gen', 'prcp': 'gen'},
'drs' : {'temp': 'kpeo', 'rhum': 'kpeo', 'prcp': 'kpeo', 'wspd': 'kpeo', 'wdir': 'kpeo', 'lwet': 'gbe', 'srad': 'gbe'},
'dun' : {'temp': 'kpeo', 'rhum': 'kpeo', 'prcp': 'kpeo', 'wspd': 'kpeo', 'wdir': 'kpeo', 'lwet': 'bar', 'srad': 'wla'},
'ede' : {'temp': 'kbuf', 'rhum': 'kbuf', 'prcp': 'kbuf', 'lwet': 'bat'},
'elb' : {'temp': 'alb', 'lwet': 'alb', 'rhum': 'alb', 'prcp': 'alb', 'wspd': 'alb', 'wdir': 'alb', 'srad': 'alb'},
'far' : {'temp': 'gbe', 'lwet': 'gbe', 'rhum': 'gbe', 'prcp': 'gbe', 'wspd': 'gbe', 'wdir': 'gbe', 'srad': 'gbe'},
'fay' : {'temp': 'gen', 'rhum': 'gen', 'prcp': 'gen', 'wspd': 'var', 'wdir': 'var', 'lwet': 'gen', 'srad': 'var'},
'1fr' : {'temp': 'kdkk', 'rhum': 'kdkk', 'prcp': 'kdkk', 'wspd': 'kdkk', 'wdir': 'kdkk', 'lwet': 'ede', 'st4i': 'pav', 'srad': 'loc'},
'fre' : {'temp': 'cu_gfr', 'rhum': 'cu_gfr', 'prcp': 'cu_gfr', 'wspd': 'cu_gfr', 'srad': 'cu_gfr', 'wdir': 'cu_gfr', 'lwet': 'ith'},
'fri' : {'temp': 'pot', 'lwet': 'pot', 'prcp': 'pot'},
'fts' : {'temp': 'kisp', 'rhum': 'kisp', 'prcp': 'kisp', 'wspd': 'kisp', 'wdir': 'kisp', 'lwet': 'brh', 'srad': 'brh'},
'gai' : {'temp': 'kdsv', 'rhum': 'kdsv', 'prcp': 'kdsv'},
'gbe' : {'temp': 'gen', 'rhum': 'gen', 'prcp': 'gen', 'wspd': 'fay', 'wdir': 'fay', 'lwet': 'gen', 'srad': 'drs'},
'gen' : {'temp': 'far', 'lwet': 'far', 'rhum': 'far', 'prcp': 'far', 'st4i': 'cu_aur'},
'gfr' : {'temp': 'cu_gfr', 'lwet': 'ith', 'prcp': 'cu_gfr', 'rhum': 'cu_gfr', 'wspd': 'cu_gfr', 'wdir': 'cu_gfr', 'srad': 'cu_gfr'},
'gra' : {'temp': 'kgfl', 'rhum': 'kgfl', 'prcp': 'kgfl', 'wspd': 'kgfl', 'wdir': 'kgfl', 'lwet': 'ved', 'srad': 'ved'},
'gro' : {'temp': 'kdsv', 'rhum': 'kdsv', 'prcp': 'kdsv'},
'gui' : {'temp': 'kalb', 'rhum': 'kalb', 'prcp': 'kalb', 'wspd': 'kalb', 'wdir': 'kalb', 'lwet': 'cli', 'srad': 'cli'},
'har' : {'temp': 'keri', 'rhum': 'keri', 'prcp': 'keri', 'wspd': 'keri', 'wdir': 'keri', 'lwet': 'por', 'srad': 'por'},
'hig' : {'temp': 'cln', 'lwet': 'cln', 'rhum': 'cln', 'prcp': 'cln', 'wspd': 'cln', 'wdir': 'cln', 'srad': 'clw'},
'him' : {'temp': 'lod', 'lwet': 'lod', 'prcp': 'lod'},
'hud' : {'temp': 'cas', 'lwet': 'cas', 'rhum': 'cas', 'prcp': 'cas', 'wspd': 'cu_val', 'wdir': 'cu_val', 'srad': 'cas'},
'ith' : {'temp': 'cu_gfr', 'prcp': 'cu_gfr', 'lwet': 'fre', 'rhum': 'cu_gfr', 'wspd': 'cu_gfr', 'wdir': 'cu_gfr', 'srad': 'ovi'},
'ken' : {'temp': 'alb', 'lwet': 'alb', 'rhum': 'alb', 'prcp': 'alb', 'wspd': 'alb', 'wdir': 'alb', 'srad': 'kno'},
'kno' : {'temp': 'alb', 'lwet': 'alb', 'rhum': 'alb', 'prcp': 'alb', 'wspd': 'alb', 'wdir': 'alb', 'srad': 'som'},
'laf' : {'temp': 'ksyr', 'rhum': 'ksyr', 'prcp': 'ksyr', 'wspd': 'ksyr', 'wdir': 'ksyr', 'lwet': 'fre', 'srad': 'bal'},
'lak' : {'temp': 'dun', 'rhum': 'dun', 'prcp': 'dun', 'wspd': 'dun', 'wdir': 'dun', 'lwet': 'dun', 'srad': 'dun'},
'lan' : {'temp': 'fre', 'lwet': 'fre', 'rhum': 'kith', 'prcp': 'fre', 'wspd': 'kith', 'srad': 'cu_gfr', 'wdir': 'kith'},
'1lo' : {'temp': 'loc', 'lwet': 'loc', 'rhum': 'loc', 'prcp': 'loc', 'wspd': 'loc', 'srad': 'loc', 'wdir': 'kiag'},
'lkp' : {'temp': 'kslk', 'rhum': 'kslk', 'lwet': 'per', 'prcp': 'kslk', 'wspd': 'kslk', 'wdir': 'kslk', 'srad': 'vso'},
'lod' : {'temp': 'los', 'lwet': 'los', 'rhum': 'los', 'prcp': 'los', 'wspd': 'los', 'wdir': 'los', 'srad': 'los'},
'los' : {'temp': 'lod', 'lwet': 'lod', 'rhum': 'lod', 'prcp': 'lod', 'wspd': 'lod', 'wdir': 'lod', 'srad': 'lod'},
'lol' : {'temp': 'los', 'lwet': 'los', 'rhum': 'los', 'prcp': 'los', 'wspd': 'los', 'wdir': 'los', 'srad': 'los'},
'lyn' : {'temp': 'wat', 'lwet': 'wat', 'rhum': 'wat', 'prcp': 'wat', 'wspd': 'ash', 'wdir': 'ash', 'srad': 'ash'},
'man' : {'temp': 'riv', 'rhum': 'riv', 'prcp': 'riv', 'wspd': 'riv', 'wdir': 'riv', 'lwet': 'riv', 'srad': 'riv'},
'mar' : {'temp': 'kpou', 'rhum': 'kpou', 'prcp': 'kpou', 'wspd': 'kpou', 'wdir': 'kpou', 'lwet': 'cln', 'srad': 'hig'},
'mat' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'lwet': 'rvp', 'srad': 'cut'},
'med' : {'temp': 'lyn', 'lwet': 'lyn', 'rhum': 'lyn', 'prcp': 'lyn', 'wspd': 'lyn', 'wdir': 'lyn', 'srad': 'som'},
'mex' : {'temp': 'scr', 'lwet': 'scr', 'prcp': 'scr'},
'mod' : {'temp': 'kpou', 'lwet': 'clw', 'rhum': 'kpou', 'prcp': 'kpou', 'wspd': 'kpou', 'wdir': 'kpou', 'srad': 'clw'},
'mtd' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'lwet': 'rvp', 'srad': 'cut'},
'mts' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'lwet': 'rvp', 'srad': 'cut'},
'nap' : {'temp': 'fri', 'lwet': 'fri', 'prcp': 'fri'},
'nea' : {'temp': 'cli', 'rhum': 'cli', 'prcp': 'cli', 'wspd': 'cli', 'wdir': 'cli', 'lwet': 'cli', 'srad': 'cli'},
'nee' : {'temp': 'nel', 'rhum': 'nel', 'prcp': 'nel', 'wspd': 'nel', 'wdir': 'nel', 'lwet': 'nel', 'srad': 'poe'},
'nel' : {'temp': 'nee', 'rhum': 'nee', 'prcp': 'nee', 'wspd': 'nee', 'wdir': 'nee', 'lwet': 'nee', 'srad': 'nee'},
'npt' : {'temp': 'kisp', 'rhum': 'kisp', 'prcp': 'kisp', 'wspd': 'kisp', 'wdir': 'kisp', 'lwet': 'brh', 'srad': 'brh'},
'ovi' : {'temp': 'lol', 'rhum': 'lol', 'prcp': 'lol', 'wspd': 'lol', 'wdir': 'lol', 'lwet': 'lol', 'srad': 'lol'},
'pav' : {'temp': 'bat', 'prcp': 'bat', 'st4i': 'bat'},
'per' : {'temp': 'chz', 'rhum': 'chz', 'prcp': 'chz', 'wspd': 'chz', 'wdir': 'chz', 'srad': 'vsh', 'lwet': 'chz'},
'por' : {'temp': 'kdkk', 'rhum': 'kdkk', 'prcp': 'kdkk', 'wspd': 'kdkk', 'wdir': 'kdkk', 'lwet': 'loc', 'srad': 'poe'},
'pr5' : {'temp': 'por', 'rhum': 'por', 'prcp': 'por', 'wspd': 'por', 'wdir': 'por', 'srad': 'por', 'lwet': 'por'},
'poe' : {'temp': 'por', 'rhum': 'por', 'prcp': 'por', 'wspd': 'por', 'wdir': 'por', 'srad': 'por', 'lwet': 'por'},
'pot' : {'temp': 'fri', 'lwet': 'fri', 'prcp': 'fri', 'rhum': 'kpeo'},
'pra' : {'temp': 'pul', 'rhum': 'pul', 'prcp': 'pul'},
'pul' : {'temp': 'bra', 'lwet': 'bra', 'rhum': 'bra', 'prcp': 'bra'},
'loc' : {'temp': 'soa', 'lwet': 'soa', 'rhum': 'soa', 'prcp': 'soa', 'wspd': 'soa', 'srad': 'soa'},
'red' : {'temp': 'kpou', 'rhum': 'kpou', 'prcp': 'kpou', 'lwet': 'hud', 'wspd': 'kpou', 'wdir': 'kpou', 'srad': 'hud'},
'rip' : {'temp': 'por', 'rhum': 'por', 'prcp': 'por', 'lwet': 'por', 'wspd': 'por', 'wdir': 'por', 'srad': 'por'},
'riv' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'lwet': 'rvp', 'wspd': 'kfok', 'wdir': 'kfok', 'srad': 'cut'},
'rvm' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'lwet': 'riv', 'wspd': 'kfok', 'wdir': 'kfok', 'srad': 'cut'},
'rvp' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'lwet': 'riv', 'wspd': 'kfok', 'wdir': 'kfok', 'srad': 'cut'},
'rom' : {'temp': 'var', 'rhum': 'var', 'prcp': 'var', 'wspd': 'var', 'wdir': 'var', 'lwet': 'var', 'srad': 'var'},
'sav' : {'temp': 'gen', 'rhum': 'gen', 'prcp': 'gen'},
'scr' : {'temp': 'kfzy', 'lwet': 'laf', 'prcp': 'kfzy', 'rhum': 'kfzy', 'wspd': 'kfzy', 'wdir': 'kfzy', 'srad': 'wol'},
'sdl' : {'temp': 'sod', 'lwet': 'sod', 'rhum': 'sod', 'prcp': 'sod', 'wspd': 'sod', 'wdir': 'sod', 'srad': '3wi'},
'shc' : {'temp': 'kfok', 'lwet': 'shd', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'srad': 'cut'},
'shd' : {'temp': 'kfok', 'lwet': 'mat', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'srad': 'cut'},
'shm' : {'temp': 'kfok', 'lwet': 'shd', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'srad': 'cut'},
'she' : {'temp': 'sil', 'lwet': 'sil', 'rhum': 'sil', 'prcp': 'sil', 'wspd': 'sil', 'wdir': 'sil', 'srad': 'sil'},
'sil' : {'temp': 'she', 'lwet': 'she', 'rhum': 'she', 'prcp': 'she', 'wspd': 'she', 'wdir': 'she', 'srad': 'por'},
'sod' : {'temp': 'sdl', 'lwet': 'sdl', 'rhum': 'sdl', 'prcp': 'sdl', 'wspd': 'sdl', 'wdir': 'sdl', 'srad': 'sdl'},
'som' : {'temp': 'noa', 'lwet': 'noa', 'rhum': 'noa', 'prcp': 'noa', 'wspd': 'noa', 'wdir': 'noa', 'srad': 'noa'},
'val' : {'temp': 'wgl', 'lwet': 'wgl', 'rhum': 'wgl', 'prcp': 'wgl'},
'var' : {'temp': 'fay', 'rhum': 'fay', 'prcp': 'fay', 'wspd': 'fay', 'wdir': 'fay', 'lwet': 'fay', 'srad': 'aur'},
'vca' : {'temp': 'kmpv', 'rhum': 'kmpv', 'prcp': 'kmpv', 'wspd': 'kmpv', 'wdir': 'kmpv', 'lwet': 'vsb', 'srad': 'vsb'},
'vdu' : {'temp': 'vpu', 'rhum': 'vpu', 'prcp': 'vpu', 'wspd': 'vpu', 'wdir': 'vpu', 'lwet': 'vpu', 'srad': 'vpu'},
'ver' : {'temp': 'sil', 'lwet': 'sil', 'rhum': 'sil', 'prcp': 'sil', 'wspd': 'sil', 'wdir': 'sil', 'srad': 'sil'},
'vsb' : {'temp': 'kbtv', 'rhum': 'kbtv', 'prcp': 'kbtv', 'wspd': 'kbtv', 'wdir': 'kbtv', 'lwet': 'vso', 'srad': 'vso'},
'vsh' : {'temp': 'krut', 'rhum': 'krut', 'prcp': 'krut', 'wspd': 'krut', 'wdir': 'krut', 'lwet': 'cro', 'srad': 'ved'},
'vso' : {'temp': 'kbtv', 'rhum': 'kbtv', 'prcp': 'kbtv', 'wspd': 'kbtv', 'wdir': 'kbtv', 'lwet': 'vsb', 'srad': 'vsb'},
'ved' : {'temp': 'krut', 'rhum': 'krut', 'prcp': 'krut', 'wspd': 'krut', 'wdir': 'krut', 'lwet': 'gra', 'srad': 'vsh'},
'vpu' : {'temp': 'um_clk', 'rhum': 'um_clk', 'prcp': 'um_clk', 'wspd': 'um_clk', 'wdir': 'um_clk', 'lwet': 'um_clk', 'srad': 'hwa'},
'wat' : {'temp': 'ash', 'lwet': 'ash', 'rhum': 'ash', 'prcp': 'ash', 'wspd': 'ash', 'wdir': 'ash'},
'wgl' : {'temp': 'wla', 'rhum': 'wla', 'prcp': 'wla', 'wspd': 'wla', 'wdir': 'wla', 'lwet': 'wla', 'srad': 'wla'},
'wad' : {'temp': 'khwv', 'rhum': 'khwv', 'prcp': 'khwv', 'lwet': 'riv', 'wspd': 'khwv', 'wdir': 'khwv', 'srad': 'cut'},
'wla' : {'temp': 'wgl', 'rhum': 'wgl', 'prcp': 'wgl', 'wspd': 'los', 'wdir': 'los', 'lwet': 'wgl', 'srad': 'los'},
'wlb' : {'temp': 'vsb', 'rhum': 'vsb', 'prcp': 'vsb', 'wspd': 'vsb', 'wdir': 'vsb', 'lwet': 'vsb', 'srad': 'vsb'},
'way' : {'temp': 'kdsv', 'rhum': 'kdsv', 'prcp': 'kdsv', 'wspd': 'kdsv', 'srad': 'drs'},
'wmi' : {'temp': 'kmtp', 'lwet': 'cut', 'rhum': 'kmtp', 'prcp': 'kmtp', 'wspd': 'kmtp', 'wdir': 'kmtp', 'srad': 'cut'},
'wmn' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok', 'lwet': 'wmi', 'srad': 'cut'},
'wol' : {'temp': '1wi', 'lwet': '1wi', 'rhum': '1wi', 'prcp': '1wi', 'wspd': '1wi', 'wdir': '1wi', 'srad': 'sdl'},
'1wi' : {'temp': '3wi', 'lwet': '3wi', 'rhum': '3wi', 'prcp': '3wi'},
'2wi' : {'temp': '1wi', 'lwet': '1wi', 'rhum': '1wi', 'prcp': '1wi', 'wspd': '3wi', 'wdir': '3wi', 'srad': 'sdl'},
'3wi' : {'temp': '1wi', 'lwet': '1wi', 'rhum': '1wi', 'prcp': '1wi', 'wspd': 'sod', 'wdir': 'sod', 'srad': 'sdl'},
'avo' : {'temp': 'kroc', 'rhum': 'kroc', 'prcp': 'kroc'},
'sho' : {'temp': 'cro', 'rhum': 'cro', 'prcp': 'cro', 'wspd': 'cro', 'wdir': 'cro', 'lwet': 'cro', 'srad': 'cro'},
'mty' : {'temp': 'klwm', 'rhum': 'klwm', 'prcp': 'klwm', 'wspd': 'klwm', 'wdir': 'klwm', 'lwet': 'um_tff', 'srad': 'mam'},
'mbe' : {'temp': 'msd', 'rhum': 'msd', 'prcp': 'msd', 'wspd': 'msd', 'wdir': 'msd', 'lwet': 'msd', 'srad': 'mwe'},
'msd' : {'temp': 'um_clk', 'rhum': 'um_clk', 'prcp': 'um_clk', 'wspd': 'um_clk', 'wdir': 'um_clk', 'lwet': 'um_clk', 'srad': 'mbe'},
'hwa' : {'temp': 'vpu', 'rhum': 'vpu', 'prcp': 'vpu', 'wspd': 'vpu', 'wdir': 'vpu', 'lwet': 'vpu', 'srad': 'vpu'},
'mdr' : {'temp': 'klwm', 'rhum': 'klwm', 'prcp': 'klwm', 'wspd': 'klwm', 'wdir': 'klwm', 'lwet': 'mty', 'srad': 'mty'},
'mam' : {'temp': 'klwm', 'rhum': 'klwm', 'prcp': 'klwm', 'wspd': 'klwm', 'wdir': 'klwm', 'lwet': 'mdr', 'srad': 'mty'},
'vsa' : {'temp': 'vpu', 'rhum': 'vpu', 'prcp': 'vpu', 'wspd': 'vpu', 'wdir': 'vpu', 'lwet': 'vpu', 'srad': 'vpu'},
'mty' : {'temp': 'mdr', 'rhum': 'mdr', 'prcp': 'mdr', 'wspd': 'mdr', 'wdir': 'mdr', 'lwet': 'mdr', 'srad': 'mam'},
'mst' : {'temp': 'msw', 'rhum': 'msw', 'prcp': 'msw', 'wspd': 'msw', 'wdir': 'msw', 'lwet': 'msw', 'srad': 'msw'},
'mwe' : {'temp': 'kbaf', 'rhum': 'kbaf', 'prcp': 'kbaf', 'wspd': 'kbaf', 'wdir': 'kbaf', 'lwet': 'um_cso', 'srad': 'mbe'},
'mbo' : {'temp': 'cu_tff', 'rhum': 'cu_tff', 'prcp': 'cu_tff', 'wspd': 'cu_tff', 'wdir': 'cu_tff', 'lwet': 'um_tff', 'srad': 'mha'},
'mas' : {'temp': 'um_clk', 'rhum': 'um_clk', 'prcp': 'um_clk', 'wspd': 'um_clk', 'wdir': 'um_clk', 'lwet': 'um_clk', 'srad': 'msd'},
'meb' : {'temp': 'ktan', 'rhum': 'ktan', 'prcp': 'ktan', 'wspd': 'ktan', 'wdir': 'ktan', 'lwet': 'um_tff', 'srad': 'msh'},
'mre' : {'temp': 'kewb', 'rhum': 'kewb', 'prcp': 'kewb', 'wspd': 'kewb', 'wdir': 'kewb', 'lwet': 'um_tff', 'srad': 'meb'},
'mha' : {'temp': 'msw', 'rhum': 'msw', 'prcp': 'msw', 'wspd': 'msw', 'wdir': 'msw', 'lwet': 'msw', 'srad': 'msw'},
'msw' : {'temp': 'mst', 'rhum': 'mst', 'prcp': 'mst', 'wspd': 'mst', 'wdir': 'mst', 'lwet': 'mst', 'srad': 'mha'},
'msh' : {'temp': 'kfmh', 'rhum': 'kfmh', 'prcp': 'kfmh', 'wspd': 'kfmh', 'wdir': 'kfmh', 'lwet': 'meb', 'srad': 'meb'},
'mwa' : {'temp': 'um_whs', 'rhum': 'um_whs', 'prcp': 'um_whs', 'wspd': 'kbos', 'wdir': 'kbos', 'lwet': 'um_whs', 'srad': 'um_whs'},
'mno' : {'temp': 'korh', 'rhum': 'korh', 'prcp': 'korh', 'wspd': 'korh', 'wdir': 'korh', 'lwet': 'mbo', 'srad': 'mbo'},
'wi_gay' : {'temp': 'kovs', 'rhum': 'kovs', 'prcp': 'kovs', 'wspd': 'kovs', 'wdir': 'kovs', 'lwet': 'nee', 'srad': 'nee'},
'um_whs' : {'temp': 'kmqe', 'rhum': 'kmqe', 'prcp': 'kmqe', 'wspd': 'kmqe', 'wdir': 'kmqe', 'lwet': 'msh', 'srad': 'msh'},
'um_cso' : {'temp': 'kcef', 'rhum': 'kcef', 'prcp': 'kcef', 'wspd': 'kcef', 'wdir': 'kcef', 'lwet': 'um_clk', 'srad': 'um_clk'},
'um_tff' : {'temp': 'korh', 'rhum': 'korh', 'prcp': 'korh', 'wspd': 'korh', 'wdir': 'korh', 'lwet': 'um_cso', 'srad': 'um_cso'},
'um_clk' : {'temp': 'kore', 'rhum': 'kore', 'prcp': 'kore', 'wspd': 'kore', 'wdir': 'kore', 'lwet': 'um_cso', 'srad': 'um_cso'},
'um_new' : {'temp': 'kpve', 'rhum': 'kpvd', 'prcp': 'kpvd', 'wspd': 'kpvd', 'wdir': 'kpvd', 'lwet': 'meb', 'srad': 'meb'},
'um_bcf' : {'temp': 'khya', 'rhum': 'khya', 'prcp': 'khya', 'wspd': 'khya', 'wdir': 'khya', 'lwet': 'meb'},
'cu_aur' : {'temp': 'cu_gfr', 'rhum': 'cu_gfr', 'prcp': 'cu_gfr', 'st4i': 'cu_gfr', 'wspd': 'cu_gfr', 'wdir': 'cu_gfr', 'srad': 'cu_gfr'},
'cu_chz' : {'temp': 'chz', 'rhum': 'chz', 'prcp': 'chz', 'wspd': 'chz', 'wdir': 'chz', 'st4i': 'cu_wlb', 'srad': 'cu_wlb'},
'cu_gfr' : {'temp': 'ith', 'prcp': 'ith', 'rhum': 'ith', 'st4i': 'cu_aur', 'wspd': 'ith', 'wdir': 'ith', 'srad': 'aur'},
'cu_lkp' : {'temp': 'kslk', 'rhum': 'kslk', 'prcp': 'kslk', 'wspd': 'kslk', 'wdir': 'kslk', 'st4i': 'cu_wlb', 'srad': 'cu_wlb'},
'cu_val' : {'temp': 'hud', 'rhum': 'hud', 'prcp': 'hud', 'wspd': 'hud', 'wdir': 'hud', 'srad': 'cu_wlb', 'st4i': 'cu_gfr'},
'cu_wlb' : {'temp': 'vsb', 'rhum': 'vsb', 'prcp': 'vsb', 'wspd': 'vsb', 'wdir': 'vsb', 'srad': 'cu_chz', 'st4i': 'cu_chz'},
'kalb' : {'temp': 'gui', 'rhum': 'gui', 'prcp': 'gui', 'wspd': 'gui', 'wdir': 'gui'},
'kbgm' : {'temp': 'cu_gfr', 'rhum': 'cu_gfr', 'prcp': 'cu_gfr', 'wspd': 'cu_gfr', 'wdir': 'cu_gfr'},
'kbfd' : {'temp': 'kelz', 'rhum': 'kelz', 'prcp': 'kelz', 'wspd': 'kelz', 'wdir': 'kelz'},
'khwv' : {'temp': 'kisp', 'rhum': 'kisp', 'prcp': 'kisp', 'wspd': 'kisp', 'wdir': 'kisp'},
'kbuf' : {'temp': 'kiag', 'rhum': 'kiag', 'prcp': 'kiag', 'wspd': 'kiag', 'wdir': 'kiag'},
'kbtv' : {'temp': 'cu_wlb', 'rhum': 'cu_wlb', 'prcp': 'cu_wlb', 'wspd': 'cu_wlb', 'wdir': 'cu_wlb'},
'kvsf' : {'temp': 'krut', 'rhum': 'krut', 'prcp': 'krut', 'wspd': 'krut', 'wdir': 'krut'},
'kdsv' : {'temp': 'way', 'rhum': 'way', 'prcp': 'way', 'wspd': 'way', 'wdir': 'kelz'},
'kdkk' : {'temp': 'kjhw', 'rhum': 'kjhw', 'prcp': 'kjhw', 'wspd': 'kjhw', 'wdir': 'kjhw'},
'kelm' : {'temp': 'wgl', 'rhum': 'wgl', 'prcp': 'wgl', 'wspd': 'kbgm', 'wdir': 'kbgm'},
'keri' : {'temp': 'kdkk', 'rhum': 'kdkk', 'prcp': 'kdkk', 'wspd': 'kdkk', 'wdir': 'kdkk'},
'kfrg' : {'temp': 'kisp', 'rhum': 'kisp', 'prcp': 'kisp', 'wspd': 'kisp', 'wdir': 'kisp'},
'kfzy' : {'temp': 'scr', 'rhum': 'scr', 'prcp': 'scr', 'wspd': 'ksyr', 'wdir': 'ksyr'},
'kgfl' : {'temp': 'kalb', 'rhum': 'kalb', 'prcp': 'kalb', 'wspd': 'kalb', 'wdir': 'kalb'},
'krme' : {'temp': 'ksyr', 'rhum': 'ksyr', 'prcp': 'ksyr', 'wspd': 'ksyr', 'wdir': 'ksyr'},
'kisp' : {'temp': 'khwv', 'rhum': 'khwv', 'prcp': 'kfrg', 'wspd': 'khwv', 'wdir': 'khwv'},
'kith' : {'temp': 'cu_gfr', 'rhum': 'cu_gfr', 'prcp': 'cu_gfr', 'wspd': 'cu_gfr', 'wdir': 'cu_gfr'},
'kjhw' : {'temp': 'kdkk', 'rhum': 'kdkk', 'prcp': 'kdkk', 'wspd': 'kdkk', 'wdir': 'kdkk'},
'kmss' : {'temp': 'kslk', 'rhum': 'kslk', 'prcp': 'kslk', 'wspd': 'kslk', 'wdir': 'kslk'},
'kmgj' : {'temp': 'kswf', 'rhum': 'kswf', 'prcp': 'kswf', 'wspd': 'kswf', 'wdir': 'kswf'},
'kmtp' : {'temp': 'kfok', 'rhum': 'kfok', 'prcp': 'kfok', 'wspd': 'kfok', 'wdir': 'kfok'},
'kmsv' : {'temp': 'kavp', 'rhum': 'kavp', 'prcp': 'kavp', 'wspd': 'kavp', 'wdir': 'kavp'},
'knyc' : {'temp': 'klga', 'rhum': 'klga', 'prcp': 'klga', 'wspd': 'klga', 'wdir': 'klga'},
'kjfk' : {'temp': 'klga', 'rhum': 'klga', 'prcp': 'klga', 'wspd': 'klga', 'wdir': 'klga'},
'klga' : {'temp': 'knyc', 'rhum': 'knyc', 'prcp': 'knyc', 'wspd': 'knyc', 'wdir': 'knyc'},
'kiag' : {'temp': 'loc', 'rhum': 'loc', 'prcp': 'loc', 'wspd': 'loc', 'wdir': 'kbuf'},
'kpeo' : {'temp': 'bra', 'rhum': 'bra', 'prcp': 'bra', 'wspd': 'cu_aur', 'wdir': 'cu_aur'},
'kpou' : {'temp': 'kswf', 'rhum': 'kswf', 'prcp': 'kswf', 'wspd': 'kswf', 'wdir': 'kswf'},
'kroc' : {'temp': 'far', 'rhum': 'far', 'prcp': 'far', 'wspd': 'far', 'wdir': 'far'},
'kslk' : {'temp': 'kmss', 'rhum': 'kmss', 'prcp': 'kmss', 'wspd': 'kmss', 'wdir': 'kmss'},
'kswf' : {'temp': 'mar', 'rhum': 'mar', 'prcp': 'mar', 'wspd': 'mar', 'wdir': 'mar'},
'ksyr' : {'temp': 'laf', 'rhum': 'laf', 'prcp': 'laf', 'wspd': 'laf', 'wdir': 'laf'},
'kfok' : {'temp': 'khwv', 'rhum': 'khwv', 'prcp': 'khwv', 'wspd': 'khwv', 'wdir': 'khwv'},
'kart' : {'temp': 'kgtb', 'rhum': 'kgtb', 'prcp': 'kgtb', 'wspd': 'kgtb', 'wdir': 'kgtb'},
'kgtb' : {'temp': 'kart', 'rhum': 'kart', 'prcp': 'kart', 'wspd': 'kart', 'wdir': 'kart'},
'khpn' : {'temp': 'klga', 'rhum': 'klga', 'prcp': 'klga', 'wspd': 'klga', 'wdir': 'klga'},
'kelz' : {'temp': 'kbfd', 'rhum': 'kbfd', 'prcp': 'kbfd', 'wspd': 'kbfd', 'wdir': 'kbfd'},
'kbdr' : {'temp': 'khvn', 'rhum': 'khvn', 'prcp': 'khvn', 'wspd': 'khvn', 'wdir': 'khvn'},
'kdxr' : {'temp': 'kpou', 'rhum': 'kpou', 'prcp': 'kpou', 'wspd': 'kpou', 'wdir': 'kpou'},
'kddh' : {'temp': 'krut', 'rhum': 'krut', 'prcp': 'krut', 'wspd': 'krut', 'wdir': 'krut'},
'krut' : {'temp': 'kddh', 'rhum': 'kddh', 'prcp': 'kddh', 'wspd': 'kddh', 'wdir': 'kddh'},
'kmvl' : {'temp': 'kmpv', 'rhum': 'kmpv', 'prcp': 'kmpv', 'wspd': 'kmpv', 'wdir': 'kmpv'},
'kmpv' : {'temp': 'kmvl', 'rhum': 'kmvl', 'prcp': 'kmvl', 'wspd': 'kmvl', 'wdir': 'kmvl'},
'kpsf': {'temp': 'kaqw', 'rhum': 'kaqw', 'prcp': 'kaqw', 'wspd': 'kaqw', 'wdir': 'kaqw'},
'kaqw': {'temp': 'kpsf', 'rhum': 'kpsf', 'prcp': 'kpsf', 'wspd': 'kpsf', 'wdir': 'kpsf'},
'kbaf': {'temp': 'kcef', 'rhum': 'kcef', 'prcp': 'kcef', 'wspd': 'kcef', 'wdir': 'kcef'},
'kcef': {'temp': 'kbaf', 'rhum': 'kbaf', 'prcp': 'kbaf', 'wspd': 'kbaf', 'wdir': 'kbaf'},
'korh': {'temp': 'kore', 'rhum': 'kore', 'prcp': 'kore', 'wspd': 'kore', 'wdir': 'kore'},
'kore': {'temp': 'korh', 'rhum': 'korh', 'prcp': 'korh', 'wspd': 'korh', 'wdir': 'korh'},
'kfit': {'temp': 'korh', 'rhum': 'korh', 'prcp': 'korh', 'wspd': 'korh', 'wdir': 'korh'},
'klwm': {'temp': 'kbvy', 'rhum': 'kbvy', 'prcp': 'kbvy', 'wspd': 'kbvy', 'wdir': 'kbvy'},
'kbed': {'temp': 'klwm', 'rhum': 'klwm', 'prcp': 'klwm', 'wspd': 'klwm', 'wdir': 'klwm'},
'kbvy': {'temp': 'kbos', 'rhum': 'kbos', 'prcp': 'kbos', 'wspd': 'kbos', 'wdir': 'kbos'},
'kbos': {'temp': 'kbvy', 'rhum': 'kbvy', 'prcp': 'kbvy', 'wspd': 'kbvy', 'wdir': 'kbvy'},
'kmqe': {'temp': 'kowd', 'rhum': 'kowd', 'prcp': 'kowd', 'wspd': 'kowd', 'wdir': 'kowd'},
'kowd': {'temp': 'msh', 'rhum': 'msh', 'prcp': 'msh', 'wspd': 'msh', 'wdir': 'msh'},
'knzw': {'temp': 'kbos', 'rhum': 'kbos', 'prcp': 'kbos', 'wspd': 'kbos', 'wdir': 'kbos'},
'kpym': {'temp': 'ktan', 'rhum': 'ktan', 'prcp': 'ktan', 'wspd': 'ktan', 'wdir': 'ktan'},
'ktan': {'temp': 'kpym', 'rhum': 'kpym', 'prcp': 'kpym', 'wspd': 'kpym', 'wdir': 'kpym'},
'kewb': {'temp': 'ktan', 'rhum': 'ktan', 'prcp': 'ktan', 'wspd': 'ktan', 'wdir': 'ktan'},
'kmvy': {'temp': 'kack', 'rhum': 'kack', 'prcp': 'kack', 'wspd': 'kack', 'wdir': 'kack'},
'kack': {'temp': 'kmvy', 'rhum': 'kmvy', 'prcp': 'kmvy', 'wspd': 'kmvy', 'wdir': 'kmvy'},
'kpvc': {'temp': 'kcqx', 'rhum': 'kcqx', 'prcp': 'kcqx', 'wspd': 'kcqx', 'wdir': 'kcqx'},
'kcqx': {'temp': 'khya', 'rhum': 'khya', 'prcp': 'khya', 'wspd': 'khya', 'wdir': 'khya'},
'khya': {'temp': 'kfmh', 'rhum': 'kfmh', 'prcp': 'kfmh', 'wspd': 'kfmh', 'wdir': 'kfmh'},
'kfmh': {'temp': 'khya', 'rhum': 'khya', 'prcp': 'khya', 'wspd': 'khya', 'wdir': 'khya'},
'kcdw': {'temp': 'kteb', 'rhum': 'kteb', 'prcp': 'kteb', 'wspd': 'kteb', 'wdir': 'kteb'},
'kewr': {'temp': 'knyc', 'rhum': 'knyc', 'prcp': 'knyc', 'wspd': 'knyc', 'wdir': 'knyc'},
'kteb': {'temp': 'knyc', 'rhum': 'knyc', 'prcp': 'knyc', 'wspd': 'knyc', 'wdir': 'knyc'},
'kfwn': {'temp': 'kcdw', 'rhum': 'kcdw', 'prcp': 'kcdw', 'wspd': 'kcdw', 'wdir': 'kcdw'},
'kuuu': {'temp': 'kpvd', 'rhum': 'kpvd', 'prcp': 'kpvd', 'wspd': 'kpvd', 'wdir': 'kpvd'},
'kpvd': {'temp': 'kuuu', 'rhum': 'kuuu', 'prcp': 'kuuu', 'wspd': 'kuuu', 'wdir': 'kuuu'},
'kbdl': {'temp': 'kbaf', 'rhum': 'kbaf', 'prcp': 'kbaf', 'wspd': 'kbaf', 'wdir': 'kbaf'},
'kteb': {'temp': 'kewr', 'rhum': 'kewr', 'prcp': 'kewr', 'wspd': 'kewr', 'wdir': 'kewr'},
'k12n': {'temp': 'kfwn', 'rhum': 'kfwn', 'prcp': 'kfwn', 'wspd': 'kfwn', 'wdir': 'kfwn'},
'kacy': {'temp': '232', 'rhum': '232', 'prcp': '232', 'wspd': '232', 'wdir': '232'},
'kblm': {'temp': '3397', 'rhum': '3397', 'prcp': '3397', 'wspd': '3397', 'wdir': '3397'},
'kmiv': {'temp': '284', 'rhum': '284', 'prcp': '284', 'wspd': '284', 'wdir': '284'},
'kmmu': {'temp': 'ksmq', 'rhum': 'ksmq', 'prcp': 'ksmq', 'wspd': 'ksmq', 'wdir': 'ksmq'},
'knel': {'temp': '1032', 'rhum': '1032', 'prcp': '1032', 'wspd': '1032', 'wdir': '1032'},
'ksmq': {'temp': 'kmmu', 'rhum': 'kmmu', 'prcp': 'kmmu', 'wspd': 'kmmu', 'wdir': 'kmmu'},
'kttn': {'temp': 'kpne', 'rhum': 'kpne', 'prcp': 'kpne', 'wspd': 'kpne', 'wdir': 'kpne'},
'kvay': {'temp': 'kpne', 'rhum': 'kpne', 'prcp': 'kpne', 'wspd': 'kpne', 'wdir': 'kpne'},
'kwri': {'temp': 'kvay', 'rhum': 'kvay', 'prcp': 'kvay', 'wspd': 'kvay', 'wdir': 'kvay'},
'kwwd': {'temp': '261', 'rhum': '261', 'prcp': '261', 'wspd': '261', 'wdir': '261'},
'kphl': {'temp': 'kpne', 'rhum': 'kpne', 'prcp': 'kpne', 'wspd': 'kpne', 'wdir': 'kpne'},
'kpne': {'temp': 'kphl', 'rhum': 'kphl', 'prcp': 'kphl', 'wspd': 'kphl', 'wdir': 'kphl'},
'kpit': {'temp': 'kjst', 'rhum': 'kjst', 'prcp': 'kjst', 'wspd': 'kjst', 'wdir': 'kjst'},
'kmdt': {'temp': 'krdg', 'rhum': 'krdg', 'prcp': 'krdg', 'wspd': 'krdg', 'wdir': 'krdg'},
'kipt': {'temp': 'kavp', 'rhum': 'kavp', 'prcp': 'kavp', 'wspd': 'kavp', 'wdir': 'kavp'},
'kavp': {'temp': 'kbgm', 'rhum': 'kbgm', 'prcp': 'kbgm', 'wspd': 'kbgm', 'wdir': 'kbgm'},
'kabe': {'temp': 'krdg', 'rhum': 'krdg', 'prcp': 'krdg', 'wspd': 'krdg', 'wdir': 'krdg'},
'kaoo': {'temp': 'kjst', 'rhum': 'kjst', 'prcp': 'kjst', 'wspd': 'kjst', 'wdir': 'kjst'},
'krdg': {'temp': 'kabe', 'rhum': 'kabe', 'prcp': 'kabe', 'wspd': 'kabe', 'wdir': 'kabe'},
'kjst': {'temp': 'kaoo', 'rhum': 'kaoo', 'prcp': 'kaoo', 'wspd': 'kaoo', 'wdir': 'kaoo'},
'kduj': {'temp': 'kbfd', 'rhum': 'kbfd', 'prcp': 'kbfd', 'wspd': 'kbfd', 'wdir': 'kbfd'},
'kilg': {'temp': 'kphl', 'rhum': 'kphl', 'prcp': 'kphl', 'wspd': 'kphl', 'wdir': 'kphl'},
'pa_big': {'temp': 'kmdt', 'rhum': 'kmdt', 'prcp': 'kmdt', 'wspd': 'kmdt', 'wdir': 'kmdt', 'lwet': 'pa_npa', 'srad': 'pa_npa'},
'pa_pin': {'temp': 'kmdt', 'rhum': 'kmdt', 'prcp': 'kmdt', 'wspd': 'kmdt', 'wdir': 'kmdt', 'lwet': 'pa_big', 'srad': 'pa_big'},
'pa_ysp': {'temp': 'kmdt', 'rhum': 'kmdt', 'prcp': 'kmdt', 'wspd': 'kmdt', 'wdir': 'kmdt', 'lwet': 'pa_big', 'srad': 'pa_big'},
'pa_npa': {'temp': 'kjst', 'rhum': 'kjst', 'prcp': 'kjst', 'wspd': 'kjst', 'wdir': 'kjst', 'lwet': 'pa_big', 'srad': 'pa_big'},
'pa_ntr': {'temp': 'kabe', 'rhum': 'kabe', 'prcp': 'kabe', 'wspd': 'kabe', 'wdir': 'kabe', 'lwet': 'pa_ysp', 'srad': '1029'},
'pa_rsp': {'temp': 'kaoo', 'rhum': 'kaoo', 'prcp': 'kaoo', 'wspd': 'kaoo', 'wdir': 'kaoo', 'lwet': 'pa_npa', 'srad': 'pa_npa'},
'me_bhb': {'temp': 'kbhb', 'rhum': 'kbhb', 'prcp': 'kbhb', 'wspd': 'kbhb', 'wdir': 'kbhb', 'srad': 'mam'},
'mmi' : {'temp': 'khfd', 'rhum': 'khfd', 'prcp': 'khfd', 'wspd': 'khfd', 'wdir': 'khfd', 'lwet': 'cli', 'srad': 'mwe'},
'ct_gfy': {'temp': 'ct_nwi', 'rhum': 'ct_nwi', 'prcp': 'ct_nwi', 'wspd': 'ct_nwi', 'wdir': 'ct_nwi', 'lwet': 'ct_nwi', 'srad': 'ct_nwi'},
'ct_gui': {'temp': 'kbdr', 'rhum': 'kbdr', 'prcp': 'kbdr', 'wspd': 'kbdr', 'wdir': 'kbdr', 'lwet': 'ct_she', 'srad': 'ct_she'},
'ct_sgl': {'temp': 'ct_ssm', 'rhum': 'ct_ssm', 'prcp': 'ct_ssm', 'wspd': 'ct_ssm', 'wdir': 'ct_ssm', 'lwet': 'ct_ssm', 'srad': 'ct_ssm'},
'ct_nwi': {'temp': 'ct_eas', 'rhum': 'ct_eas', 'prcp': 'ct_eas', 'wspd': 'ct_eas', 'wdir': 'ct_eas', 'lwet': 'ct_eas', 'srad': 'ct_eas'},
'ct_rid': {'temp': 'kdxr', 'rhum': 'kdxr', 'prcp': 'kdxr', 'wspd': 'kdxr', 'wdir': 'kdxr', 'lwet': 'ct_she', 'srad': 'ct_she'},
'ct_she': {'temp': 'ct_wal', 'rhum': 'ct_wal', 'prcp': 'ct_wal', 'wspd': 'ct_wal', 'wdir': 'ct_wal', 'lwet': 'ct_wal', 'srad': 'ct_wal'},
'ct_ssm': {'temp': 'ct_ssu', 'rhum': 'ct_ssu', 'prcp': 'ct_ssu', 'wspd': 'ct_ssu', 'wdir': 'ct_ssu', 'lwet': 'ct_ssu', 'srad': 'ct_ssu'},
'ct_ssu': {'temp': 'ct_ssm', 'rhum': 'ct_ssm', 'prcp': 'ct_ssm', 'wspd': 'ct_ssm', 'wdir': 'ct_ssm', 'lwet': 'ct_ssm', 'srad': 'ct_ssm'},
'ct_wal': {'temp': 'ct_ssu', 'rhum': 'ct_ssu', 'prcp': 'ct_ssu', 'wspd': 'ct_ssu', 'wdir': 'ct_ssu', 'lwet': 'ct_ssu', 'srad': 'ct_ssu'},
'ct_eas': {'temp': 'ct_nwi', 'rhum': 'ct_nwi', 'prcp': 'ct_nwi', 'wspd': 'ct_nwi', 'wdir': 'ct_nwi', 'lwet': 'ct_nwi', 'srad': 'ct_nwi'},
'ct_tol': {'temp': 'ct_ewi', 'rhum': 'ct_ewi', 'prcp': 'ct_ewi', 'wspd': 'ct_ewi', 'wdir': 'ct_ewi', 'lwet': 'ct_ewi', 'srad': 'ct_ewi'},
'ct_enf': {'temp': 'ct_ewi', 'rhum': 'ct_ewi', 'prcp': 'ct_ewi', 'wspd': 'ct_ewi', 'wdir': 'ct_ewi', 'lwet': 'ct_ewi', 'srad': 'ct_ewi'},
'ct_ewi': {'temp': 'ct_enf', 'rhum': 'ct_enf', 'prcp': 'ct_enf', 'wspd': 'ct_enf', 'wdir': 'ct_enf', 'lwet': 'ct_enf', 'srad': 'ct_enf'},
'ct_gra': {'temp': 'kbdl', 'rhum': 'kbdl', 'prcp': 'kbdl', 'wspd': 'kbdl', 'wdir': 'kbdl', 'lwet': 'ct_enf', 'srad': 'ct_enf'},
'ct_ely': {'temp': 'ct_gfy', 'rhum': 'ct_gfy', 'prcp': 'ct_gfy', 'wspd': 'ct_gfy', 'wdir': 'ct_gfy', 'lwet': 'ct_gfy', 'srad': 'ct_gfy'},
'uc_sto': {'temp': 'ct_tol', 'rhum': 'ct_tol', 'prcp': 'ct_tol', 'lwet': 'ct_tol'},
'29':   {'temp': '202', 'rhum': '202', 'prcp': '202', 'wspd': '202', 'wdir': '202'},
'33':   {'temp': '296', 'rhum': '296', 'prcp': '296', 'wspd': '296', 'wdir': '296'},
'148':  {'rhum': '296', 'prcp': '296', 'wspd': '296', 'wdir': '296'},
'198':  {'temp': '263', 'rhum': '263', 'prcp': '263', 'wspd': '263', 'wdir': '263'},
'202':  {'temp': '1034', 'rhum': '1034', 'prcp': '1034', 'wspd': '1034', 'wdir': '1034'},
'232':  {'temp': 'kacy', 'rhum': 'kacy', 'prcp': 'kacy', 'wspd': 'kacy', 'wdir': 'kacy'},
'236':  {'temp': '1034', 'rhum': '1034', 'prcp': '1034', 'wspd': '1034', 'wdir': '1034'},
'261':  {'temp': '296', 'rhum': '148', 'prcp': '148', 'wspd': '148', 'wdir': '148'}, 
'263':  {'temp': 'kmiv', 'rhum': 'kmiv', 'prcp': 'kmiv', 'wspd': 'kmiv', 'wdir': 'kmiv'},
'284':  {'temp': '3409', 'rhum': '3409', 'prcp': '3409', 'wspd': '3409', 'wdir': '3409', 'srad': '1034'},
'285':  {'temp': '1101', 'rhum': '1101', 'prcp': '1101', 'wspd': '1101', 'wdir': '1101', 'srad': '1101'},
'286':  {'temp': 'kfwn', 'rhum': 'kfwn', 'prcp': 'kfwn', 'wspd': 'kfwn', 'wdir': 'kfwn', 'srad': '471'},
'287':  {'temp': '3404', 'rhum': '3404', 'prcp': '3404', 'wspd': '3404', 'wdir': '3404', 'srad': '1032'},
'289':  {'temp': '1029', 'rhum': '1029', 'prcp': '1029', 'wspd': '1029', 'wdir': '1029', 'srad': '1029'},
'295':  {'temp': '3406', 'rhum': '3406', 'prcp': '3406', 'wspd': '3406', 'wdir': '3406', 'srad': '1032'}, 
'296':  {'temp': '33', 'rhum': '33', 'prcp': '33', 'wspd': '33', 'wdir': '33', 'srad': '284'},
'317':  {'temp': '198', 'rhum': '198', 'prcp': '198', 'wspd': '198', 'wdir': '198', 'srad': '1032'},
'471':  {'temp': 'kfwn', 'rhum': 'kfwn', 'prcp': 'kfwn', 'wspd': 'kfwn', 'wdir': 'kfwn', 'srad': '286'},
'1029': {'temp': '289', 'rhum': '289', 'prcp': '289', 'wspd': '289', 'wdir': '289', 'srad': '289'},
'1032': {'temp': 'knel', 'rhum': 'knel', 'prcp': 'knel', 'wspd': 'knel', 'wdir': 'knel', 'srad': '317'},
'1033': {'temp': 'kteb', 'rhum': 'kteb', 'prcp': 'kteb', 'wspd': 'kteb', 'wdir': 'kteb', 'srad': '471'},
'1034': {'temp': '202', 'rhum': '202', 'prcp': '202', 'wspd': '202', 'wdir': '202', 'srad': '317'},
'1101': {'temp': '285', 'rhum': '285', 'prcp': '285', 'wspd': '285', 'wdir': '285', 'srad': '285'},
'3397': {'temp': '3404', 'rhum': '3404', 'prcp': '3404', 'wspd': '3404', 'wdir': '3404'},
'3398': {'temp': '3407', 'rhum': '3407', 'prcp': '3407', 'wspd': '3407', 'wdir': '3407'},
'3403': {'temp': '3405', 'rhum': '3405', 'prcp': '1101', 'wspd': '3405', 'wdir': '3405'},
'3404': {'temp': '287', 'rhum': '287', 'prcp': '287', 'wspd': '287', 'wdir': '287'},
'3405': {'temp': '3403', 'rhum': '3403', 'wspd': '3403', 'wdir': '3403'},
'3406': {'temp': '295', 'rhum': '295', 'prcp': '295', 'wspd': '295', 'wdir': '295'},
'3407': {'temp': '3398', 'rhum': '3398', 'prcp': '3398', 'wspd': '3398', 'wdir': '3398', 'srad': '1034'},
'3408': {'temp': '1032', 'rhum': '1032', 'prcp': '1032', 'wspd': '1032', 'wdir': '1032'},
'3409': {'temp': '284', 'rhum': '284', 'prcp': '284', 'wspd': '284', 'wdir': '284'},
'3411': {'temp': 'kewr', 'rhum': 'kewr', 'prcp': 'kewr', 'wspd': 'kewr', 'wdir': 'kewr', 'srad': '1033'},
'3479':  {'temp': '263', 'rhum': '263', 'prcp': '263', 'wspd': '263', 'wdir': '263'}
}