sister_info = {"alb" : {"temp": "kno", "lwet": "kno", "rhum": "kno", "prcp": "kno", "wspd": "kno", "wdir": "kno", "srad": "kno"},
"noa" : {"temp": "som", "lwet": "som", "rhum": "som", "prcp": "som", "wspd": "som", "wdir": "som", "srad": "ash"},
"soa" : {"temp": "som", "lwet": "som", "rhum": "som", "prcp": "som", "wspd": "som", "wdir": "som", "srad": "som"},
"acc" : {"temp": "hig", "lwet": "hig", "rhum": "hig", "prcp": "hig", "wspd": "hig", "wdir": "hig", "srad": "hvl"},
"alt" : {"temp": "gui", "rhum": "gui", "prcp": "gui", "wspd": "gui", "wdir": "gui", "lwet": "gui", "srad": "gui"},
"ark" : {"temp": "kdsv", "rhum": "kdsv", "prcp": "kdsv"},
"arm" : {"temp": "kdsv", "lwet": "way", "rhum": "kdsv", "prcp": "kdsv", "wspd": "kdsv", "wdir": "kdsv", "srad": "way"},
"ash" : {"temp": "ptb", "lwet": "ptb", "rhum": "ptb", "prcp": "ptb", "wspd": "ptb", "wdir": "ptb", "srad": "ptb"},
"aur" : {"temp": "cu_gfr", "rhum": "cu_gfr", "lwet": "var", "prcp": "cu_gfr", "wspd": "cu_gfr", "wdir": "cu_gfr", "srad": "cu_gfr"},
"bal" : {"temp": "ksyr", "rhum": "ksyr", "prcp": "ksyr", "wspd": "ksyr", "wdir": "ksyr", "lwet": "laf", "srad": "aur"},
"bla" : {"temp": "bal", "rhum": "bal", "prcp": "bal", "wspd": "bal", "wdir": "bal", "lwet": "bal", "srad": "bal"},
"bar" : {"temp": "pul", "lwet": "pul", "prcp": "pul"},
"bat" : {"temp": "pav", "lwet": "alb", "rhum": "alb", "prcp": "pav", "st4i": "pav"},
"ber" : {"temp": "elb", "rhum": "elb", "prcp": "elb", "wspd": "elb", "wdir": "elb", "lwet": "elb", "srad": "med"},
"bra" : {"temp": "kpeo","rhum": "kpeo", "prcp": "kpeo", "wspd": "kpeo", "wdir": "kpeo", "lwet": "drs", "srad": "drs"},
"brh" : {"temp": "khwv", "rhum": "khwv", "prcp": "khwv", "wspd": "khwv", "wdir": "khwv", "lwet": "riv", "srad": "riv"},
"bri" : {"temp": "wmn", "rhum": "wmn", "prcp": "wmn", "wspd": "wmn", "wdir": "wmn", "lwet": "wmn", "srad": "emo"},
"but" : {"temp": "bal", "lwet": "bal", "rhum": "bal", "prcp": "bal", "wspd": "bal", "wdir": "bal", "srad": "bal"},
"cah" : {"temp": "kswf", "rhum": "kswf", "prcp": "kswf", "wspd": "kswf", "wdir": "kswf", "lwet": "rtw", "srad": "rtw"},
"cas" : {"temp": "kin", "rhum": "kin", "prcp": "kin", "wspd": "kin", "wdir": "kin", "srad": "kin", "lwet": "kin"},
"cer" : {"temp": "kelz", "rhum": "kelz", "prcp": "kelz", "wspd": "kelz", "wdir": "kelz"},
"chz" : {"temp": "vso", "rhum": "vso", "prcp": "vso", "wspd": "vso", "wdir": "vso", "lwet": "vso", "srad": "vso"},
"czy" : {"temp": "vso", "rhum": "vso", "prcp": "vso", "wspd": "vso", "wdir": "vso", "lwet": "vso", "srad": "vso"},
"cli" : {"temp": "kalb", "rhum": "kalb", "prcp": "kalb", "wspd": "kalb", "wdir": "kalb", "lwet": "gui", "srad": "gui"},
"clw" : {"temp": "hig", "rhum": "hig", "prcp": "hig", "wspd": "hig", "wdir": "hig", "lwet": "hig", "srad": "hvl"},
"cln" : {"temp": "clw", "lwet": "clw", "rhum": "clw", "prcp": "clw", "wspd": "clw", "wdir": "clw", "srad": "hvl"},
"crc" : {"temp": "chz", "rhum": "chz", "prcp": "chz", "wspd": "chz", "wdir": "chz"},
"cho" : {"temp": "cas", "rhum": "cas", "prcp": "cas", "wspd": "cas", "wdir": "cas"},
"cro" : {"temp": "vsh", "rhum": "vsh", "prcp": "vsh", "wspd": "vsh", "wdir": "vsh", "srad": "vsh", "lwet": "vsh"},
"cns" : {"temp": "shc", "lwet": "shc", "rhum": "shc", "prcp": "shc", "wspd": "shc", "wdir": "shc", "srad": "shc"},
"cut" : {"temp": "kfok", "lwet": "mat", "rhum": "kfok", "prcp": "kfok", "wspd": "kfok", "wdir": "kfok", "srad": "cns"},
"den" : {"temp": "hud", "rhum": "hud", "prcp": "hud", "wspd": "hud", "wdir": "hud", "lwet": "hud", "srad": "hud"},
"dre" : {"temp": "gbe", "lwet": "gbe", "prcp": "gbe"},
"drs" : {"temp": "kpeo", "rhum": "kpeo", "prcp": "kpeo", "wspd": "kpeo", "wdir": "kpeo", "lwet": "gbe", "srad": "gbe"},
"dun" : {"temp": "kpeo", "rhum": "kpeo", "prcp": "kpeo", "wspd": "kpeo", "wdir": "kpeo", "lwet": "bar", "srad": "wla"},
"eag" : {"temp": "kddh", "rhum": "kddh", "prcp": "kddh", "wspd": "kddh", "wdir": "kddh", "lwet": "vbe", "srad": "vbe"},
"ede" : {"temp": "kbuf", "rhum": "kbuf", "prcp": "kbuf", "lwet": "bat"},
"elb" : {"temp": "kno", "lwet": "kno", "rhum": "kno", "prcp": "kno", "wspd": "kno", "wdir": "kno", "srad": "kno"},
"emo" : {"temp": "khwv", "rhum": "khwv", "prcp": "khwv", "wspd": "khwv", "wdir": "khwv", "lwet": "man", "srad": "man"},
"fai" : {"temp": "phe", "rhum": "phe", "prcp": "phe", "wspd": "phe", "wdir": "phe", "lwet": "phe", "srad": "phe"},
"far" : {"temp": "gbe", "lwet": "gbe", "rhum": "gbe", "prcp": "gbe", "wspd": "gbe", "wdir": "gbe", "srad": "gbe"},
"fay" : {"temp": "gbe", "rhum": "gbe", "prcp": "gbe", "wspd": "var", "wdir": "var", "lwet": "gbe", "srad": "var"},
"fis" : {"temp": "kpou", "rhum": "kpou", "prcp": "kpou", "wspd": "kpou", "wdir": "kpou", "lwet": "mar", "srad": "mar"},
"1fr" : {"temp": "kdkk", "rhum": "kdkk", "prcp": "kdkk", "wspd": "kdkk", "wdir": "kdkk", "lwet": "ede", "st4i": "pav", "srad": "loc"},
"fre" : {"temp": "cu_gfr", "rhum": "cu_gfr", "prcp": "cu_gfr", "wspd": "cu_gfr", "srad": "cu_gfr", "wdir": "cu_gfr", "lwet": "ith"},
"fri" : {"temp": "pot", "lwet": "pot", "prcp": "pot"},
"fts" : {"temp": "npt", "rhum": "npt", "prcp": "npt", "wspd": "npt", "wdir": "npt", "lwet": "npt", "srad": "npt"},
"gai" : {"temp": "kdsv", "rhum": "kdsv", "prcp": "kdsv"},
"gbe" : {"temp": "gen", "rhum": "gen", "prcp": "gen", "wspd": "drs", "wdir": "drs", "lwet": "gen", "srad": "drs"},
"gen" : {"temp": "gbe", "rhum": "gbe", "prcp": "gbe", "wspd": "gbe", "wdir": "gbe", "lwet": "gbe", "srad": "gbe"},
"gfr" : {"temp": "cu_gfr", "lwet": "ith", "prcp": "cu_gfr", "rhum": "cu_gfr", "wspd": "cu_gfr", "wdir": "cu_gfr", "srad": "cu_gfr"},
"gra" : {"temp": "kgfl", "rhum": "kgfl", "prcp": "kgfl", "wspd": "kgfl", "wdir": "kgfl", "lwet": "ved", "srad": "ved"},
"gro" : {"temp": "kdsv", "rhum": "kdsv", "prcp": "kdsv"},
"gui" : {"temp": "kalb", "rhum": "kalb", "prcp": "kalb", "wspd": "kalb", "wdir": "kalb", "lwet": "cli", "srad": "cli"},
"ham" : {"temp": "bra", "rhum": "bra", "prcp": "bra", "wspd": "bra", "wdir": "bra", "lwet": "bra", "srad": "bra"},
"har" : {"temp": "keri", "rhum": "keri", "prcp": "keri", "wspd": "keri", "wdir": "keri", "lwet": "por", "srad": "por"},
"hec" : {"temp": "lod", "lwet": "lod", "rhum": "lod", "prcp": "lod", "wspd": "lod", "wdir": "lod", "srad": "lod"},
"hig" : {"temp": "hvl", "lwet": "hvl", "rhum": "hvl", "prcp": "hvl", "wspd": "hvl", "wdir": "hvl", "srad": "hvl"},
"him" : {"temp": "lod", "lwet": "lod", "prcp": "lod"},
"hud" : {"temp": "cas", "lwet": "cas", "rhum": "cas", "prcp": "cas", "wspd": "cu_val", "wdir": "cu_val", "srad": "cas"},
"hur" : {"temp": "npz", "lwet": "npz", "rhum": "npz", "prcp": "npz", "wspd": "npz", "wdir": "npz", "srad": "npz"},
"hvl" : {"temp": "hig", "lwet": "hig", "rhum": "hig", "prcp": "hig", "wspd": "hig", "wdir": "hig", "srad": "mar"},
"int" : {"temp": "rom", "rhum": "rbg", "prcp": "ovi", "wspd": "rom", "wdir": "rom", "lwet": "ovi", "srad": "rom"},
"ith" : {"temp": "cu_gfr", "prcp": "cu_gfr", "lwet": "fre", "rhum": "cu_gfr", "wspd": "cu_gfr", "wdir": "cu_gfr", "srad": "ovi"},
"kee" : {"temp": "kslk", "rhum": "kslk", "prcp": "kslk", "wspd": "kslk", "wdir": "kslk", "lwet": "wlb", "srad": "wlb"},
"ken" : {"temp": "lyn", "lwet": "lyn", "rhum": "lyn", "prcp": "lyn", "wspd": "lyn", "wdir": "lyn", "srad": "kno"},
"kin" : {"temp": "hud", "rhum": "hud", "prcp": "hud", "wspd": "hud", "wdir": "hud", "lwet": "hud", "srad": "hud"},
"kno" : {"temp": "lyn", "lwet": "lyn", "rhum": "lyn", "prcp": "lyn", "wspd": "lyn", "wdir": "lyn", "srad": "med"},
"laf" : {"temp": "ksyr", "rhum": "ksyr", "prcp": "ksyr", "wspd": "ksyr", "wdir": "ksyr", "lwet": "fre", "srad": "bal"},
"lak" : {"temp": "lod", "rhum": "hec", "prcp": "hec", "wspd": "hec", "wdir": "hec", "lwet": "hec", "srad": "hec"},
"lan" : {"temp": "fre", "lwet": "fre", "rhum": "kith", "prcp": "fre", "wspd": "kith", "srad": "cu_gfr", "wdir": "kith"},
"1lo" : {"temp": "loc", "lwet": "loc", "rhum": "loc", "prcp": "loc", "wspd": "loc", "srad": "loc", "wdir": "kiag"},
"lkp" : {"temp": "kslk", "rhum": "kslk", "lwet": "per", "prcp": "kslk", "wspd": "kslk", "wdir": "kslk", "srad": "vso"},
"lod" : {"temp": "hec", "lwet": "hec", "rhum": "hec", "prcp": "hec", "wspd": "hec", "wdir": "hec", "srad": "hec"},
"los" : {"temp": "lod", "lwet": "lod", "rhum": "lod", "prcp": "lod", "wspd": "lod", "wdir": "lod", "srad": "lod"},
"lol" : {"temp": "lod", "lwet": "lod", "rhum": "lod", "prcp": "lod", "wspd": "lod", "wdir": "lod", "srad": "lod"},
"lyn" : {"temp": "kno", "lwet": "kno", "rhum": "kno", "prcp": "kno", "wspd": "kno", "wdir": "kno", "srad": "kno"},
"man" : {"temp": "riv", "rhum": "riv", "prcp": "riv", "wspd": "riv", "wdir": "riv", "lwet": "riv", "srad": "riv"},
"mar" : {"temp": "kpou", "rhum": "kpou", "prcp": "kpou", "wspd": "kpou", "wdir": "kpou", "lwet": "hig", "srad": "hvl"},
"mat" : {"temp": "rvm", "rhum": "rvm", "prcp": "rvm", "wspd": "rvm", "wdir": "rvm", "lwet": "rvm", "srad": "rvm"},
"med" : {"temp": "lyn", "lwet": "lyn", "rhum": "lyn", "prcp": "lyn", "wspd": "lyn", "wdir": "lyn", "srad": "kno"},
"mex" : {"temp": "scr", "lwet": "scr", "prcp": "scr"},
"mil" : {"temp": "mar", "lwet": "mar", "rhum": "mar", "prcp": "mar", "wspd": "mar", "wdir": "mar", "srad": "mar"},
"mlc" : {"temp": "mil", "lwet": "mil", "rhum": "mil", "prcp": "mil", "wspd": "mil", "wdir": "mil", "srad": "mil"},
"mod" : {"temp": "kpou", "lwet": "hig", "rhum": "kpou", "prcp": "kpou", "wspd": "kpou", "wdir": "kpou", "srad": "hvl"},
"mtd" : {"temp": "mts", "rhum": "mts", "prcp": "mts", "wspd": "mts", "wdir": "mts", "lwet": "mts", "srad": "mts"},
"mts" : {"temp": "mtd", "rhum": "mtd", "prcp": "mtd", "wspd": "mtd", "wdir": "mtd", "lwet": "mtd", "srad": "mtd"},
"nap" : {"temp": "fri", "lwet": "fri", "prcp": "fri"},
"nea" : {"temp": "cli", "rhum": "cli", "prcp": "cli", "wspd": "cli", "wdir": "cli", "lwet": "cli", "srad": "cli"},
"nee" : {"temp": "nel", "rhum": "nel", "prcp": "nel", "wspd": "nel", "wdir": "nel", "lwet": "nel", "srad": "har"},
"nel" : {"temp": "nee", "rhum": "nee", "prcp": "nee", "wspd": "nee", "wdir": "nee", "lwet": "nee", "srad": "nee"},
"npt" : {"temp": "kisp", "rhum": "kisp", "prcp": "kisp", "wspd": "kisp", "wdir": "kisp", "lwet": "brh", "srad": "brh"},
"npz" : {"temp": "hig", "lwet": "hig", "rhum": "hig", "prcp": "hig", "wspd": "hig", "wdir": "hig", "srad": "hvl"},
"npw" : {"temp": "hig", "lwet": "hig", "rhum": "hig", "prcp": "hig", "wspd": "hig", "wdir": "hig", "srad": "hvl"},
"ovi" : {"temp": "lod", "rhum": "lod", "prcp": "lod", "wspd": "lod", "wdir": "lod", "lwet": "lod", "srad": "lod"},
"pav" : {"temp": "bat", "prcp": "bat", "st4i": "bat"},
"per" : {"temp": "chz", "rhum": "chz", "prcp": "chz", "wspd": "chz", "wdir": "chz", "srad": "vsh", "lwet": "chz"},
"pno" : {"temp": "per", "rhum": "per", "lwet": "per", "prcp": "per", "wspd": "per", "wdir": "per", "srad": "per"},
"phe" : {"temp": "gen", "rhum": "gen", "prcp": "gen", "wspd": "gen", "wdir": "gen", "lwet": "gen", "srad": "gbe"},
"por" : {"temp": "kdkk", "rhum": "kdkk", "prcp": "kdkk", "wspd": "kdkk", "wdir": "kdkk", "lwet": "poe", "srad": "sil"},
"pr5" : {"temp": "por", "rhum": "por", "prcp": "por", "wspd": "por", "wdir": "por", "srad": "por", "lwet": "por"},
"poe" : {"temp": "por", "rhum": "por", "prcp": "por", "wspd": "por", "wdir": "por", "srad": "por", "lwet": "por"},
"pot" : {"temp": "fri", "lwet": "fri", "prcp": "fri", "rhum": "kpeo"},
"pra" : {"temp": "pul", "rhum": "pul", "prcp": "pul"},
"ptb" : {"temp": "kno", "lwet": "kno", "rhum": "kno", "prcp": "kno", "wspd": "kno", "wdir": "kno", "srad": "kno"},
"pul" : {"temp": "bra", "lwet": "bra", "rhum": "bra", "prcp": "bra"},
"loc" : {"temp": "som", "lwet": "som", "rhum": "som", "prcp": "som", "wspd": "som", "srad": "som"},
"rbg" : {"temp": "rom", "rhum": "rom", "prcp": "rom", "wspd": "rom", "wdir": "rom", "lwet": "rom", "srad": "rom"},
"red" : {"temp": "kpou", "rhum": "kpou", "prcp": "kpou", "lwet": "hud", "wspd": "kpou", "wdir": "kpou", "srad": "hud"},
"rip" : {"temp": "por", "rhum": "por", "prcp": "por", "lwet": "por", "wspd": "por", "wdir": "por", "srad": "por"},
"riv" : {"temp": "rvp", "rhum": "rvp", "prcp": "rvp", "lwet": "rvp", "wspd": "rvp", "wdir": "rvp", "srad": "rvp"},
"rtw" : {"temp": "kswf", "rhum": "kswf", "prcp": "kswf", "lwet": "mar", "wspd": "kswf", "wdir": "kswf", "srad": "mar"},
"rvm" : {"temp": "rvp", "rhum": "rvp", "prcp": "rvp", "lwet": "rvp", "wspd": "rvp", "wdir": "rvp", "srad": "rvp"},
"rvp" : {"temp": "riv", "rhum": "riv", "prcp": "riv", "lwet": "riv", "wspd": "riv", "wdir": "riv", "srad": "riv"},
"rom" : {"temp": "var", "rhum": "var", "prcp": "var", "wspd": "var", "wdir": "var", "lwet": "var", "srad": "var"},
"sav" : {"temp": "gbe", "rhum": "gbe", "prcp": "gbe"},
"scr" : {"temp": "kfzy", "lwet": "laf", "prcp": "kfzy", "rhum": "kfzy", "wspd": "kfzy", "wdir": "kfzy", "srad": "wol"},
"sdl" : {"temp": "sod", "lwet": "sod", "rhum": "sod", "prcp": "sod", "wspd": "sod", "wdir": "sod", "srad": "3wi"},
"shc" : {"temp": "cns", "lwet": "cns", "rhum": "cns", "prcp": "cns", "wspd": "cns", "wdir": "cns", "srad": "cns"},
"shd" : {"temp": "shc", "lwet": "shc", "rhum": "shc", "prcp": "shc", "wspd": "shc", "wdir": "shc", "srad": "shc"},
"shm" : {"temp": "shd", "lwet": "shd", "rhum": "shd", "prcp": "shd", "wspd": "shd", "wdir": "shd", "srad": "shd"},
"she" : {"temp": "sil", "lwet": "sil", "rhum": "sil", "prcp": "sil", "wspd": "sil", "wdir": "sil", "srad": "sil"},
"sil" : {"temp": "kdkk", "lwet": "por", "rhum": "kdkk", "prcp": "kdkk", "wspd": "kdkk", "wdir": "kdkk", "srad": "por"},
"sod" : {"temp": "sdl", "lwet": "sdl", "rhum": "sdl", "prcp": "sdl", "wspd": "sdl", "wdir": "sdl", "srad": "wbs"},
"som" : {"temp": "noa", "lwet": "noa", "rhum": "noa", "prcp": "noa", "wspd": "noa", "wdir": "noa", "srad": "noa"},
"val" : {"temp": "wgl", "lwet": "wgl", "rhum": "wgl", "prcp": "wgl"},
"var" : {"temp": "rom", "rhum": "rom", "prcp": "rom", "wspd": "rom", "wdir": "rom", "lwet": "rom", "srad": "rom"},
"vca" : {"temp": "kmpv", "rhum": "kmpv", "prcp": "kmpv", "wspd": "kmpv", "wdir": "kmpv", "lwet": "vsb", "srad": "vsb"},
"vem" : {"temp": "kmpv", "rhum": "kmpv", "prcp": "kmpv", "wspd": "kmpv", "wdir": "kmpv", "lwet": "vex", "srad": "vex"},
"vet" : {"temp": "kleb", "rhum": "kleb", "prcp": "kleb", "wspd": "kleb", "wdir": "kleb", "lwet": "nh_pla", "srad": "nh_pla"},
"vco" : {"temp": "vsh", "rhum": "vsh", "prcp": "vsh", "wspd": "vsh", "wdir": "vsh", "srad": "vsh", "lwet": "vsh"},
"vdu" : {"temp": "vpu", "rhum": "vpu", "prcp": "vpu", "wspd": "vpu", "wdir": "vpu", "lwet": "vpu", "srad": "vpu"},
"ver" : {"temp": "sil", "lwet": "sil", "rhum": "sil", "prcp": "sil", "wspd": "sil", "wdir": "sil", "srad": "sil"},
"vlt" : {"temp": "cas", "lwet": "cas", "rhum": "cas", "prcp": "cas", "wspd": "cas", "wdir": "cas", "srad": "cas"},
"vrf" : {"temp": "cas", "lwet": "cas", "rhum": "cas", "prcp": "cas", "wspd": "cas", "wdir": "cas", "srad": "cas"},
"vsb" : {"temp": "kbtv", "rhum": "kbtv", "prcp": "kbtv", "wspd": "kbtv", "wdir": "kbtv", "lwet": "vso", "srad": "vso"},
"vex" : {"temp": "kbtv", "rhum": "kbtv", "prcp": "kbtv", "wspd": "kbtv", "wdir": "kbtv", "lwet": "vsb", "srad": "vsb"},
"vsh" : {"temp": "krut", "rhum": "krut", "prcp": "krut", "wspd": "krut", "wdir": "krut", "lwet": "cro", "srad": "ved"},
"vso" : {"temp": "kbtv", "rhum": "kbtv", "prcp": "kbtv", "wspd": "kbtv", "wdir": "kbtv", "lwet": "vsb", "srad": "vsb"},
"ved" : {"temp": "krut", "rhum": "krut", "prcp": "krut", "wspd": "krut", "wdir": "krut", "lwet": "vsh", "srad": "vsh"},
"vol" : {"temp": "kfzy", "lwet": "bla", "prcp": "kfzy", "rhum": "kfzy", "wspd": "kfzy", "wdir": "kfzy", "srad": "bla"},
"vpu" : {"temp": "vdu", "rhum": "vdu", "prcp": "vdu", "wspd": "vdu", "wdir": "vdu", "lwet": "vdu", "srad": "vbe"},
"vbe" : {"temp": "kddh", "rhum": "kddh", "prcp": "kddh", "wspd": "kddh", "wdir": "kddh", "lwet": "vdu", "srad": "vpu"},
"wal" : {"temp": "kswf", "rhum": "kswf", "prcp": "kswf", "wspd": "kswf", "wdir": "kswf", "lwet": "mod", "srad": "mod"},
"wat" : {"temp": "ash", "lwet": "ash", "rhum": "ash", "prcp": "ash", "wspd": "ash", "wdir": "ash"},
"wgl" : {"temp": "wla", "rhum": "wla", "prcp": "wla", "wspd": "wla", "wdir": "wla", "lwet": "wla", "srad": "wla"},
"wad" : {"temp": "riv", "rhum": "riv", "prcp": "riv", "lwet": "riv", "wspd": "riv", "wdir": "riv", "srad": "riv"},
"wes" : {"temp": "por", "rhum": "por", "prcp": "por", "wspd": "por", "wdir": "por", "srad": "por", "lwet": "por"},
"wla" : {"temp": "wgl", "rhum": "wgl", "prcp": "wgl", "wspd": "lod", "wdir": "lod", "lwet": "wgl", "srad": "lod"},
"wlb" : {"temp": "vsb", "rhum": "vsb", "prcp": "vsb", "wspd": "vsb", "wdir": "vsb", "lwet": "vsb", "srad": "vsb"},
"way" : {"temp": "kdsv", "rhum": "kdsv", "prcp": "kdsv", "wspd": "kdsv", "srad": "drs"},
"wmi" : {"temp": "kmtp", "lwet": "cut", "rhum": "kmtp", "prcp": "kmtp", "wspd": "kmtp", "wdir": "kmtp", "srad": "cut"},
"wmn" : {"temp": "wmi", "rhum": "wmi", "prcp": "wmi", "wspd": "wmi", "wdir": "wmi", "lwet": "wmi", "srad": "cns"},
"wol" : {"temp": "3wi", "lwet": "3wi", "rhum": "3wi", "prcp": "3wi", "wspd": "3wi", "wdir": "3wi", "srad": "wbs"},
"yap" : {"temp": "khwv", "rhum": "khwv", "prcp": "khwv", "wspd": "khwv", "wdir": "khwv", "lwet": "man", "srad": "brh"},
"1wi" : {"temp": "3wi", "lwet": "3wi", "rhum": "3wi", "prcp": "3wi"},
"2wi" : {"temp": "3wi", "lwet": "3wi", "rhum": "3wi", "prcp": "3wi", "wspd": "3wi", "wdir": "3wi", "srad": "wbs"},
"3wi" : {"temp": "2wi", "lwet": "2wi", "rhum": "2wi", "prcp": "2wi", "wspd": "sod", "wdir": "sod", "srad": "wbs"},
"wbs" : {"temp": "3wi", "lwet": "3wi", "rhum": "3wi", "prcp": "3wi", "wspd": "3wi", "wdir": "3wi", "srad": "2wi"},
"wor" : {"temp": "3wi", "lwet": "3wi", "rhum": "3wi", "prcp": "3wi", "wspd": "3wi", "wdir": "3wi", "srad": "3wi"},
"avo" : {"temp": "kroc", "rhum": "kroc", "prcp": "kroc"},
"sho" : {"temp": "cro", "rhum": "cro", "prcp": "cro", "wspd": "cro", "wdir": "cro", "lwet": "cro", "srad": "cro"},
"mad" : {"temp": "kmss", "rhum": "kmss", "prcp": "kmss", "wspd": "kmss", "wdir": "kmss"},
"paf" : {"temp": "per", "rhum": "per", "prcp": "per", "wspd": "per", "wdir": "per"},
"mbf" : {"temp": "kmss", "rhum": "kmss", "prcp": "kmss", "wspd": "kmss", "wdir": "kmss"},
"pbd" : {"temp": "chz", "rhum": "chz", "prcp": "chz", "wspd": "chz", "wdir": "chz"},
"pcf" : {"temp": "chz", "rhum": "chz", "prcp": "chz", "wspd": "chz", "wdir": "chz"},
"pdf" : {"temp": "per", "rhum": "per", "prcp": "per", "wspd": "per", "wdir": "per"},
"sar" : {"temp": "gkd", "rhum": "gkd", "prcp": "gkd", "wspd": "gkd", "wdir": "gkd"},
"hid" : {"temp": "kgfl", "rhum": "kgfl", "prcp": "kgfl", "wspd": "kgfl", "wdir": "kgfl"},
"chm" : {"temp": "chz", "rhum": "chz", "prcp": "chz", "wspd": "chz", "wdir": "chz"},
"ora" : {"temp": "kmss", "rhum": "kmss", "prcp": "kmss", "wspd": "kmss", "wdir": "kmss"},
"ams" : {"temp": "gui", "rhum": "gui", "prcp": "gui", "wspd": "gui", "wdir": "gui"},
"ori" : {"temp": "ksyr", "rhum": "ksyr", "prcp": "ksyr", "wspd": "ksyr", "wdir": "ksyr"},
"gws" : {"temp": "kgfl", "rhum": "kgfl", "prcp": "kgfl", "wspd": "kgfl", "wdir": "kgfl"},
"cng" : {"temp": "kmss", "rhum": "kmss", "prcp": "kmss", "wspd": "kmss", "wdir": "kmss"},
"gkd" : {"temp": "kgfl", "rhum": "kgfl", "prcp": "kgfl", "wspd": "kgfl", "wdir": "kgfl"},
"pcv" : {"temp": "per", "rhum": "per", "prcp": "per", "wspd": "per", "wdir": "per"},
"ell" : {"temp": "chz", "rhum": "chz", "prcp": "chz", "wspd": "chz", "wdir": "chz"},
"sce" : {"temp": "cli", "rhum": "cli", "prcp": "cli", "wspd": "cli", "wdir": "cli"},
"mcd" : {"temp": "kmss", "rhum": "kmss", "prcp": "kmss", "wspd": "kmss", "wdir": "kmss"},
"skr" : {"temp": "cli", "rhum": "cli", "prcp": "cli", "wspd": "cli", "wdir": "cli"},
"mbe" : {"temp": "um_cso", "rhum": "um_cso", "prcp": "um_cso", "wspd": "um_cso", "wdir": "um_cso", "lwet": "um_cso", "srad": "um_cso"},
"msd" : {"temp": "korh", "rhum": "korh", "prcp": "korh", "wspd": "korh", "wdir": "korh", "lwet": "mas", "srad": "mbe"},
"hwa" : {"temp": "vpu", "rhum": "vpu", "prcp": "vpu", "wspd": "vpu", "wdir": "vpu", "lwet": "vpu", "srad": "vpu"},
"mdr" : {"temp": "klwm", "rhum": "klwm", "prcp": "klwm", "wspd": "klwm", "wdir": "klwm", "lwet": "mty", "srad": "mty"},
"mam" : {"temp": "klwm", "rhum": "klwm", "prcp": "klwm", "wspd": "klwm", "wdir": "klwm", "lwet": "mdr", "srad": "mna"},
"vsa" : {"temp": "vpu", "rhum": "vpu", "prcp": "vpu", "wspd": "vpu", "wdir": "vpu", "lwet": "vpu", "srad": "vpu"},
"mty" : {"temp": "mdr", "rhum": "mdr", "prcp": "mdr", "wspd": "mdr", "wdir": "mdr", "lwet": "mdr", "srad": "mna"},
"mst" : {"temp": "msw", "rhum": "msw", "prcp": "msw", "wspd": "msw", "wdir": "msw", "lwet": "msw", "srad": "msw"},
"mwe" : {"temp": "kbaf", "rhum": "kbaf", "prcp": "kbaf", "wspd": "kbaf", "wdir": "kbaf", "lwet": "um_cso", "srad": "mbe"},
"mbo" : {"temp": "msw", "rhum": "msw", "prcp": "msw", "wspd": "msw", "wdir": "msw", "lwet": "msw", "srad": "mha"},
"mas" : {"temp": "msd", "rhum": "msd", "prcp": "msd", "wspd": "msd", "wdir": "msd", "lwet": "msd", "srad": "um_clk"},
"meb" : {"temp": "ktan", "rhum": "ktan", "prcp": "ktan", "wspd": "ktan", "wdir": "ktan", "lwet": "um_tff", "srad": "um_whs"},
"mre" : {"temp": "kewb", "rhum": "kewb", "prcp": "kewb", "wspd": "kewb", "wdir": "kewb", "lwet": "um_tff", "srad": "meb"},
"mha" : {"temp": "msw", "rhum": "msw", "prcp": "msw", "wspd": "msw", "wdir": "msw", "lwet": "msw", "srad": "msw"},
"msw" : {"temp": "mst", "rhum": "mst", "prcp": "mst", "wspd": "mst", "wdir": "mst", "lwet": "mst", "srad": "mha"},
"msh" : {"temp": "kfmh", "rhum": "kfmh", "prcp": "kfmh", "wspd": "kfmh", "wdir": "kfmh", "lwet": "meb", "srad": "um_whs"},
"mwa" : {"temp": "um_whs", "rhum": "um_whs", "prcp": "um_whs", "wspd": "kbos", "wdir": "kbos", "lwet": "um_whs", "srad": "um_whs"},
"mno" : {"temp": "korh", "rhum": "korh", "prcp": "korh", "wspd": "korh", "wdir": "korh", "lwet": "msw", "srad": "msw"},
"mna" : {"temp": "klwm", "rhum": "klwm", "prcp": "klwm", "wspd": "klwm", "wdir": "klwm", "lwet": "mdr", "srad": "mam"},
"mnb" : {"temp": "msh", "rhum": "msh", "prcp": "msh", "wspd": "msh", "wdir": "msh", "lwet": "msh", "srad": "msh"},
"mle" : {"temp": "kfit", "rhum": "kfit", "prcp": "kfit", "wspd": "kfit", "wdir": "kfit", "lwet": "mbo", "srad": "mbo"},
"mph" : {"temp": "kore", "rhum": "kore", "prcp": "kore", "wspd": "kore", "wdir": "kore", "lwet": "msd", "srad": "mle"},
"mip" : {"temp": "kbvy", "rhum": "kbvy", "prcp": "kbvy", "wspd": "kbvy", "wdir": "kbvy", "lwet": "mam", "srad": "mam"},
"mum" : {"temp": "kcef", "rhum": "kcef", "prcp": "kcef", "wspd": "kcef", "wdir": "kcef", "lwet": "um_cso", "srad": "um_cso"},
"nh_hol" : {"temp": "kash", "rhum": "kash", "prcp": "kash", "wspd": "kash", "wdir": "kash", "lwet": "mty", "srad": "mna"},
"nh_bos" : {"temp": "kcon", "rhum": "kcon", "prcp": "kcon", "wspd": "kcon", "wdir": "kcon", "lwet": "nh_hol", "srad": "nh_hol"},
"nh_bre" : {"temp": "kdaw", "rhum": "kdaw", "prcp": "kdaw", "wspd": "kdaw", "wdir": "kdaw", "lwet": "mam", "srad": "mam"},
"nh_dur" : {"temp": "kdaw", "rhum": "kdaw", "prcp": "kdaw", "wspd": "kdaw", "wdir": "kdaw", "lwet": "mam", "srad": "mam"},
"nh_mer" : {"temp": "klci", "rhum": "klci", "prcp": "klci", "wspd": "klci", "wdir": "klci", "lwet": "nh_dur", "srad": "nh_dur"},
"nh_oss" : {"temp": "klci", "rhum": "klci", "prcp": "klci", "wspd": "klci", "wdir": "klci", "lwet": "nh_dur", "srad": "nh_dur"},
"nh_wal" : {"temp": "keen", "rhum": "keen", "prcp": "keen", "wspd": "keen", "wdir": "keen", "lwet": "vpu", "srad": "vpu"},
"nh_col" : {"temp": "kbml", "rhum": "kbml", "prcp": "kbml", "wspd": "kbml", "wdir": "kbml", "lwet": "vem", "srad": "vem"},
"nh_pla" : {"temp": "kleb", "rhum": "kleb", "prcp": "kleb", "wspd": "kleb", "wdir": "kleb", "lwet": "nh_bos", "srad": "nh_bos"},
"nh_gof" : {"temp": "kmht", "rhum": "kmht", "prcp": "kmht", "wspd": "kmht", "wdir": "kmht", "lwet": "nh_hol", "srad": "nh_hol"},
"nh_nha" : {"temp": "kmpv", "rhum": "kmpv", "prcp": "kmpv", "wspd": "kmpv", "wdir": "kmpv", "lwet": "vem", "srad": "vem"},
"wi_gay" : {"temp": "kovs", "rhum": "kovs", "prcp": "kovs", "wspd": "kovs", "wdir": "kovs", "lwet": "mn_lac", "srad": "mn_lac"},
"wi_ver" : {"temp": "kmsn", "rhum": "kmsn", "prcp": "kmsn", "wspd": "kmsn", "wdir": "kmsn", "lwet": "wi_gay", "srad": "wi_gay"},
"um_whs" : {"temp": "kmqe", "rhum": "kmqe", "prcp": "kmqe", "wspd": "kmqe", "wdir": "kmqe", "lwet": "msh", "srad": "mwa"},
"um_cso" : {"temp": "mbe", "rhum": "mbe", "prcp": "mbe", "wspd": "kcef", "wdir": "kcef", "lwet": "mbe", "srad": "um_clk"},
"um_tff" : {"temp": "korh", "rhum": "korh", "prcp": "korh", "wspd": "korh", "wdir": "korh", "lwet": "um_cso", "srad": "um_cso"},
"um_clk" : {"temp": "msd", "rhum": "msd", "prcp": "msd", "wspd": "msd", "wdir": "msd", "lwet": "msd", "srad": "mph"},
"um_new" : {"temp": "kpve", "rhum": "kpvd", "prcp": "kpvd", "wspd": "kpvd", "wdir": "kpvd", "lwet": "meb", "srad": "ct_gfy"},
"um_bcf" : {"temp": "khya", "rhum": "khya", "prcp": "khya", "wspd": "khya", "wdir": "khya", "lwet": "meb"},
"um_ces" : {"temp": "mwa", "rhum": "mwa", "prcp": "mwa", "wspd": "mwa", "wdir": "mwa", "lwet": "mwa", "srad": "mwa"},
"um_pho" : {"temp": "kcef", "rhum": "kcef", "prcp": "kcef", "wspd": "kcef", "wdir": "kcef", "lwet": "um_cso", "srad": "um_cso"},
"un_nec" : {"temp": "koma", "prcp": "koma", "rhum": "koma", "wspd": "koma", "wdir": "koma", "srad": "koma"},
"cu_aur" : {"temp": "cu_gfr", "rhum": "cu_gfr", "prcp": "cu_gfr", "st4i": "cu_gfr", "wspd": "cu_gfr", "wdir": "cu_gfr", "srad": "cu_gfr"},
"cu_chz" : {"temp": "chz", "rhum": "chz", "prcp": "chz", "wspd": "chz", "wdir": "chz", "st4i": "cu_wlb", "srad": "cu_wlb"},
"cu_gfr" : {"temp": "ith", "prcp": "ith", "rhum": "ith", "st4i": "cu_aur", "wspd": "ith", "wdir": "ith", "srad": "aur"},
"cu_lkp" : {"temp": "kslk", "rhum": "kslk", "prcp": "kslk", "wspd": "kslk", "wdir": "kslk", "st4i": "cu_wlb", "srad": "cu_wlb"},
"cu_val" : {"temp": "hud", "rhum": "hud", "prcp": "hud", "wspd": "hud", "wdir": "hud", "srad": "cu_wlb", "st4i": "cu_gfr"},
"cu_wlb" : {"temp": "vsb", "rhum": "vsb", "prcp": "vsb", "wspd": "vsb", "wdir": "vsb", "srad": "cu_chz", "st4i": "cu_chz"},
"kalb" : {"temp": "gui", "rhum": "gui", "prcp": "gui", "wspd": "gui", "wdir": "gui"},
"kbgm" : {"temp": "cu_gfr", "rhum": "cu_gfr", "prcp": "cu_gfr", "wspd": "cu_gfr", "wdir": "cu_gfr"},
"kbfd" : {"temp": "kelz", "rhum": "kelz", "prcp": "kelz", "wspd": "kelz", "wdir": "kelz"},
"khwv" : {"temp": "kisp", "rhum": "kisp", "prcp": "kisp", "wspd": "kisp", "wdir": "kisp"},
"kbuf" : {"temp": "kiag", "rhum": "kiag", "prcp": "kiag", "wspd": "kiag", "wdir": "kiag"},
"kbtv" : {"temp": "cu_wlb", "rhum": "cu_wlb", "prcp": "cu_wlb", "wspd": "cu_wlb", "wdir": "cu_wlb"},
"kvsf" : {"temp": "krut", "rhum": "krut", "prcp": "krut", "wspd": "krut", "wdir": "krut"},
"kdsv" : {"temp": "way", "rhum": "way", "prcp": "way", "wspd": "way", "wdir": "kelz"},
"kdkk" : {"temp": "kjhw", "rhum": "kjhw", "prcp": "kjhw", "wspd": "kjhw", "wdir": "kjhw"},
"kelm" : {"temp": "wgl", "rhum": "wgl", "prcp": "wgl", "wspd": "kbgm", "wdir": "kbgm"},
"keri" : {"temp": "kdkk", "rhum": "kdkk", "prcp": "kdkk", "wspd": "kdkk", "wdir": "kdkk"},
"kfrg" : {"temp": "kisp", "rhum": "kisp", "prcp": "kisp", "wspd": "kisp", "wdir": "kisp"},
"kfzy" : {"temp": "vol", "rhum": "vol", "prcp": "vol", "wspd": "ksyr", "wdir": "ksyr"},
"kgfl" : {"temp": "kalb", "rhum": "kalb", "prcp": "kalb", "wspd": "kalb", "wdir": "kalb"},
"krme" : {"temp": "ksyr", "rhum": "ksyr", "prcp": "ksyr", "wspd": "ksyr", "wdir": "ksyr"},
"kisp" : {"temp": "khwv", "rhum": "khwv", "prcp": "kfrg", "wspd": "khwv", "wdir": "khwv"},
"kith" : {"temp": "cu_gfr", "rhum": "cu_gfr", "prcp": "cu_gfr", "wspd": "cu_gfr", "wdir": "cu_gfr"},
"kjhw" : {"temp": "kdkk", "rhum": "kdkk", "prcp": "kdkk", "wspd": "kdkk", "wdir": "kdkk"},
"kmss" : {"temp": "kslk", "rhum": "kslk", "prcp": "kslk", "wspd": "kslk", "wdir": "kslk"},
"kmgj" : {"temp": "kswf", "rhum": "kswf", "prcp": "kswf", "wspd": "kswf", "wdir": "kswf"},
"kmtp" : {"temp": "kfok", "rhum": "kfok", "prcp": "kfok", "wspd": "kfok", "wdir": "kfok"},
"kmsv" : {"temp": "kavp", "rhum": "kavp", "prcp": "kavp", "wspd": "kavp", "wdir": "kavp"},
"knyc" : {"temp": "klga", "rhum": "klga", "prcp": "klga", "wspd": "klga", "wdir": "klga"},
"kjfk" : {"temp": "klga", "rhum": "klga", "prcp": "klga", "wspd": "klga", "wdir": "klga"},
"klga" : {"temp": "knyc", "rhum": "knyc", "prcp": "knyc", "wspd": "knyc", "wdir": "knyc"},
"kiag" : {"temp": "kbuf", "rhum": "kbuf", "prcp": "kbuf", "wspd": "kbuf", "wdir": "kbuf"},
"kpeo" : {"temp": "bra", "rhum": "bra", "prcp": "bra", "wspd": "cu_aur", "wdir": "cu_aur"},
"kpou" : {"temp": "kswf", "rhum": "kswf", "prcp": "kswf", "wspd": "kswf", "wdir": "kswf"},
"kroc" : {"temp": "far", "rhum": "far", "prcp": "far", "wspd": "far", "wdir": "far"},
"kslk" : {"temp": "kmss", "rhum": "kmss", "prcp": "kmss", "wspd": "kmss", "wdir": "kmss"},
"kswf" : {"temp": "mar", "rhum": "mar", "prcp": "mar", "wspd": "mar", "wdir": "mar"},
"ksyr" : {"temp": "laf", "rhum": "laf", "prcp": "laf", "wspd": "laf", "wdir": "laf"},
"kfok" : {"temp": "khwv", "rhum": "khwv", "prcp": "khwv", "wspd": "khwv", "wdir": "khwv"},
"kart" : {"temp": "kgtb", "rhum": "kgtb", "prcp": "kgtb", "wspd": "kgtb", "wdir": "kgtb"},
"kgtb" : {"temp": "kart", "rhum": "kart", "prcp": "kart", "wspd": "kart", "wdir": "kart"},
"khpn" : {"temp": "klga", "rhum": "klga", "prcp": "klga", "wspd": "klga", "wdir": "klga"},
"kelz" : {"temp": "kbfd", "rhum": "kbfd", "prcp": "kbfd", "wspd": "kbfd", "wdir": "kbfd"},
"kbdr" : {"temp": "khvn", "rhum": "khvn", "prcp": "khvn", "wspd": "khvn", "wdir": "khvn"},
"kdxr" : {"temp": "kpou", "rhum": "kpou", "prcp": "kpou", "wspd": "kpou", "wdir": "kpou"},
"kddh" : {"temp": "krut", "rhum": "krut", "prcp": "krut", "wspd": "krut", "wdir": "krut"},
"krut" : {"temp": "kddh", "rhum": "kddh", "prcp": "kddh", "wspd": "kddh", "wdir": "kddh"},
"kmvl" : {"temp": "kmpv", "rhum": "kmpv", "prcp": "kmpv", "wspd": "kmpv", "wdir": "kmpv"},
"kmpv" : {"temp": "kmvl", "rhum": "kmvl", "prcp": "kmvl", "wspd": "kmvl", "wdir": "kmvl"},
"kpsf": {"temp": "kaqw", "rhum": "kaqw", "prcp": "kaqw", "wspd": "kaqw", "wdir": "kaqw"},
"kaqw": {"temp": "kpsf", "rhum": "kpsf", "prcp": "kpsf", "wspd": "kpsf", "wdir": "kpsf"},
"kbaf": {"temp": "kcef", "rhum": "kcef", "prcp": "kcef", "wspd": "kcef", "wdir": "kcef"},
"kcef": {"temp": "kbaf", "rhum": "kbaf", "prcp": "kbaf", "wspd": "kbaf", "wdir": "kbaf"},
"korh": {"temp": "kore", "rhum": "kore", "prcp": "kore", "wspd": "kore", "wdir": "kore"},
"kore": {"temp": "korh", "rhum": "korh", "prcp": "korh", "wspd": "korh", "wdir": "korh"},
"kfit": {"temp": "korh", "rhum": "korh", "prcp": "korh", "wspd": "korh", "wdir": "korh"},
"klwm": {"temp": "kbvy", "rhum": "kbvy", "prcp": "kbvy", "wspd": "kbvy", "wdir": "kbvy"},
"kbed": {"temp": "klwm", "rhum": "klwm", "prcp": "klwm", "wspd": "klwm", "wdir": "klwm"},
"kbvy": {"temp": "kbos", "rhum": "kbos", "prcp": "kbos", "wspd": "kbos", "wdir": "kbos"},
"kbos": {"temp": "kbvy", "rhum": "kbvy", "prcp": "kbvy", "wspd": "kbvy", "wdir": "kbvy"},
"kmqe": {"temp": "kowd", "rhum": "kowd", "prcp": "kowd", "wspd": "kowd", "wdir": "kowd"},
"kowd": {"temp": "msh", "rhum": "msh", "prcp": "msh", "wspd": "msh", "wdir": "msh"},
"knzw": {"temp": "kbos", "rhum": "kbos", "prcp": "kbos", "wspd": "kbos", "wdir": "kbos"},
"kpym": {"temp": "ktan", "rhum": "ktan", "prcp": "ktan", "wspd": "ktan", "wdir": "ktan"},
"ktan": {"temp": "kpym", "rhum": "kpym", "prcp": "kpym", "wspd": "kpym", "wdir": "kpym"},
"kewb": {"temp": "ktan", "rhum": "ktan", "prcp": "ktan", "wspd": "ktan", "wdir": "ktan"},
"kmvy": {"temp": "kack", "rhum": "kack", "prcp": "kack", "wspd": "kack", "wdir": "kack"},
"kack": {"temp": "kmvy", "rhum": "kmvy", "prcp": "kmvy", "wspd": "kmvy", "wdir": "kmvy"},
"kpvc": {"temp": "kcqx", "rhum": "kcqx", "prcp": "kcqx", "wspd": "kcqx", "wdir": "kcqx"},
"kcqx": {"temp": "khya", "rhum": "khya", "prcp": "khya", "wspd": "khya", "wdir": "khya"},
"khya": {"temp": "kfmh", "rhum": "kfmh", "prcp": "kfmh", "wspd": "kfmh", "wdir": "kfmh"},
"kfmh": {"temp": "khya", "rhum": "khya", "prcp": "khya", "wspd": "khya", "wdir": "khya"},
"kcdw": {"temp": "kteb", "rhum": "kteb", "prcp": "kteb", "wspd": "kteb", "wdir": "kteb"},
"kewr": {"temp": "knyc", "rhum": "knyc", "prcp": "knyc", "wspd": "knyc", "wdir": "knyc"},
"kfwn": {"temp": "kcdw", "rhum": "kcdw", "prcp": "kcdw", "wspd": "kcdw", "wdir": "kcdw"},
"kuuu": {"temp": "kpvd", "rhum": "kpvd", "prcp": "kpvd", "wspd": "kpvd", "wdir": "kpvd"},
"kpvd": {"temp": "kuuu", "rhum": "kuuu", "prcp": "kuuu", "wspd": "kuuu", "wdir": "kuuu"},
"kbdl": {"temp": "kbaf", "rhum": "kbaf", "prcp": "kbaf", "wspd": "kbaf", "wdir": "kbaf"},
"kteb": {"temp": "kewr", "rhum": "kewr", "prcp": "kewr", "wspd": "kewr", "wdir": "kewr"},
"k12n": {"temp": "kfwn", "rhum": "kfwn", "prcp": "kfwn", "wspd": "kfwn", "wdir": "kfwn"},
"kacy": {"temp": "232", "rhum": "232", "prcp": "232", "wspd": "232", "wdir": "232"},
"kblm": {"temp": "3397", "rhum": "3397", "prcp": "3397", "wspd": "3397", "wdir": "3397"},
"kmiv": {"temp": "284", "rhum": "284", "prcp": "284", "wspd": "284", "wdir": "284"},
"kmmu": {"temp": "ksmq", "rhum": "ksmq", "prcp": "ksmq", "wspd": "ksmq", "wdir": "ksmq"},
"knel": {"temp": "1032", "rhum": "1032", "prcp": "1032", "wspd": "1032", "wdir": "1032"},
"ksmq": {"temp": "kmmu", "rhum": "kmmu", "prcp": "kmmu", "wspd": "kmmu", "wdir": "kmmu"},
"kttn": {"temp": "kpne", "rhum": "kpne", "prcp": "kpne", "wspd": "kpne", "wdir": "kpne"},
"kvay": {"temp": "kpne", "rhum": "kpne", "prcp": "kpne", "wspd": "kpne", "wdir": "kpne"},
"kwri": {"temp": "kvay", "rhum": "kvay", "prcp": "kvay", "wspd": "kvay", "wdir": "kvay"},
"kwwd": {"temp": "261", "rhum": "261", "prcp": "261", "wspd": "261", "wdir": "261"},
"kphl": {"temp": "kpne", "rhum": "kpne", "prcp": "kpne", "wspd": "kpne", "wdir": "kpne"},
"kpne": {"temp": "kphl", "rhum": "kphl", "prcp": "kphl", "wspd": "kphl", "wdir": "kphl"},
"kpit": {"temp": "kjst", "rhum": "kjst", "prcp": "kjst", "wspd": "kjst", "wdir": "kjst"},
"kmdt": {"temp": "krdg", "rhum": "krdg", "prcp": "krdg", "wspd": "krdg", "wdir": "krdg"},
"kipt": {"temp": "kavp", "rhum": "kavp", "prcp": "kavp", "wspd": "kavp", "wdir": "kavp"},
"kavp": {"temp": "kbgm", "rhum": "kbgm", "prcp": "kbgm", "wspd": "kbgm", "wdir": "kbgm"},
"kabe": {"temp": "krdg", "rhum": "krdg", "prcp": "krdg", "wspd": "krdg", "wdir": "krdg"},
"kaoo": {"temp": "kjst", "rhum": "kjst", "prcp": "kjst", "wspd": "kjst", "wdir": "kjst"},
"krdg": {"temp": "kabe", "rhum": "kabe", "prcp": "kabe", "wspd": "kabe", "wdir": "kabe"},
"kjst": {"temp": "kaoo", "rhum": "kaoo", "prcp": "kaoo", "wspd": "kaoo", "wdir": "kaoo"},
"kduj": {"temp": "kbfd", "rhum": "kbfd", "prcp": "kbfd", "wspd": "kbfd", "wdir": "kbfd"},
"kilg": {"temp": "kphl", "rhum": "kphl", "prcp": "kphl", "wspd": "kphl", "wdir": "kphl"},
"kged": {"temp": "ksby", "rhum": "ksby", "prcp": "ksby", "wspd": "ksby", "wdir": "ksby"},
"ksby": {"temp": "kged", "rhum": "kged", "prcp": "kged", "wspd": "kged", "wdir": "kged"},
"kbwi": {"temp": "kdca", "rhum": "kdca", "prcp": "kdca", "wspd": "kdca", "wdir": "kdca"},
"kdca": {"temp": "kbwi", "rhum": "kbwi", "prcp": "kbwi", "wspd": "kbwi", "wdir": "kbwi"},
"koma": {"temp": "klnk", "rhum": "klnk", "prcp": "klnk", "wspd": "klnk", "wdir": "klnk"},
"klnk": {"temp": "koma", "rhum": "koma", "prcp": "koma", "wspd": "koma", "wdir": "koma"},
"kcid": {"temp": "kiow", "rhum": "kiow", "prcp": "kiow", "wspd": "kiow", "wdir": "kiow"},
"kiow": {"temp": "kcid", "rhum": "kcid", "prcp": "kcid", "wspd": "kcid", "wdir": "kcid"},
"kcon": {"temp": "kmht", "rhum": "kmht", "prcp": "kmht", "wspd": "kmht", "wdir": "kmht"},
"kafn": {"temp": "keen", "rhum": "keen", "prcp": "keen", "wspd": "keen", "wdir": "keen"},
"keen": {"temp": "kafn", "rhum": "kafn", "prcp": "kafn", "wspd": "kafn", "wdir": "kafn"},
"klci": {"temp": "kcon", "rhum": "kcon", "prcp": "kcon", "wspd": "kcon", "wdir": "kcon"},
"kdaw": {"temp": "kcon", "rhum": "kcon", "prcp": "kcon", "wspd": "kcon", "wdir": "kcon"},
"kleb": {"temp": "kvsf", "rhum": "kvsf", "prcp": "kvsf", "wspd": "kvsf", "wdir": "kvsf"},
"kbml": {"temp": "kmvl", "rhum": "kmvl", "prcp": "kmvl", "wspd": "kmvl", "wdir": "kmvl"},
"kash": {"temp": "kmht", "rhum": "kmht", "prcp": "kmht", "wspd": "kmht", "wdir": "kmht"},
"kmht": {"temp": "kcon", "rhum": "kcon", "prcp": "kcon", "wspd": "kcon", "wdir": "kcon"},
"kdlh": {"temp": "kstc", "rhum": "kstc", "prcp": "kstc", "wspd": "kstc", "wdir": "kstc"},
"kmsp": {"temp": "krst", "rhum": "krst", "prcp": "krst", "wspd": "krst", "wdir": "krst"},
"krst": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp"},
"kstc": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp"},
"kgpz": {"temp": "kdlh", "rhum": "kdlh", "prcp": "kdlh", "wspd": "kdlh", "wdir": "kdlh"},
"kfsd": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp"},
"kavl": {"temp": "khky", "rhum": "khky", "prcp": "khky", "wspd": "khky", "wdir": "khky"},
"khky": {"temp": "kclt", "rhum": "kclt", "prcp": "kclt", "wspd": "kclt", "wdir": "kclt"},
"kclt": {"temp": "khky", "rhum": "khky", "prcp": "khky", "wspd": "khky", "wdir": "khky"},
"kgsp": {"temp": "kavl", "rhum": "kavl", "prcp": "kavl", "wspd": "kavl", "wdir": "kavl"},
"kgso": {"temp": "kint", "rhum": "kint", "prcp": "kint", "wspd": "kint", "wdir": "kint"},
"krdu": {"temp": "kigx", "rhum": "kigx", "prcp": "kigx", "wspd": "kigx", "wdir": "kigx"},
"kakh": {"temp": "kclt", "rhum": "kclt", "prcp": "kclt", "wspd": "kclt", "wdir": "kclt"},
"kbuy": {"temp": "krdu", "rhum": "krdu", "prcp": "krdu", "wspd": "krdu", "wdir": "krdu"},
"keqy": {"temp": "kclt", "rhum": "kclt", "prcp": "kclt", "wspd": "kclt", "wdir": "kclt"},
"kfay": {"temp": "keqy", "rhum": "keqy", "prcp": "keqy", "wspd": "keqy", "wdir": "keqy"},
"kigx": {"temp": "krdu", "rhum": "krdu", "prcp": "krdu", "wspd": "krdu", "wdir": "krdu"},
"kint": {"temp": "kgso", "rhum": "kgso", "prcp": "kgso", "wspd": "kgso", "wdir": "kgso"},
"klbt": {"temp": "kfay", "rhum": "kfay", "prcp": "kfay", "wspd": "kfay", "wdir": "kfay"},
"kilm": {"temp": "kfay", "rhum": "kfay", "prcp": "kfay", "wspd": "kfay", "wdir": "kfay"},
"kmeb": {"temp": "kfay", "rhum": "kfay", "prcp": "kfay", "wspd": "kfay", "wdir": "kfay"},
"klse": {"temp": "krst", "rhum": "krst", "prcp": "krst", "wspd": "krst", "wdir": "krst"},
"kovs": {"temp": "klse", "rhum": "klse", "prcp": "klse", "wspd": "klse", "wdir": "klse"},
"kmsn": {"temp": "kovs", "rhum": "kovs", "prcp": "kovs", "wspd": "kovs", "wdir": "kovs"},
"krfd": {"temp": "karr", "rhum": "karr", "prcp": "karr", "wspd": "karr", "wdir": "karr"},
"karr": {"temp": "krfd", "rhum": "krfd", "prcp": "krfd", "wspd": "krfd", "wdir": "krfd"},
"kcho": {"temp": "kshd", "rhum": "kshd", "prcp": "kshd", "wspd": "kshd", "wdir": "kshd"},
"kshd": {"temp": "kcho", "rhum": "kcho", "prcp": "kcho", "wspd": "kcho", "wdir": "kcho"},
"kakq": {"temp": "kphf", "rhum": "kphf", "prcp": "kphf", "wspd": "kphf", "wdir": "kphf"},
"kdan": {"temp": "kroa", "rhum": "kroa", "prcp": "kroa", "wspd": "kroa", "wdir": "kroa"},
"khef": {"temp": "knyg", "rhum": "knyg", "prcp": "knyg", "wspd": "knyg", "wdir": "knyg"},
"kiad": {"temp": "kdca", "rhum": "kdca", "prcp": "kdca", "wspd": "kdca", "wdir": "kdca"},
"klyh": {"temp": "kroa", "rhum": "kroa", "prcp": "kroa", "wspd": "kroa", "wdir": "kroa"},
"kntu": {"temp": "korf", "rhum": "korf", "prcp": "korf", "wspd": "korf", "wdir": "korf"},
"knyg": {"temp": "kdca", "rhum": "kdca", "prcp": "kdca", "wspd": "kdca", "wdir": "kdca"},
"korf": {"temp": "kphf", "rhum": "kphf", "prcp": "kphf", "wspd": "kphf", "wdir": "kphf"},
"kphf": {"temp": "korf", "rhum": "korf", "prcp": "korf", "wspd": "korf", "wdir": "korf"},
"kric": {"temp": "kakq", "rhum": "kakq", "prcp": "kakq", "wspd": "kakq", "wdir": "kakq"},
"kroa": {"temp": "klyh", "rhum": "klyh", "prcp": "klyh", "wspd": "klyh", "wdir": "klyh"},
"kwal": {"temp": "ksby", "rhum": "ksby", "prcp": "ksby", "wspd": "ksby", "wdir": "ksby"},
"kmrb": {"temp": "khgr", "rhum": "khgr", "prcp": "khgr", "wspd": "khgr", "wdir": "khgr"},
"khgr": {"temp": "kmrb", "rhum": "kmrb", "prcp": "kmrb", "wspd": "kmrb", "wdir": "kmrb"},
"kanj": {"temp": "kapn", "rhum": "kapn", "prcp": "kapn", "wspd": "kapn", "wdir": "kapn"},
"kapn": {"temp": "kglr", "rhum": "kglr", "prcp": "kglr", "wspd": "kglr", "wdir": "kglr"},
"kazo": {"temp": "kbtl", "rhum": "kbtl", "prcp": "kbtl", "wspd": "kbtl", "wdir": "kbtl"},
"kbiv": {"temp": "kmkg", "rhum": "kmkg", "prcp": "kmkg", "wspd": "kmkg", "wdir": "kmkg"},
"kbtl": {"temp": "kazo", "rhum": "kazo", "prcp": "kazo", "wspd": "kazo", "wdir": "kazo"},
"kdtw": {"temp": "ktol", "rhum": "ktol", "prcp": "ktol", "wspd": "ktol", "wdir": "ktol"},
"kfnt": {"temp": "klan", "rhum": "klan", "prcp": "klan", "wspd": "klan", "wdir": "klan"},
"kglr": {"temp": "khtl", "rhum": "khtl", "prcp": "khtl", "wspd": "khtl", "wdir": "khtl"},
"kgrr": {"temp": "klan", "rhum": "klan", "prcp": "klan", "wspd": "klan", "wdir": "klan"},
"khtl": {"temp": "kglr", "rhum": "kglr", "prcp": "kglr", "wspd": "kglr", "wdir": "kglr"},
"kjxn": {"temp": "klan", "rhum": "klan", "prcp": "klan", "wspd": "klan", "wdir": "klan"},
"klan": {"temp": "kfnt", "rhum": "kfnt", "prcp": "kfnt", "wspd": "kfnt", "wdir": "kfnt"},
"kmbs": {"temp": "kfnt", "rhum": "kfnt", "prcp": "kfnt", "wspd": "kfnt", "wdir": "kfnt"},
"kmkg": {"temp": "kbiv", "rhum": "kbiv", "prcp": "kbiv", "wspd": "kbiv", "wdir": "kbiv"},
"ktvc": {"temp": "kglr", "rhum": "kglr", "prcp": "kglr", "wspd": "kglr", "wdir": "kglr"},
"kcvg": {"temp": "kday", "rhum": "kday", "prcp": "kday", "wspd": "kday", "wdir": "kday"},
"kday": {"temp": "kcvg", "rhum": "kcvg", "prcp": "kcvg", "wspd": "kcvg", "wdir": "kcvg"},
"kcmh": {"temp": "kday", "rhum": "kday", "prcp": "kday", "wspd": "kday", "wdir": "kday"},
"kcle": {"temp": "ktol", "rhum": "ktol", "prcp": "ktol", "wspd": "ktol", "wdir": "ktol"},
"kcak": {"temp": "kyng", "rhum": "kyng", "prcp": "kyng", "wspd": "kyng", "wdir": "kyng"},
"kmfd": {"temp": "kcak", "rhum": "kcak", "prcp": "kcak", "wspd": "kcak", "wdir": "kcak"},
"ktol": {"temp": "kdtw", "rhum": "kdtw", "prcp": "kdtw", "wspd": "kdtw", "wdir": "kdtw"},
"kyng": {"temp": "kcak", "rhum": "kcak", "prcp": "kcak", "wspd": "kcak", "wdir": "kcak"},
"kdfi": {"temp": "ktol", "rhum": "ktol", "prcp": "ktol", "wspd": "ktol", "wdir": "ktol"},
"khzy": {"temp": "kcle", "rhum": "kcle", "prcp": "kcle", "wspd": "kcle", "wdir": "kcle"},
"kaoh": {"temp": "kdfi", "rhum": "kdfi", "prcp": "kdfi", "wspd": "kdfi", "wdir": "kdfi"},
"kzzv": {"temp": "kcmh", "rhum": "kcmh", "prcp": "kcmh", "wspd": "kcmh", "wdir": "kcmh"},
"khsv": {"temp": "kbhm", "rhum": "kbhm", "prcp": "kbhm", "wspd": "kbhm", "wdir": "kbhm"},
"klex": {"temp": "kfft", "rhum": "kfft", "prcp": "kfft", "wspd": "kfft", "wdir": "kfft"},
"kfft": {"temp": "klex", "rhum": "klex", "prcp": "klex", "wspd": "klex", "wdir": "klex"},
"kcmi": {"temp": "kdec", "rhum": "kdec", "prcp": "kdec", "wspd": "kdec", "wdir": "kdec"},
"kaug": {"temp": "klew", "rhum": "klew", "prcp": "klew", "wspd": "klew", "wdir": "klew", "srad": "klew", "tsky": "klew"},
"klew": {"temp": "kaug", "rhum": "kaug", "prcp": "kaug", "wspd": "kaug", "wdir": "kaug", "srad": "kaug", "tsky": "kaug"},
"kstl": {"temp": "il_gra", "rhum": "il_gra", "prcp": "il_gra", "wspd": "il_gra", "wdir": "il_gra"},
"pa_big": {"temp": "kmdt", "rhum": "kmdt", "prcp": "kmdt", "wspd": "kmdt", "wdir": "kmdt", "lwet": "pa_npa", "srad": "pa_npa"},
"pa_pin": {"temp": "kmdt", "rhum": "kmdt", "prcp": "kmdt", "wspd": "kmdt", "wdir": "kmdt", "lwet": "pa_big", "srad": "pa_big"},
"pa_ysp": {"temp": "kmdt", "rhum": "kmdt", "prcp": "kmdt", "wspd": "kmdt", "wdir": "kmdt", "lwet": "pa_big", "srad": "pa_big"},
"pa_npa": {"temp": "kjst", "rhum": "kjst", "prcp": "kjst", "wspd": "kjst", "wdir": "kjst", "lwet": "pa_big", "srad": "pa_big"},
"pa_ntr": {"temp": "kabe", "rhum": "kabe", "prcp": "kabe", "wspd": "kabe", "wdir": "kabe", "lwet": "pa_ysp", "srad": "pa_rsp"},
"pa_rsp": {"temp": "kaoo", "rhum": "kaoo", "prcp": "kaoo", "wspd": "kaoo", "wdir": "kaoo", "lwet": "pa_npa", "srad": "pa_npa"},
"pa_hun": {"temp": "kaoo", "rhum": "kaoo", "prcp": "kaoo", "wspd": "kaoo", "wdir": "kaoo", "lwet": "pa_rsp", "srad": "pa_rsp"},
"me_bhb": {"temp": "kbhb", "rhum": "kbhb", "prcp": "kbhb", "wspd": "kbhb", "wdir": "kbhb", "srad": "mam"},
"pa_sco": {"temp": "kavp", "rhum": "kavp", "prcp": "kavp", "wspd": "kavp", "wdir": "kavp", "lwet": "pa_ntr", "srad": "471"},
"pa_bre": {"temp": "pa_ntr", "rhum": "pa_ntr", "prcp": "pa_ntr", "wspd": "pa_ntr", "wdir": "pa_ntr", "lwet": "pa_ntr", "srad": "pa_ntr"},
"pa_cab": {"temp": "kpit", "rhum": "kpit", "prcp": "kpit", "wspd": "kpit", "wdir": "kpit", "lwet": "pa_npa", "srad": "pa_npa"},
"pa_lew": {"temp": "kipt", "rhum": "kipt", "prcp": "kipt", "wspd": "kipt", "wdir": "kipt", "lwet": "pa_rsp", "srad": "pa_rsp"},
"pa_heg": {"temp": "kmdt", "rhum": "kmdt", "prcp": "kmdt", "wspd": "kmdt", "wdir": "kmdt", "lwet": "pa_ntr", "srad": "pa_ntr"},
"mmi" : {"temp": "khfd", "rhum": "khfd", "prcp": "khfd", "wspd": "khfd", "wdir": "khfd", "lwet": "cli", "srad": "mwe"},
"ct_gfy": {"temp": "ct_nwi", "rhum": "ct_nwi", "prcp": "ct_nwi", "wspd": "ct_nwi", "wdir": "ct_nwi", "lwet": "ct_nwi", "srad": "ct_pre"},
"ct_gui": {"temp": "kbdr", "rhum": "kbdr", "prcp": "kbdr", "wspd": "kbdr", "wdir": "kbdr", "lwet": "ct_she", "srad": "ct_she"},
"ct_sgl": {"temp": "ct_ssm", "rhum": "ct_ssm", "prcp": "ct_ssm", "wspd": "ct_ssm", "wdir": "ct_ssm", "lwet": "ct_ssm", "srad": "ct_ssm"},
"ct_nwi": {"temp": "ct_eas", "rhum": "ct_eas", "prcp": "ct_eas", "wspd": "ct_eas", "wdir": "ct_eas", "lwet": "ct_eas", "srad": "ct_eas"},
"ct_rid": {"temp": "kdxr", "rhum": "kdxr", "prcp": "kdxr", "wspd": "kdxr", "wdir": "kdxr", "lwet": "ct_she", "srad": "ct_she"},
"ct_npr": {"temp": "kdxr", "rhum": "kdxr", "prcp": "kdxr", "wspd": "kdxr", "wdir": "kdxr", "lwet": "ct_rid", "srad": "ct_rid"},
"ct_she": {"temp": "ct_wal", "rhum": "ct_wal", "prcp": "ct_wal", "wspd": "ct_wal", "wdir": "ct_wal", "lwet": "ct_wal", "srad": "ct_wal"},
"ct_ssm": {"temp": "ct_ssu", "rhum": "ct_ssu", "prcp": "ct_ssu", "wspd": "ct_ssu", "wdir": "ct_ssu", "lwet": "ct_ssu", "srad": "ct_ssu"},
"ct_ssu": {"temp": "ct_ssm", "rhum": "ct_ssm", "prcp": "ct_ssm", "wspd": "ct_ssm", "wdir": "ct_ssm", "lwet": "ct_ssm", "srad": "ct_ssm"},
"ct_wal": {"temp": "ct_ssu", "rhum": "ct_ssu", "prcp": "ct_ssu", "wspd": "ct_ssu", "wdir": "ct_ssu", "lwet": "ct_ssu", "srad": "ct_ssu"},
"ct_eas": {"temp": "ct_nwi", "rhum": "ct_nwi", "prcp": "ct_nwi", "wspd": "ct_nwi", "wdir": "ct_nwi", "lwet": "ct_nwi", "srad": "ct_woo"},
"ct_tol": {"temp": "ct_enf", "rhum": "ct_enf", "prcp": "ct_enf", "wspd": "ct_enf", "wdir": "ct_enf", "lwet": "ct_enf", "srad": "ct_enf"},
"ct_enf": {"temp": "ct_tol", "rhum": "ct_tol", "prcp": "ct_tol", "wspd": "ct_tol", "wdir": "ct_tol", "lwet": "ct_tol", "srad": "ct_tol"},
"ct_ewi": {"temp": "ct_enf", "rhum": "ct_enf", "prcp": "ct_enf", "wspd": "ct_enf", "wdir": "ct_enf", "lwet": "ct_enf", "srad": "ct_enf"},
"ct_gra": {"temp": "kbdl", "rhum": "kbdl", "prcp": "kbdl", "wspd": "kbdl", "wdir": "kbdl", "lwet": "ct_enf", "srad": "ct_enf"},
"ct_woo": {"temp": "ct_eas", "rhum": "ct_eas", "prcp": "ct_eas", "wspd": "ct_eas", "wdir": "ct_eas", "lwet": "ct_eas", "srad": "ct_eas"},
"ct_ely": {"temp": "ct_gfy", "rhum": "ct_gfy", "prcp": "ct_gfy", "wspd": "ct_gfy", "wdir": "ct_gfy", "lwet": "ct_gfy", "srad": "ct_gfy"},
"ct_can": {"temp": "kbdl", "rhum": "kbdl", "prcp": "kbdl", "wspd": "kbdl", "wdir": "kbdl", "lwet": "ct_ssm", "srad": "ct_ssm"},
"ct_cha": {"temp": "ct_nwi", "rhum": "ct_nwi", "prcp": "ct_nwi", "wspd": "ct_nwi", "wdir": "ct_nwi", "lwet": "ct_nwi", "srad": "ct_sto"},
"ct_eha": {"temp": "ct_sgl", "rhum": "ct_sgl", "prcp": "ct_sgl", "wspd": "ct_sgl", "wdir": "ct_sgl", "lwet": "ct_sgl", "srad": "ct_sgl"},
"ct_ell": {"temp": "kbdl", "rhum": "kbdl", "prcp": "kbdl", "wspd": "kbdl", "wdir": "kbdl", "lwet": "ct_tol", "srad": "ct_tol"},
"ct_ham": {"temp": "kbdr", "rhum": "kbdr", "prcp": "kbdr", "wspd": "kbdr", "wdir": "kbdr", "lwet": "ct_wal", "srad": "ct_wal"},
"ct_har": {"temp": "ct_ssm", "rhum": "ct_ssm", "prcp": "ct_ssm", "wspd": "ct_ssm", "wdir": "ct_ssm", "lwet": "ct_ssm", "srad": "ct_ssm"},
"ct_heb": {"temp": "ct_nwi", "rhum": "ct_nwi", "prcp": "ct_nwi", "wspd": "ct_nwi", "wdir": "ct_nwi", "lwet": "ct_nwi", "srad": "ct_leb"},
"ct_nca": {"temp": "kbdr", "rhum": "kbdr", "prcp": "kbdr", "wspd": "kbdr", "wdir": "kbdr", "lwet": "ct_rid", "srad": "ct_rid"},
"ct_new": {"temp": "kdxr", "rhum": "kdxr", "prcp": "kdxr", "wspd": "kdxr", "wdir": "kdxr", "lwet": "ct_rid", "srad": "ct_rid"},
"ct_por": {"temp": "kbdl", "rhum": "kbdl", "prcp": "kbdl", "wspd": "kbdl", "wdir": "kbdl", "lwet": "ct_ssm", "srad": "ct_ssm"},
"ct_was": {"temp": "kdxr", "rhum": "kdxr", "prcp": "kdxr", "wspd": "kdxr", "wdir": "kdxr", "lwet": "ct_npr", "srad": "ct_npr"},
"ct_kil": {"temp": "ct_mad", "rhum": "ct_mad", "prcp": "ct_mad", "wspd": "ct_mad", "wdir": "ct_mad", "lwet": "ct_mad", "srad": "ct_mad"},
"ct_mad": {"temp": "kbdr", "rhum": "kbdr", "prcp": "kbdr", "wspd": "kbdr", "wdir": "kbdr", "lwet": "ct_gui", "srad": "ct_gui"},
"ct_nha": {"temp": "kbdl", "rhum": "kbdl", "prcp": "kbdl", "wspd": "kbdl", "wdir": "kbdl", "lwet": "ct_ssm", "srad": "ct_ssm"},
"ct_nia": {"temp": "ct_ely", "rhum": "ct_ely", "prcp": "ct_ely", "wspd": "ct_ely", "wdir": "ct_ely", "lwet": "ct_ely", "srad": "ct_ely"},
"ct_sto": {"temp": "ct_tol", "rhum": "ct_tol", "prcp": "ct_tol", "wspd": "ct_tol", "wdir": "ct_tol", "lwet": "ct_tol", "srad": "ct_tol"},
"ct_mid": {"temp": "ct_por", "rhum": "ct_por", "prcp": "ct_por", "wspd": "ct_por", "wdir": "ct_por", "lwet": "ct_por", "srad": "ct_por"},
"ct_pla": {"temp": "ct_ssm", "rhum": "ct_ssm", "prcp": "ct_ssm", "wspd": "ct_ssm", "wdir": "ct_ssm", "lwet": "ct_ssm", "srad": "ct_ssm"},
"ct_swo": {"temp": "ct_woo", "rhum": "ct_woo", "prcp": "ct_woo", "wspd": "ct_woo", "wdir": "ct_woo", "lwet": "ct_woo", "srad": "ct_woo"},
"ct_gos": {"temp": "ct_nha", "rhum": "ct_nha", "prcp": "ct_nha", "wspd": "ct_nha", "wdir": "ct_nha", "lwet": "ct_nha", "srad": "ct_npr"},
"ct_pre": {"temp": "ct_gfy", "rhum": "ct_gfy", "prcp": "ct_gfy", "wspd": "ct_gfy", "wdir": "ct_gfy", "lwet": "ct_gfy", "srad": "ct_gfy"},
"uc_sto": {"temp": "ct_tol", "rhum": "ct_tol", "prcp": "ct_tol", "wspd": "ct_tol", "wdir": "ct_tol", "lwet": "ct_tol", "srad": "ct_tol"},
"ct_gla": {"temp": "ct_sgl", "rhum": "ct_sgl", "prcp": "ct_sgl", "wspd": "ct_sgl", "wdir": "ct_sgl", "lwet": "ct_sgl", "srad": "ct_sgl"},
"ct_eki": {"temp": "ct_woo", "rhum": "ct_woo", "prcp": "ct_woo", "wspd": "ct_woo", "wdir": "ct_woo", "lwet": "ct_woo", "srad": "ct_woo"},
"ct_oak": {"temp": "ct_gfy", "rhum": "ct_gfy", "prcp": "ct_gfy", "wspd": "ct_gfy", "wdir": "ct_gfy", "lwet": "ct_gfy", "srad": "ct_gfy"},
"ct_leb": {"temp": "ct_nwi", "rhum": "ct_nwi", "prcp": "ct_nwi", "wspd": "ct_nwi", "wdir": "ct_nwi", "lwet": "ct_nwi", "srad": "ct_heb"},
"ct_nor": {"temp": "ct_wal", "rhum": "ct_wal", "prcp": "ct_wal", "wspd": "ct_wal", "wdir": "ct_wal", "lwet": "ct_wal", "srad": "ct_wal"},
"mn_wbl": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_lkc": {"temp": "krst", "rhum": "krst", "prcp": "krst", "wspd": "krst", "wdir": "krst", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_pre": {"temp": "krst", "rhum": "krst", "prcp": "krst", "wspd": "krst", "wdir": "krst", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_has": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_och": {"temp": "kfsd", "rhum": "kfsd", "prcp": "kfsd", "wspd": "kfsd", "wdir": "kfsd", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_buf": {"temp": "kstc", "rhum": "kstc", "prcp": "kstc", "wspd": "kstc", "wdir": "kstc", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_del": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_alx": {"temp": "kstc", "rhum": "kstc", "prcp": "kstc", "wspd": "kstc", "wdir": "kstc", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_aft": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_web": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_sha": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_lac": {"temp": "klse", "rhum": "klse", "prcp": "klse", "wspd": "klse", "wdir": "klse", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_elg": {"temp": "krst", "rhum": "krst", "prcp": "krst", "wspd": "krst", "wdir": "krst", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_gra": {"temp": "kgpz", "rhum": "kdlh", "prcp": "kdlh", "wspd": "kgpz", "wdir": "kgpz", "lwet": "wi_gay", "srad": "wi_gay"},
"mn_cha": {"temp": "kmsp", "rhum": "kmsp", "prcp": "kmsp", "wspd": "kmsp", "wdir": "kmsp", "lwet": "mn_del", "srad": "mn_del"},
"il_bel": {"temp": "kstl", "rhum": "kstl", "prcp": "kstl", "wspd": "kstl", "wdir": "kstl", "lwet": "il_pgr", "srad": "kstl"},
"il_pgr": {"temp": "krfd", "rhum": "krfd", "prcp": "krfd", "wspd": "krfd", "wdir": "krfd", "lwet": "wi_gay", "srad": "wi_gay"},
"il_woo": {"temp": "krfd", "rhum": "krfd", "prcp": "krfd", "wspd": "krfd", "wdir": "krfd", "lwet": "il_pgr", "srad": "il_pgr"},
"il_gra": {"temp": "kstl", "rhum": "kstl", "prcp": "kstl", "wspd": "kstl", "wdir": "kstl", "lwet": "il_bel", "srad": "il_woo"},
"il_mil": {"temp": "kstl", "rhum": "kstl", "prcp": "kstl", "wspd": "kstl", "wdir": "kstl", "lwet": "il_bel", "srad": "il_woo"},
"il_cha": {"temp": "kcmi", "rhum": "kcmi", "prcp": "kcmi", "wspd": "kcmi", "wdir": "kcmi", "lwet": "il_gra", "srad": "il_gra"},
"nj_pri": {"temp": "kttn", "rhum": "kttn", "prcp": "kttn", "wspd": "kttn", "wdir": "kttn", "lwet": "3518", "srad": "3406"},
"nj_elk": {"temp": "kphl", "rhum": "kphl", "prcp": "kphl", "wspd": "202", "wdir": "202", "lwet": "3520", "srad": "1034"},
"nj_mil": {"temp": "kabe", "rhum": "kabe", "prcp": "kabe", "wspd": "289", "wdir": "289", "lwet": "3518", "srad": "289"},
"nj_blu": {"temp": "1034", "rhum": "1034", "prcp": "1034", "wspd": "1034", "wdir": "1034", "lwet": "nj_elk", "srad": "1034"},
"va_cha": {"temp": "kcho", "rhum": "kcho", "prcp": "kcho", "wspd": "kcho", "wdir": "kcho", "lwet": "va_cro", "srad": "va_cro"},
"va_cro": {"temp": "kcho", "rhum": "kcho", "prcp": "kcho", "wspd": "kcho", "wdir": "kcho", "lwet": "va_cha", "srad": "va_cha"},
"va_red": {"temp": "kcho", "rhum": "kcho", "prcp": "kcho", "wspd": "kcho", "wdir": "kcho", "lwet": "va_cro", "srad": "va_cro"},
"va_bat": {"temp": "kcho", "rhum": "kcho", "prcp": "kcho", "wspd": "kcho", "wdir": "kcho", "lwet": "va_cro", "srad": "va_cro"},
"va_was": {"temp": "kiad", "rhum": "kiad", "prcp": "kiad", "wspd": "kiad", "wdir": "kiad", "lwet": "va_cro", "srad": "va_cro"},
"va_win": {"temp": "kmrb", "rhum": "kmrb", "prcp": "kmrb", "wspd": "kmrb", "wdir": "kmrb", "lwet": "va_cha", "srad": "va_cha"},
"va_cov": {"temp": "kcho", "rhum": "kcho", "prcp": "kcho", "wspd": "kcho", "wdir": "kcho", "lwet": "va_cha", "srad": "va_cha"},
"va_oak": {"temp": "knyg", "rhum": "knyg", "prcp": "knyg", "wspd": "knyg", "wdir": "knyg", "lwet": "va_was", "srad": "va_was"},
"va_pae": {"temp": "kiad", "rhum": "kiad", "prcp": "kiad", "wspd": "kiad", "wdir": "kiad", "lwet": "va_win", "srad": "va_win"},
"va_fis": {"temp": "kshd", "rhum": "kshd", "prcp": "kshd", "wspd": "kshd", "wdir": "kshd", "lwet": "va_cro", "srad": "va_cro"},
"ne_gre": {"temp": "koma", "rhum": "koma", "prcp": "koma", "wspd": "koma", "wdir": "koma", "lwet": "mn_och", "srad": "un_nec"},
"oh_ber": {"temp": "kcle", "rhum": "kcle", "prcp": "kcle", "wspd": "kcle", "wdir": "kcle", "lwet": "oh_mor", "srad": "oh_mor"},
"oh_mor": {"temp": "kmfd", "rhum": "kmfd", "prcp": "kmfd", "wspd": "kmfd", "wdir": "kmfd", "lwet": "pa_cab", "srad": "pa_cab"},
"oh_mtv": {"temp": "kcmh", "rhum": "kcmh", "prcp": "kcmh", "wspd": "kcmh", "wdir": "kcmh", "lwet": "oh_mor", "srad": "oh_mor"},
"oh_rog": {"temp": "kyng", "rhum": "kyng", "prcp": "kyng", "wspd": "kyng", "wdir": "kyng", "lwet": "oh_mor", "srad": "oh_mor"},
"oh_pat": {"temp": "kcmh", "rhum": "kcmh", "prcp": "kcmh", "wspd": "kcmh", "wdir": "kcmh", "lwet": "oh_mor", "srad": "oh_mor"},
"asht":   {"temp": "khzy", "lwet": "oh_ber", "prcp": "khzy", "rhum": "khzy", "wspd": "khzy", "wdir": "khzy", "srad": "perr", "st4i": "avon"},
"perr":   {"temp": "khzy", "prcp": "khzy", "rhum": "khzy", "wspd": "khzy", "wdir": "khzy", "srad": "asht"},
"avon":   {"temp": "kcle", "prcp": "kcle", "rhum": "kcle", "wspd": "kcle", "wdir": "kcle", "srad": "oh_ber"},
"ncen":   {"temp": "pemb", "lwet": "nwst", "prcp": "pemb", "rhum": "pemb", "wspd": "pemb", "wdir": "pemb", "srad": "pemb", "st4i": "pemb"},
"pemb":   {"temp": "ktol", "prcp": "ktol", "rhum": "ktol", "wspd": "ktol", "wdir": "ktol", "srad": "ncen", "st4i": "ncen"},
"nwst":   {"temp": "kdfi", "lwet": "ncen", "prcp": "kdfi", "rhum": "kdfi", "wspd": "kdfi", "wdir": "kdfi", "srad": "pemb", "st4i": "pemb"},
"muck":   {"temp": "kmfd", "lwet": "ncen", "prcp": "kmfd", "rhum": "kmfd", "wspd": "kmfd", "wdir": "kmfd", "srad": "ncen", "st4i": "ncen"},
"woos":   {"temp": "kcak", "lwet": "muck", "prcp": "kcak", "rhum": "kcak", "wspd": "kcak", "wdir": "kcak", "srad": "muck", "st4i": "muck"},
"cbus":   {"temp": "kcmh", "lwet": "west", "prcp": "kcmh", "rhum": "kcmh", "wspd": "kcmh", "wdir": "kcmh", "srad": "west", "st4i": "west"},
"west":   {"temp": "kday", "lwet": "cbus", "prcp": "kday", "rhum": "kday", "wspd": "kday", "wdir": "kday", "srad": "cbus", "st4i": "cbus"},
"east":   {"temp": "kzzv", "lwet": "cbus", "prcp": "kzzv", "rhum": "kzzv", "wspd": "kzzv", "wdir": "kzzv", "srad": "cbus", "st4i": "cbus"},
"jack":   {"temp": "pike", "prcp": "pike", "rhum": "pike", "wspd": "pike", "wdir": "pike", "srad": "pike", "st4i": "pike"},
"pike":   {"temp": "jack", "lwet": "oh_pat", "prcp": "jack", "rhum": "jack", "wspd": "jack", "wdir": "jack", "srad": "jack", "st4i": "jack"},
"ky_ver": {"temp": "klex", "rhum": "klex", "prcp": "klex", "wspd": "klex", "wdir": "klex", "lwet": "il_gra", "srad": "klex"},
"29":   {"temp": "202", "rhum": "202", "prcp": "202", "wspd": "202", "wdir": "202", "srad": "3529"},
"33":   {"temp": "296", "rhum": "296", "prcp": "296", "wspd": "296", "wdir": "296"},
"111" : {"temp": "kteb", "rhum": "kteb", "prcp": "kteb", "wspd": "kteb", "wdir": "kteb", "srad": "3411"},
"148":  {"temp": "296", "rhum": "296", "prcp": "296", "wspd": "296", "wdir": "296", "srad": "296"},
"198":  {"temp": "263", "rhum": "263", "prcp": "263", "wspd": "263", "wdir": "263"},
"202":  {"temp": "1034", "rhum": "1034", "prcp": "1034", "wspd": "1034", "wdir": "1034"},
"232":  {"temp": "kacy", "rhum": "kacy", "prcp": "kacy", "wspd": "kacy", "wdir": "kacy"},
"236":  {"temp": "1034", "rhum": "1034", "prcp": "1034", "wspd": "1034", "wdir": "1034"},
"261":  {"temp": "296", "rhum": "148", "prcp": "148", "wspd": "148", "wdir": "148"}, 
"263":  {"temp": "kmiv", "rhum": "kmiv", "prcp": "kmiv", "wspd": "kmiv", "wdir": "kmiv"},
"284":  {"temp": "kttn", "rhum": "kttn", "prcp": "kttn", "wspd": "kttn", "wdir": "kttn", "srad": "1034"},
"285":  {"temp": "1101", "rhum": "1101", "prcp": "1101", "wspd": "1101", "wdir": "1101", "srad": "1101"},
"286":  {"temp": "kfwn", "rhum": "kfwn", "prcp": "kfwn", "wspd": "kfwn", "wdir": "kfwn", "srad": "471"},
"287":  {"temp": "3404", "rhum": "3404", "prcp": "3404", "wspd": "3404", "wdir": "3404", "srad": "1032"},
"289":  {"temp": "kttn", "rhum": "kttn", "prcp": "kttn", "wspd": "kttn", "wdir": "kttn", "srad": "1029"},
"295":  {"temp": "3406", "rhum": "3406", "prcp": "3406", "wspd": "3406", "wdir": "3406", "srad": "1032"}, 
"296":  {"temp": "33", "rhum": "33", "prcp": "33", "wspd": "33", "wdir": "33", "srad": "284"},
"317":  {"temp": "1032", "rhum": "1032", "prcp": "1032", "wspd": "1032", "wdir": "1032", "srad": "1032"},
"471":  {"temp": "kfwn", "rhum": "kfwn", "prcp": "kfwn", "wspd": "kfwn", "wdir": "kfwn", "srad": "286"},
"1029": {"temp": "289", "rhum": "289", "prcp": "289", "wspd": "289", "wdir": "289", "srad": "289"},
"1032": {"temp": "knel", "rhum": "knel", "prcp": "knel", "wspd": "knel", "wdir": "knel", "srad": "317"},
"1033": {"temp": "kteb", "rhum": "kteb", "prcp": "kteb", "wspd": "kteb", "wdir": "kteb", "srad": "471"},
"1034": {"temp": "202", "rhum": "202", "prcp": "202", "wspd": "202", "wdir": "202", "srad": "317"},
"1101": {"temp": "285", "rhum": "285", "prcp": "285", "wspd": "285", "wdir": "285", "srad": "285"},
"3397": {"temp": "3404", "rhum": "3404", "prcp": "3404", "wspd": "3404", "wdir": "3404"},
"3398": {"temp": "3407", "rhum": "3407", "prcp": "3407", "wspd": "3407", "wdir": "3407"},
"3403": {"temp": "3405", "rhum": "3405", "prcp": "1101", "wspd": "3405", "wdir": "3405"},
"3404": {"temp": "287", "rhum": "287", "prcp": "287", "wspd": "287", "wdir": "287"},
"3405": {"temp": "3403", "rhum": "3403", "wspd": "3403", "wdir": "3403"},
"3406": {"temp": "295", "rhum": "295", "prcp": "295", "wspd": "295", "wdir": "295", "srad": "295"},
"3407": {"temp": "3398", "rhum": "3398", "prcp": "3398", "wspd": "3398", "wdir": "3398", "srad": "1034"},
"3408": {"temp": "1032", "rhum": "1032", "prcp": "1032", "wspd": "1032", "wdir": "1032"},
"3409": {"temp": "284", "rhum": "284", "prcp": "284", "wspd": "284", "wdir": "284"},
"3411": {"temp": "kewr", "rhum": "kewr", "prcp": "kewr", "wspd": "kewr", "wdir": "kewr", "srad": "1033"},
"3479": {"temp": "263", "rhum": "263", "prcp": "263", "wspd": "263", "wdir": "263"},
"3481": {"temp": "3404", "prcp": "3404", "rhum": "3404", "wspd": "3404", "wdir": "3404", "srad": "287"},
"3485": {"temp": "kmiv", "rhum": "kmiv", "prcp": "kmiv", "wspd": "kmiv", "wdir": "kmiv", "srad": "284"},
"3517": {"temp": "289", "lwet": "3518", "prcp": "kabe", "rhum": "289", "wspd": "289", "wdir": "289"},
"3518": {"temp": "kttn", "lwet": "pa_bre", "prcp": "kttn", "rhum": "kttn", "wspd": "kttn", "wdir": "kttn"},
"3519": {"temp": "kwwd", "lwet": "3520", "prcp": "kwwd", "rhum": "kwwd", "wspd": "kwwd", "wdir": "kwwd"},
"3520": {"temp": "kvay", "lwet": "3519", "prcp": "kvay", "rhum": "kvay", "wspd": "3479", "wdir": "3479"},
"3521": {"temp": "kttn", "lwet": "3518", "prcp": "kttn", "rhum": "kttn", "wspd": "kttn", "wdir": "kttn"},
"3522": {"temp": "263", "lwet": "3520", "prcp": "3520", "rhum": "263", "wspd": "263", "wdir": "263"},
"3523": {"temp": "3406", "lwet": "3521", "prcp": "3521", "rhum": "3406", "wspd": "3406", "wdir": "3406"},
"3526": {"temp": "kttn", "rhum": "kttn", "prcp": "kttn", "wspd": "kttn", "wdir": "kttn", "srad": "3406"},
"3527": {"temp": "kphl", "rhum": "kphl", "prcp": "kphl", "wspd": "kphl", "wdir": "kphl", "srad": "nj_elk"},
"3529": {"temp": "kilg", "rhum": "kilg", "prcp": "kilg", "wspd": "kilg", "wdir": "kilg", "srad": "284"},
"3530": {"temp": "296", "rhum": "296", "prcp": "296", "wspd": "296", "wdir": "296", "srad": "296"},
"3531": {"temp": "kphl", "rhum": "kphl", "prcp": "kphl", "wspd": "kphl", "wdir": "kphl", "srad": "3552"},
"3532": {"temp": "kvay", "rhum": "kvay", "prcp": "kvay", "wspd": "kvay", "wdir": "kvay", "srad": "3533"},
"3533": {"temp": "kvay", "rhum": "kvay", "prcp": "kvay", "wspd": "kvay", "wdir": "kvay", "srad": "3532"},
"3552": {"temp": "3533", "rhum": "3533", "prcp": "3533", "wspd": "3533", "wdir": "3533", "srad": "3533"},
"ia_ccy": {"temp": "kcid", "rhum": "kcid", "prcp": "kcid", "wspd": "kcid", "wdir": "kcid", "lwet": "wi_gay", "srad": "kcid"},
"md_wdb": {"temp": "kbwi", "rhum": "kbwi", "prcp": "kbwi", "wspd": "kbwi", "wdir": "kbwi", "lwet": "pa_big", "srad": "kbwi"},
"nc_hen": {"temp": "kavl", "rhum": "kavl", "prcp": "kavl", "wspd": "kavl", "wdir": "kavl", "lwet": "nc_edn", "srad": "nc_edn"},
"nc_mor": {"temp": "khky", "rhum": "khky", "prcp": "khky", "wspd": "khky", "wdir": "khky", "lwet": "nc_edn", "srad": "nc_edn"},
"nc_edn": {"temp": "kavl", "rhum": "kavl", "prcp": "kavl", "wspd": "kavl", "wdir": "kavl", "lwet": "nc_mor", "srad": "nc_mor"},
"nc_esm": {"temp": "kavl", "rhum": "kavl", "prcp": "kavl", "wspd": "kavl", "wdir": "kavl", "lwet": "nc_edn", "srad": "nc_edn"},
"nc_emm": {"temp": "kavl", "rhum": "kavl", "prcp": "kavl", "wspd": "kavl", "wdir": "kavl", "lwet": "nc_edn", "srad": "nc_edn"},
"nc_eaw": {"temp": "kavl", "rhum": "kavl", "prcp": "kavl", "wspd": "kavl", "wdir": "kavl", "lwet": "nc_edn", "srad": "nc_edn"},
"nc_fla": {"temp": "kavl", "rhum": "kavl", "prcp": "kavl", "wspd": "kavl", "wdir": "kavl", "lwet": "nc_edn", "srad": "nc_edn"},
"nc_mof": {"temp": "khky", "rhum": "khky", "prcp": "khky", "wspd": "khky", "wdir": "khky", "lwet": "nc_mor", "srad": "nc_mor"},
"nc_gre": {"temp": "kgsp", "rhum": "kgsp", "prcp": "kgsp", "wspd": "kgsp", "wdir": "kgsp", "lwet": "nc_esm", "srad": "nc_edn"},
"ew_elb": {"temp": "ew_hrt", "rhum": "ew_hrt", "prcp": "ew_hrt", "wspd": "ew_hrt", "wdir": "ew_hrt", "lwet": "ew_hrt", "srad": "ew_hrt"},
"ew_hdn": {"temp": "ew_drf", "rhum": "ew_drf", "prcp": "ew_drf", "wspd": "ew_drf", "wdir": "ew_drf", "lwet": "ew_drf", "srad": "ew_drf"},
"ew_pig": {"temp": "ew_knd", "rhum": "ew_knd", "prcp": "ew_knd", "wspd": "ew_knd", "wdir": "ew_knd", "lwet": "ew_knd", "srad": "ew_knd"},
"ew_epr": {"temp": "ew_kwd", "rhum": "ew_kwd", "prcp": "ew_kwd", "wspd": "ew_kwd", "wdir": "ew_kwd", "lwet": "ew_kwd", "srad": "ew_kwd"},
"ew_eld": {"temp": "ew_nth", "rhum": "ew_nth", "prcp": "ew_nth", "wspd": "ew_nth", "wdir": "ew_nth", "lwet": "ew_nth", "srad": "ew_nth"},
"ew_hfd": {"temp": "ew_klr", "rhum": "ew_klr", "prcp": "ew_klr", "wspd": "ew_klr", "wdir": "ew_klr", "lwet": "ew_klr", "srad": "ew_klr"},
"ew_elk": {"temp": "ew_old", "rhum": "ew_old", "prcp": "ew_old", "wspd": "ew_old", "wdir": "ew_old", "lwet": "ew_old", "srad": "ew_old"},
"ew_tpd": {"temp": "ew_law", "rhum": "ew_law", "prcp": "ew_law", "wspd": "ew_law", "wdir": "ew_law", "lwet": "ew_law", "srad": "ew_law"},
"ew_kbs": {"temp": "ew_pcc", "rhum": "ew_pcc", "prcp": "ew_pcc", "wspd": "ew_pcc", "wdir": "ew_pcc", "lwet": "ew_pcc", "srad": "ew_pcc"},
"ew_knd": {"temp": "ew_ver", "rhum": "ew_ver", "prcp": "ew_ver", "wspd": "ew_ver", "wdir": "ew_ver", "lwet": "ew_ver", "srad": "ew_ver"},
"ew_hrt": {"temp": "ew_elb", "rhum": "ew_elb", "prcp": "ew_elb", "wspd": "ew_elb", "wdir": "ew_elb", "lwet": "ew_elb", "srad": "ew_elb"},
"ew_grj": {"temp": "ew_shv", "rhum": "ew_shv", "prcp": "ew_shv", "wspd": "ew_shv", "wdir": "ew_shv", "lwet": "ew_shv", "srad": "ew_shv"},
"ew_pcc": {"temp": "ew_kbs", "rhum": "ew_kbs", "prcp": "ew_kbs", "wspd": "ew_kbs", "wdir": "ew_kbs", "lwet": "ew_kbs", "srad": "ew_kbs"},
"ew_drf": {"temp": "ew_hdn", "rhum": "ew_hdn", "prcp": "ew_hdn", "wspd": "ew_hdn", "wdir": "ew_hdn", "lwet": "ew_hdn", "srad": "ew_hdn"},
"ew_old": {"temp": "ew_elk", "rhum": "ew_elk", "prcp": "ew_elk", "wspd": "ew_elk", "wdir": "ew_elk", "lwet": "ew_elk", "srad": "ew_elk"},
"ew_kwd": {"temp": "ew_old", "rhum": "ew_old", "prcp": "ew_old", "wspd": "ew_old", "wdir": "ew_old", "lwet": "ew_old", "srad": "ew_old"},
"ew_swm": {"temp": "ew_bbc", "rhum": "ew_bbc", "prcp": "ew_bbc", "wspd": "ew_bbc", "wdir": "ew_bbc", "lwet": "ew_bbc", "srad": "ew_bbc"},
"ew_sdk": {"temp": "ew_ver", "rhum": "ew_ver", "prcp": "ew_ver", "wspd": "ew_ver", "wdir": "ew_ver", "lwet": "ew_ver", "srad": "ew_ver"},
"ew_ent": {"temp": "ew_mct", "rhum": "ew_mct", "prcp": "ew_mct", "wspd": "ew_mct", "wdir": "ew_mct", "lwet": "ew_mct", "srad": "ew_mct"},
"ew_fgv": {"temp": "ew_mgr", "rhum": "ew_mgr", "prcp": "ew_mgr", "wspd": "ew_mgr", "wdir": "ew_mgr", "lwet": "ew_mgr", "srad": "ew_mgr"},
"ew_brs": {"temp": "ew_scd", "rhum": "ew_scd", "prcp": "ew_scd", "wspd": "ew_scd", "wdir": "ew_scd", "lwet": "ew_scd", "srad": "ew_scd"},
"ew_alg": {"temp": "ew_ost", "rhum": "ew_ost", "prcp": "ew_ost", "wspd": "ew_ost", "wdir": "ew_ost", "lwet": "ew_ost", "srad": "ew_ost"},
"ew_lpr": {"temp": "ew_flt", "rhum": "ew_flt", "prcp": "ew_flt", "wspd": "ew_flt", "wdir": "ew_flt", "lwet": "ew_flt", "srad": "ew_flt"},
"ew_alb": {"temp": "ew_cer", "rhum": "ew_cer", "prcp": "ew_cer", "wspd": "ew_cer", "wdir": "ew_cer", "lwet": "ew_cer", "srad": "ew_cer"},
"ew_klr": {"temp": "ew_hfd", "rhum": "ew_hfd", "prcp": "ew_hfd", "wspd": "ew_hfd", "wdir": "ew_hfd", "lwet": "ew_hfd", "srad": "ew_hfd"},
"ew_ost": {"temp": "ew_kzo", "rhum": "ew_kzo", "prcp": "ew_kzo", "wspd": "ew_kzo", "wdir": "ew_kzo", "lwet": "ew_kzo", "srad": "ew_kzo"},
"ew_mgr": {"temp": "ew_rvl", "rhum": "ew_rvl", "prcp": "ew_rvl", "wspd": "ew_rvl", "wdir": "ew_rvl", "lwet": "ew_rvl", "srad": "ew_rvl"},
"ew_stn": {"temp": "ew_hvl", "rhum": "ew_hvl", "prcp": "ew_hvl", "wspd": "ew_hvl", "wdir": "ew_hvl", "lwet": "ew_hvl", "srad": "ew_hvl"},
"ew_kal": {"temp": "ew_elk", "rhum": "ew_elk", "prcp": "ew_elk", "wspd": "ew_elk", "wdir": "ew_elk", "lwet": "ew_elk", "srad": "ew_elk"},
"ew_les": {"temp": "ew_msu", "rhum": "ew_msu", "prcp": "ew_msu", "wspd": "ew_msu", "wdir": "ew_msu", "lwet": "ew_msu", "srad": "ew_msu"},
"ew_weo": {"temp": "ew_hvl", "rhum": "ew_hvl", "prcp": "ew_hvl", "wspd": "ew_hvl", "wdir": "ew_hvl", "lwet": "ew_hvl", "srad": "ew_hvl"},
"ew_cer": {"temp": "ew_kbs", "rhum": "ew_kbs", "prcp": "ew_kbs", "wspd": "ew_kbs", "wdir": "ew_kbs", "lwet": "ew_kbs", "srad": "ew_kbs"},
"ew_stv": {"temp": "ew_esc", "rhum": "ew_esc", "prcp": "ew_esc", "wspd": "ew_esc", "wdir": "ew_esc", "lwet": "ew_esc", "srad": "ew_esc"},
"ew_mcb": {"temp": "ew_arl", "rhum": "ew_arl", "prcp": "ew_arl", "wspd": "ew_arl", "wdir": "ew_arl", "lwet": "ew_arl", "srad": "ew_arl"},
"ew_nwm": {"temp": "ew_old", "rhum": "ew_old", "prcp": "ew_old", "wspd": "ew_old", "wdir": "ew_old", "lwet": "ew_old", "srad": "ew_old"},
"ew_cmc": {"temp": "ew_rom", "rhum": "ew_rom", "prcp": "ew_rom", "wspd": "ew_rom", "wdir": "ew_rom", "lwet": "ew_rom", "srad": "ew_rom"},
"ew_cth": {"temp": "ew_esc", "rhum": "ew_esc", "prcp": "ew_esc", "wspd": "ew_esc", "wdir": "ew_esc", "lwet": "ew_esc", "srad": "ew_esc"},
"ew_flt": {"temp": "ew_lpr", "rhum": "ew_lpr", "prcp": "ew_lpr", "wspd": "ew_lpr", "wdir": "ew_lpr", "lwet": "ew_lpr", "srad": "ew_lpr"},
"ew_law": {"temp": "ew_tpd", "rhum": "ew_tpd", "prcp": "ew_tpd", "wspd": "ew_tpd", "wdir": "ew_tpd", "lwet": "ew_tpd", "srad": "ew_tpd"},
"ew_haw": {"temp": "ew_gay", "rhum": "ew_gay", "prcp": "ew_gay", "wspd": "ew_gay", "wdir": "ew_gay", "lwet": "ew_gay", "srad": "ew_gay"},
"ew_rom": {"temp": "ew_emt", "rhum": "ew_emt", "prcp": "ew_emt", "wspd": "ew_emt", "wdir": "ew_emt", "lwet": "ew_emt", "srad": "ew_emt"},
"ew_men": {"temp": "ew_cnt", "rhum": "ew_cnt", "prcp": "ew_cnt", "wspd": "ew_cnt", "wdir": "ew_cnt", "lwet": "ew_cnt", "srad": "ew_cnt"},
"ew_has": {"temp": "ew_htc", "rhum": "ew_htc", "prcp": "ew_htc", "wspd": "ew_htc", "wdir": "ew_htc", "lwet": "ew_htc", "srad": "ew_htc"},
"ew_kct": {"temp": "ew_spo", "rhum": "ew_spo", "prcp": "ew_spo", "wspd": "ew_spo", "wdir": "ew_spo", "lwet": "ew_spo", "srad": "ew_spo"},
"ew_mml": {"temp": "ew_cth", "rhum": "ew_cth", "prcp": "ew_cth", "wspd": "ew_cth", "wdir": "ew_cth", "lwet": "ew_cth", "srad": "ew_cth"},
"ew_cas": {"temp": "ew_dow", "rhum": "ew_dow", "prcp": "ew_dow", "wspd": "ew_dow", "wdir": "ew_dow", "lwet": "ew_dow", "srad": "ew_dow"},
"ew_scd": {"temp": "ew_swm", "rhum": "ew_swm", "prcp": "ew_swm", "wspd": "ew_swm", "wdir": "ew_swm", "lwet": "ew_swm", "srad": "ew_swm"},
"ew_msu": {"temp": "ew_htc", "rhum": "ew_htc", "prcp": "ew_htc", "wspd": "ew_htc", "wdir": "ew_htc", "lwet": "ew_htc", "srad": "ew_htc"},
"ew_mct": {"temp": "ew_ent", "rhum": "ew_ent", "prcp": "ew_ent", "wspd": "ew_ent", "wdir": "ew_ent", "lwet": "ew_ent", "srad": "ew_ent"},
"ew_fev": {"temp": "ew_grj", "rhum": "ew_grj", "prcp": "ew_grj", "wspd": "ew_grj", "wdir": "ew_grj", "lwet": "ew_grj", "srad": "ew_grj"},
"ew_dow": {"temp": "ew_bbc", "rhum": "ew_bbc", "prcp": "ew_bbc", "wspd": "ew_bbc", "wdir": "ew_bbc", "lwet": "ew_bbc", "srad": "ew_bbc"},
"ew_kzo": {"temp": "ew_ost", "rhum": "ew_ost", "prcp": "ew_ost", "wspd": "ew_ost", "wdir": "ew_ost", "lwet": "ew_ost", "srad": "ew_ost"},
"ew_bel": {"temp": "ew_clr", "rhum": "ew_clr", "prcp": "ew_clr", "wspd": "ew_clr", "wdir": "ew_clr", "lwet": "ew_clr", "srad": "ew_clr"},
"ew_esc": {"temp": "ew_cth", "rhum": "ew_cth", "prcp": "ew_cth", "wspd": "ew_cth", "wdir": "ew_cth", "lwet": "ew_cth", "srad": "ew_cth"},
"ew_lin": {"temp": "ew_frl", "rhum": "ew_frl", "prcp": "ew_frl", "wspd": "ew_frl", "wdir": "ew_frl", "lwet": "ew_frl", "srad": "ew_frl"},
"ew_spo": {"temp": "ew_kct", "rhum": "ew_kct", "prcp": "ew_kct", "wspd": "ew_kct", "wdir": "ew_kct", "lwet": "ew_kct", "srad": "ew_kct"},
"ew_bbc": {"temp": "ew_swm", "rhum": "ew_swm", "prcp": "ew_swm", "wspd": "ew_swm", "wdir": "ew_swm", "lwet": "ew_swm", "srad": "ew_swm"},
"ew_shv": {"temp": "ew_grj", "rhum": "ew_grj", "prcp": "ew_grj", "wspd": "ew_grj", "wdir": "ew_grj", "lwet": "ew_grj", "srad": "ew_grj"},
"ew_cnt": {"temp": "ew_men", "rhum": "ew_men", "prcp": "ew_men", "wspd": "ew_men", "wdir": "ew_men", "lwet": "ew_men", "srad": "ew_men"},
"ew_blk": {"temp": "ew_bnz", "rhum": "ew_bnz", "prcp": "ew_bnz", "wspd": "ew_bnz", "wdir": "ew_bnz", "lwet": "ew_bnz", "srad": "ew_bnz"},
"ew_clt": {"temp": "ew_pcc", "rhum": "ew_pcc", "prcp": "ew_pcc", "wspd": "ew_pcc", "wdir": "ew_pcc", "lwet": "ew_pcc", "srad": "ew_pcc"},
"ew_gay": {"temp": "ew_epr", "rhum": "ew_epr", "prcp": "ew_epr", "wspd": "ew_epr", "wdir": "ew_epr", "lwet": "ew_epr", "srad": "ew_epr"},
"ew_bnz": {"temp": "ew_blk", "rhum": "ew_blk", "prcp": "ew_blk", "wspd": "ew_blk", "wdir": "ew_blk", "lwet": "ew_blk", "srad": "ew_blk"},
"ew_clr": {"temp": "ew_bel", "rhum": "ew_bel", "prcp": "ew_bel", "wspd": "ew_bel", "wdir": "ew_bel", "lwet": "ew_bel", "srad": "ew_bel"},
"ew_ldt": {"temp": "ew_hrt", "rhum": "ew_hrt", "prcp": "ew_hrt", "wspd": "ew_hrt", "wdir": "ew_hrt", "lwet": "ew_hrt", "srad": "ew_hrt"},
"ew_arl": {"temp": "ew_mcb", "rhum": "ew_mcb", "prcp": "ew_mcb", "wspd": "ew_mcb", "wdir": "ew_mcb", "lwet": "ew_mcb", "srad": "ew_mcb"},
"ew_nth": {"temp": "ew_eld", "rhum": "ew_eld", "prcp": "ew_eld", "wspd": "ew_eld", "wdir": "ew_eld", "lwet": "ew_eld", "srad": "ew_eld"},
"ew_ver": {"temp": "ew_knd", "rhum": "ew_knd", "prcp": "ew_knd", "wspd": "ew_knd", "wdir": "ew_knd", "lwet": "ew_knd", "srad": "ew_knd"},
"ew_rvl": {"temp": "ew_mgr", "rhum": "ew_mgr", "prcp": "ew_mgr", "wspd": "ew_mgr", "wdir": "ew_mgr", "lwet": "ew_mgr", "srad": "ew_mgr"},
"ew_bna": {"temp": "ew_hrt", "rhum": "ew_hrt", "prcp": "ew_hrt", "wspd": "ew_hrt", "wdir": "ew_hrt", "lwet": "ew_hrt", "srad": "ew_hrt"},
"ew_cld": {"temp": "ew_men", "rhum": "ew_men", "prcp": "ew_men", "wspd": "ew_men", "wdir": "ew_men", "lwet": "ew_men", "srad": "ew_men"},
"ew_hvl": {"temp": "ew_stn", "rhum": "ew_stn", "prcp": "ew_stn", "wspd": "ew_stn", "wdir": "ew_stn", "lwet": "ew_stn", "srad": "ew_stn"},
"ew_frm": {"temp": "ew_kct", "rhum": "ew_kct", "prcp": "ew_kct", "wspd": "ew_kct", "wdir": "ew_kct", "lwet": "ew_kct", "srad": "ew_kct"},
"ew_frl": {"temp": "ew_lin", "rhum": "ew_lin", "prcp": "ew_lin", "wspd": "ew_lin", "wdir": "ew_lin", "lwet": "ew_lin", "srad": "ew_lin"},
"ew_htc": {"temp": "ew_msu", "rhum": "ew_msu", "prcp": "ew_msu", "wspd": "ew_msu", "wdir": "ew_msu", "lwet": "ew_msu", "srad": "ew_msu"},
"ew_ith": {"temp": "ew_frl", "rhum": "ew_frl", "prcp": "ew_frl", "wspd": "ew_frl", "wdir": "ew_frl", "lwet": "ew_frl", "srad": "ew_frl"},
"ew_emt": {"temp": "ew_rom", "rhum": "ew_rom", "prcp": "ew_rom", "wspd": "ew_rom", "wdir": "ew_rom", "lwet": "ew_rom", "srad": "ew_rom"}
}