stn_info = {'hwa': {'srqual': 'ok', 'state': 'NH', 'name': 'Walpole', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 43.033333, 'elev': 605, 'lon': -72.433056, 'network': 'newa'},
'me_bhb': {'srqual': 'ok', 'state': 'ME', 'name': 'Bar Harbor', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 44.389786, 'elev': 55, 'lon': -68.208026, 'network': 'newa'},
'3519': {'state': 'NJ', 'name': 'Hawk Haven Winery', 'vars': ['temp', 'lwet', 'rhum', 'wspd'], 'disconnected': 'yes', 'lat': 39.0095, 'elev': 16, 'lon': -74.8881, 'network': 'njwx'},
'3518': {'state': 'NJ', 'name': 'Unionville Winery', 'vars': ['temp', 'lwet', 'rhum', 'wspd'], 'disconnected': 'yes', 'lat': 40.4254, 'elev': 233, 'lon': -74.8256, 'network': 'njwx'},
'198': {'state': 'NJ', 'name': 'Hammonton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'disconnected': 'yes', 'lat': 39.64, 'elev': 21, 'lon': -74.75, 'network': 'njwx'},
'3517': {'state': 'NJ', 'name': 'Alba Vineyards', 'vars': ['temp', 'lwet', 'rhum', 'wspd'], 'disconnected': 'yes', 'lat': 40.6146, 'elev': 238, 'lon': -75.1663, 'network': 'njwx'},
'3405': {'state': 'NJ', 'name': 'Fort Monmouth', 'vars': ['temp', 'rhum', 'wspd', 'wdir'], 'disconnected': 'yes', 'lat': 40.3137, 'elev': 5, 'lon': -74.049, 'network': 'njwx'},
'3523': {'state': 'NJ', 'name': 'Working Dog Winery', 'vars': ['temp', 'lwet', 'rhum', 'wspd'], 'disconnected': 'yes', 'lat': 40.2315, 'elev': 121, 'lon': -74.5377, 'network': 'njwx'},
'3520': {'state': 'NJ', 'name': 'Tomasello Winery', 'vars': ['temp', 'lwet', 'rhum', 'wspd'], 'disconnected': 'yes', 'lat': 39.6569, 'elev': 105, 'lon': -74.8347, 'network': 'njwx'},
'3521': {'state': 'NJ', 'name': 'Terhune Winery', 'vars': ['temp', 'lwet', 'rhum', 'wspd'], 'disconnected': 'yes', 'lat': 40.3218, 'elev': 187, 'lon': -74.7293, 'network': 'njwx'},
'3409': {'state': 'NJ', 'name': 'Upper Deerfield (RISE)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'disconnected': 'yes', 'lat': 39.5037, 'elev': 26, 'lon': -75.254, 'network': 'njwx'},
'3522': {'state': 'NJ', 'name': 'Bellview Winery', 'vars': ['temp', 'lwet', 'rhum', 'wspd'], 'disconnected': 'yes', 'lat': 39.536, 'elev': 115, 'lon': -74.9345, 'network': 'njwx'},
'3407': {'state': 'NJ', 'name': 'Eastampton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'disconnected': 'yes', 'lat': 39.9856, 'elev': 12, 'lon': -74.7469, 'network': 'njwx'},
'um_tff': {'name': 'Northboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -71.67833, 'state': 'MA', 'elev': 610, 'lat': 42.34611, 'network': 'cu_log'},
'um_ces': {'srqual': 'ok', 'state': 'MA', 'name': 'Weston (Case Estates)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 42.35806, 'elev': 246, 'lon': -71.29889, 'network': 'cu_log'},
'mno': {'srqual': 'ok', 'state': 'MA', 'name': 'Northboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 42.345831, 'elev': 610, 'lon': -71.677843, 'network': 'newa'},
'mn_buf': {'srqual': 'ok', 'state': 'MN', 'name': 'Buffalo', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.22, 'elev': 1015, 'lon': -93.84, 'network': 'newa'},
'ew_sga': {'srqual': 'ok', 'state': 'MI', 'name': 'Saginaw', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 43.3787, 'elev': 180.125, 'lon': -84.1128, 'network': 'miwx'},
'ew_dmo': {'srqual': 'ok', 'state': 'MI', 'name': 'East Lansing (Ag Expo)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 42.7136, 'elev': -9999, 'lon': -84.4913, 'network': 'miwx'},
'ew_gde': {'srqual': 'ok', 'state': 'MI', 'name': 'Goodells', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 42.9864, 'elev': 213, 'lon': -82.6563, 'network': 'miwx'},
'ew_bat': {'srqual': 'ok', 'state': 'MI', 'name': 'Bath', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 42.8269, 'elev': -9999, 'lon': -84.365, 'network': 'miwx'},
'ew_ptr': {'srqual': 'ok', 'state': 'MI', 'name': 'Petersburg', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 41.9301, 'elev': 212, 'lon': -83.7011, 'network': 'miwx'},
'un_nec': {'srqual': 'ok', 'state': 'NE', 'name': 'Nebraska City 2N', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.7, 'elev': 1076.0, 'lon': -95.8833, 'network': 'cu_log'},
'klnk': {'srqual': 'ok', 'state': 'NE', 'name': 'Lincoln Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.8508, 'elev': 1190.0, 'lon': -96.7475, 'network': 'icao'},
'soa': {'srqual': 'toolow', 'state': 'NY', 'name': 'Appleton, South', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 43.31044, 'elev': 330.0, 'lon': -78.651778, 'network': 'newa'},
'pra': {'state': 'NY', 'name': 'Prattsburg', 'vars': ['temp', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 42.481937, 'elev': 1300.0, 'lon': -77.266594, 'network': 'newa'},
'1wi': {'state': 'NY', 'name': 'Williamson (Motts)', 'vars': ['temp', 'lwet', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 43.23925, 'elev': 430.0, 'lon': -77.1759, 'network': 'newa'},
'ede': {'state': 'NY', 'name': 'Eden', 'vars': ['temp', 'lwet', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 42.692416, 'elev': 800.0, 'lon': -78.85878, 'network': 'newa'},
'2wi': {'srqual': 'ok', 'state': 'NY', 'name': 'Williamson (Mason)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.22206, 'elev': 427.0, 'lon': -77.23158, 'network': 'newa'},
'pot': {'state': 'NY', 'name': 'Potter', 'vars': ['temp', 'lwet', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 42.715445, 'elev': 915.0, 'lon': -77.19175905, 'network': 'newa'},
'him': {'state': 'NY', 'name': 'Himrod', 'vars': ['temp', 'lwet', 'prcp'], 'disconnected': 'yes', 'lat': 42.61763, 'elev': 500.0, 'lon': -76.92226, 'network': 'newa'},
'chm': {'name': 'Champlain (Leducs Green Acres)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -73.419842, 'state': 'NY', 'elev': 173, 'lat': 44.975916, 'network': 'newa'},
'1lo': {'srqual': 'toolow', 'state': 'NY', 'name': 'Lockport', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.187325, 'elev': 478.0, 'lon': -78.762107, 'network': 'newa'},
'avo': {'state': 'NY', 'name': 'Avon', 'vars': ['temp', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 42.92, 'elev': 650.0, 'lon': -77.75, 'network': 'newa'},
'bri': {'srqual': 'ok', 'state': 'NY', 'name': 'Bridgehampton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 40.96, 'elev': 87, 'lon': -72.31, 'network': 'newa'},
'sci': {'state': 'NY', 'name': 'Scipioville', 'vars': ['temp', 'prcp'], 'disconnected': 'yes', 'lat': 42.78, 'elev': 984.0, 'lon': -76.63, 'network': 'newa'},
'ark': {'state': 'NY', 'name': 'Arkport', 'vars': ['temp', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 42.41731, 'elev': 1200.0, 'lon': -77.70358, 'network': 'newa'},
'arm': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Arkport (Mahany)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.42882, 'elev': 1300.0, 'lon': -77.6843, 'network': 'newa'},
'scr': {'state': 'NY', 'name': 'Scriba', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 43.410025, 'elev': 400.0, 'lon': -76.402453, 'network': 'newa'},
'cha': {'state': 'NY', 'name': 'Chateguay', 'vars': ['temp', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 44.92, 'elev': 972.0, 'lon': -74.07, 'network': 'newa'},
'cln': {'srqual': 'toolow', 'state': 'NY', 'name': 'Clintondale', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'disconnected': 'yes', 'lat': 41.699821, 'elev': 491.0, 'lon': -74.058165, 'network': 'newa'},
'cut': {'srqual': 'ok', 'state': 'NY', 'name': 'Cutchogue', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.026664, 'elev': 30, 'lon': -72.486658, 'network': 'newa'},
'pav': {'state': 'NY', 'name': 'Pavilion', 'vars': ['temp', 'prcp', 'st4i'], 'disconnected': 'yes', 'lat': 42.83144, 'elev': 1100.0, 'lon': -77.96731, 'network': 'newa'},
'fri': {'state': 'NY', 'name': 'Friend', 'vars': ['temp', 'lwet', 'prcp'], 'disconnected': 'yes', 'lat': 42.6558, 'elev': 1050.0, 'lon': -77.19255, 'network': 'newa'},
'yap': {'srqual': 'ok', 'state': 'NY', 'name': 'Yaphank', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.827944, 'elev': 54, 'lon': -72.919242, 'network': 'newa'},
'1fr': {'srqual': 'toolow', 'state': 'NY', 'name': 'Fredonia', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'st4i', 'wdir'], 'disconnected': 'yes', 'lat': 42.44971, 'elev': 700.0, 'lon': -79.3125, 'network': 'newa'},
'nea': {'srqual': 'ok', 'state': 'NY', 'name': 'North Easton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.00515, 'elev': 490, 'lon': -73.5495, 'network': 'newa'},
'los': {'srqual': 'ok', 'state': 'NY', 'name': 'Lodi (Shalestone)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 42.56253, 'elev': 522.0, 'lon': -76.87803, 'network': 'newa'},
'nap': {'state': 'NY', 'name': 'Naples', 'vars': ['temp', 'lwet', 'prcp'], 'disconnected': 'yes', 'lat': 42.62615, 'elev': 700.0, 'lon': -77.38729, 'network': 'newa'},
'cu_chz': {'state': 'NY', 'name': 'Chazy (Miner)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 44.8872, 'elev': 201.0, 'lon': -73.4664, 'network': 'cu_log'},
'gra': {'srqual': 'toolow', 'state': 'NY', 'name': 'Granville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.4125, 'elev': 670.0, 'lon': -73.331111, 'network': 'newa'},
'gro': {'state': 'NY', 'name': 'Groveland', 'vars': ['temp', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 42.6605, 'elev': 590.0, 'lon': -77.80193, 'network': 'newa'},
'clw': {'srqual': 'ok', 'state': 'NY', 'name': 'Clintondale (WG Minard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'disconnected': 'yes', 'lat': 41.693276, 'elev': 577.0, 'lon': -74.054027, 'network': 'newa'},
'lkp': {'srqual': 'ok', 'state': 'NY', 'name': 'Lake Placid', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 44.273768, 'elev': 1680, 'lon': -73.94865, 'network': 'newa'},
'pul': {'state': 'NY', 'name': 'Pulteney', 'vars': ['temp', 'lwet', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 42.49775, 'elev': 1450.0, 'lon': -77.17093, 'network': 'newa'},
'fay': {'srqual': 'ok', 'state': 'NY', 'name': 'Fayette 3 Brothers', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.8235, 'elev': 615.0, 'lon': -76.92445, 'network': 'newa'},
'mat': {'srqual': 'ok', 'state': 'NY', 'name': 'Mattituck (Harbes)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.986493, 'elev': 96, 'lon': -72.578489, 'network': 'newa'},
'cu_val': {'state': 'NY', 'name': 'Valatie', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 42.43, 'elev': 300.0, 'lon': -73.6776, 'network': 'cu_log'},
'lak': {'srqual': 'ok', 'state': 'NY', 'name': 'Lakemont', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.510207, 'elev': 880, 'lon': -76.92744, 'network': 'newa'},
'sav': {'state': 'NY', 'name': 'Savannah', 'vars': ['temp', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 43.022533, 'elev': 400.0, 'lon': -76.741219, 'network': 'newa'},
'pr5': {'state': 'NY', 'name': 'Portland (Route 5)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'disconnected': 'yes', 'lat': 42.39027, 'elev': 640, 'lon': -79.473605, 'network': 'newa'},
'cu_lkp': {'state': 'NY', 'name': 'Lake Placid (logger)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 44.25, 'elev': 1940.0, 'lon': -73.98, 'network': 'cu_log'},
'hig': {'srqual': 'ok', 'state': 'NY', 'name': 'Highland HVL', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 41.746139, 'elev': 436.0, 'lon': -73.96699, 'network': 'newa'},
'mex': {'state': 'NY', 'name': 'Mexico', 'vars': ['temp', 'lwet', 'prcp'], 'disconnected': 'yes', 'lat': 43.459805, 'elev': 400.0, 'lon': -76.230703, 'network': 'newa'},
'mlc': {'name': 'Milton (Crist)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -73.9882, 'state': 'NY', 'elev': 491, 'lat': 41.6503, 'network': 'newa'},
'bat': {'state': 'NY', 'name': 'Batavia', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'st4i'], 'disconnected': 'yes', 'lat': 43.02882, 'elev': 900.0, 'lon': -78.15402, 'network': 'newa'},
'wat': {'state': 'NY', 'name': 'Waterport', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'disconnected': 'yes', 'lat': 43.34422, 'elev': 330.0, 'lon': -78.21406, 'network': 'newa'},
'bar': {'state': 'NY', 'name': 'Barrington', 'vars': ['temp', 'lwet', 'prcp'], 'disconnected': 'yes', 'lat': 42.551651, 'elev': 1089.0, 'lon': -77.084785, 'network': 'newa'},
'val': {'state': 'NY', 'name': 'Valois', 'vars': ['temp', 'lwet', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 42.55903, 'elev': 800.0, 'lon': -76.8656, 'network': 'newa'},
'cu_aur': {'state': 'NY', 'name': 'Aurora (logger)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 42.7341, 'elev': 830.0, 'lon': -76.6591, 'network': 'cu_log'},
'cu_wlb': {'state': 'NY', 'name': 'Willsboro', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 44.3843, 'elev': 180.0, 'lon': -73.3818, 'network': 'cu_log'},
'cat': {'state': 'NY', 'name': 'Catatonk', 'vars': ['temp', 'prcp', 'lwet', 'rhum'], 'disconnected': 'yes', 'lat': 42.16, 'elev': 853.0, 'lon': -76.31, 'network': 'newa'},
'cah': {'name': 'Campbell Hall (Crist)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -74.2394, 'state': 'NY', 'elev': 520, 'lat': 41.42667, 'network': 'newa'},
'cam': {'state': 'NY', 'name': 'Cambridge', 'vars': ['temp', 'prcp', 'rhum'], 'disconnected': 'yes', 'lat': 43.03, 'elev': 496.0, 'lon': -73.38, 'network': 'newa'},
'dre': {'state': 'NY', 'name': 'Dresden', 'vars': ['temp', 'lwet', 'prcp'], 'disconnected': 'yes', 'lat': 42.70218, 'elev': 850.0, 'lon': -76.99813, 'network': 'newa'},
'shm': {'srqual': 'toolow', 'state': 'NY', 'name': 'Southold (Mudd)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.06, 'elev': 25, 'lon': -72.45, 'network': 'newa'},
'vca': {'srqual': 'ok', 'state': 'VT', 'name': 'Calais', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 44.3395, 'elev': 1434, 'lon': -72.5293, 'network': 'newa'},
'vsa': {'srqual': 'ok', 'state': 'VT', 'name': 'Saxtons River', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 43.153611, 'elev': 802, 'lon': -72.533611, 'network': 'newa'},
'um_new': {'srqual': 'ok', 'state': 'RI', 'name': 'Middletown', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 41.529167, 'elev': 197, 'lon': -71.2725, 'network': 'cu_log'},
'ct_ham': {'srqual': 'ok', 'state': 'CT', 'name': 'Hamden', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.380279, 'elev': 83, 'lon': -72.912015, 'network': 'newa'},
'ct_cha': {'srqual': 'ok', 'state': 'CT', 'name': 'Chaplin', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.75252, 'elev': 592, 'lon': -72.103485, 'network': 'newa'},
'ct_gra': {'srqual': 'ok', 'state': 'CT', 'name': 'Granby', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.958341, 'elev': 270, 'lon': -72.817436, 'network': 'newa'},
'ct_nca': {'srqual': 'toolow', 'state': 'CT', 'name': 'New Canaan', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.132771, 'elev': 274, 'lon': -73.484614, 'network': 'newa'},
'mmi': {'srqual': 'ok', 'state': 'CT', 'name': 'Middlefield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'disconnected': 'yes', 'lat': 41.49667, 'elev': 180, 'lon': -72.71083, 'network': 'newa'},
}