stn_info = {'karr': {'srqual': 'ok', 'state': 'IL', 'name': 'Aurora', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.77, 'elev': 710, 'lon': -88.4814, 'network': 'icao'},
'il_pgr': {'srqual': 'ok', 'state': 'IL', 'name': 'Poplar Grove', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.391312, 'elev': 916, 'lon': -88.800936, 'network': 'newa'},
'il_woo': {'srqual': 'ok', 'state': 'IL', 'name': 'Woodstock', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.259406, 'elev': 876, 'lon': -88.485386, 'network': 'newa'},
'il_bel': {'srqual': 'toolow', 'state': 'IL', 'name': 'Belleville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 38.480416, 'elev': 539, 'lon': -89.93904, 'network': 'newa'},
'il_cha': {'srqual': 'ok', 'state': 'IL', 'name': 'Champaign', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.063902, 'elev': 738, 'lon': -88.292253, 'network': 'newa'},
'kcmi': {'srqual': 'ok', 'state': 'IL', 'name': 'Champaign Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.0397, 'elev': 754, 'lon': -88.2778, 'network': 'icao'},
'il_mil': {'srqual': 'toolow', 'state': 'IL', 'name': 'Millstadt', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 38.51105, 'elev': 545, 'lon': -90.12701, 'network': 'newa'},
'il_gra': {'srqual': 'ok', 'state': 'IL', 'name': 'Grafton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.01571, 'elev': 670, 'lon': -90.40783, 'network': 'newa'},
'krfd': {'srqual': 'ok', 'state': 'IL', 'name': 'Rockford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.1928, 'elev': 730, 'lon': -89.0931, 'network': 'icao'},
}