stn_info = {'kleb': {'srqual': 'ok', 'state': 'NH', 'name': 'Lebanon', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.6264, 'elev': 598, 'lon': -72.3047, 'network': 'icao'},
'klci': {'srqual': 'ok', 'state': 'NH', 'name': 'Laconia', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.56667, 'elev': 545, 'lon': -71.43333, 'network': 'icao'},
'kbml': {'srqual': 'ok', 'state': 'NH', 'name': 'Berlin', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.5761, 'elev': 1158, 'lon': -71.1786, 'network': 'icao'},
'keen': {'srqual': 'ok', 'state': 'NH', 'name': 'Keene', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.9, 'elev': 487, 'lon': -72.26667, 'network': 'icao'},
'nh_bre': {'srqual': 'ok', 'state': 'NH', 'name': 'Brentwood', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.008804, 'elev': 121, 'lon': -71.050185, 'network': 'newa'},
'nh_bos': {'srqual': 'ok', 'state': 'NH', 'name': 'Boscawen', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.369903, 'elev': 282, 'lon': -71.652851, 'network': 'newa'},
'nh_oss': {'srqual': 'ok', 'state': 'NH', 'name': 'Ossipee', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.683564, 'elev': 851, 'lon': -71.134999, 'network': 'newa'},
'kcon': {'srqual': 'ok', 'state': 'NH', 'name': 'Concord', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.1953, 'elev': 346, 'lon': -71.5011, 'network': 'icao'},
'kmht': {'srqual': 'ok', 'state': 'NH', 'name': 'Manchester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.9333, 'elev': 225, 'lon': -71.4383, 'network': 'icao'},
'kash': {'srqual': 'ok', 'state': 'NH', 'name': 'Nashua', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.7824, 'elev': 200, 'lon': -71.5141, 'network': 'icao'},
'nh_hol': {'srqual': 'ok', 'state': 'NH', 'name': 'Hollis', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.739297, 'elev': 104, 'lon': -71.579226, 'network': 'newa'},
'kdaw': {'srqual': 'ok', 'state': 'NH', 'name': 'Rochester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.2781, 'elev': 323, 'lon': -70.9222, 'network': 'icao'},
'kafn': {'srqual': 'ok', 'state': 'NH', 'name': 'Jaffrey', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.805, 'elev': 1040, 'lon': -72.0036, 'network': 'icao'},
'nh_dur': {'srqual': 'toolow', 'state': 'NH', 'name': 'Durham', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.150628, 'elev': 151, 'lon': -70.942607, 'network': 'newa'},
'nh_mer': {'srqual': 'ok', 'state': 'NH', 'name': 'Meredith', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.676673, 'elev': 642, 'lon': -71.470985, 'network': 'newa'},
'nh_wal': {'srqual': 'ok', 'state': 'NH', 'name': 'Walpole', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.033883, 'elev': 642, 'lon': -72.430225, 'network': 'newa'},
}