stn_info = {'kalb': {'srqual': 'ok', 'state': 'NY', 'name': 'Albany', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.74306, 'elev': 275.0, 'lon': -73.80917, 'network': 'icao'},
'rom': {'srqual': 'ok', 'state': 'NY', 'name': 'Romulus (Thirsty Owl)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.69709, 'elev': 485, 'lon': -76.746448, 'network': 'newa'},
'ith': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Ithaca Cornell Orchards', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.444543, 'elev': 902.0, 'lon': -76.461786, 'network': 'newa'},
'kith': {'srqual': 'ok', 'state': 'NY', 'name': 'Ithaca Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.48333, 'elev': 1066.0, 'lon': -76.46667, 'network': 'icao'},
'alb': {'srqual': 'toolow', 'state': 'NY', 'name': 'Albion', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.275135, 'elev': 430.0, 'lon': -78.134927, 'network': 'newa'},
'ptb': {'srqual': 'ok', 'state': 'NY', 'name': 'Point Breeze', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.355, 'elev': 91, 'lon': -78.19, 'network': 'newa'},
'kjfk': {'srqual': 'ok', 'state': 'NY', 'name': 'NYC-JFK Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.63861, 'elev': 11.0, 'lon': -73.76222, 'network': 'icao'},
'kpou': {'srqual': 'ok', 'state': 'NY', 'name': 'Poughkeepsie', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.62667, 'elev': 166.0, 'lon': -73.88417, 'network': 'icao'},
'fis': {'srqual': 'ok', 'state': 'NY', 'name': 'Fishkill', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.517978, 'elev': 114, 'lon': -73.824541, 'network': 'newa'},
'cut': {'srqual': 'ok', 'state': 'NY', 'name': 'Cutchogue', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.026664, 'elev': 30, 'lon': -72.486658, 'network': 'newa'},
'ver': {'name': 'Versailles', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -79.02689, 'state': 'NY', 'elev': 863, 'lat': 42.5164, 'network': 'newa'},
'cli': {'srqual': 'ok', 'state': 'NY', 'name': 'Clifton Park', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.815913, 'elev': 378.0, 'lon': -73.837641, 'network': 'newa'},
'elb': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Elba', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.15204, 'elev': 651.0, 'lon': -78.147, 'network': 'newa'},
'kelm': {'srqual': 'ok', 'state': 'NY', 'name': 'Elmira', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.15944, 'elev': 955.0, 'lon': -76.89194, 'network': 'icao'},
'vlt': {'name': 'Valatie', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -73.6845, 'state': 'NY', 'elev': 306.1, 'lat': 42.4358, 'network': 'newa'},
'wmi': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Water Mill', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.91111, 'elev': 15.0, 'lon': -72.31748, 'network': 'newa'},
'aur': {'srqual': 'ok', 'state': 'NY', 'name': 'Aurora', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.73367, 'elev': 840, 'lon': -76.65383, 'network': 'newa'},
'clw': {'srqual': 'ok', 'state': 'NY', 'name': 'Clintondale (WG Minard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'lat': 41.693276, 'elev': 577.0, 'lon': -74.054027, 'network': 'newa'},
'lkp': {'srqual': 'ok', 'state': 'NY', 'name': 'Lake Placid', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.273768, 'elev': 1680, 'lon': -73.94865, 'network': 'newa'},
'klga': {'srqual': 'ok', 'state': 'NY', 'name': 'NYC-LaGuardia Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.77944, 'elev': 11.0, 'lon': -73.88028, 'network': 'icao'},
'far': {'srqual': 'toolow', 'state': 'NY', 'name': 'Farmington', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.99004, 'elev': 600.0, 'lon': -77.2623, 'network': 'newa'},
'som': {'srqual': 'ok', 'state': 'NY', 'name': 'Somerset', 'vars': ['temp', 'lwet', 'rhum', 'prcp', 'wspd', 'wdir', 'srad'], 'lat': 43.325911, 'elev': 318.0, 'lon': -78.626908, 'network': 'newa'},
'noa': {'srqual': 'ok', 'state': 'NY', 'name': 'Appleton, North', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.34403, 'elev': 300.0, 'lon': -78.66566, 'network': 'newa'},
'cer': {'name': 'Ceres', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -78.299024, 'state': 'NY', 'elev': 1500, 'lat': 42.007429, 'network': 'newa'},
'hig': {'srqual': 'ok', 'state': 'NY', 'name': 'Highland HVL', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.746139, 'elev': 436.0, 'lon': -73.96699, 'network': 'newa'},
'gen': {'srqual': 'ok', 'state': 'NY', 'name': 'Geneva', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.87295, 'elev': 650.0, 'lon': -77.02818, 'network': 'newa'},
'mod': {'srqual': 'ok', 'state': 'NY', 'name': 'Modena', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.670619, 'elev': 460, 'lon': -74.116855, 'network': 'newa'},
'gbe': {'srqual': 'ok', 'state': 'NY', 'name': 'Geneva (Bejo)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.82755, 'elev': 700.0, 'lon': -77.01053, 'network': 'newa'},
'kmtp': {'srqual': 'bad', 'state': 'NY', 'name': 'Montauk', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.07306, 'elev': 7.0, 'lon': -71.92333, 'network': 'icao'},
'wbs': {'srqual': 'ok', 'state': 'NY', 'name': 'Williamson (Bear Swamp)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.250549, 'elev': 367, 'lon': -77.160323, 'network': 'newa'},
'emo': {'srqual': 'ok', 'state': 'NY', 'name': 'East Moriches', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.801728, 'elev': 30, 'lon': -72.769788, 'network': 'newa'},
'dun': {'srqual': 'ok', 'state': 'NY', 'name': 'Dundee (Wiemer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.570677, 'elev': 702, 'lon': -76.928593, 'network': 'newa'},
'shc': {'srqual': 'ok', 'state': 'NY', 'name': 'Southold (Corey Creek)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.045194, 'elev': 25, 'lon': -72.4452, 'network': 'newa'},
'shd': {'srqual': 'ok', 'state': 'NY', 'name': 'Southold (One Woman)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.08, 'elev': 29, 'lon': -72.42, 'network': 'newa'},
'she': {'srqual': 'ok', 'state': 'NY', 'name': 'Sheridan', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.50207, 'elev': 750, 'lon': -79.20513, 'network': 'newa'},
'bal': {'srqual': 'ok', 'state': 'NY', 'name': 'Baldwinsville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.169525, 'elev': 443, 'lon': -76.400886, 'network': 'newa'},
'cro': {'srqual': 'ok', 'state': 'NY', 'name': 'Crown Point', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.951858, 'elev': 120.0, 'lon': -73.414106, 'network': 'newa'},
'kswf': {'srqual': 'ok', 'state': 'NY', 'name': 'Newburgh Stewart Field', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.5, 'elev': 581.0, 'lon': -74.1, 'network': 'icao'},
'gfr': {'srqual': 'ok', 'state': 'NY', 'name': 'Ithaca (Game Farm Rd)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.44924, 'elev': 968, 'lon': -76.44905, 'network': 'newa'},
'kpeo': {'srqual': 'ok', 'state': 'NY', 'name': 'Penn Yan', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.6425, 'elev': 903.0, 'lon': -77.05639, 'network': 'icao'},
'kfzy': {'srqual': 'ok', 'state': 'NY', 'name': 'Fulton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.34972, 'elev': 475.0, 'lon': -76.38472, 'network': 'icao'},
'mar': {'srqual': 'ok', 'state': 'NY', 'name': 'Marlboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'lat': 41.590299, 'elev': 390.0, 'lon': -73.984509, 'network': 'newa'},
'kgfl': {'srqual': 'ok', 'state': 'NY', 'name': 'Glens Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.34111, 'elev': 320.0, 'lon': -73.61028, 'network': 'icao'},
'arm': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Arkport (Mahany)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.42882, 'elev': 1300.0, 'lon': -77.6843, 'network': 'newa'},
'fts': {'srqual': 'ok', 'state': 'NY', 'name': 'Fort Salonga', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.897214, 'elev': 99, 'lon': -73.278708, 'network': 'newa'},
'cns': {'srqual': 'ok', 'state': 'NY', 'name': 'Cutchogue (New Suffolk)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.01, 'elev': 26, 'lon': -72.48, 'network': 'newa'},
'kdsv': {'srqual': 'ok', 'state': 'NY', 'name': 'Dansville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.5675, 'elev': 649.0, 'lon': -77.71417, 'network': 'icao'},
'wgl': {'srqual': 'ok', 'state': 'NY', 'name': 'Watkins Glen', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.377077, 'elev': 1100.0, 'lon': -76.925487, 'network': 'newa'},
'per': {'srqual': 'ok', 'state': 'NY', 'name': 'Peru', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.566692, 'elev': 370.0, 'lon': -73.512769, 'network': 'newa'},
'kfrg': {'srqual': 'ok', 'state': 'NY', 'name': 'Farmingdale', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.73417, 'elev': 81.0, 'lon': -73.41694, 'network': 'icao'},
'knyc': {'name': 'NYC-Central Park', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -73.96917, 'state': 'NY', 'elev': 130.0, 'lat': 40.77889, 'network': 'icao'},
'bla': {'srqual': 'ok', 'state': 'NY', 'name': 'Baldwinsville (Abbott)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.145093, 'elev': 502, 'lon': -76.282136, 'network': 'newa'},
'red': {'srqual': 'ok', 'state': 'NY', 'name': 'Red Hook', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.008868, 'elev': 230.0, 'lon': -73.849695, 'network': 'newa'},
'med': {'srqual': 'ok', 'state': 'NY', 'name': 'Medina', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.2, 'elev': 600, 'lon': -78.39275, 'network': 'newa'},
'kmgj': {'srqual': 'ok', 'state': 'NY', 'name': 'Montgomery', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.50917, 'elev': 365.0, 'lon': -74.265, 'network': 'icao'},
'kroc': {'srqual': 'ok', 'state': 'NY', 'name': 'Rochester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.11667, 'elev': 533.0, 'lon': -77.67667, 'network': 'icao'},
'ber': {'srqual': 'ok', 'state': 'NY', 'name': 'Bergen', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i'], 'lat': 43.085377, 'elev': 620, 'lon': -77.948586, 'network': 'newa'},
'sod': {'srqual': 'toolow', 'state': 'NY', 'name': 'Sodus', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.171946, 'elev': 450.0, 'lon': -77.078962, 'network': 'newa'},
'acc': {'srqual': 'ok', 'state': 'NY', 'name': 'Accord', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.807602, 'elev': 386, 'lon': -74.248764, 'network': 'newa'},
'kdkk': {'srqual': 'ok', 'state': 'NY', 'name': 'Dunkirk', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.49333, 'elev': 666.0, 'lon': -79.27222, 'network': 'icao'},
'lod': {'srqual': 'ok', 'state': 'NY', 'name': 'Lodi (Standing Stone)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.543054, 'elev': 719.0, 'lon': -76.874138, 'network': 'newa'},
'drs': {'srqual': 'ok', 'state': 'NY', 'name': 'Dresden (FLGP/FLCC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.706147, 'elev': 1021, 'lon': -76.974658, 'network': 'newa'},
'shm': {'srqual': 'toolow', 'state': 'NY', 'name': 'Southold (Mudd)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.06, 'elev': 25, 'lon': -72.45, 'network': 'newa'},
'int': {'srqual': 'ok', 'state': 'NY', 'name': 'Interlaken (Airy Acres)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.636288, 'elev': 242, 'lon': -76.725271, 'network': 'newa'},
'wla': {'srqual': 'ok', 'state': 'NY', 'name': 'Watkins Glen (Lakewood)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.428133, 'elev': 906, 'lon': -76.9057, 'network': 'newa'},
'wlb': {'srqual': 'ok', 'state': 'NY', 'name': 'Willsboro', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'lwet', 'srad'], 'lat': 44.3843, 'elev': 180.0, 'lon': -73.3818, 'network': 'newa'},
'hvl': {'name': 'Highland HVL 2', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -73.967, 'state': 'NY', 'elev': 437, 'lat': 41.75, 'network': 'newa'},
'2wi': {'srqual': 'ok', 'state': 'NY', 'name': 'Williamson (Mason)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.22206, 'elev': 427.0, 'lon': -77.23158, 'network': 'newa'},
'khpn': {'srqual': 'ok', 'state': 'NY', 'name': 'White Plains', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.06694, 'elev': 379.0, 'lon': -73.7075, 'network': 'icao'},
'por': {'srqual': 'ok', 'state': 'NY', 'name': 'Portland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.371481, 'elev': 700.0, 'lon': -79.487296, 'network': 'newa'},
'bri': {'srqual': 'ok', 'state': 'NY', 'name': 'Bridgehampton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.96, 'elev': 87, 'lon': -72.31, 'network': 'newa'},
'brh': {'srqual': 'ok', 'state': 'NY', 'name': 'Brookhaven Hamlet', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.769289, 'elev': 18, 'lon': -72.922614, 'network': 'newa'},
'poe': {'srqual': 'ok', 'state': 'NY', 'name': 'Portland Escarpment', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.34944, 'elev': 1076, 'lon': -79.47194, 'network': 'newa'},
'bra': {'srqual': 'ok', 'state': 'NY', 'name': 'Branchport', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.584167, 'elev': 1043, 'lon': -77.167778, 'network': 'newa'},
'fre': {'srqual': 'bad', 'state': 'NY', 'name': 'Freeville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.51914, 'elev': 1100.0, 'lon': -76.33113, 'network': 'newa'},
'cu_gfr': {'srqual': 'ok', 'state': 'NY', 'name': 'Ithaca Cornell', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.4492, 'elev': 960.0, 'lon': -76.4492, 'network': 'cu_log'},
'wad': {'srqual': 'ok', 'state': 'NY', 'name': 'Wading River', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.95, 'elev': 107, 'lon': -72.81, 'network': 'newa'},
'lol': {'srqual': 'ok', 'state': 'NY', 'name': 'Lodi (Lamoreaux)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.57664, 'elev': 853, 'lon': -76.85844, 'network': 'newa'},
'kjhw': {'srqual': 'ok', 'state': 'NY', 'name': 'Jamestown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.15, 'elev': 1719.0, 'lon': -79.25, 'network': 'icao'},
'kgtb': {'srqual': 'ok', 'state': 'NY', 'name': 'Wheeler Sack Field', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.05, 'elev': 702.0, 'lon': -75.73333, 'network': 'icao'},
'way': {'srqual': 'ok', 'state': 'NY', 'name': 'Wayland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.604968, 'elev': 1600.0, 'lon': -77.578797, 'network': 'newa'},
'hec': {'srqual': 'ok', 'state': 'NY', 'name': 'Hector', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.50804, 'elev': 800, 'lon': -76.877825, 'network': 'newa'},
'var': {'srqual': 'ok', 'state': 'NY', 'name': 'Varick (Swedish Hill)', 'vars': ['temp', 'lwet', 'rhum', 'prcp', 'wspd', 'wdir', 'srad'], 'lat': 42.80248, 'elev': 662.0, 'lon': -76.81007, 'network': 'newa'},
'chz': {'srqual': 'ok', 'state': 'NY', 'name': 'Chazy (Grower)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.8619, 'elev': 167.0, 'lon': -73.429071, 'network': 'newa'},
'hud': {'srqual': 'ok', 'state': 'NY', 'name': 'Hudson', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'lat': 42.1910246, 'elev': 216.0, 'lon': -73.8303834, 'network': 'newa'},
'kslk': {'srqual': 'ok', 'state': 'NY', 'name': 'Saranac Lake', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.38528, 'elev': 1663.0, 'lon': -74.20667, 'network': 'icao'},
'kbuf': {'srqual': 'ok', 'state': 'NY', 'name': 'Buffalo', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.94083, 'elev': 705.0, 'lon': -78.73583, 'network': 'icao'},
'but': {'srqual': 'ok', 'state': 'NY', 'name': 'Butler (Tree Crisp)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.067219, 'elev': 457, 'lon': -76.760174, 'network': 'newa'},
'rvm': {'srqual': 'ok', 'state': 'NY', 'name': 'Riverhead (MCV)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.98, 'elev': 54, 'lon': -72.58, 'network': 'newa'},
'gai': {'srqual': 'toolow', 'state': 'NY', 'name': 'Gainesville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.652126, 'elev': 1600.0, 'lon': -78.162607, 'network': 'newa'},
'sdl': {'srqual': 'ok', 'state': 'NY', 'name': 'Sodus (Lake)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.252375, 'elev': 373, 'lon': -77.06239, 'network': 'newa'},
'ksyr': {'srqual': 'ok', 'state': 'NY', 'name': 'Syracuse', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.10917, 'elev': 410.0, 'lon': -76.10333, 'network': 'icao'},
'cas': {'srqual': 'ok', 'state': 'NY', 'name': 'Castleton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.537142, 'elev': 288, 'lon': -73.71053, 'network': 'newa'},
'mts': {'srqual': 'ok', 'state': 'NY', 'name': 'Mattituck (Shinn)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.01, 'elev': 42, 'lon': -72.53, 'network': 'newa'},
'kelz': {'srqual': 'bad', 'state': 'NY', 'name': 'Wellsville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.10944, 'elev': 2124.0, 'lon': -77.99194, 'network': 'icao'},
'den': {'srqual': 'ok', 'state': 'NY', 'name': 'Denver (Stoneline)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.25056, 'elev': 2022, 'lon': -74.52583, 'network': 'newa'},
'rbg': {'name': 'Romulus (Buttonwood Grove)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -76.77, 'state': 'NY', 'elev': 460, 'lat': 42.7331, 'network': 'newa'},
'mtd': {'srqual': 'ok', 'state': 'NY', 'name': 'Mattituck (Dorsett)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.019322, 'elev': 52, 'lon': -72.524561, 'network': 'newa'},
'czy': {'srqual': 'ok', 'state': 'NY', 'name': 'Chazy (Miner)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'lwet', 'srad'], 'lat': 44.886, 'elev': 201.0, 'lon': -73.4705, 'network': 'newa'},
'kart': {'srqual': 'ok', 'state': 'NY', 'name': 'Watertown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.99222, 'elev': 318.0, 'lon': -76.02167, 'network': 'icao'},
'riv': {'srqual': 'ok', 'state': 'NY', 'name': 'Riverhead (LIHREC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.96222, 'elev': 112, 'lon': -72.71611, 'network': 'newa'},
'rip': {'srqual': 'toolow', 'state': 'NY', 'name': 'Ripley', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.265872, 'elev': 758, 'lon': -79.704125, 'network': 'newa'},
'kmss': {'srqual': 'ok', 'state': 'NY', 'name': 'Massena', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.93583, 'elev': 214.0, 'lon': -74.84556, 'network': 'icao'},
'rvp': {'srqual': 'ok', 'state': 'NY', 'name': 'Riverhead (Palmer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.97, 'elev': 49, 'lon': -72.63, 'network': 'newa'},
'kmsv': {'srqual': 'ok', 'state': 'NY', 'name': 'Monticello', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.7, 'elev': 1407.0, 'lon': -74.8, 'network': 'icao'},
'lyn': {'srqual': 'ok', 'state': 'NY', 'name': 'Lyndonville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'lat': 43.298085, 'elev': 361.0, 'lon': -78.369044, 'network': 'newa'},
'kfok': {'srqual': 'ok', 'state': 'NY', 'name': 'Westhampton Beach', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.84361, 'elev': 67.0, 'lon': -72.63222, 'network': 'icao'},
'kiag': {'srqual': 'ok', 'state': 'NY', 'name': 'Niagara Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.10722, 'elev': 585.0, 'lon': -78.94528, 'network': 'icao'},
'gui': {'srqual': 'ok', 'state': 'NY', 'name': 'Guilderland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.721046, 'elev': 390.0, 'lon': -74.017886, 'network': 'newa'},
'krme': {'srqual': 'ok', 'state': 'NY', 'name': 'Griffiss', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.23333, 'elev': 519.0, 'lon': -75.4, 'network': 'icao'},
'sil': {'srqual': 'ok', 'state': 'NY', 'name': 'Silver Creek', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.54247, 'elev': 608, 'lon': -79.19673, 'network': 'newa'},
'lan': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Lansing', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.572295, 'elev': 407.0, 'lon': -76.595127, 'network': 'newa'},
'kbgm': {'srqual': 'ok', 'state': 'NY', 'name': 'Binghamton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.20667, 'elev': 1595.0, 'lon': -75.98, 'network': 'icao'},
'lak': {'srqual': 'ok', 'state': 'NY', 'name': 'Lakemont', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.510207, 'elev': 880, 'lon': -76.92744, 'network': 'newa'},
'laf': {'srqual': 'ok', 'state': 'NY', 'name': 'Lafayette', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.909686, 'elev': 584.0, 'lon': -76.195207, 'network': 'newa'},
'phe': {'srqual': 'ok', 'state': 'NY', 'name': 'Phelps', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.977429, 'elev': 558, 'lon': -77.043439, 'network': 'newa'},
'kin': {'srqual': 'ok', 'state': 'NY', 'name': 'Kinderhook', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.398814, 'elev': 266, 'lon': -73.703383, 'network': 'newa'},
'khwv': {'srqual': 'ok', 'state': 'NY', 'name': 'Brookhaven', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.82167, 'elev': 82.0, 'lon': -72.86889, 'network': 'icao'},
'npz': {'srqual': 'ok', 'state': 'NY', 'name': 'New Paltz', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.7575583, 'elev': 115, 'lon': -74.0502361, 'network': 'newa'},
'npt': {'srqual': 'ok', 'state': 'NY', 'name': 'Northport (Richters)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.884686, 'elev': 213, 'lon': -73.294411, 'network': 'newa'},
'ovi': {'srqual': 'ok', 'state': 'NY', 'name': 'Ovid (Hosmer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.68564, 'elev': 590.0, 'lon': -76.74525, 'network': 'newa'},
'man': {'srqual': 'ok', 'state': 'NY', 'name': 'Manorville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.860597, 'elev': 44, 'lon': -72.821942, 'network': 'newa'},
'3wi': {'srqual': 'ok', 'state': 'NY', 'name': 'Williamson (Demarree)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.27615, 'elev': 300.0, 'lon': -77.1425, 'network': 'newa'},
'kno': {'srqual': 'ok', 'state': 'NY', 'name': 'Knowlesville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.225833, 'elev': 524.0, 'lon': -78.301944, 'network': 'newa'},
'kisp': {'srqual': 'ok', 'state': 'NY', 'name': 'Islip', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.79389, 'elev': 84.0, 'lon': -73.10167, 'network': 'icao'},
}