stn_info = {'kaoh': {'srqual': 'ok', 'state': 'OH', 'name': 'Lima', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.7075, 'elev': 975, 'lon': -84.0272, 'network': 'icao'},
'kcvg': {'srqual': 'ok', 'state': 'OH', 'name': 'Cincinnati', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.0444, 'elev': 888, 'lon': -84.6725, 'network': 'icao'},
'kmfd': {'srqual': 'ok', 'state': 'OH', 'name': 'Mansfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.8203, 'elev': 1241, 'lon': -82.5178, 'network': 'icao'},
'kcmh': {'srqual': 'ok', 'state': 'OH', 'name': 'Columbus', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.9908, 'elev': 813, 'lon': -82.8769, 'network': 'icao'},
'oh_ber': {'name': 'Berlin Heights', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -82.47252, 'state': 'OH', 'elev': 793, 'lat': 41.336259, 'network': 'newa'},
'kyng': {'srqual': 'ok', 'state': 'OH', 'name': 'Youngstown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.2547, 'elev': 1199, 'lon': -80.6736, 'network': 'icao'},
'kzzv': {'srqual': 'ok', 'state': 'OH', 'name': 'Zanesville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.9444, 'elev': 880, 'lon': -81.8922, 'network': 'icao'},
'kdfi': {'srqual': 'ok', 'state': 'OH', 'name': 'Defiance', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.3375, 'elev': 707, 'lon': -84.4289, 'network': 'icao'},
'kday': {'srqual': 'ok', 'state': 'OH', 'name': 'Dayton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.9064, 'elev': 1005, 'lon': -84.2186, 'network': 'icao'},
'ktol': {'srqual': 'ok', 'state': 'OH', 'name': 'Toledo', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.5872, 'elev': 693, 'lon': -83.8056, 'network': 'icao'},
'kcak': {'srqual': 'ok', 'state': 'OH', 'name': 'Akron/Canton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.9181, 'elev': 1241, 'lon': -81.4436, 'network': 'icao'},
'oh_mor': {'srqual': 'ok', 'state': 'OH', 'name': 'Moreland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.711771, 'elev': 995, 'lon': -81.970384, 'network': 'newa'},
'khzy': {'srqual': 'ok', 'state': 'OH', 'name': 'Ashtabula', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.7781, 'elev': 924, 'lon': -80.6958, 'network': 'icao'},
'kcle': {'srqual': 'ok', 'state': 'OH', 'name': 'Cleveland', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.4058, 'elev': 779, 'lon': -81.8519, 'network': 'icao'},
}