stn_info = {'kcon': {'srqual': 'ok', 'state': 'NH', 'name': 'Concord', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.1953, 'elev': 346, 'lon': -71.5011, 'network': 'icao'},
'kmht': {'srqual': 'ok', 'state': 'NH', 'name': 'Manchester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.9333, 'elev': 225, 'lon': -71.4383, 'network': 'icao'},
'kash': {'srqual': 'ok', 'state': 'NH', 'name': 'Nashua', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.7824, 'elev': 200, 'lon': -71.5141, 'network': 'icao'},
'kcho': {'srqual': 'ok', 'state': 'VA', 'name': 'Charlottesville (Airport)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.1386, 'elev': 641, 'lon': -78.4531, 'network': 'icao'},
'kshd': {'srqual': 'ok', 'state': 'VA', 'name': 'Staunton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.27, 'elev': 1188, 'lon': -78.85, 'network': 'icao'},
'va_cro': {'name': 'Crozet (Chiles Peach Orchard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st1i', 'sm1i'], 'lon': -78.748675, 'state': 'VA', 'elev': 922, 'lat': 38.068007, 'network': 'newa'},
'va_cha': {'name': 'Charlottesville (Carter Mtn Orchard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st1i', 'sm1i'], 'lon': -78.472665, 'state': 'VA', 'elev': 1148, 'lat': 37.9906478, 'network': 'newa'},
'nj_elk': {'srqual': 'ok', 'state': 'NJ', 'name': 'Elk Township', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.6664019, 'elev': 136, 'lon': -75.184658, 'network': 'newa'},
'ksmq': {'srqual': 'ok', 'state': 'NJ', 'name': 'Somerville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.62, 'elev': 105, 'lon': -74.67, 'network': 'icao'},
'kteb': {'srqual': 'ok', 'state': 'NJ', 'name': 'Teterboro', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.85, 'elev': 9.0, 'lon': -74.06139, 'network': 'icao'},
'1029': {'srqual': 'ok', 'state': 'NJ', 'name': 'Pequest', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.8383, 'elev': 135, 'lon': -74.9491, 'network': 'njwx'},
'k12n': {'srqual': 'bad', 'state': 'NJ', 'name': 'Andover', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.0089, 'elev': 583, 'lon': -74.7367, 'network': 'icao'},
'nj_pri': {'srqual': 'ok', 'state': 'NJ', 'name': 'Princeton (Terhune)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.3218, 'elev': 186, 'lon': -74.7292, 'network': 'newa'},
'111': {'srqual': 'ok', 'state': 'NJ', 'name': 'Lyndhurst (NJMC)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.784214, 'elev': 0, 'lon': -74.104617, 'network': 'njwx'},
'3411': {'srqual': 'ok', 'state': 'NJ', 'name': 'Jersey City (LSC)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.70877, 'elev': 1, 'lon': -74.053, 'network': 'njwx'},
'236': {'name': 'Cherry Hill III', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -75.0257, 'state': 'NJ', 'elev': 7, 'lat': 39.9098, 'network': 'njwx'},
'232': {'name': 'Egg Harbor', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.5421, 'state': 'NJ', 'elev': 12, 'lat': 39.4227, 'network': 'njwx'},
'kwwd': {'srqual': 'bad', 'state': 'NJ', 'name': 'Wildwood', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.02, 'elev': 23, 'lon': -74.92, 'network': 'icao'},
'nj_mil': {'srqual': 'ok', 'state': 'NJ', 'name': 'Milford', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.585858, 'elev': 123, 'lon': -75.157788, 'network': 'newa'},
'kblm': {'srqual': 'bad', 'state': 'NJ', 'name': 'Farmingdale', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.18, 'elev': 157, 'lon': -74.13, 'network': 'icao'},
'kewr': {'srqual': 'ok', 'state': 'NJ', 'name': 'Newark', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.6825, 'elev': 7.0, 'lon': -74.16944, 'network': 'icao'},
'3479': {'name': 'Hammonton 2', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.75, 'state': 'NJ', 'elev': 55, 'lat': 39.64, 'network': 'njwx'},
'289': {'srqual': 'ok', 'state': 'NJ', 'name': 'Pittstown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.5612, 'elev': 183, 'lon': -74.961, 'network': 'njwx'},
'kvay': {'srqual': 'ok', 'state': 'NJ', 'name': 'Mount Holly', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.94, 'elev': 52, 'lon': -74.84, 'network': 'icao'},
'kmiv': {'srqual': 'ok', 'state': 'NJ', 'name': 'Millville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.37, 'elev': 70, 'lon': -75.07, 'network': 'icao'},
'1032': {'srqual': 'ok', 'state': 'NJ', 'name': 'Berkeley Twp', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.92578, 'elev': 24, 'lon': -74.2981, 'network': 'njwx'},
'1033': {'srqual': 'ok', 'state': 'NJ', 'name': 'Haworth', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.9593, 'elev': 8, 'lon': -74.0135, 'network': 'njwx'},
'285': {'srqual': 'ok', 'state': 'NJ', 'name': 'Basking Ridge', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.6956, 'elev': 67, 'lon': -74.5198, 'network': 'njwx'},
'284': {'srqual': 'ok', 'state': 'NJ', 'name': 'Upper Deerfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.5243, 'elev': 33, 'lon': -75.2009, 'network': 'njwx'},
'1034': {'srqual': 'ok', 'state': 'NJ', 'name': 'Sicklerville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.7638, 'elev': 45, 'lon': -74.9785, 'network': 'njwx'},
'kcdw': {'srqual': 'ok', 'state': 'NJ', 'name': 'Fairfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.87639, 'elev': 173.0, 'lon': -74.28306, 'network': 'icao'},
'202': {'name': 'Bethel Mill Park', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -75.1138, 'state': 'NJ', 'elev': 30, 'lat': 39.7485, 'network': 'njwx'},
'286': {'srqual': 'ok', 'state': 'NJ', 'name': 'High Point', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.305, 'elev': 422, 'lon': -74.666, 'network': 'njwx'},
'3481': {'srqual': 'ok', 'state': 'NJ', 'name': 'Oceanport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.31126, 'elev': 16, 'lon': -74.01465, 'network': 'njwx'},
'317': {'srqual': 'ok', 'state': 'NJ', 'name': 'Oswego Lake', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.71539, 'elev': 15, 'lon': -74.5142, 'network': 'njwx'},
'kmmu': {'srqual': 'ok', 'state': 'NJ', 'name': 'Morristown', 'vars': ['temp', 'rhum', 'wspd', 'wdir'], 'lat': 40.8, 'elev': 187, 'lon': -74.42, 'network': 'icao'},
'knel': {'srqual': 'bad', 'state': 'NJ', 'name': 'Lakehurst NAS', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.03, 'elev': 112, 'lon': -74.35, 'network': 'icao'},
'3403': {'name': 'Holmdel', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.18, 'state': 'NJ', 'elev': 48, 'lat': 40.3776, 'network': 'njwx'},
'3404': {'name': 'Wall Twp', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.072, 'state': 'NJ', 'elev': 7, 'lat': 40.1548, 'network': 'njwx'},
'3520': {'name': 'Tomasello Winery', 'vars': ['temp', 'lwet', 'rhum', 'wspd'], 'lon': -74.8347, 'state': 'NJ', 'elev': 105, 'lat': 39.6569, 'network': 'njwx'},
'3406': {'srqual': 'ok', 'state': 'NJ', 'name': 'Hamilton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.2244, 'elev': 28, 'lon': -74.6117, 'network': 'njwx'},
'3408': {'name': 'Toms River', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.2078, 'state': 'NJ', 'elev': 21, 'lat': 39.9553, 'network': 'njwx'},
'kwri': {'srqual': 'bad', 'state': 'NJ', 'name': 'McGuire AFB', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.02, 'elev': 148, 'lon': -74.6, 'network': 'icao'},
'263': {'name': 'Piney Hollow', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.92, 'state': 'NJ', 'elev': 30, 'lat': 39.58, 'network': 'njwx'},
'3397': {'name': 'Howell', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.1958, 'state': 'NJ', 'elev': 3, 'lat': 40.1922, 'network': 'njwx'},
'33': {'name': 'Dennis Twp', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.8923, 'state': 'NJ', 'elev': 5, 'lat': 39.2039, 'network': 'njwx'},
'3398': {'name': 'Mansfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.75, 'state': 'NJ', 'elev': 21, 'lat': 40.0778, 'network': 'njwx'},
'kttn': {'srqual': 'ok', 'state': 'NJ', 'name': 'Trenton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.28, 'elev': 194, 'lon': -74.82, 'network': 'icao'},
'kfwn': {'srqual': 'bad', 'state': 'NJ', 'name': 'Sussex', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.20028, 'elev': 421.0, 'lon': -74.62306, 'network': 'icao'},
'261': {'name': 'West Cape May', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.9441, 'state': 'NJ', 'elev': 5, 'lat': 38.9422, 'network': 'njwx'},
'471': {'srqual': 'ok', 'state': 'NJ', 'name': 'Charlotteburg', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.0299, 'elev': 232, 'lon': -74.4247, 'network': 'njwx'},
'kacy': {'srqual': 'ok', 'state': 'NJ', 'name': 'Atlantic City Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.45, 'elev': 118, 'lon': -74.57, 'network': 'icao'},
'287': {'srqual': 'ok', 'state': 'NJ', 'name': 'Sea Girt', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.1203, 'elev': 2, 'lon': -74.0327, 'network': 'njwx'},
'1101': {'srqual': 'ok', 'state': 'NJ', 'name': 'New Brunswick', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.4727, 'elev': 21, 'lon': -74.4225, 'network': 'njwx'},
'296': {'srqual': 'ok', 'state': 'NJ', 'name': 'Woodbine', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.2202, 'elev': 10, 'lon': -74.7959, 'network': 'njwx'},
'295': {'srqual': 'ok', 'state': 'NJ', 'name': 'Cream Ridge', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.1185, 'elev': 36, 'lon': -74.5256, 'network': 'njwx'},
'kavl': {'srqual': 'ok', 'state': 'NC', 'name': 'Asheville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 35.4319, 'elev': 2117, 'lon': -82.5375, 'network': 'icao'},
'nc_hen': {'srqual': 'ok', 'state': 'NC', 'name': 'Hendersonville (Klimstra)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 35.280923, 'elev': 2343, 'lon': -82.530513, 'network': 'newa'},
'nc_edn': {'name': 'Edneyville (Lewis Creek)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -82.338506, 'state': 'NC', 'elev': 2223, 'lat': 35.368132, 'network': 'newa'},
'kclt': {'srqual': 'ok', 'state': 'NC', 'name': 'Charlotte', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 35.2236, 'elev': 728, 'lon': -80.9553, 'network': 'icao'},
'mbo': {'srqual': 'ok', 'state': 'MA', 'name': 'Bolton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.418889, 'elev': 516, 'lon': -71.641389, 'network': 'newa'},
'kpvc': {'srqual': 'ok', 'state': 'MA', 'name': 'Provincetown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.07194, 'elev': 8.0, 'lon': -70.22111, 'network': 'icao'},
'mbe': {'srqual': 'ok', 'state': 'MA', 'name': 'Belchertown-2', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.25306, 'elev': 623, 'lon': -72.35972, 'network': 'newa'},
'kpym': {'srqual': 'ok', 'state': 'MA', 'name': 'Plymouth', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.90972, 'elev': 149.0, 'lon': -70.72944, 'network': 'icao'},
'kpsf': {'srqual': 'bad', 'state': 'MA', 'name': 'Pittsfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.42722, 'elev': 1194.0, 'lon': -73.28917, 'network': 'icao'},
'kcef': {'srqual': 'ok', 'state': 'MA', 'name': 'Chicopee Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.2, 'elev': 246.0, 'lon': -72.53333, 'network': 'icao'},
'ktan': {'srqual': 'ok', 'state': 'MA', 'name': 'Taunton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.87556, 'elev': 43.0, 'lon': -71.02111, 'network': 'icao'},
'kowd': {'srqual': 'ok', 'state': 'MA', 'name': 'Norwood', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.19083, 'elev': 50.0, 'lon': -71.17361, 'network': 'icao'},
'mdr': {'srqual': 'toolow', 'county': 'Middlesex', 'state': 'MA', 'name': 'Dracut', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.680556, 'elev': 151, 'lon': -71.264722, 'climate_div': 'MA02', 'network': 'newa'},
'korh': {'srqual': 'ok', 'state': 'MA', 'name': 'Worcester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.26722, 'elev': 986.0, 'lon': -71.87611, 'network': 'icao'},
'mnb': {'srqual': 'ok', 'state': 'MA', 'name': 'Northbridge', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.151711, 'elev': 444, 'lon': -71.680108, 'network': 'newa'},
'um_clk': {'srqual': 'ok', 'state': 'MA', 'name': 'Deerfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.56333, 'elev': 328, 'lon': -72.62333, 'network': 'cu_log'},
'kfit': {'srqual': 'ok', 'state': 'MA', 'name': 'Fitchburg', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.55194, 'elev': 348.0, 'lon': -71.75583, 'network': 'icao'},
'um_tff': {'name': 'Northboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -71.67833, 'state': 'MA', 'elev': 610, 'lat': 42.34611, 'network': 'cu_log'},
'msw': {'srqual': 'ok', 'state': 'MA', 'name': 'Stow (Shelburne)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.446944, 'elev': 233, 'lon': -71.501111, 'network': 'newa'},
'mst': {'srqual': 'ok', 'county': 'Middlesex', 'state': 'MA', 'name': 'Stow', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.409444, 'elev': 239, 'lon': -71.513889, 'climate_div': 'MA02', 'network': 'newa'},
'um_whs': {'srqual': 'ok', 'state': 'MA', 'name': 'Boston (Weld Hill)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i'], 'lat': 42.29556, 'elev': 151, 'lon': -71.13361, 'network': 'cu_log'},
'mwa': {'srqual': 'ok', 'state': 'MA', 'name': 'UMass Waltham Center', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.383988, 'elev': 66, 'lon': -71.212285, 'network': 'newa'},
'mwe': {'srqual': 'toolow', 'state': 'MA', 'name': 'Westfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.185, 'elev': 321, 'lon': -72.765, 'network': 'newa'},
'msh': {'srqual': 'ok', 'state': 'MA', 'name': 'Sharon', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.09861, 'elev': 265, 'lon': -71.21583, 'network': 'newa'},
'um_cso': {'srqual': 'ok', 'state': 'MA', 'name': 'Belchertown', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.25333, 'elev': 638, 'lon': -72.35917, 'network': 'cu_log'},
'klwm': {'srqual': 'ok', 'state': 'MA', 'name': 'Lawrence', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.71722, 'elev': 149.0, 'lon': -71.12389, 'network': 'icao'},
'msd': {'srqual': 'ok', 'state': 'MA', 'name': 'South Deerfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.47972, 'elev': 131, 'lon': -72.57944, 'network': 'newa'},
'kmqe': {'srqual': 'bad', 'state': 'MA', 'name': 'E Milton Blue Hill', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.21222, 'elev': 630.0, 'lon': -71.11361, 'network': 'icao'},
'kaqw': {'srqual': 'bad', 'state': 'MA', 'name': 'North Adams', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.69583, 'elev': 654.0, 'lon': -73.17083, 'network': 'icao'},
'mas': {'srqual': 'toohigh', 'county': 'Franklin', 'state': 'MA', 'name': 'Ashfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.560278, 'elev': 946, 'lon': -72.815833, 'climate_div': 'MA01', 'network': 'newa'},
'kbed': {'srqual': 'ok', 'state': 'MA', 'name': 'Bedford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.47, 'elev': 133.0, 'lon': -71.28944, 'network': 'icao'},
'meb': {'srqual': 'toolow', 'state': 'MA', 'name': 'East Bridgewater', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.007778, 'elev': 40, 'lon': -70.943333, 'network': 'newa'},
'kore': {'srqual': 'ok', 'state': 'MA', 'name': 'Orange', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.57, 'elev': 555.0, 'lon': -72.29111, 'network': 'icao'},
'kewb': {'srqual': 'ok', 'state': 'MA', 'name': 'New Bedford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.67639, 'elev': 80.0, 'lon': -70.95833, 'network': 'icao'},
'mph': {'srqual': 'ok', 'state': 'MA', 'name': 'Phillipston', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.580777, 'elev': 1183, 'lon': -72.146067, 'network': 'newa'},
'um_ces': {'srqual': 'ok', 'state': 'MA', 'name': 'Weston (Case Estates)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.35806, 'elev': 246, 'lon': -71.29889, 'network': 'cu_log'},
'mty': {'srqual': 'ok', 'county': 'Windham', 'state': 'MA', 'name': 'Tyngsboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.688889, 'elev': 45, 'lon': -71.425556, 'climate_div': 'MA02', 'network': 'newa'},
'kcqx': {'srqual': 'ok', 'state': 'MA', 'name': 'Chatham', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.6875, 'elev': 68.0, 'lon': -69.99333, 'network': 'icao'},
'kfmh': {'srqual': 'bad', 'state': 'MA', 'name': 'Falmouth Otis AFB', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.65, 'elev': 131.0, 'lon': -70.51667, 'network': 'icao'},
'mam': {'srqual': 'ok', 'county': 'Essex', 'state': 'MA', 'name': 'Amesbury', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.871822, 'elev': 115, 'lon': -70.925278, 'climate_div': 'MA03', 'network': 'newa'},
'kbvy': {'srqual': 'ok', 'state': 'MA', 'name': 'Beverly', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.58417, 'elev': 108.0, 'lon': -70.9175, 'network': 'icao'},
'khya': {'srqual': 'ok', 'state': 'MA', 'name': 'Hyannis', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.66861, 'elev': 55.0, 'lon': -70.28, 'network': 'icao'},
'kbos': {'srqual': 'ok', 'state': 'MA', 'name': 'Boston Logan', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.36056, 'elev': 20.0, 'lon': -71.01056, 'network': 'icao'},
'kack': {'srqual': 'ok', 'state': 'MA', 'name': 'Nantucket', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.25306, 'elev': 45.0, 'lon': -70.06083, 'network': 'icao'},
'mle': {'srqual': 'ok', 'state': 'MA', 'name': 'Leominster (Sholan Farm)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.4875, 'elev': 720, 'lon': -71.7756, 'network': 'newa'},
'kmvy': {'srqual': 'ok', 'state': 'MA', 'name': 'Vineyard Haven', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.39306, 'elev': 68.0, 'lon': -70.615, 'network': 'icao'},
'mha': {'srqual': 'ok', 'state': 'MA', 'name': 'Harvard', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.500556, 'elev': 564, 'lon': -71.5625, 'network': 'newa'},
'um_bcf': {'name': 'Barnstable County Farm', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -70.288709, 'state': 'MA', 'elev': 53, 'lat': 41.697834, 'network': 'cu_log'},
'mre': {'srqual': 'toolow', 'state': 'MA', 'name': 'Seekonk', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.777314, 'elev': 16, 'lon': -71.320638, 'network': 'newa'},
'kbaf': {'srqual': 'bad', 'state': 'MA', 'name': 'Westfield Arpt', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.15778, 'elev': 271.0, 'lon': -72.71611, 'network': 'icao'},
'ksby': {'srqual': 'ok', 'state': 'MD', 'name': 'Salisbury', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.3406, 'elev': 48, 'lon': -75.5103, 'network': 'icao'},
'md_wdb': {'srqual': 'ok', 'state': 'MD', 'name': 'Woodbine', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.31527, 'elev': 628, 'lon': -77.10401, 'network': 'newa'},
'kbwi': {'srqual': 'ok', 'state': 'MD', 'name': 'Baltimore', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.1667, 'elev': 156, 'lon': -76.6833, 'network': 'icao'},
'kstl': {'srqual': 'ok', 'state': 'MO', 'name': 'St. Louis', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.7525, 'elev': 531, 'lon': -90.3736, 'network': 'icao'},
'kmsp': {'srqual': 'ok', 'state': 'MN', 'name': 'Minneapolis', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.8831, 'elev': 872, 'lon': -93.2289, 'network': 'icao'},
'kstc': {'srqual': 'ok', 'state': 'MN', 'name': 'St Cloud', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 45.5433, 'elev': 1032, 'lon': -94.0514, 'network': 'icao'},
'mn_lkc': {'srqual': 'ok', 'state': 'MN', 'name': 'Lake City', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.420187, 'elev': 1140, 'lon': -92.227366, 'network': 'newa'},
'kdlh': {'srqual': 'ok', 'state': 'MN', 'name': 'Diluth', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 46.8369, 'elev': 1433, 'lon': -92.1833, 'network': 'icao'},
'mn_lac': {'srqual': 'ok', 'state': 'MN', 'name': 'La Crescent', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.858199, 'elev': 1231, 'lon': -91.318371, 'network': 'newa'},
'mn_aft': {'srqual': 'ok', 'state': 'MN', 'name': 'Afton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.819, 'elev': 881, 'lon': -92.796, 'network': 'newa'},
'mn_cha': {'name': 'Chaska (Univ MN HRC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -93.634693, 'state': 'MN', 'elev': 1029, 'lat': 44.86252, 'network': 'newa'},
'krst': {'srqual': 'ok', 'state': 'MN', 'name': 'Rochester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.9042, 'elev': 1304, 'lon': -92.4917, 'network': 'icao'},
'mn_buf': {'srqual': 'ok', 'state': 'MN', 'name': 'Buffalo', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.22, 'elev': 1015, 'lon': -93.84, 'network': 'newa'},
'mn_och': {'srqual': 'ok', 'state': 'MN', 'name': 'Worthington (Ocheda)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.56208, 'elev': 1594, 'lon': -95.573347, 'network': 'newa'},
'mn_pre': {'srqual': 'ok', 'state': 'MN', 'name': 'Preston', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.6825, 'elev': 1088, 'lon': -92.0761, 'network': 'newa'},
'mn_has': {'srqual': 'ok', 'state': 'MN', 'name': 'Hastings', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.7884, 'elev': 904, 'lon': -92.81677, 'network': 'newa'},
'mn_wbl': {'srqual': 'ok', 'state': 'MN', 'name': 'White Bear Lake', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.10632, 'elev': 955, 'lon': -92.955087, 'network': 'newa'},
'mn_sha': {'srqual': 'ok', 'state': 'MN', 'name': 'Shafer', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.352665, 'elev': 938, 'lon': -92.753021, 'network': 'newa'},
'kgpz': {'srqual': 'ok', 'state': 'MN', 'name': 'Grand Rapids (Airport)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 47.2111, 'elev': 1355, 'lon': -93.5097, 'network': 'icao'},
'mn_elg': {'srqual': 'ok', 'state': 'MN', 'name': 'Elgin', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.1364, 'elev': 1050, 'lon': -92.242435, 'network': 'newa'},
'mn_del': {'srqual': 'ok', 'state': 'MN', 'name': 'Delano (Apple Jack)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.0997, 'elev': 925, 'lon': -93.7902, 'network': 'newa'},
'mn_gra': {'srqual': 'ok', 'state': 'MN', 'name': 'Grand Rapids', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 47.24245, 'elev': 1289, 'lon': -93.492838, 'network': 'newa'},
'mn_alx': {'srqual': 'ok', 'state': 'MN', 'name': 'Alexandria', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.872756, 'elev': 1403, 'lon': -95.470478, 'network': 'newa'},
'kged': {'srqual': 'ok', 'state': 'DE', 'name': 'Georgetown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.6892, 'elev': 51, 'lon': -75.3592, 'network': 'icao'},
'kilg': {'srqual': 'ok', 'state': 'DE', 'name': 'Wilmington', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.67, 'elev': 79, 'lon': -75.6, 'network': 'icao'},
'koma': {'srqual': 'ok', 'state': 'NE', 'name': 'Omaha', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.3103, 'elev': 982, 'lon': -95.8992, 'network': 'icao'},
'un_nec': {'srqual': 'ok', 'state': 'NE', 'name': 'Nebraska City 2N', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.7, 'elev': 1076.0, 'lon': -95.8833, 'network': 'cu_log'},
'klnk': {'srqual': 'ok', 'state': 'NE', 'name': 'Lincoln Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.8508, 'elev': 1190.0, 'lon': -96.7475, 'network': 'icao'},
'kovs': {'srqual': 'ok', 'state': 'WI', 'name': 'Boscobel', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.16085, 'elev': 672.0, 'lon': -90.6737, 'network': 'icao'},
'klse': {'srqual': 'ok', 'state': 'WI', 'name': 'La Crosse', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.8789, 'elev': 652, 'lon': -91.2528, 'network': 'icao'},
'wi_gay': {'srqual': 'ok', 'state': 'WI', 'name': 'Gays Mills', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.314584, 'elev': 942, 'lon': -90.841526, 'network': 'newa'},
'kdca': {'srqual': 'ok', 'state': 'DC', 'name': 'Washington', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.8483, 'elev': 10, 'lon': -77.0342, 'network': 'icao'},
'kalb': {'srqual': 'ok', 'state': 'NY', 'name': 'Albany', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.74306, 'elev': 275.0, 'lon': -73.80917, 'network': 'icao'},
'rom': {'srqual': 'ok', 'state': 'NY', 'name': 'Romulus (Thirsty Owl)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.69709, 'elev': 485, 'lon': -76.746448, 'network': 'newa'},
'ith': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Ithaca Cornell Orchards', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.444543, 'elev': 902.0, 'lon': -76.461786, 'network': 'newa'},
'kith': {'srqual': 'ok', 'state': 'NY', 'name': 'Ithaca Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.48333, 'elev': 1066.0, 'lon': -76.46667, 'network': 'icao'},
'alb': {'srqual': 'toolow', 'state': 'NY', 'name': 'Albion', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.275135, 'elev': 430.0, 'lon': -78.134927, 'network': 'newa'},
'ptb': {'srqual': 'ok', 'state': 'NY', 'name': 'Point Breeze', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.355, 'elev': 91, 'lon': -78.19, 'network': 'newa'},
'kjfk': {'srqual': 'ok', 'state': 'NY', 'name': 'NYC-JFK Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.63861, 'elev': 11.0, 'lon': -73.76222, 'network': 'icao'},
'kpou': {'srqual': 'ok', 'state': 'NY', 'name': 'Poughkeepsie', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.62667, 'elev': 166.0, 'lon': -73.88417, 'network': 'icao'},
'fis': {'srqual': 'ok', 'state': 'NY', 'name': 'Fishkill', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.517978, 'elev': 114, 'lon': -73.824541, 'network': 'newa'},
'cut': {'srqual': 'ok', 'state': 'NY', 'name': 'Cutchogue', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.026664, 'elev': 30, 'lon': -72.486658, 'network': 'newa'},
'ver': {'name': 'Versailles', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -79.02689, 'state': 'NY', 'elev': 863, 'lat': 42.5164, 'network': 'newa'},
'cli': {'srqual': 'ok', 'state': 'NY', 'name': 'Clifton Park', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.815913, 'elev': 378.0, 'lon': -73.837641, 'network': 'newa'},
'elb': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Elba', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.15204, 'elev': 651.0, 'lon': -78.147, 'network': 'newa'},
'kelm': {'srqual': 'ok', 'state': 'NY', 'name': 'Elmira', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.15944, 'elev': 955.0, 'lon': -76.89194, 'network': 'icao'},
'vlt': {'name': 'Valatie', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -73.6845, 'state': 'NY', 'elev': 306.1, 'lat': 42.4358, 'network': 'newa'},
'wmi': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Water Mill', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.91111, 'elev': 15.0, 'lon': -72.31748, 'network': 'newa'},
'aur': {'srqual': 'ok', 'state': 'NY', 'name': 'Aurora', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.73367, 'elev': 840, 'lon': -76.65383, 'network': 'newa'},
'clw': {'srqual': 'ok', 'state': 'NY', 'name': 'Clintondale (WG Minard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'lat': 41.693276, 'elev': 577.0, 'lon': -74.054027, 'network': 'newa'},
'lkp': {'srqual': 'ok', 'state': 'NY', 'name': 'Lake Placid', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.273768, 'elev': 1680, 'lon': -73.94865, 'network': 'newa'},
'klga': {'srqual': 'ok', 'state': 'NY', 'name': 'NYC-LaGuardia Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.77944, 'elev': 11.0, 'lon': -73.88028, 'network': 'icao'},
'far': {'srqual': 'toolow', 'state': 'NY', 'name': 'Farmington', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.99004, 'elev': 600.0, 'lon': -77.2623, 'network': 'newa'},
'som': {'srqual': 'ok', 'state': 'NY', 'name': 'Somerset', 'vars': ['temp', 'lwet', 'rhum', 'prcp', 'wspd', 'wdir', 'srad'], 'lat': 43.325911, 'elev': 318.0, 'lon': -78.626908, 'network': 'newa'},
'noa': {'srqual': 'ok', 'state': 'NY', 'name': 'Appleton, North', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.34403, 'elev': 300.0, 'lon': -78.66566, 'network': 'newa'},
'cer': {'name': 'Ceres', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -78.299024, 'state': 'NY', 'elev': 1500, 'lat': 42.007429, 'network': 'newa'},
'hig': {'srqual': 'ok', 'state': 'NY', 'name': 'Highland HVL', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.746139, 'elev': 436.0, 'lon': -73.96699, 'network': 'newa'},
'gen': {'srqual': 'ok', 'state': 'NY', 'name': 'Geneva', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.87295, 'elev': 650.0, 'lon': -77.02818, 'network': 'newa'},
'mod': {'srqual': 'ok', 'state': 'NY', 'name': 'Modena', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.670619, 'elev': 460, 'lon': -74.116855, 'network': 'newa'},
'gbe': {'srqual': 'ok', 'state': 'NY', 'name': 'Geneva (Bejo)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.82755, 'elev': 700.0, 'lon': -77.01053, 'network': 'newa'},
'kmtp': {'srqual': 'bad', 'state': 'NY', 'name': 'Montauk', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.07306, 'elev': 7.0, 'lon': -71.92333, 'network': 'icao'},
'wbs': {'srqual': 'ok', 'state': 'NY', 'name': 'Williamson (Bear Swamp)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.250549, 'elev': 367, 'lon': -77.160323, 'network': 'newa'},
'emo': {'srqual': 'ok', 'state': 'NY', 'name': 'East Moriches', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.801728, 'elev': 30, 'lon': -72.769788, 'network': 'newa'},
'dun': {'srqual': 'ok', 'state': 'NY', 'name': 'Dundee (Wiemer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.570677, 'elev': 702, 'lon': -76.928593, 'network': 'newa'},
'shc': {'srqual': 'ok', 'state': 'NY', 'name': 'Southold (Corey Creek)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.045194, 'elev': 25, 'lon': -72.4452, 'network': 'newa'},
'shd': {'srqual': 'ok', 'state': 'NY', 'name': 'Southold (One Woman)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.08, 'elev': 29, 'lon': -72.42, 'network': 'newa'},
'she': {'srqual': 'ok', 'state': 'NY', 'name': 'Sheridan', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.50207, 'elev': 750, 'lon': -79.20513, 'network': 'newa'},
'bal': {'srqual': 'ok', 'state': 'NY', 'name': 'Baldwinsville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.169525, 'elev': 443, 'lon': -76.400886, 'network': 'newa'},
'cro': {'srqual': 'ok', 'state': 'NY', 'name': 'Crown Point', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.951858, 'elev': 120.0, 'lon': -73.414106, 'network': 'newa'},
'kswf': {'srqual': 'ok', 'state': 'NY', 'name': 'Newburgh Stewart Field', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.5, 'elev': 581.0, 'lon': -74.1, 'network': 'icao'},
'gfr': {'srqual': 'ok', 'state': 'NY', 'name': 'Ithaca (Game Farm Rd)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.44924, 'elev': 968, 'lon': -76.44905, 'network': 'newa'},
'kpeo': {'srqual': 'ok', 'state': 'NY', 'name': 'Penn Yan', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.6425, 'elev': 903.0, 'lon': -77.05639, 'network': 'icao'},
'kfzy': {'srqual': 'ok', 'state': 'NY', 'name': 'Fulton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.34972, 'elev': 475.0, 'lon': -76.38472, 'network': 'icao'},
'mar': {'srqual': 'ok', 'state': 'NY', 'name': 'Marlboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'lat': 41.590299, 'elev': 390.0, 'lon': -73.984509, 'network': 'newa'},
'kgfl': {'srqual': 'ok', 'state': 'NY', 'name': 'Glens Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.34111, 'elev': 320.0, 'lon': -73.61028, 'network': 'icao'},
'arm': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Arkport (Mahany)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.42882, 'elev': 1300.0, 'lon': -77.6843, 'network': 'newa'},
'fts': {'srqual': 'ok', 'state': 'NY', 'name': 'Fort Salonga', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.897214, 'elev': 99, 'lon': -73.278708, 'network': 'newa'},
'cns': {'srqual': 'ok', 'state': 'NY', 'name': 'Cutchogue (New Suffolk)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.01, 'elev': 26, 'lon': -72.48, 'network': 'newa'},
'kdsv': {'srqual': 'ok', 'state': 'NY', 'name': 'Dansville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.5675, 'elev': 649.0, 'lon': -77.71417, 'network': 'icao'},
'wgl': {'srqual': 'ok', 'state': 'NY', 'name': 'Watkins Glen', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.377077, 'elev': 1100.0, 'lon': -76.925487, 'network': 'newa'},
'per': {'srqual': 'ok', 'state': 'NY', 'name': 'Peru', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.566692, 'elev': 370.0, 'lon': -73.512769, 'network': 'newa'},
'kfrg': {'srqual': 'ok', 'state': 'NY', 'name': 'Farmingdale', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.73417, 'elev': 81.0, 'lon': -73.41694, 'network': 'icao'},
'knyc': {'name': 'NYC-Central Park', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -73.96917, 'state': 'NY', 'elev': 130.0, 'lat': 40.77889, 'network': 'icao'},
'bla': {'srqual': 'ok', 'state': 'NY', 'name': 'Baldwinsville (Abbott)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.145093, 'elev': 502, 'lon': -76.282136, 'network': 'newa'},
'red': {'srqual': 'ok', 'state': 'NY', 'name': 'Red Hook', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.008868, 'elev': 230.0, 'lon': -73.849695, 'network': 'newa'},
'med': {'srqual': 'ok', 'state': 'NY', 'name': 'Medina', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.2, 'elev': 600, 'lon': -78.39275, 'network': 'newa'},
'kmgj': {'srqual': 'ok', 'state': 'NY', 'name': 'Montgomery', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.50917, 'elev': 365.0, 'lon': -74.265, 'network': 'icao'},
'kroc': {'srqual': 'ok', 'state': 'NY', 'name': 'Rochester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.11667, 'elev': 533.0, 'lon': -77.67667, 'network': 'icao'},
'ber': {'srqual': 'ok', 'state': 'NY', 'name': 'Bergen', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i'], 'lat': 43.085377, 'elev': 620, 'lon': -77.948586, 'network': 'newa'},
'sod': {'srqual': 'toolow', 'state': 'NY', 'name': 'Sodus', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.171946, 'elev': 450.0, 'lon': -77.078962, 'network': 'newa'},
'acc': {'srqual': 'ok', 'state': 'NY', 'name': 'Accord', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.807602, 'elev': 386, 'lon': -74.248764, 'network': 'newa'},
'kdkk': {'srqual': 'ok', 'state': 'NY', 'name': 'Dunkirk', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.49333, 'elev': 666.0, 'lon': -79.27222, 'network': 'icao'},
'lod': {'srqual': 'ok', 'state': 'NY', 'name': 'Lodi (Standing Stone)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.543054, 'elev': 719.0, 'lon': -76.874138, 'network': 'newa'},
'drs': {'srqual': 'ok', 'state': 'NY', 'name': 'Dresden (FLGP/FLCC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.706147, 'elev': 1021, 'lon': -76.974658, 'network': 'newa'},
'shm': {'srqual': 'toolow', 'state': 'NY', 'name': 'Southold (Mudd)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.06, 'elev': 25, 'lon': -72.45, 'network': 'newa'},
'int': {'srqual': 'ok', 'state': 'NY', 'name': 'Interlaken (Airy Acres)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.636288, 'elev': 242, 'lon': -76.725271, 'network': 'newa'},
'wla': {'srqual': 'ok', 'state': 'NY', 'name': 'Watkins Glen (Lakewood)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.428133, 'elev': 906, 'lon': -76.9057, 'network': 'newa'},
'wlb': {'srqual': 'ok', 'state': 'NY', 'name': 'Willsboro', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'lwet', 'srad'], 'lat': 44.3843, 'elev': 180.0, 'lon': -73.3818, 'network': 'newa'},
'hvl': {'name': 'Highland HVL 2', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -73.967, 'state': 'NY', 'elev': 437, 'lat': 41.75, 'network': 'newa'},
'2wi': {'srqual': 'ok', 'state': 'NY', 'name': 'Williamson (Mason)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.22206, 'elev': 427.0, 'lon': -77.23158, 'network': 'newa'},
'khpn': {'srqual': 'ok', 'state': 'NY', 'name': 'White Plains', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.06694, 'elev': 379.0, 'lon': -73.7075, 'network': 'icao'},
'por': {'srqual': 'ok', 'state': 'NY', 'name': 'Portland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.371481, 'elev': 700.0, 'lon': -79.487296, 'network': 'newa'},
'bri': {'srqual': 'ok', 'state': 'NY', 'name': 'Bridgehampton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.96, 'elev': 87, 'lon': -72.31, 'network': 'newa'},
'brh': {'srqual': 'ok', 'state': 'NY', 'name': 'Brookhaven Hamlet', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.769289, 'elev': 18, 'lon': -72.922614, 'network': 'newa'},
'poe': {'srqual': 'ok', 'state': 'NY', 'name': 'Portland Escarpment', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.34944, 'elev': 1076, 'lon': -79.47194, 'network': 'newa'},
'bra': {'srqual': 'ok', 'state': 'NY', 'name': 'Branchport', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.584167, 'elev': 1043, 'lon': -77.167778, 'network': 'newa'},
'fre': {'srqual': 'bad', 'state': 'NY', 'name': 'Freeville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.51914, 'elev': 1100.0, 'lon': -76.33113, 'network': 'newa'},
'cu_gfr': {'srqual': 'ok', 'state': 'NY', 'name': 'Ithaca Cornell', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.4492, 'elev': 960.0, 'lon': -76.4492, 'network': 'cu_log'},
'wad': {'srqual': 'ok', 'state': 'NY', 'name': 'Wading River', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.95, 'elev': 107, 'lon': -72.81, 'network': 'newa'},
'lol': {'srqual': 'ok', 'state': 'NY', 'name': 'Lodi (Lamoreaux)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.57664, 'elev': 853, 'lon': -76.85844, 'network': 'newa'},
'kjhw': {'srqual': 'ok', 'state': 'NY', 'name': 'Jamestown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.15, 'elev': 1719.0, 'lon': -79.25, 'network': 'icao'},
'kgtb': {'srqual': 'ok', 'state': 'NY', 'name': 'Wheeler Sack Field', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.05, 'elev': 702.0, 'lon': -75.73333, 'network': 'icao'},
'way': {'srqual': 'ok', 'state': 'NY', 'name': 'Wayland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.604968, 'elev': 1600.0, 'lon': -77.578797, 'network': 'newa'},
'hec': {'srqual': 'ok', 'state': 'NY', 'name': 'Hector', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.50804, 'elev': 800, 'lon': -76.877825, 'network': 'newa'},
'var': {'srqual': 'ok', 'state': 'NY', 'name': 'Varick (Swedish Hill)', 'vars': ['temp', 'lwet', 'rhum', 'prcp', 'wspd', 'wdir', 'srad'], 'lat': 42.80248, 'elev': 662.0, 'lon': -76.81007, 'network': 'newa'},
'chz': {'srqual': 'ok', 'state': 'NY', 'name': 'Chazy (Grower)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.8619, 'elev': 167.0, 'lon': -73.429071, 'network': 'newa'},
'hud': {'srqual': 'ok', 'state': 'NY', 'name': 'Hudson', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'lat': 42.1910246, 'elev': 216.0, 'lon': -73.8303834, 'network': 'newa'},
'kslk': {'srqual': 'ok', 'state': 'NY', 'name': 'Saranac Lake', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.38528, 'elev': 1663.0, 'lon': -74.20667, 'network': 'icao'},
'kbuf': {'srqual': 'ok', 'state': 'NY', 'name': 'Buffalo', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.94083, 'elev': 705.0, 'lon': -78.73583, 'network': 'icao'},
'but': {'srqual': 'ok', 'state': 'NY', 'name': 'Butler (Tree Crisp)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.067219, 'elev': 457, 'lon': -76.760174, 'network': 'newa'},
'rvm': {'srqual': 'ok', 'state': 'NY', 'name': 'Riverhead (MCV)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.98, 'elev': 54, 'lon': -72.58, 'network': 'newa'},
'gai': {'srqual': 'toolow', 'state': 'NY', 'name': 'Gainesville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.652126, 'elev': 1600.0, 'lon': -78.162607, 'network': 'newa'},
'sdl': {'srqual': 'ok', 'state': 'NY', 'name': 'Sodus (Lake)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.252375, 'elev': 373, 'lon': -77.06239, 'network': 'newa'},
'ksyr': {'srqual': 'ok', 'state': 'NY', 'name': 'Syracuse', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.10917, 'elev': 410.0, 'lon': -76.10333, 'network': 'icao'},
'cas': {'srqual': 'ok', 'state': 'NY', 'name': 'Castleton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.537142, 'elev': 288, 'lon': -73.71053, 'network': 'newa'},
'mts': {'srqual': 'ok', 'state': 'NY', 'name': 'Mattituck (Shinn)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.01, 'elev': 42, 'lon': -72.53, 'network': 'newa'},
'kelz': {'srqual': 'bad', 'state': 'NY', 'name': 'Wellsville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.10944, 'elev': 2124.0, 'lon': -77.99194, 'network': 'icao'},
'den': {'srqual': 'ok', 'state': 'NY', 'name': 'Denver (Stoneline)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.25056, 'elev': 2022, 'lon': -74.52583, 'network': 'newa'},
'rbg': {'name': 'Romulus (Buttonwood Grove)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -76.77, 'state': 'NY', 'elev': 460, 'lat': 42.7331, 'network': 'newa'},
'mtd': {'srqual': 'ok', 'state': 'NY', 'name': 'Mattituck (Dorsett)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.019322, 'elev': 52, 'lon': -72.524561, 'network': 'newa'},
'czy': {'srqual': 'ok', 'state': 'NY', 'name': 'Chazy (Miner)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'lwet', 'srad'], 'lat': 44.886, 'elev': 201.0, 'lon': -73.4705, 'network': 'newa'},
'kart': {'srqual': 'ok', 'state': 'NY', 'name': 'Watertown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.99222, 'elev': 318.0, 'lon': -76.02167, 'network': 'icao'},
'riv': {'srqual': 'ok', 'state': 'NY', 'name': 'Riverhead (LIHREC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.96222, 'elev': 112, 'lon': -72.71611, 'network': 'newa'},
'rip': {'srqual': 'toolow', 'state': 'NY', 'name': 'Ripley', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.265872, 'elev': 758, 'lon': -79.704125, 'network': 'newa'},
'kmss': {'srqual': 'ok', 'state': 'NY', 'name': 'Massena', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.93583, 'elev': 214.0, 'lon': -74.84556, 'network': 'icao'},
'rvp': {'srqual': 'ok', 'state': 'NY', 'name': 'Riverhead (Palmer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.97, 'elev': 49, 'lon': -72.63, 'network': 'newa'},
'kmsv': {'srqual': 'ok', 'state': 'NY', 'name': 'Monticello', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.7, 'elev': 1407.0, 'lon': -74.8, 'network': 'icao'},
'lyn': {'srqual': 'ok', 'state': 'NY', 'name': 'Lyndonville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'lat': 43.298085, 'elev': 361.0, 'lon': -78.369044, 'network': 'newa'},
'kfok': {'srqual': 'ok', 'state': 'NY', 'name': 'Westhampton Beach', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.84361, 'elev': 67.0, 'lon': -72.63222, 'network': 'icao'},
'kiag': {'srqual': 'ok', 'state': 'NY', 'name': 'Niagara Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.10722, 'elev': 585.0, 'lon': -78.94528, 'network': 'icao'},
'gui': {'srqual': 'ok', 'state': 'NY', 'name': 'Guilderland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.721046, 'elev': 390.0, 'lon': -74.017886, 'network': 'newa'},
'krme': {'srqual': 'ok', 'state': 'NY', 'name': 'Griffiss', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.23333, 'elev': 519.0, 'lon': -75.4, 'network': 'icao'},
'sil': {'srqual': 'ok', 'state': 'NY', 'name': 'Silver Creek', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.54247, 'elev': 608, 'lon': -79.19673, 'network': 'newa'},
'lan': {'srqual': 'toohigh', 'state': 'NY', 'name': 'Lansing', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.572295, 'elev': 407.0, 'lon': -76.595127, 'network': 'newa'},
'kbgm': {'srqual': 'ok', 'state': 'NY', 'name': 'Binghamton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.20667, 'elev': 1595.0, 'lon': -75.98, 'network': 'icao'},
'lak': {'srqual': 'ok', 'state': 'NY', 'name': 'Lakemont', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.510207, 'elev': 880, 'lon': -76.92744, 'network': 'newa'},
'laf': {'srqual': 'ok', 'state': 'NY', 'name': 'Lafayette', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.909686, 'elev': 584.0, 'lon': -76.195207, 'network': 'newa'},
'phe': {'srqual': 'ok', 'state': 'NY', 'name': 'Phelps', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.977429, 'elev': 558, 'lon': -77.043439, 'network': 'newa'},
'kin': {'srqual': 'ok', 'state': 'NY', 'name': 'Kinderhook', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.398814, 'elev': 266, 'lon': -73.703383, 'network': 'newa'},
'khwv': {'srqual': 'ok', 'state': 'NY', 'name': 'Brookhaven', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.82167, 'elev': 82.0, 'lon': -72.86889, 'network': 'icao'},
'npz': {'srqual': 'ok', 'state': 'NY', 'name': 'New Paltz', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.7575583, 'elev': 115, 'lon': -74.0502361, 'network': 'newa'},
'npt': {'srqual': 'ok', 'state': 'NY', 'name': 'Northport (Richters)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.884686, 'elev': 213, 'lon': -73.294411, 'network': 'newa'},
'ovi': {'srqual': 'ok', 'state': 'NY', 'name': 'Ovid (Hosmer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.68564, 'elev': 590.0, 'lon': -76.74525, 'network': 'newa'},
'man': {'srqual': 'ok', 'state': 'NY', 'name': 'Manorville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.860597, 'elev': 44, 'lon': -72.821942, 'network': 'newa'},
'3wi': {'srqual': 'ok', 'state': 'NY', 'name': 'Williamson (Demarree)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.27615, 'elev': 300.0, 'lon': -77.1425, 'network': 'newa'},
'kno': {'srqual': 'ok', 'state': 'NY', 'name': 'Knowlesville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.225833, 'elev': 524.0, 'lon': -78.301944, 'network': 'newa'},
'kisp': {'srqual': 'ok', 'state': 'NY', 'name': 'Islip', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.79389, 'elev': 84.0, 'lon': -73.10167, 'network': 'icao'},
'pa_ntr': {'srqual': 'ok', 'state': 'PA', 'name': 'New Tripoli (NWLHS)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.68263, 'elev': 738, 'lon': -75.724929, 'network': 'newa'},
'kbfd': {'srqual': 'ok', 'state': 'PA', 'name': 'Bradford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.80306, 'elev': 2117.0, 'lon': -78.64028, 'network': 'icao'},
'pa_big': {'srqual': 'ok', 'state': 'PA', 'name': 'Biglerville (Hollabaugh)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.946944, 'elev': 732, 'lon': -77.247222, 'network': 'newa'},
'pa_pin': {'srqual': 'ok', 'state': 'PA', 'name': 'Piney Mountain', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.977669, 'elev': 1217, 'lon': -77.339694, 'network': 'newa'},
'pa_ysp': {'srqual': 'ok', 'state': 'PA', 'name': 'York Springs (Lerew)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.038978, 'elev': 740, 'lon': -77.136408, 'network': 'newa'},
'pa_sco': {'srqual': 'ok', 'state': 'PA', 'name': 'Scott Township', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.572091, 'elev': 1750, 'lon': -75.593225, 'network': 'newa'},
'kpit': {'srqual': 'ok', 'state': 'PA', 'name': 'Pittsburgh', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.3547, 'elev': 1248, 'lon': -79.9217, 'network': 'icao'},
'kduj': {'srqual': 'ok', 'state': 'PA', 'name': 'DuBois', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.1783, 'elev': 1814, 'lon': -78.8989, 'network': 'icao'},
'nel': {'srqual': 'ok', 'state': 'PA', 'name': 'North East Lab', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.22834, 'elev': 680, 'lon': -79.85432, 'network': 'newa'},
'kjst': {'srqual': 'ok', 'state': 'PA', 'name': 'Johnstown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.3161, 'elev': 2270, 'lon': -78.8339, 'network': 'icao'},
'kabe': {'srqual': 'ok', 'state': 'PA', 'name': 'Allentown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.6508, 'elev': 390, 'lon': -75.4492, 'network': 'icao'},
'kipt': {'srqual': 'ok', 'state': 'PA', 'name': 'Williamsport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.2433, 'elev': 520, 'lon': -76.9217, 'network': 'icao'},
'nee': {'srqual': 'ok', 'state': 'PA', 'name': 'North East Escarpment', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.18097, 'elev': 1029, 'lon': -79.8517, 'network': 'newa'},
'har': {'srqual': 'ok', 'state': 'PA', 'name': 'Harborcreek', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.1931232, 'elev': 742.0, 'lon': -79.9049196, 'network': 'newa'},
'kaoo': {'srqual': 'ok', 'state': 'PA', 'name': 'Altoona', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.2964, 'elev': 1480, 'lon': -78.3203, 'network': 'icao'},
'krdg': {'srqual': 'ok', 'state': 'PA', 'name': 'Reading', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.3667, 'elev': 341, 'lon': -75.9667, 'network': 'icao'},
'kpne': {'srqual': 'ok', 'state': 'PA', 'name': 'NE Philadelphia', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.08, 'elev': 100, 'lon': -75.02, 'network': 'icao'},
'kphl': {'srqual': 'ok', 'state': 'PA', 'name': 'Philadelphia', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.88, 'elev': 63, 'lon': -75.25, 'network': 'icao'},
'kmdt': {'srqual': 'ok', 'state': 'PA', 'name': 'Middletown Harrisburg', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.1961, 'elev': 312, 'lon': -76.7725, 'network': 'icao'},
'pa_rsp': {'srqual': 'ok', 'state': 'PA', 'name': 'Rock Springs', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.713993, 'elev': 1213, 'lon': -77.948844, 'network': 'newa'},
'pa_npa': {'srqual': 'ok', 'state': 'PA', 'name': 'New Paris (Boyer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.105321, 'elev': 1556, 'lon': -78.629474, 'network': 'newa'},
'kavp': {'srqual': 'ok', 'state': 'PA', 'name': 'Wilkes-Barre', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.3336, 'elev': 930, 'lon': -75.7269, 'network': 'icao'},
'keri': {'srqual': 'ok', 'state': 'PA', 'name': 'Erie', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.08, 'elev': 730.0, 'lon': -80.1825, 'network': 'icao'},
'vpu': {'srqual': 'ok', 'state': 'VT', 'name': 'Putney', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.991, 'elev': 715, 'lon': -72.5421, 'network': 'newa'},
'kvsf': {'srqual': 'ok', 'state': 'VT', 'name': 'Springfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.3436, 'elev': 578.0, 'lon': -72.5178, 'network': 'icao'},
'vdu': {'srqual': 'ok', 'state': 'VT', 'name': 'Dummerston', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.904167, 'elev': 561, 'lon': -72.568466, 'network': 'newa'},
'kbtv': {'srqual': 'ok', 'state': 'VT', 'name': 'Burlington', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.46806, 'elev': 330.0, 'lon': -73.15028, 'network': 'icao'},
'kddh': {'srqual': 'ok', 'state': 'VT', 'name': 'Bennington', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.89139, 'elev': 826.0, 'lon': -73.24694, 'network': 'icao'},
'kmpv': {'srqual': 'ok', 'state': 'VT', 'name': 'Montpelier', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.2, 'elev': 1126.0, 'lon': -72.57, 'network': 'icao'},
'vco': {'srqual': 'ok', 'state': 'VT', 'name': 'Cornwall', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.962033, 'elev': 398, 'lon': -73.239449, 'network': 'newa'},
'ved': {'srqual': 'ok', 'state': 'VT', 'name': 'East Dorset', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.2685, 'elev': 1339, 'lon': -72.9909, 'network': 'newa'},
'krut': {'srqual': 'ok', 'state': 'VT', 'name': 'Rutland', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.53, 'elev': 784.0, 'lon': -72.95, 'network': 'icao'},
'vsb': {'srqual': 'ok', 'state': 'VT', 'name': 'South Burlington', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.4308, 'elev': 233, 'lon': -73.2042, 'network': 'newa'},
'vsh': {'srqual': 'ok', 'state': 'VT', 'name': 'Shoreham', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.8861, 'elev': 351, 'lon': -73.3517, 'network': 'newa'},
'kmvl': {'srqual': 'ok', 'state': 'VT', 'name': 'Morrisville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.53, 'elev': 768.0, 'lon': -72.61, 'network': 'icao'},
'vso': {'srqual': 'ok', 'state': 'VT', 'name': 'South Hero', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.6355, 'elev': 177, 'lon': -73.3033, 'network': 'newa'},
'karr': {'srqual': 'ok', 'state': 'IL', 'name': 'Aurora', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.77, 'elev': 710, 'lon': -88.4814, 'network': 'icao'},
'il_bel': {'srqual': 'ok', 'state': 'IL', 'name': 'Belleville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 38.480416, 'elev': 539, 'lon': -89.93904, 'network': 'newa'},
'il_pgr': {'srqual': 'ok', 'state': 'IL', 'name': 'Poplar Grove', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.391312, 'elev': 916, 'lon': -88.800936, 'network': 'newa'},
'krfd': {'srqual': 'ok', 'state': 'IL', 'name': 'Rockford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.1928, 'elev': 730, 'lon': -89.0931, 'network': 'icao'},
'ia_ccy': {'srqual': 'ok', 'state': 'IA', 'name': 'Central City', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.224159, 'elev': 958, 'lon': -91.494571, 'network': 'newa'},
'kcid': {'srqual': 'ok', 'state': 'IA', 'name': 'Cedar Rapids', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.8833, 'elev': 868.0, 'lon': -91.7167, 'network': 'icao'},
'kiow': {'srqual': 'ok', 'state': 'IA', 'name': 'Iowa City', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.6328, 'elev': 650.0, 'lon': -91.5431, 'network': 'icao'},
'kfsd': {'srqual': 'ok', 'state': 'SD', 'name': 'Sioux Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.5778, 'elev': 1428, 'lon': -96.7539, 'network': 'icao'},
'kuuu': {'srqual': 'ok', 'state': 'RI', 'name': 'Newport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.53333, 'elev': 155.0, 'lon': -71.28333, 'network': 'icao'},
'kpvd': {'srqual': 'ok', 'state': 'RI', 'name': 'Providence', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.71667, 'elev': 60.0, 'lon': -71.43333, 'network': 'icao'},
'ct_npr': {'srqual': 'ok', 'state': 'CT', 'name': 'New Preston', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.665955, 'elev': 860, 'lon': -73.334845, 'network': 'newa'},
'ct_gra': {'srqual': 'ok', 'state': 'CT', 'name': 'Granby', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.958341, 'elev': 270, 'lon': -72.817436, 'network': 'newa'},
'kbdl': {'srqual': 'ok', 'state': 'CT', 'name': 'Hartford (Bradley AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.94, 'elev': 190.0, 'lon': -72.68, 'network': 'icao'},
'kbdr': {'srqual': 'ok', 'state': 'CT', 'name': 'Bridgeport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.15833, 'elev': 5.0, 'lon': -73.12889, 'network': 'icao'},
'ct_gla': {'name': 'Glastonbury HS', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lon': -72.586423, 'state': 'CT', 'elev': 110, 'lat': 41.701804, 'network': 'newa'},
'ct_wal': {'srqual': 'ok', 'state': 'CT', 'name': 'Wallingford', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.449683, 'elev': 249, 'lon': -72.867125, 'network': 'newa'},
'ct_sgl': {'srqual': 'ok', 'state': 'CT', 'name': 'S. Glastonbury', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.652024, 'elev': 350, 'lon': -72.576445, 'network': 'newa'},
'ct_ely': {'srqual': 'ok', 'state': 'CT', 'name': 'East Lyme', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.353398, 'elev': 150, 'lon': -72.247315, 'network': 'newa'},
'ct_rid': {'srqual': 'ok', 'state': 'CT', 'name': 'Ridgefield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.291379, 'elev': 670, 'lon': -73.462419, 'network': 'newa'},
'ct_pla': {'srqual': 'toolow', 'state': 'CT', 'name': 'Plainville MS', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.684327, 'elev': 246, 'lon': -72.885093, 'network': 'newa'},
'ct_por': {'srqual': 'ok', 'state': 'CT', 'name': 'Portland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.580457, 'elev': 303, 'lon': -72.6184, 'network': 'newa'},
'ct_ssm': {'srqual': 'ok', 'state': 'CT', 'name': 'Southington (Shuttle Meadow)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.636917, 'elev': 450, 'lon': -72.839023, 'network': 'newa'},
'ct_sto': {'srqual': 'ok', 'state': 'CT', 'name': 'Storrs (Research Farm)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.7941049, 'elev': 669, 'lon': -72.230211, 'network': 'newa'},
'ct_eas': {'srqual': 'ok', 'state': 'CT', 'name': 'Eastford', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.925038, 'elev': 690, 'lon': -72.106909, 'network': 'newa'},
'ct_mid': {'srqual': 'ok', 'state': 'CT', 'name': 'Middlefield (UConn)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.4940344, 'elev': 364, 'lon': -72.726152, 'network': 'newa'},
'ct_gos': {'srqual': 'ok', 'state': 'CT', 'name': 'Goshen', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.792852, 'elev': 1255, 'lon': -73.20965, 'network': 'newa'},
'ct_nia': {'srqual': 'ok', 'state': 'CT', 'name': 'Niantic', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.349326, 'elev': 28, 'lon': -72.213006, 'network': 'newa'},
'ct_swo': {'srqual': 'bad', 'state': 'CT', 'name': 'South Woodstock MS', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.928673, 'elev': 421, 'lon': -71.956196, 'network': 'newa'},
'ct_mad': {'srqual': 'ok', 'state': 'CT', 'name': 'Madison', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.29511, 'elev': 30, 'lon': -72.62142, 'network': 'newa'},
'uc_sto': {'srqual': 'ok', 'state': 'CT', 'name': 'Storrs (UConn)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.79417, 'elev': 663, 'lon': -72.22889, 'network': 'cu_log'},
'ct_nwi': {'srqual': 'ok', 'state': 'CT', 'name': 'North Windham', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.72157, 'elev': 301, 'lon': -72.167526, 'network': 'newa'},
'ct_she': {'srqual': 'ok', 'state': 'CT', 'name': 'Shelton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.332251, 'elev': 400, 'lon': -73.172193, 'network': 'newa'},
'ct_nca': {'srqual': 'ok', 'state': 'CT', 'name': 'New Canaan', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.132771, 'elev': 274, 'lon': -73.484614, 'network': 'newa'},
'ct_woo': {'srqual': 'ok', 'state': 'CT', 'name': 'Woodstock', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.930842, 'elev': 201, 'lon': -71.985308, 'network': 'newa'},
'ct_new': {'srqual': 'ok', 'state': 'CT', 'name': 'Newtown', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.404534, 'elev': 400, 'lon': -73.28775, 'network': 'newa'},
'ct_ssu': {'srqual': 'ok', 'state': 'CT', 'name': 'Southington (Sunnymount)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.558953, 'elev': 650, 'lon': -72.943323, 'network': 'newa'},
'ct_har': {'srqual': 'ok', 'state': 'CT', 'name': 'Harwinton-Burlington', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.781196, 'elev': 847, 'lon': -72.989213, 'network': 'newa'},
'ct_tol': {'srqual': 'ok', 'state': 'CT', 'name': 'Tolland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.86547, 'elev': 425, 'lon': -72.311078, 'network': 'newa'},
'ct_cha': {'srqual': 'ok', 'state': 'CT', 'name': 'Chaplin', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.75252, 'elev': 592, 'lon': -72.103485, 'network': 'newa'},
'ct_gfy': {'srqual': 'ok', 'state': 'CT', 'name': 'Gales Ferry', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.468442, 'elev': 160, 'lon': -72.057294, 'network': 'newa'},
'ct_ewi': {'srqual': 'ok', 'state': 'CT', 'name': 'East Windsor', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.870777, 'elev': 220, 'lon': -72.530493, 'network': 'newa'},
'ct_was': {'srqual': 'ok', 'state': 'CT', 'name': 'Washington', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.602175, 'elev': 868, 'lon': -73.306449, 'network': 'newa'},
'kdxr': {'srqual': 'ok', 'state': 'CT', 'name': 'Danbury', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.37139, 'elev': 457.0, 'lon': -73.48278, 'network': 'icao'},
'ct_gui': {'srqual': 'ok', 'state': 'CT', 'name': 'Guilford', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.293201, 'elev': 58, 'lon': -72.694292, 'network': 'newa'},
'ct_eha': {'srqual': 'ok', 'state': 'CT', 'name': 'Moodus', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.520094, 'elev': 422, 'lon': -72.444341, 'network': 'newa'},
'ct_heb': {'srqual': 'ok', 'state': 'CT', 'name': 'Hebron', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lat': 41.684921, 'elev': 593, 'lon': -72.392705, 'network': 'newa'},
'ct_pre': {'name': 'Preston', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'lon': -72.018675, 'state': 'CT', 'elev': 238, 'lat': 41.519728, 'network': 'newa'},
}