stn_info = {'vpu': {'srqual': 'ok', 'state': 'VT', 'name': 'Putney', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.991, 'elev': 715, 'lon': -72.5421, 'network': 'newa'},
'kvsf': {'srqual': 'ok', 'state': 'VT', 'name': 'Springfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.3436, 'elev': 578.0, 'lon': -72.5178, 'network': 'icao'},
'vdu': {'srqual': 'ok', 'state': 'VT', 'name': 'Dummerston', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.904167, 'elev': 561, 'lon': -72.568466, 'network': 'newa'},
'kbtv': {'srqual': 'ok', 'state': 'VT', 'name': 'Burlington', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.46806, 'elev': 330.0, 'lon': -73.15028, 'network': 'icao'},
'kddh': {'srqual': 'ok', 'state': 'VT', 'name': 'Bennington', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.89139, 'elev': 826.0, 'lon': -73.24694, 'network': 'icao'},
'kmpv': {'srqual': 'ok', 'state': 'VT', 'name': 'Montpelier', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.2, 'elev': 1126.0, 'lon': -72.57, 'network': 'icao'},
'vco': {'srqual': 'ok', 'state': 'VT', 'name': 'Cornwall', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.962033, 'elev': 398, 'lon': -73.239449, 'network': 'newa'},
'ved': {'srqual': 'ok', 'state': 'VT', 'name': 'East Dorset', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.2685, 'elev': 1339, 'lon': -72.9909, 'network': 'newa'},
'krut': {'srqual': 'ok', 'state': 'VT', 'name': 'Rutland', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.53, 'elev': 784.0, 'lon': -72.95, 'network': 'icao'},
'vsb': {'srqual': 'ok', 'state': 'VT', 'name': 'South Burlington', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.4308, 'elev': 233, 'lon': -73.2042, 'network': 'newa'},
'vsh': {'srqual': 'ok', 'state': 'VT', 'name': 'Shoreham', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.8861, 'elev': 351, 'lon': -73.3517, 'network': 'newa'},
'kmvl': {'srqual': 'ok', 'state': 'VT', 'name': 'Morrisville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.53, 'elev': 768.0, 'lon': -72.61, 'network': 'icao'},
'vso': {'srqual': 'ok', 'state': 'VT', 'name': 'South Hero', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.6355, 'elev': 177, 'lon': -73.3033, 'network': 'newa'},
}