stn_info = {'kcho': {'srqual': 'ok', 'state': 'VA', 'name': 'Charlottesville (Arpt)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.1386, 'elev': 641, 'lon': -78.4531, 'network': 'icao'},
'kroa': {'srqual': 'ok', 'state': 'VA', 'name': 'Roanoke', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 37.3169, 'elev': 1175, 'lon': -79.9742, 'network': 'icao'},
'va_cov': {'name': 'Covesville (Purvis Orchard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -78.717696, 'state': 'VA', 'elev': 747, 'lat': 37.868371, 'network': 'newa'},
'klyh': {'srqual': 'ok', 'state': 'VA', 'name': 'Lynchburg', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 37.3208, 'elev': 940, 'lon': -79.2067, 'network': 'icao'},
'kshd': {'srqual': 'ok', 'state': 'VA', 'name': 'Staunton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.27, 'elev': 1188, 'lon': -78.85, 'network': 'icao'},
'va_oak': {'srqual': 'ok', 'state': 'VA', 'name': 'Oak Grove (Ingleside)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 38.153703, 'elev': 178, 'lon': -77.004929, 'network': 'newa'},
'kwal': {'srqual': 'ok', 'state': 'VA', 'name': 'Wallops Island', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 37.9372, 'elev': 46, 'lon': -75.4708, 'network': 'icao'},
'va_pae': {'name': 'Paeonian Springs (Twin Notch)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -77.5839, 'state': 'VA', 'elev': 685, 'lat': 39.1689, 'network': 'newa'},
'kiad': {'srqual': 'ok', 'state': 'VA', 'name': 'Dulles Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.9408, 'elev': 290, 'lon': -77.4636, 'network': 'icao'},
'va_bat': {'srqual': 'ok', 'state': 'VA', 'name': 'Batesville (Crown Orchard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 37.974299, 'elev': 832, 'lon': -78.730016, 'network': 'newa'},
'kric': {'srqual': 'ok', 'state': 'VA', 'name': 'Richmond', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 37.505, 'elev': 164, 'lon': -77.3203, 'network': 'icao'},
'khef': {'srqual': 'ok', 'state': 'VA', 'name': 'Manassas', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.72139, 'elev': 192, 'lon': -77.51528, 'network': 'icao'},
'va_fis': {'srqual': 'ok', 'state': 'VA', 'name': 'Fishersville (Barren Ridge)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 38.13448, 'elev': 1390, 'lon': -78.95803, 'network': 'newa'},
'korf': {'srqual': 'ok', 'state': 'VA', 'name': 'Norfolk', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 36.9033, 'elev': 30, 'lon': -76.1922, 'network': 'icao'},
'knyg': {'srqual': 'ok', 'state': 'VA', 'name': 'Quantico', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.5, 'elev': 10, 'lon': -77.3, 'network': 'icao'},
'kdan': {'srqual': 'ok', 'state': 'VA', 'name': 'Danville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 36.5728, 'elev': 571, 'lon': -79.3361, 'network': 'icao'},
'va_cha': {'srqual': 'ok', 'state': 'VA', 'name': 'Charlottesville (Carter Mtn Orchard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st1i', 'sm1i'], 'lat': 37.9906478, 'elev': 1148, 'lon': -78.472665, 'network': 'newa'},
'va_win': {'srqual': 'ok', 'state': 'VA', 'name': 'Winchester (VT AHS AREC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.112873, 'elev': 925, 'lon': -78.284048, 'network': 'newa'},
'va_was': {'srqual': 'ok', 'state': 'VA', 'name': 'Washington (Gadino Cellars)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 38.688727, 'elev': 681, 'lon': -78.175908, 'network': 'newa'},
'kphf': {'srqual': 'ok', 'state': 'VA', 'name': 'Newport News', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 37.1319, 'elev': 42, 'lon': -76.4931, 'network': 'icao'},
'kakq': {'srqual': 'ok', 'state': 'VA', 'name': 'Wakefield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 36.9839, 'elev': 109, 'lon': -77.0072, 'network': 'icao'},
'kntu': {'srqual': 'ok', 'state': 'VA', 'name': 'Oceana', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 36.8167, 'elev': 23, 'lon': -76.0333, 'network': 'icao'},
'va_cro': {'srqual': 'ok', 'state': 'VA', 'name': 'Crozet (Chiles Peach Orchard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st1i', 'sm1i'], 'lat': 38.068007, 'elev': 922, 'lon': -78.748675, 'network': 'newa'},
'va_red': {'name': 'Red Hill', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -78.613412, 'state': 'VA', 'elev': 676, 'lat': 37.954253, 'network': 'newa'},
}