stn_info = {'mbo': {'srqual': 'ok', 'state': 'MA', 'name': 'Bolton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.418889, 'elev': 516, 'lon': -71.641389, 'network': 'newa'},
'kpvc': {'srqual': 'ok', 'state': 'MA', 'name': 'Provincetown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.07194, 'elev': 8.0, 'lon': -70.22111, 'network': 'icao'},
'mbe': {'srqual': 'ok', 'state': 'MA', 'name': 'Belchertown-2', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.25306, 'elev': 623, 'lon': -72.35972, 'network': 'newa'},
'kpym': {'srqual': 'ok', 'state': 'MA', 'name': 'Plymouth', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.90972, 'elev': 149.0, 'lon': -70.72944, 'network': 'icao'},
'kpsf': {'srqual': 'bad', 'state': 'MA', 'name': 'Pittsfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.42722, 'elev': 1194.0, 'lon': -73.28917, 'network': 'icao'},
'kcef': {'srqual': 'ok', 'state': 'MA', 'name': 'Chicopee Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.2, 'elev': 246.0, 'lon': -72.53333, 'network': 'icao'},
'ktan': {'srqual': 'ok', 'state': 'MA', 'name': 'Taunton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.87556, 'elev': 43.0, 'lon': -71.02111, 'network': 'icao'},
'kowd': {'srqual': 'ok', 'state': 'MA', 'name': 'Norwood', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.19083, 'elev': 50.0, 'lon': -71.17361, 'network': 'icao'},
'mdr': {'srqual': 'toolow', 'county': 'Middlesex', 'state': 'MA', 'name': 'Dracut', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.680556, 'elev': 151, 'lon': -71.264722, 'climate_div': 'MA02', 'network': 'newa'},
'korh': {'srqual': 'ok', 'state': 'MA', 'name': 'Worcester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.26722, 'elev': 986.0, 'lon': -71.87611, 'network': 'icao'},
'mnb': {'srqual': 'ok', 'state': 'MA', 'name': 'Northbridge', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.151711, 'elev': 444, 'lon': -71.680108, 'network': 'newa'},
'um_clk': {'srqual': 'ok', 'state': 'MA', 'name': 'Deerfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.56333, 'elev': 328, 'lon': -72.62333, 'network': 'cu_log'},
'kfit': {'srqual': 'ok', 'state': 'MA', 'name': 'Fitchburg', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.55194, 'elev': 348.0, 'lon': -71.75583, 'network': 'icao'},
'um_tff': {'name': 'Northboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -71.67833, 'state': 'MA', 'elev': 610, 'lat': 42.34611, 'network': 'cu_log'},
'msw': {'srqual': 'ok', 'state': 'MA', 'name': 'Stow (Shelburne)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.446944, 'elev': 233, 'lon': -71.501111, 'network': 'newa'},
'mst': {'srqual': 'ok', 'county': 'Middlesex', 'state': 'MA', 'name': 'Stow', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.409444, 'elev': 239, 'lon': -71.513889, 'climate_div': 'MA02', 'network': 'newa'},
'um_whs': {'srqual': 'ok', 'state': 'MA', 'name': 'Boston (Weld Hill)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i'], 'lat': 42.29556, 'elev': 151, 'lon': -71.13361, 'network': 'cu_log'},
'mwa': {'srqual': 'ok', 'state': 'MA', 'name': 'UMass Waltham Center', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.383988, 'elev': 66, 'lon': -71.212285, 'network': 'newa'},
'mwe': {'srqual': 'toolow', 'state': 'MA', 'name': 'Westfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.185, 'elev': 321, 'lon': -72.765, 'network': 'newa'},
'msh': {'srqual': 'ok', 'state': 'MA', 'name': 'Sharon', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.09861, 'elev': 265, 'lon': -71.21583, 'network': 'newa'},
'um_cso': {'srqual': 'ok', 'state': 'MA', 'name': 'Belchertown', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.25333, 'elev': 638, 'lon': -72.35917, 'network': 'cu_log'},
'klwm': {'srqual': 'ok', 'state': 'MA', 'name': 'Lawrence', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.71722, 'elev': 149.0, 'lon': -71.12389, 'network': 'icao'},
'msd': {'srqual': 'ok', 'state': 'MA', 'name': 'South Deerfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.47972, 'elev': 131, 'lon': -72.57944, 'network': 'newa'},
'kmqe': {'srqual': 'bad', 'state': 'MA', 'name': 'E Milton Blue Hill', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.21222, 'elev': 630.0, 'lon': -71.11361, 'network': 'icao'},
'kaqw': {'srqual': 'bad', 'state': 'MA', 'name': 'North Adams', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.69583, 'elev': 654.0, 'lon': -73.17083, 'network': 'icao'},
'mas': {'srqual': 'toohigh', 'county': 'Franklin', 'state': 'MA', 'name': 'Ashfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.560278, 'elev': 946, 'lon': -72.815833, 'climate_div': 'MA01', 'network': 'newa'},
'kbed': {'srqual': 'ok', 'state': 'MA', 'name': 'Bedford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.47, 'elev': 133.0, 'lon': -71.28944, 'network': 'icao'},
'meb': {'srqual': 'toolow', 'state': 'MA', 'name': 'East Bridgewater', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.007778, 'elev': 40, 'lon': -70.943333, 'network': 'newa'},
'kore': {'srqual': 'ok', 'state': 'MA', 'name': 'Orange', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.57, 'elev': 555.0, 'lon': -72.29111, 'network': 'icao'},
'kewb': {'srqual': 'ok', 'state': 'MA', 'name': 'New Bedford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.67639, 'elev': 80.0, 'lon': -70.95833, 'network': 'icao'},
'mph': {'srqual': 'ok', 'state': 'MA', 'name': 'Phillipston', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.580777, 'elev': 1183, 'lon': -72.146067, 'network': 'newa'},
'um_ces': {'srqual': 'ok', 'state': 'MA', 'name': 'Weston (Case Estates)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.35806, 'elev': 246, 'lon': -71.29889, 'network': 'cu_log'},
'mty': {'srqual': 'ok', 'county': 'Windham', 'state': 'MA', 'name': 'Tyngsboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.688889, 'elev': 45, 'lon': -71.425556, 'climate_div': 'MA02', 'network': 'newa'},
'kcqx': {'srqual': 'ok', 'state': 'MA', 'name': 'Chatham', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.6875, 'elev': 68.0, 'lon': -69.99333, 'network': 'icao'},
'kfmh': {'srqual': 'bad', 'state': 'MA', 'name': 'Falmouth Otis AFB', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.65, 'elev': 131.0, 'lon': -70.51667, 'network': 'icao'},
'mam': {'srqual': 'ok', 'county': 'Essex', 'state': 'MA', 'name': 'Amesbury', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.871822, 'elev': 115, 'lon': -70.925278, 'climate_div': 'MA03', 'network': 'newa'},
'kbvy': {'srqual': 'ok', 'state': 'MA', 'name': 'Beverly', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.58417, 'elev': 108.0, 'lon': -70.9175, 'network': 'icao'},
'khya': {'srqual': 'ok', 'state': 'MA', 'name': 'Hyannis', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.66861, 'elev': 55.0, 'lon': -70.28, 'network': 'icao'},
'kbos': {'srqual': 'ok', 'state': 'MA', 'name': 'Boston Logan', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.36056, 'elev': 20.0, 'lon': -71.01056, 'network': 'icao'},
'kack': {'srqual': 'ok', 'state': 'MA', 'name': 'Nantucket', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.25306, 'elev': 45.0, 'lon': -70.06083, 'network': 'icao'},
'mle': {'srqual': 'ok', 'state': 'MA', 'name': 'Leominster (Sholan Farm)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.4875, 'elev': 720, 'lon': -71.7756, 'network': 'newa'},
'kmvy': {'srqual': 'ok', 'state': 'MA', 'name': 'Vineyard Haven', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.39306, 'elev': 68.0, 'lon': -70.615, 'network': 'icao'},
'mha': {'srqual': 'ok', 'state': 'MA', 'name': 'Harvard', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.500556, 'elev': 564, 'lon': -71.5625, 'network': 'newa'},
'um_bcf': {'name': 'Barnstable County Farm', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -70.288709, 'state': 'MA', 'elev': 53, 'lat': 41.697834, 'network': 'cu_log'},
'mre': {'srqual': 'toolow', 'state': 'MA', 'name': 'Seekonk', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.777314, 'elev': 16, 'lon': -71.320638, 'network': 'newa'},
'kbaf': {'srqual': 'bad', 'state': 'MA', 'name': 'Westfield Arpt', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.15778, 'elev': 271.0, 'lon': -72.71611, 'network': 'icao'},
}