stn_info = {
'2wi': {'name': 'Williamson (Mason)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -77.23158, 'elev': 427.0, 'lat': 43.22206, 'network': 'newa', 'state': 'NY'},
'3wi': {'name': 'Williamson (Demarree)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -77.142499999999998, 'elev': 300.0, 'lat': 43.276150000000001, 'network': 'newa', 'state': 'NY'},
'acc': {'name': 'Accord', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', ], 'srqual': 'ok', 'lat': 41.807602, 'lon': -74.248764, 'elev': 386, 'network': 'newa', 'state': 'NY'},
'alb': {'name': 'Albion', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lon': -78.134927, 'elev': 430.0, 'lat': 43.275135, 'network': 'newa', 'state': 'NY'},
'alt': {'name': 'Altamont (Indian Ladder Farms)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.654948, 'lon': -73.967705, 'elev': 360.9, 'network': 'newa', 'state': 'NY'},
'ams': {'name': 'Amsterdam (Stony Brook Farm)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.874326, 'lon': -74.249408, 'elev': 651, 'network': 'newa', 'state': 'NY'},
'arm': {'name': 'Arkport (Mahany)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toohigh', 'lon': -77.68430, 'elev': 1300.0, 'lat': 42.42882, 'network': 'newa', 'state': 'NY'},
'ash': {'name': 'Ashwood', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -78.309579999999997, 'elev': 330.0, 'lat': 43.338540000000002, 'network': 'newa', 'state': 'NY'},
'aur': {'name': 'Aurora', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.73367, 'lon': -76.65383, 'elev': 840, 'network': 'newa', 'state': 'NY'},
'bal': {'name': 'Baldwinsville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 43.169525, 'lon': -76.400886, 'elev': 443, 'network': 'newa', 'state': 'NY'},
'ber': {'name': 'Bergen', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad','st4i'], 'srqual': 'ok', 'lat': 43.085377, 'lon': -77.948586, 'elev': 620, 'network': 'newa', 'state': 'NY'},
'bla': {'name': 'Baldwinsville (Abbott)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.145093, 'lon': -76.282136, 'elev': 502, 'network': 'newa', 'state': 'NY'},
'bra': {'name': 'Branchport', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.584167, 'lon': -77.167778, 'elev': 1043, 'network': 'newa', 'state': 'NY'},
'brh': {'name': 'Brookhaven Hamlet', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.769289, 'lon': -72.922614, 'elev': 18, 'network': 'newa', 'state': 'NY'},
'but': {'name': 'Butler (Tree Crisp)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat':43.067219, 'lon': -76.760174, 'elev': 457, 'network': 'newa', 'state': 'NY'},
'cas': {'name': 'Castleton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.537142, 'lon': -73.710530, 'elev': 288, 'network': 'newa', 'state': 'NY'},
'cer': {'name': 'Ceres', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.007429, 'lon': -78.299024, 'elev': 1500, 'network': 'newa', 'state': 'NY'},
'chz': {'name': 'Chazy (Grower)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -73.429071, 'elev': 167.0, 'lat': 44.861900, 'network': 'newa', 'state': 'NY'},
'crc': {'name': 'Chazy (Rusty Creek)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.9356, 'lon': -73.4189, 'elev': 140, 'network': 'newa', 'state': 'NY'},
'cli': {'name': 'Clifton Park', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -73.837641, 'elev': 378.0, 'lat': 42.815913, 'network': 'newa', 'state': 'NY'},
'cng': {'name': 'Canton (Greenwood)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.671842, 'lon': -75.148409, 'elev': 354, 'network': 'newa', 'state': 'NY'},
'chm': {'name': 'Champlain (Leducs Green Acres)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.975916, 'lon': -73.419842, 'elev': 173, 'network': 'newa', 'state': 'NY'},
'cho': {'name': 'Coeymans Hollow (Stanton)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.5050, 'lon': -73.8982, 'elev': 720, 'network': 'newa', 'state': 'NY'},
'cns': {'name': 'Cutchogue (New Suffolk)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.01, 'lon': -72.48, 'elev': 26, 'network': 'newa', 'state': 'NY'},
'cro': {'name': 'Crown Point', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -73.414106, 'elev': 120.0, 'lat': 43.951858, 'network': 'newa', 'state': 'NY'},
'cu_gfr': {'name': 'Ithaca Cornell', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -76.449200000000005, 'elev': 960.0, 'lat': 42.449199999999998, 'network': 'cu_log', 'state': 'NY'},
'den': {'name': 'Denver (Stoneline)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.25056, 'lon': -74.52583, 'elev': 2022, 'network': 'newa', 'state': 'NY'},
'drs': {'name': 'Dresden (FLGP/FLCC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.706147, 'lon': -76.974658, 'elev': 1021, 'network': 'newa', 'state': 'NY'},
'dun': {'name': 'Dundee (Wiemer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.570677, 'lon': -76.928593, 'elev': 702, 'network': 'newa', 'state': 'NY'},
'eag': {'name': 'Eagle Bridge', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.964861, 'lon': -73.339623, 'elev': 687, 'network': 'newa', 'state': 'NY'},
'elb': {'name': 'Elba', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -78.14700, 'elev': 651.0, 'lat': 43.15204, 'network': 'newa', 'state': 'NY'},
'emo': {'name': 'East Moriches', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.801728, 'lon': -72.769788, 'elev': 30, 'network': 'newa', 'state': 'NY'},
'fai': {'name': 'Fairville (The Apple Shed)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.130064, 'lon': -77.095780, 'elev': 509, 'network': 'newa', 'state': 'NY'},
'far': {'name': 'Farmington', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'toolow', 'lon': -77.262299999999996, 'elev': 600.0, 'lat': 42.99004, 'network': 'newa', 'state': 'NY'},
'fis': {'name': 'Fishkill', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.517978, 'lon': -73.824541, 'elev': 114, 'network': 'newa', 'state': 'NY'},
'fre': {'name': 'Freeville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'bad', 'lon': -76.331130000000002, 'elev': 1100.0, 'lat': 42.51914, 'network': 'newa', 'state': 'NY'},
'fts': {'name': 'Fort Salonga', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.897214, 'lon': -73.278708, 'elev': 99, 'network': 'newa', 'state': 'NY'},
'gai': {'name': 'Gainesville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'toolow', 'lon': -78.162607, 'elev': 1600.0, 'lat': 42.652126, 'network': 'newa', 'state': 'NY'},
'gbe': {'name': 'Geneva (Bejo)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.82755, 'lon': -77.01053, 'elev': 700.0, 'network': 'newa', 'state': 'NY'},
'gen': {'name': 'Geneva', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir','srad'], 'srqual': 'toolow', 'lon': -77.02818, 'elev': 650.0, 'lat': 42.87295, 'network': 'newa', 'state': 'NY'},
'gfr': {'name': 'Ithaca (Game Farm Rd)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.44924, 'lon': -76.44905, 'elev': 968, 'network': 'newa', 'state': 'NY'},
'gkd': {'name': 'Gansevoort (Killians Dairy)', 'vars': ['temp', 'prcp', 'wspd', 'wdir'], 'lat': 43.235108, 'lon': -73.627054, 'elev': 245, 'network': 'newa', 'state': 'NY'},
'gui': {'name': 'Guilderland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -74.017886, 'elev': 390.0, 'lat': 42.721046, 'network': 'newa', 'state': 'NY'},
'gws': {'name': 'Gansevoort (Welcome Stock)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.146532, 'lon': -73.599276, 'elev': 227, 'network': 'newa', 'state': 'NY'},
'har': {'name': 'Harborcreek, PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -79.9049196, 'elev': 742.0, 'lat': 42.1931232, 'network': 'newa', 'state': 'PA'},
'hec': {'name': 'Hector', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.508040, 'lon': -76.877825, 'elev': 800, 'network': 'newa', 'state': 'NY'},
'hid': {'name': 'Hudson Falls (Ideal Dairy)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.331821, 'lon': -73.58052, 'elev': 293, 'network': 'newa', 'state': 'NY'},
'hvl': {'name': 'Highland HVL 2', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.75, 'lon': -73.9670, 'elev': 437, 'network': 'newa', 'state': 'NY'},
'hud': {'name': 'Hudson', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'srqual': 'ok', 'lon': -73.8303834, 'elev': 216.0, 'lat': 42.1910246, 'network': 'newa', 'state': 'NY'},
'int': {'name': 'Interlaken (Airy Acres)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.636288, 'lon': -76.725271, 'elev': 242, 'network': 'newa', 'state': 'NY'},
'ith': {'name': 'Ithaca Cornell Orchards', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lon': -76.461786, 'elev': 902.0, 'lat': 42.444543, 'network': 'newa', 'state': 'NY'},
'kee': {'name': 'Keene (Fisk Highlands)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 44.239743, 'lon': -73.768373, 'elev': 1400, 'network': 'newa', 'state': 'NY'},
'ken': {'name': 'Kendall (Zingler)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.345406, 'lon': -78.034467, 'elev': 308, 'network': 'newa', 'state': 'NY'},
'kin': {'name': 'Kinderhook', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.398814, 'lon': -73.703383, 'elev': 266, 'network': 'newa', 'state': 'NY'},
'kno': {'name': 'Knowlesville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -78.301944, 'elev': 524.0, 'lat': 43.225833, 'network': 'newa', 'state': 'NY'},
'laf': {'name': 'Lafayette', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -76.195206999999996, 'elev': 584.0, 'lat': 42.909686000000001, 'network': 'newa', 'state': 'NY'},
'lan': {'name': 'Lansing', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toohigh', 'lon': -76.595127, 'elev': 407.0, 'lat': 42.572295, 'network': 'newa', 'state': 'NY'},
'loc': {'name': 'Ransomville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'toolow', 'lon': -78.901556999999997, 'elev': 387.0, 'lat': 43.187325000000001, 'network': 'newa', 'state': 'NY'},
'lod': {'name': 'Lodi (Standing Stone)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -76.874138, 'elev': 719.0, 'lat': 42.543054, 'network': 'newa', 'state': 'NY'},
'lol': {'name': 'Lodi (Lamoreaux)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.57664, 'lon': -76.85844, 'elev': 853, 'network': 'newa', 'state': 'NY'},
'lyn': {'name': 'Lyndonville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'srqual': 'ok', 'lon': -78.369044000000002, 'elev': 361.0, 'lat': 43.298085, 'network': 'newa', 'state': 'NY'},
'mad': {'name': 'Madrid (Mapleview)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.738169, 'lon': -75.158919, 'elev': 340, 'network': 'newa', 'state': 'NY'},
'man': {'name': 'Manorville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.860597, 'lon': -72.821942, 'elev': 44, 'network': 'newa', 'state': 'NY'},
'mar': {'name': 'Marlboro', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'srad', 'wdir'], 'srqual': 'ok', 'lon': -73.984509, 'elev': 390.0, 'lat': 41.590299, 'network': 'newa', 'state': 'NY'},
'mbf': {'name': 'Malone (Bilow Farms)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.847783, 'lon': -74.15328, 'elev': 1260, 'network': 'newa', 'state': 'NY'},
'med': {'name': 'Medina', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.20000, 'lon': -78.39275, 'elev': 600, 'network': 'newa', 'state': 'NY'},
'mod': {'name': 'Modena', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat':41.670619, 'lon': -74.116855, 'elev': 460, 'network': 'newa', 'state': 'NY'},
'mtd': {'name': 'Mattituck (Dorsett)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.019322, 'lon': -72.524561, 'elev': 52, 'network': 'newa', 'state': 'NY'},
'mts': {'name': 'Mattituck (Shinn)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.01, 'lon': -72.53, 'elev': 42, 'network': 'newa', 'state': 'NY'},
'nee': {'name': 'North East Escarpment, PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.18097, 'lon': -79.85170, 'elev': 1029, 'network': 'newa', 'state': 'PA'},
'nel': {'name': 'North East Lab, PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.22834, 'lon': -79.85432, 'elev': 680, 'network': 'newa', 'state': 'PA'},
'noa': {'name': 'Appleton, North', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -78.665660000000003, 'elev': 300.0, 'lat': 43.344029999999997, 'network': 'newa', 'state': 'NY'},
'npt': {'name': 'Northport (Richters)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.884686, 'lon': -73.294411, 'elev': 213, 'network': 'newa', 'state': 'NY'},
'npz': {'name': 'New Paltz', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 41.7575583, 'lon': -74.0502361, 'elev': 115, 'network': 'newa', 'state': 'NY'},
'npw': {'name': 'New Paltz (WG Minard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.699491, 'lon': -74.074365, 'elev': 451.5, 'network': 'newa', 'state': 'NY'},
'ora': {'name': 'Ogdensburg (Royal J Acres)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.641553, 'lon': -75.46004, 'elev': 321, 'network': 'newa', 'state': 'NY'},
'ori': {'name': 'Oriskany Falls (Truandvin)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.976266, 'lon': -75.512764, 'elev': 1115, 'network': 'newa', 'state': 'NY'},
'ovi': {'name': 'Ovid (Hosmer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -76.74525, 'elev': 590.0, 'lat': 42.68564, 'network': 'newa', 'state': 'NY'},
'paf': {'name': 'Peru (Adirondack Farms)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.544698, 'lon': -73.526481, 'elev': 427, 'network': 'newa', 'state': 'NY'},
'pbd': {'name': 'Plattsburgh (Bubbins Dairy)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.761165, 'lon': -73.43563, 'elev': 133, 'network': 'newa', 'state': 'NY'},
'pcf': {'name': 'Plattsburgh (Carter Farms)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.778653, 'lon': -73.446475, 'elev': 144, 'network': 'newa', 'state': 'NY'},
'pdf': {'name': 'Peru (Dimock Farms)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.606961, 'lon': -73.539581, 'elev': 371, 'network': 'newa', 'state': 'NY'},
'per': {'name': 'Peru', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -73.512769, 'elev': 370.0, 'lat': 44.566692, 'network': 'newa', 'state': 'NY'},
'phe': {'name': 'Phelps', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.977429, 'lon': -77.043439, 'elev': 558, 'network': 'newa', 'state': 'NY'},
'pno': {'name': 'Peru (Northern Orchard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 44.560966, 'lon': -73.536215, 'elev': 459, 'network': 'newa', 'state': 'NY'},
'poe': {'name': 'Portland Escarpment', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.34944, 'lon': -79.47194, 'elev': 1076, 'network': 'newa', 'state': 'NY'},
'por': {'name': 'Portland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -79.487296, 'elev': 700.0, 'lat': 42.371481, 'network': 'newa', 'state': 'NY'},
'ptb': {'name': 'Point Breeze', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.355, 'lon': -78.19, 'elev': 91, 'network': 'newa', 'state': 'NY'},
'red': {'name': 'Red Hook', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir','srad'], 'srqual': 'toolow', 'lon': -73.849695, 'elev': 230.0, 'lat': 42.008868, 'network': 'newa', 'state': 'NY'},
'rip': {'name': 'Ripley', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.265872, 'lon': -79.704125, 'elev': 758, 'network': 'newa', 'state': 'NY'},
'riv': {'name': 'Riverhead (LIHREC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.96222, 'lon': -72.71611, 'elev': 112, 'network': 'newa', 'state': 'NY'},
'rbg': {'name': 'Romulus (Buttonwood Grove)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.7331, 'lon': -76.7700, 'elev': 460, 'network': 'newa', 'state': 'NY'},
'rom': {'name': 'Romulus (Thirsty Owl)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.69709, 'lon': -76.746448, 'elev': 485, 'network': 'newa', 'state': 'NY'},
'rtw': {'name': 'Rock Tavern (WG Minard)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.45497, 'lon': -74.16315, 'elev': 439, 'network': 'newa', 'state': 'NY'},
'rvm': {'name': 'Riverhead (MCV)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.98, 'lon': -72.58, 'elev': 54, 'network': 'newa', 'state': 'NY'},
'rvp': {'name': 'Riverhead (Palmer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.97, 'lon': -72.63, 'elev': 49, 'network': 'newa', 'state': 'NY'},
'sar': {'name': 'Saratoga Springs (Hanehan)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.067554, 'lon': -73.68402, 'elev': 342, 'network': 'newa', 'state': 'NY'},
'sdl': {'name': 'Sodus (Lake)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lon': -77.06239, 'elev': 373, 'lat': 43.252375, 'network': 'newa', 'state': 'NY'},
'sod': {'name': 'Sodus', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'toolow', 'lon': -77.078962, 'elev': 450.0, 'lat': 43.171946, 'network': 'newa', 'state': 'NY'},
'shc': {'name': 'Southold (Corey Creek)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.045194, 'lon': -72.4452, 'elev': 25, 'network': 'newa', 'state': 'NY'},
'she': {'name': 'Sheridan', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.50207, 'lon': -79.20513, 'elev': 750, 'network': 'newa', 'state': 'NY'},
'shd': {'name': 'Southold (One Woman)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.08, 'lon': -72.42, 'elev': 29, 'network': 'newa', 'state': 'NY'},
'sil': {'name': 'Silver Creek', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.54247, 'lon': -79.19673, 'elev': 608, 'network': 'newa', 'state': 'NY'},
'som': {'name': 'Somerset', 'vars': ['temp', 'lwet', 'rhum', 'prcp', 'wspd', 'wdir', 'srad'], 'srqual': 'bad', 'lon': -78.626908, 'elev': 318.0, 'lat': 43.325911, 'network': 'newa', 'state': 'NY'},
'var': {'name': 'Varick (Swedish Hill)', 'vars': ['temp', 'lwet', 'rhum', 'prcp', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -76.81007, 'elev': 662.0, 'lat': 42.80248, 'network': 'newa', 'state': 'NY'},
'ver': {'name': 'Versailles', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.51640, 'lon': -79.02689, 'elev': 863, 'network': 'newa', 'state': 'NY'},
'vlt': {'name': 'Valatie', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.4358, 'lon': -73.6845, 'elev': 306.1, 'network': 'newa', 'state': 'NY'},
'vrf': {'name': 'Valatie Research Farm', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.428470, 'lon': -73.663931, 'elev': 303, 'network': 'newa', 'state': 'NY'},
'way': {'name': 'Wayland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -77.578797, 'elev': 1600.0, 'lat': 42.604968, 'network': 'newa', 'state': 'NY'},
'wbs': {'name': 'Williamson (Bear Swamp)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.250549, 'lon': -77.160323, 'elev': 367, 'network': 'newa', 'state': 'NY'},
'wes': {'name': 'Westfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.341379, 'lon': -79.572976, 'elev': 671, 'network': 'newa', 'state': 'NY'},
'wgl': {'name': 'Watkins Glen', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -76.925487, 'elev': 1100.0, 'lat': 42.377077, 'network': 'newa', 'state': 'NY'},
'wla': {'name': 'Watkins Glen (Lakewood)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.428133, 'lon': -76.9057, 'elev': 906, 'network': 'newa', 'state': 'NY'},
'wmi': {'name': 'Water Mill', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -72.317480, 'elev': 15.0, 'lat': 40.911110, 'network': 'newa', 'state': 'NY'},
'wmn': {'name': 'Water Mill (North)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.92, 'lon': -72.34, 'elev': 15, 'network': 'newa', 'state': 'NY'},
'wlb': {'name': 'Willsboro', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'lwet', 'srad'], 'srqual': 'ok', 'lon': -73.38180, 'elev': 180.0, 'lat': 44.38430, 'network': 'newa', 'state': 'NY'},
'wi_gay': {'name': 'Gays Mills, WI', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.314584, 'lon': -90.841526, 'elev': 942, 'network': 'newa', 'state': 'WI'},
'wol': {'name': 'Wolcott', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -76.876728, 'elev': 280, 'lat': 43.262683, 'network': 'newa', 'state': 'NY'},
'wor': {'name': 'Williamson (Orbaker)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.2820897, 'lon': -77.21698766, 'elev': 270, 'network': 'newa', 'state': 'NY'},
'vco': {'name': 'Cornwall, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.962033, 'lon': -73.239449, 'elev': 398, 'network': 'newa', 'state': 'VT'},
'vdu': {'name': 'Dummerston, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.904167, 'lon': -72.568466, 'elev': 561, 'network': 'newa', 'state': 'VT'},
'vex': {'name': 'Essex, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 44.537492, 'lon': -73.061060, 'elev': 572, 'network': 'newa', 'state': 'VT'},
'vsb': {'name': 'South Burlington, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -73.2042, 'elev': 233, 'lat': 44.4308, 'network': 'newa', 'state': 'VT'},
'vpu': {'name': 'Putney, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -72.5421, 'elev': 715,  'lat': 42.9910, 'network': 'newa', 'state': 'VT'},
'vsh': {'name': 'Shoreham, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -73.3517, 'elev': 351,  'lat': 43.8861, 'network': 'newa', 'state': 'VT'},
'vso': {'name': 'South Hero, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -73.3033, 'elev': 177,  'lat': 44.6355, 'network': 'newa', 'state': 'VT'},
'ved': {'name': 'East Dorset, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -72.9909, 'elev': 1339, 'lat': 43.2685, 'network': 'newa', 'state': 'VT'},
'vbe': {'name': 'Bennington (SVO), VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.841119, 'lon': -73.218067, 'elev': 1312, 'network': 'newa', 'state': 'VT'},
'vem': {'name': 'East Montpelier, VT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat':  44.3182, 'lon':  -72.5070, 'elev':  1162, 'network': 'newa', 'state': 'VT'},
'mam': {'name': 'Amesbury, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.871822, 'lon': -70.925278, 'elev': 115, 'network': 'newa', 'state': 'MA'},
'mbe': {'name': 'Belchertown-2, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toohigh', 'lon': -72.35972, 'elev': 623,  'lat': 42.25306, 'network': 'newa', 'state': 'MA'},
'msd': {'name': 'South Deerfield, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -72.57944, 'elev': 131,  'lat': 42.47972, 'network': 'newa', 'state': 'MA'},
'mdr': {'name': 'Dracut, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.680556, 'lon': -71.264722, 'elev': 151, 'network': 'newa', 'state': 'MA', 'county': 'Middlesex', 'climate_div': 'MA02'},
'mty': {'name': 'Tyngsboro, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'bad', 'lat': 42.688889, 'lon': -71.425556, 'elev': 45, 'network': 'newa', 'state': 'MA', 'county': 'Windham', 'climate_div': 'MA02'},
'mas': {'name': 'Ashfield, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toohigh', 'lat': 42.560278, 'lon': -72.815833, 'elev': 946, 'network': 'newa', 'state': 'MA', 'county': 'Franklin', 'climate_div': 'MA01'},
'mha': {'name': 'Harvard, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.500556, 'lon': -71.5625, 'elev': 564, 'network': 'newa', 'state': 'MA'},
'mna': {'name': 'North Andover, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.6462, 'lon': -71.0887, 'elev': 180, 'network': 'newa', 'state': 'MA'},
'msw': {'name': 'Stow (Shelburne), MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.446944, 'lon': -71.501111, 'elev': 233, 'network': 'newa', 'state': 'MA'},
'msh': {'name': 'Sharon, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.09861, 'lon': -71.21583, 'elev': 265, 'network': 'newa', 'state': 'MA'},
'mre': {'name': 'Seekonk, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 41.777314, 'lon': -71.320638, 'elev': 16, 'network': 'newa', 'state': 'MA'},
'mwa': {'name': 'UMass Waltham Center, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.383988, 'lon': -71.212285, 'elev': 66, 'network': 'newa', 'state': 'MA'},
'mwe': {'name': 'Westfield, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.185000, 'lon': -72.765000, 'elev': 321, 'network': 'newa', 'state': 'MA'},
'mbo': {'name': 'Bolton, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.418889, 'lon': -71.641389, 'elev': 516, 'network': 'newa', 'state': 'MA'},
'mst': {'name': 'Stow, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.409444, 'lon': -71.513889, 'elev': 239, 'network': 'newa', 'state': 'MA', 'county': 'Middlesex', 'climate_div': 'MA02'},
'mnb': {'name': 'Northbridge, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.151711, 'lon': -71.680108, 'elev': 444, 'network': 'newa', 'state': 'MA'},
'mle': {'name': 'Leominster (Sholan Farm), MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.4875, 'lon': -71.7756, 'elev': 720, 'network': 'newa', 'state': 'MA'},
'mph': {'name': 'Phillipston, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.580777, 'lon': -72.146067, 'elev': 1183, 'network': 'newa', 'state': 'MA'},
'meb': {'name': 'East Bridgewater, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.007778, 'lon': -70.943333, 'elev': 40, 'network': 'newa', 'state': 'MA'},
'mip': {'name': 'Ipswich (Russell Orchards), MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 42.661677, 'lon': -70.803066, 'elev': 14, 'network': 'newa', 'state': 'MA'},
'mum': {'name': 'Amherst (UM ALC), MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'bad', 'lat': 42.4015, 'lon': -72.5269, 'elev': 200, 'network': 'newa', 'state': 'MA'},
'um_cso': {'name': 'Belchertown, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -72.35917, 'elev': 638, 'lat': 42.25333, 'network': 'cu_log', 'state': 'MA'},
'um_clk': {'name': 'Deerfield, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -72.62333, 'elev': 328, 'lat': 42.56333, 'network': 'cu_log', 'state': 'MA'},
'um_whs': {'name': 'Boston (Weld Hill), MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i'], 'srqual': 'ok', 'lat': 42.29556, 'lon': -71.13361, 'elev': 151, 'network': 'cu_log', 'state': 'MA'},
'um_bcf': {'name': 'Barnstable County Farm, MA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.697834, 'lon': -70.288709, 'elev': 53, 'network': 'cu_log', 'state': 'MA'},
'pa_big': {'name': 'Biglerville (Hollabaugh), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat':39.946944, 'lon': -77.247222, 'elev': 732, 'network': 'newa', 'state': 'PA'},
'pa_bre': {'name': 'Breinigsville (Grim), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.5433, 'lon': -75.6622, 'elev': 470, 'network': 'newa', 'state': 'PA'},
'pa_npa': {'name': 'New Paris (Boyer), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.105321, 'lon': -78.629474, 'elev': 1556, 'network': 'newa', 'state': 'PA'},
'pa_ysp': {'name': 'York Springs (Lerew), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat':40.038978, 'lon': -77.136408, 'elev': 740, 'network': 'newa', 'state': 'PA'},
'pa_pin': {'name': 'Piney Mountain, PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat':39.977669, 'lon': -77.339694, 'elev': 1217, 'network': 'newa', 'state': 'PA'},
'pa_ntr': {'name': 'New Tripoli (NWLHS), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat':40.682630, 'lon': -75.724929, 'elev': 738, 'network': 'newa', 'state': 'PA'},
'pa_rsp': {'name': 'Rock Springs, PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat':40.713993, 'lon': -77.948844, 'elev': 1213, 'network': 'newa', 'state': 'PA'},
'pa_sco': {'name': 'Scott Township, PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.572091, 'lon': -75.593225, 'elev': 1750, 'network': 'newa', 'state': 'PA'},
'pa_cab': {'name': 'Cabot (Mathias Farm), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.7792, 'lon': -79.7334, 'elev': 1330, 'network': 'newa', 'state': 'PA'},
'pa_hun': {'name': 'Hostetler Airport (StoneView), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.631244, 'lon': -77.850166, 'elev': 741.8598, 'network': 'newa', 'state': 'PA'},
'pa_lew': {'name': 'Lewisburg (Fero Vineyards), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.997036, 'lon': -76.886299, 'elev': 565, 'network': 'newa', 'state': 'PA'},
'pa_heg': {'name': 'Hegins (Schwalm), PA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.6568, 'lon': -76.4887, 'elev': 237, 'network': 'newa', 'state': 'PA'},
'ct_gfy': {'name': 'Gales Ferry, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.468442, 'lon': -72.057294, 'elev': 160, 'network': 'newa', 'state': 'CT'},
'ct_gui': {'name': 'Guilford, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.293201, 'lon': -72.694292, 'elev': 58, 'network': 'newa', 'state': 'CT'},
'ct_sgl': {'name': 'S. Glastonbury, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.652024, 'lon': -72.576445, 'elev': 350, 'network': 'newa', 'state': 'CT'},
'ct_nwi': {'name': 'North Windham, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 41.721570, 'lon': -72.167526, 'elev': 301, 'network': 'newa', 'state': 'CT'},
'ct_she': {'name': 'Shelton, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.332251, 'lon': -73.172193, 'elev': 400, 'network': 'newa', 'state': 'CT'},
'ct_ssm': {'name': 'Southington (Shuttle Meadow), CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.636917, 'lon': -72.839023, 'elev': 450, 'network': 'newa', 'state': 'CT'},
'ct_ssu': {'name': 'Southington (Sunnymount), CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.558953, 'lon': -72.943323, 'elev': 650, 'network': 'newa', 'state': 'CT'},
'ct_wal': {'name': 'Wallingford, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.449683, 'lon': -72.867125, 'elev': 249, 'network': 'newa', 'state': 'CT'},
'ct_eas': {'name': 'Eastford, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.925038, 'lon': -72.106909, 'elev': 690, 'network': 'newa', 'state': 'CT'},
'ct_tol': {'name': 'Tolland, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.865470, 'lon': -72.311078, 'elev': 425, 'network': 'newa', 'state': 'CT'},
'ct_ely': {'name': 'East Lyme, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.353398, 'lon': -72.247315, 'elev': 150, 'network': 'newa', 'state': 'CT'},
'ct_enf': {'name': 'Enfield, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.976093, 'lon': -72.504194, 'elev': 250, 'network': 'newa', 'state': 'CT'},
'uc_sto': {'name': 'Storrs (UConn), CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.79417, 'lon': -72.22889, 'elev': 663, 'network': 'cu_log', 'state': 'CT'},
'ct_npr': {'name': 'New Preston, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.665955, 'lon': -73.334845, 'elev': 860, 'network': 'newa', 'state': 'CT'},
'ct_woo': {'name': 'Woodstock, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.930842, 'lon': -71.985308, 'elev': 201, 'network': 'newa', 'state': 'CT'},
'ct_eha': {'name': 'Moodus, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.520094, 'lon': -72.444341, 'elev': 422, 'network': 'newa', 'state': 'CT'},
'ct_mad': {'name': 'Madison, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.295110, 'lon': -72.621420, 'elev': 30, 'network': 'newa', 'state': 'CT'},
'ct_por': {'name': 'Portland, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.580457, 'lon': -72.618400, 'elev': 303, 'network': 'newa', 'state': 'CT'},
'ct_heb': {'name': 'Hebron, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.684921, 'lon': -72.392705, 'elev': 593, 'network': 'newa', 'state': 'CT'},
'ct_har': {'name': 'Harwinton-Burlington, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.781196, 'lon': -72.989213, 'elev': 847, 'network': 'newa', 'state': 'CT'},
'ct_new': {'name': 'Newtown, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.404534, 'lon': -73.287750, 'elev': 400, 'network': 'newa', 'state': 'CT'},
'ct_nca': {'name': 'New Canaan, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'toolow', 'lat': 41.132771, 'lon': -73.484614, 'elev': 274, 'network': 'newa', 'state': 'CT'},
'ct_nia': {'name': 'Niantic, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.349326, 'lon': -72.213006, 'elev': 28, 'network': 'newa', 'state': 'CT'},
'ct_sto': {'name': 'Storrs (Research Farm), CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.7941049, 'lon': -72.230211, 'elev': 669, 'network': 'newa', 'state': 'CT'},
'ct_mid': {'name': 'Middlefield (UConn), CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.4940344, 'lon': -72.726152, 'elev': 364, 'network': 'newa', 'state': 'CT'},
'ct_ewi': {'name': 'East Windsor, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'bad', 'lat': 41.870777, 'lon': -72.530493, 'elev': 220, 'network': 'newa', 'state': 'CT'},
'ct_gos': {'name': 'Goshen, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.792852, 'lon': -73.20965, 'elev': 1255, 'network': 'newa', 'state': 'CT'},
'ct_pla': {'name': 'Plainville MS, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.684327, 'lon': -72.885093, 'elev': 246, 'network': 'newa', 'state': 'CT'},
'ct_pre': {'name': 'Preston, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.519728, 'lon': -72.018675, 'elev': 238, 'network': 'newa', 'state': 'CT'},
'ct_gla': {'name': 'Glastonbury HS, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.701804, 'lon': -72.586423, 'elev': 110, 'network': 'newa', 'state': 'CT'},
'ct_swo': {'name': 'South Woodstock MS, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'bad', 'lat': 41.928673, 'lon': -71.956196, 'elev': 421, 'network': 'newa', 'state': 'CT'},
'ct_eki': {'name': 'East Killingly, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.871175, 'lon': -71.809891, 'elev': 748, 'network': 'newa', 'state': 'CT'},
'ct_nha': {'name': 'New Hartford, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.799465, 'lon': -73.016757, 'elev': 932, 'network': 'newa', 'state': 'CT'},
'ct_leb': {'name': 'Lebanon, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.625186, 'lon': -72.23729, 'elev': 515, 'network': 'newa', 'state': 'CT'},
'ct_ell': {'name': 'Ellington, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st4i', 'sm4i'], 'srqual': 'ok', 'lat': 41.917283, 'lon': -72.458236, 'elev': 246, 'network': 'newa', 'state': 'CT'},
'ct_rid': {'name': 'Ridgefield, CT', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.291379, 'lon': -73.462419, 'elev': 670, 'network': 'newa', 'state': 'CT'},
'ia_ccy': {'name': 'Central City, IA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.224159, 'lon': -91.494571, 'elev': 958, 'network': 'newa', 'state': 'IA'},
'il_pgr': {'name': 'Poplar Grove, IL', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.391312, 'lon': -88.800936, 'elev': 916, 'network': 'newa', 'state': 'IL'},
'il_bel': {'name': 'Belleville, IL', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 38.480416, 'lon': -89.939040, 'elev': 539, 'network': 'newa', 'state': 'IL'},
'il_woo': {'name': 'Woodstock, IL', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.259406, 'lon': -88.485386, 'elev': 876, 'network': 'newa', 'state': 'IL'},
'il_gra': {'name': 'Grafton, IL', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.01571, 'lon': -90.40783, 'elev': 670, 'network': 'newa', 'state': 'IL'},
'il_mil': {'name': 'Millstadt, IL', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 38.51105, 'lon': -90.12701, 'elev': 545, 'network': 'newa', 'state': 'IL'},
'un_nec': {'name': 'Nebraska City 2N, NE', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lon': -95.8833, 'elev': 1076.0, 'lat': 40.7000, 'network': 'cu_log', 'state': 'NE'},
'ne_gre': {'name': 'Gretna, NE', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 41.128806, 'lon': -96.201133, 'elev': 354, 'network': 'newa', 'state': 'NE'},
'nc_hen': {'name': 'Hendersonville (Klimstra), NC', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 35.280923, 'lon': -82.530513, 'elev': 2343, 'network': 'newa', 'state': 'NC'},
'nc_edn': {'name': 'Edneyville (Lewis Creek), NC', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 35.368132, 'lon': -82.338506, 'elev': 2223, 'network': 'newa', 'state': 'NC'},
'nc_esm': {'name': 'Edneyville (Sugarloaf Mtn), NC', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 35.391921, 'lon': -82.275268, 'elev': 2964, 'network': 'newa', 'state': 'NC'},
'nc_mor': {'name': 'Morganton (Apple Hill Orchard), NC', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 35.668366, 'lon': -81.660265, 'elev': 1421, 'network': 'newa', 'state': 'NC'},
'nc_mof': {'name': 'Moravian Falls, NC', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'],'srqual': 'ok', 'lat': 36.038122, 'lon': -81.206226, 'elev': 2241, 'network': 'newa', 'state': 'NC'},
'nc_emm': {'name': 'Edneyville (M&M Berry Farm), NC', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'],'srqual': 'ok', 'lat': 35.359935, 'lon': -82.357588, 'elev': 2230, 'network': 'newa', 'state': 'NC'},
'nc_eaw': {'name': 'Edneyville (Apple Wedge), NC', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'],'srqual': 'ok', 'lat': 35.40492, 'lon': -82.35360, 'elev': 2248, 'network': 'newa', 'state': 'NC'},
'nc_fla': {'name': 'Flat Rock (Richmind), NC', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'],'srqual': 'ok', 'lat': 35.307008, 'lon': -82.370352, 'elev': 2264, 'network': 'newa', 'state': 'NC'},
'mn_wbl': {'name': 'White Bear Lake, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 45.106320, 'lon': -92.955087, 'elev': 955, 'network': 'newa', 'state': 'MN'},
'mn_pre': {'name': 'Preston, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.6825, 'lon': -92.0761, 'elev': 1088, 'network': 'newa', 'state': 'MN'},
'mn_has': {'name': 'Hastings, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 44.78840, 'lon': -92.81677, 'elev': 904, 'network': 'newa', 'state': 'MN'},
'mn_och': {'name': 'Worthington (Ocheda), MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 43.562080, 'lon': -95.573347, 'elev': 1594, 'network': 'newa', 'state': 'MN'},
'mn_del': {'name': 'Delano (Apple Jack), MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 45.0997, 'lon': -93.7902, 'elev': 925, 'network': 'newa', 'state': 'MN'},
'mn_alx': {'name': 'Alexandria, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 45.872756, 'lon': -95.470478, 'elev': 1403, 'network': 'newa', 'state': 'MN'},
'mn_aft': {'name': 'Afton, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 44.819, 'lon': -92.796, 'elev': 881, 'network': 'newa', 'state': 'MN'},
'mn_sha': {'name': 'Shafer, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 45.352665, 'lon': -92.753021, 'elev': 938, 'network': 'newa', 'state': 'MN'},
'mn_elg': {'name': 'Elgin, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 44.1364, 'lon': -92.242435, 'elev': 1050, 'network': 'newa', 'state': 'MN'},
'mn_gra': {'name': 'Grand Rapids, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 47.242450, 'lon': -93.492838, 'elev': 1289, 'network': 'newa', 'state': 'MN'},
'mn_lkc': {'name': 'Lake City, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 44.420187, 'lon': -92.227366, 'elev': 1140, 'network': 'newa', 'state': 'MN'},
'mn_cha': {'name': 'Chaska (Univ MN HRC), MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'sensoroff', 'lat': 44.86252, 'lon': -93.634693, 'elev': 1029, 'network': 'newa', 'state': 'MN'},
'mn_web': {'name': 'Webster, MN', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 44.540397, 'lon': -93.361096, 'elev': 1069, 'network': 'newa', 'state': 'MN'},
'nj_pri': {'name': 'Princeton (Terhune), NJ', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 40.3218, 'lon': -74.7292, 'elev': 186, 'network': 'newa', 'state': 'NJ'},
'nj_elk': {'name': 'Elk Township, NJ', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.6664019, 'lon': -75.184658, 'elev': 136, 'network': 'newa', 'state': 'NJ'},
'nj_blu': {'name': 'Blue Anchor (Sharrott Winery), NJ', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 39.677, 'lon': -74.874, 'elev': 131, 'network': 'newa', 'state': 'NJ'},
'va_bat': {'name': 'Batesville (Crown Orchard), VA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'toolow', 'lat': 37.974299, 'lon': -78.730016, 'elev': 832, 'network': 'newa', 'state': 'VA'},
'va_cha': {'name': 'Charlottesville (Carter Mtn Orchard), VA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st1i', 'sm1i'], 'srqual': 'ok', 'lat': 37.9906478, 'lon': -78.472665, 'elev': 1148, 'network': 'newa', 'state': 'VA'},
'va_cov': {'name': 'Covesville (Purvis Orchard), VA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 37.868371, 'lon': -78.717696, 'elev': 747, 'network': 'newa', 'state': 'VA'},
'va_cro': {'name': 'Crozet (Chiles Peach Orchard), VA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad', 'st1i', 'sm1i'], 'srqual': 'ok', 'lat': 38.068007, 'lon': -78.748675, 'elev': 922, 'network': 'newa', 'state': 'VA'},
'va_oak': {'name': 'Oak Grove (Ingleside)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 38.153703, 'lon': -77.004929, 'elev': 178, 'network': 'newa', 'state': 'VA'},
'va_red': {'name': 'Red Hill, VA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 37.954253, 'lon': -78.613412, 'elev': 676, 'network': 'newa', 'state': 'VA'},
'va_was': {'name': 'Washington (Gadino Cellars), VA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 38.688727, 'lon': -78.175908, 'elev': 681, 'network': 'newa', 'state': 'VA'},
'va_win': {'name': 'Winchester (VT AHS AREC), VA', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.112873, 'lon': -78.284048, 'elev': 925, 'network': 'newa', 'state': 'VA'},
'nh_hol': {'name': 'Hollis, NH', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 42.739297, 'lon': -71.579226, 'elev': 104, 'network': 'newa', 'state': 'NH'},
'ew_men': {'name': 'Mendon, MI', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 41.9833, 'lon': -85.4333, 'elev': 840, 'network': 'miwx', 'state': 'MI'},
'29': {'name': 'South Harrison, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.712359, 'lon': -75.280754, 'elev': 141, 'network': 'njwx', 'state': 'NJ'},
'33': {'name': 'Dennis Twp, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.2039, 'lon': -74.8923, 'elev': 5, 'network': 'njwx', 'state': 'NJ'},
'148': {'name': 'Cape May Courthouse, NJ', 'vars': ['temp','prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.1246, 'lon': -74.7873, 'elev': 7, 'network': 'njwx', 'state': 'NJ'},
'111': {'name': 'Lyndhurst (NJMC), NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.784214, 'lon': -74.104617, 'elev': 0, 'network': 'njwx', 'state': 'NJ'},
'202': {'name': 'Bethel Mill Park, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.7485, 'lon': -75.1138, 'elev': 30, 'network': 'njwx', 'state': 'NJ'},
'232': {'name': 'Egg Harbor, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.4227, 'lon': -74.5421, 'elev': 12, 'network': 'njwx', 'state': 'NJ'},
'236': {'name': 'Cherry Hill III, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.9098, 'lon': -75.0257, 'elev': 7, 'network': 'njwx', 'state': 'NJ'},
'261': {'name': 'West Cape May, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 38.9422, 'lon': -74.9441, 'elev': 5, 'network': 'njwx', 'state': 'NJ'},
'263': {'name': 'Piney Hollow, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.58, 'lon': -74.92, 'elev': 30, 'network': 'njwx', 'state': 'NJ'},
'284': {'name': 'Upper Deerfield, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 39.5243, 'lon': -75.2009, 'elev': 33, 'network': 'njwx', 'state': 'NJ'},
'285': {'name': 'Basking Ridge, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 40.6956, 'lon': -74.5198, 'elev': 67, 'network': 'njwx', 'state': 'NJ'},
'286': {'name': 'High Point, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 41.305, 'lon': -74.666, 'elev': 422, 'network': 'njwx', 'state': 'NJ'},
'287': {'name': 'Sea Girt, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 40.1203, 'lon': -74.0327, 'elev': 2, 'network': 'njwx', 'state': 'NJ'},
'289': {'name': 'Pittstown, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 40.5612, 'lon': -74.961, 'elev': 183, 'network': 'njwx', 'state': 'NJ'},
'295': {'name': 'Cream Ridge, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 40.1185, 'lon': -74.5256, 'elev': 36, 'network': 'njwx', 'state': 'NJ'},
'296': {'name': 'Woodbine, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 39.2202, 'lon': -74.7959, 'elev': 10, 'network': 'njwx', 'state': 'NJ'},
'317': {'name': 'Oswego Lake, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 39.71539, 'lon': -74.5142, 'elev': 15, 'network': 'njwx', 'state': 'NJ'},
'471': {'name': 'Charlotteburg, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 41.0299, 'lon': -74.4247, 'elev': 232, 'network': 'njwx', 'state': 'NJ'},
'1029': {'name': 'Pequest, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 40.8383, 'lon': -74.9491, 'elev': 135, 'network': 'njwx', 'state': 'NJ'},
'1032': {'name': 'Berkeley Twp, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 39.92578, 'lon': -74.2981, 'elev': 24, 'network': 'njwx', 'state': 'NJ'},
'1033': {'name': 'Haworth, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 40.9593, 'lon': -74.0135, 'elev': 8, 'network': 'njwx', 'state': 'NJ'},
'1034': {'name': 'Sicklerville, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 39.7638, 'lon': -74.9785, 'elev': 45, 'network': 'njwx', 'state': 'NJ'},
'1101': {'name': 'New Brunswick, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 40.4727, 'lon': -74.4225, 'elev': 21, 'network': 'njwx', 'state': 'NJ'},
'3397': {'name': 'Howell, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.1922, 'lon': -74.1958, 'elev': 3, 'network': 'njwx', 'state': 'NJ'},
'3398': {'name': 'Mansfield, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.0778, 'lon': -74.75, 'elev': 21, 'network': 'njwx', 'state': 'NJ'},
'3403': {'name': 'Holmdel, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.3776, 'lon': -74.18, 'elev': 48, 'network': 'njwx', 'state': 'NJ'},
'3404': {'name': 'Wall Twp, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.1548, 'lon': -74.072, 'elev': 7, 'network': 'njwx', 'state': 'NJ'},
'3406': {'name': 'Hamilton, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir','srad'], 'srqual': 'ok', 'lat': 40.2244, 'lon': -74.6117, 'elev': 28, 'network': 'njwx', 'state': 'NJ'},
'3408': {'name': 'Toms River, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.9553, 'lon': -74.2078, 'elev': 21, 'network': 'njwx', 'state': 'NJ'},
'3411': {'name': 'Jersey City (LSC), NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir' ,'srad'], 'srqual': 'ok', 'lat': 40.70877, 'lon': -74.053, 'elev': 1, 'network': 'njwx', 'state': 'NJ'},
'3479': {'name': 'Hammonton 2, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.64, 'lon': -74.75, 'elev': 55, 'network': 'njwx', 'state': 'NJ'},
'3481': {'name': 'Oceanport, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.31126, 'lon': -74.01465, 'elev': 16, 'network': 'njwx', 'state': 'NJ'},
'3485': {'name': 'Greenwich, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.441883, 'lon': -75.382315, 'elev': 39, 'network': 'njwx', 'state': 'NJ'},
'3526': {'name': 'Hopewell Twp, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.352330, 'lon': -74.774986, 'elev': 195, 'network': 'njwx', 'state': 'NJ'},
'3527': {'name': 'Logan, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.804434, 'lon': -75.365640, 'elev': 10, 'network': 'njwx', 'state': 'NJ'},
'3529': {'name': 'Mannington, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.629444, 'lon': -75.359167, 'elev': 49, 'network': 'njwx', 'state': 'NJ'},
'3530': {'name': 'Fortescue, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.242525, 'lon': -75.177046, 'elev': 4, 'network': 'njwx', 'state': 'NJ'},
'3531': {'name': 'West Deptford, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.877742, 'lon': -75.1387889, 'elev': 14, 'network': 'njwx', 'state': 'NJ'},
'3532': {'name': 'Columbus, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 40.033403, 'lon': -74.732469, 'elev': 47, 'network': 'njwx', 'state': 'NJ'},
'3533': {'name': 'Moorestown, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.983344, 'lon': -74.895686, 'elev':71, 'network': 'njwx', 'state': 'NJ'},
'3552': {'name': 'Pennsauken, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'srqual': 'ok', 'lat': 39.985098, 'lon': -75.039108, 'elev': 109, 'network': 'njwx', 'state': 'NJ'},
'kalb': {'name': 'Albany', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.809169999999995, 'elev': 275.0, 'lat': 42.74306, 'network': 'icao', 'state': 'NY'},
'kart': {'name': 'Watertown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -76.02167, 'elev': 318.0, 'lat': 43.992220000000003, 'network': 'icao', 'state': 'NY'},
'kbgm': {'name': 'Binghamton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -75.980000000000004, 'elev': 1595.0, 'lat': 42.206670000000003, 'network': 'icao', 'state': 'NY'},
'kbuf': {'name': 'Buffalo', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -78.735830000000007, 'elev': 705.0, 'lat': 42.940829999999998, 'network': 'icao', 'state': 'NY'},
'kdkk': {'name': 'Dunkirk', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -79.272220000000004, 'elev': 666.0, 'lat': 42.49333, 'network': 'icao', 'state': 'NY'},
'kdsv': {'name': 'Dansville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -77.714169999999996, 'elev': 649.0, 'lat': 42.567500000000003, 'network': 'icao', 'state': 'NY'},
'kelm': {'name': 'Elmira', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -76.891940000000005, 'elev': 955.0, 'lat': 42.159439999999996, 'network': 'icao', 'state': 'NY'},
'kelz': {'name': 'Wellsville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lon': -77.99194, 'elev': 2124.0, 'lat': 42.109439999999999, 'network': 'icao', 'state': 'NY'},
'kfok': {'name': 'Westhampton Beach', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.632220000000004, 'elev': 67.0, 'lat': 40.843609999999998, 'network': 'icao', 'state': 'NY'},
'kfrg': {'name': 'Farmingdale', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.416939999999997, 'elev': 81.0, 'lat': 40.734169999999999, 'network': 'icao', 'state': 'NY'},
'kfzy': {'name': 'Fulton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -76.384720000000002, 'elev': 475.0, 'lat': 43.349719999999998, 'network': 'icao', 'state': 'NY'},
'kgfl': {'name': 'Glens Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.610280000000003, 'elev': 320.0, 'lat': 43.34111, 'network': 'icao', 'state': 'NY'},
'kgtb': {'name': 'Wheeler Sack Field', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -75.733329999999995, 'elev': 702.0, 'lat': 44.049999999999997, 'network': 'icao', 'state': 'NY'},
'khpn': {'name': 'White Plains', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.707499999999996, 'elev': 379.0, 'lat': 41.066940000000002, 'network': 'icao', 'state': 'NY'},
'khwv': {'name': 'Brookhaven', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.868889999999993, 'elev': 82.0, 'lat': 40.821669999999997, 'network': 'icao', 'state': 'NY'},
'kiag': {'name': 'Niagara Falls', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -78.945279999999997, 'elev': 585.0, 'lat': 43.107219999999998, 'network': 'icao', 'state': 'NY'},
'kisp': {'name': 'Islip', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.101669999999999, 'elev': 84.0, 'lat': 40.793889999999998, 'network': 'icao', 'state': 'NY'},
'kith': {'name': 'Ithaca Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -76.466669999999993, 'elev': 1066.0, 'lat': 42.483330000000002, 'network': 'icao', 'state': 'NY'},
'kjfk': {'name': 'NYC-JFK Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.762219999999999, 'elev': 11.0, 'lat': 40.63861, 'network': 'icao', 'state': 'NY'},
'kjhw': {'name': 'Jamestown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -79.25, 'elev': 1719.0, 'lat': 42.149999999999999, 'network': 'icao', 'state': 'NY'},
'klga': {'name': 'NYC-LaGuardia Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.880279999999999, 'elev': 11.0, 'lat': 40.779440000000001, 'network': 'icao', 'state': 'NY'},
'kmgj': {'name': 'Montgomery', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -74.265000000000001, 'elev': 365.0, 'lat': 41.509169999999997, 'network': 'icao', 'state': 'NY'},
'kmss': {'name': 'Massena', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -74.845560000000006, 'elev': 214.0, 'lat': 44.935830000000003, 'network': 'icao', 'state': 'NY'},
'kmsv': {'name': 'Monticello', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -74.799999999999997, 'elev': 1407.0, 'lat': 41.700000000000003, 'network': 'icao', 'state': 'NY'},
'kmtp': {'name': 'Montauk', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lon': -71.923330000000007, 'elev': 7.0, 'lat': 41.073059999999998, 'network': 'icao', 'state': 'NY'},
'knyc': {'name': 'NYC-Central Park', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -73.969170000000005, 'elev': 130.0, 'lat': 40.778889999999997, 'network': 'icao', 'state': 'NY'},
'kpeo': {'name': 'Penn Yan', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -77.056389999999993, 'elev': 903.0, 'lat': 42.642499999999998, 'network': 'icao', 'state': 'NY'},
'kpou': {'name': 'Poughkeepsie', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.884169999999997, 'elev': 166.0, 'lat': 41.626669999999997, 'network': 'icao', 'state': 'NY'},
'krme': {'name': 'Griffiss', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -75.400000000000006, 'elev': 519.0, 'lat': 43.233330000000002, 'network': 'icao', 'state': 'NY'},
'kroc': {'name': 'Rochester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -77.676670000000001, 'elev': 533.0, 'lat': 43.116669999999999, 'network': 'icao', 'state': 'NY'},
'kslk': {'name': 'Saranac Lake', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -74.206670000000003, 'elev': 1663.0, 'lat': 44.385280000000002, 'network': 'icao', 'state': 'NY'},
'kswf': {'name': 'Newburgh Stewart Field', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -74.099999999999994, 'elev': 581.0, 'lat': 41.5, 'network': 'icao', 'state': 'NY'},
'ksyr': {'name': 'Syracuse', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -76.10333, 'elev': 410.0, 'lat': 43.109169999999999, 'network': 'icao', 'state': 'NY'},
'kddh': {'name': 'Bennington (airport), VT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.246939999999995, 'elev': 826.0, 'lat': 42.891390000000001, 'network': 'icao', 'state': 'VT'},
'kbtv': {'name': 'Burlington, VT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.150279999999995, 'elev': 330.0, 'lat': 44.468060000000001, 'network': 'icao', 'state': 'VT'},
'krut': {'name': 'Rutland, VT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.95, 'elev': 784.0, 'lat': 43.53, 'network': 'icao', 'state': 'VT'},
'kmpv': {'name': 'Montpelier, VT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.57, 'elev': 1126.0, 'lat': 44.20, 'network': 'icao', 'state': 'VT'},
'kmvl': {'name': 'Morrisville, VT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.61, 'elev': 768.0, 'lat': 44.53, 'network': 'icao', 'state': 'VT'},
'kvsf': {'name': 'Springfield, VT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.5178, 'elev': 578.0, 'lat': 43.3436, 'network': 'icao', 'state': 'VT'},
'kewr': {'name': 'Newark, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -74.169439999999994, 'elev': 7.0, 'lat': 40.682499999999997, 'network': 'icao', 'state': 'NJ'},
'kfwn': {'name': 'Sussex, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lon': -74.623059999999995, 'elev': 421.0, 'lat': 41.200279999999999, 'network': 'icao', 'state': 'NJ'},
'kcdw': {'name': 'Fairfield, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -74.283060000000006, 'elev': 173.0, 'lat': 40.876390000000001, 'network': 'icao', 'state': 'NJ'},
'kteb': {'name': 'Teterboro, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -74.061390000000003, 'elev': 9.0, 'lat': 40.850000000000001, 'network': 'icao', 'state': 'NJ'},
'k12n': {'name': 'Andover, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lat': 41.0089, 'lon': -74.7367, 'elev': 583, 'network': 'icao', 'state': 'NJ'},
'kacy': {'name': 'Atlantic City Airport, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 39.45, 'lon': -74.57, 'elev': 118, 'network': 'icao', 'state': 'NJ'},
'kblm': {'name': 'Farmingdale, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lat': 40.18, 'lon': -74.13, 'elev': 157, 'network': 'icao', 'state': 'NJ'},
'kmiv': {'name': 'Millville, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 39.37, 'lon': -75.07, 'elev': 70, 'network': 'icao', 'state': 'NJ'},
'kmmu': {'name': 'Morristown, NJ', 'vars': ['temp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.80, 'lon': -74.42, 'elev': 187, 'network': 'icao', 'state': 'NJ'},
'knel': {'name': 'Lakehurst NAS, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lat': 40.03, 'lon': -74.35, 'elev': 112, 'network': 'icao', 'state': 'NJ'},
'ksmq': {'name': 'Somerville, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.62, 'lon': -74.67, 'elev': 105, 'network': 'icao', 'state': 'NJ'},
'kttn': {'name': 'Trenton, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.28, 'lon': -74.82, 'elev': 194, 'network': 'icao', 'state': 'NJ'},
'kvay': {'name': 'Mount Holly, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 39.94, 'lon': -74.84, 'elev': 52, 'network': 'icao', 'state': 'NJ'},
'kwri': {'name': 'McGuire AFB, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lat': 40.02, 'lon': -74.60, 'elev': 148, 'network': 'icao', 'state': 'NJ'},
'kwwd': {'name': 'Wildwood, NJ', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lat': 39.02, 'lon': -74.92, 'elev': 23, 'network': 'icao', 'state': 'NJ'},
'keri': {'name': 'Erie, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -80.182500000000005, 'elev': 730.0, 'lat': 42.079999999999998, 'network': 'icao', 'state': 'PA'},
'kbfd': {'name': 'Bradford, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -78.640280000000004, 'elev': 2117.0, 'lat': 41.803060000000002, 'network': 'icao', 'state': 'PA'},
'kphl': {'name': 'Philadelphia, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 39.88, 'lon': -75.25, 'elev': 63, 'network': 'icao', 'state': 'PA'},
'kpne': {'name': 'NE Philadelphia, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.08, 'lon': -75.02, 'elev': 100, 'network': 'icao', 'state': 'PA'},
'kpit': {'name': 'Pittsburgh, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.3547, 'lon': -79.9217, 'elev': 1248, 'network': 'icao', 'state': 'PA'},
'kmdt': {'name': 'Middletown Harrisburg, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.1961 , 'lon': -76.7725, 'elev': 312, 'network': 'icao', 'state': 'PA'},
'kipt': {'name': 'Williamsport, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 41.2433 , 'lon': -76.9217, 'elev': 520, 'network': 'icao', 'state': 'PA'},
'kavp': {'name': 'Wilkes-Barre, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 41.3336, 'lon': -75.7269, 'elev': 930, 'network': 'icao', 'state': 'PA'},
'kabe': {'name': 'Allentown, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.6508, 'lon': -75.4492, 'elev': 390, 'network': 'icao', 'state': 'PA'},
'kaoo': {'name': 'Altoona, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.2964, 'lon': -78.3203, 'elev': 1480, 'network': 'icao', 'state': 'PA'},
'krdg': {'name': 'Reading, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.3667, 'lon': -75.9667, 'elev': 341, 'network': 'icao', 'state': 'PA'},
'kjst': {'name': 'Johnstown, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 40.3161, 'lon': -78.8339, 'elev': 2270, 'network': 'icao', 'state': 'PA'},
'kduj': {'name': 'DuBois, PA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 41.1783, 'lon': -78.8989, 'elev': 1814, 'network': 'icao', 'state': 'PA'},
'kilg': {'name': 'Wilmington, DE', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 39.67, 'lon': -75.60, 'elev': 79, 'network': 'icao', 'state': 'DE'},
'kpsf': {'name': 'Pittsfield, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lon': -73.28917, 'elev': 1194.0, 'lat': 42.42722, 'network': 'icao', 'state': 'MA'},
'korh': {'name': 'Worcester, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.87611, 'elev': 986.0, 'lat': 42.26722, 'network': 'icao', 'state': 'MA'},
'kore': {'name': 'Orange, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.29111, 'elev': 555.0, 'lat': 42.57000, 'network': 'icao', 'state': 'MA'},
'kpym': {'name': 'Plymouth, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -70.72944, 'elev': 149.0, 'lat': 41.90972, 'network': 'icao', 'state': 'MA'},
'kbvy': {'name': 'Beverly, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -70.91750, 'elev': 108.0, 'lat': 42.58417, 'network': 'icao', 'state': 'MA'},
'khya': {'name': 'Hyannis, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -70.28000, 'elev': 55.0,  'lat': 41.66861, 'network': 'icao', 'state': 'MA'},
'kbos': {'name': 'Boston Logan, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.01056, 'elev': 20.0,  'lat': 42.36056, 'network': 'icao', 'state': 'MA'},
'kack': {'name': 'Nantucket, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -70.06083, 'elev': 45.0,  'lat': 41.25306, 'network': 'icao', 'state': 'MA'},
'kcef': {'name': 'Chicopee Falls, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.53333, 'elev': 246.0, 'lat': 42.20000, 'network': 'icao', 'state': 'MA'},
'klwm': {'name': 'Lawrence, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.12389, 'elev': 149.0, 'lat': 42.71722, 'network': 'icao', 'state': 'MA'},
'kbaf': {'name': 'Westfield Arpt, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lon': -72.71611, 'elev': 271.0, 'lat': 42.15778, 'network': 'icao', 'state': 'MA'},
'kmqe': {'name': 'E Milton Blue Hill, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lon': -71.11361, 'elev': 630.0, 'lat': 42.21222, 'network': 'icao', 'state': 'MA'},
'kaqw': {'name': 'North Adams, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lon': -73.17083, 'elev': 654.0, 'lat': 42.69583, 'network': 'icao', 'state': 'MA'},
'kbed': {'name': 'Bedford, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.28944, 'elev': 133.0, 'lat': 42.47000, 'network': 'icao', 'state': 'MA'},
'kpvc': {'name': 'Provincetown, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -70.22111, 'elev': 8.0,   'lat': 42.07194, 'network': 'icao', 'state': 'MA'},
'ktan': {'name': 'Taunton, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.02111, 'elev': 43.0,  'lat': 41.87556, 'network': 'icao', 'state': 'MA'},
'kowd': {'name': 'Norwood, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.17361, 'elev': 50.0,  'lat': 42.19083, 'network': 'icao', 'state': 'MA'},
'kfmh': {'name': 'Falmouth Otis AFB, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'bad', 'lon': -70.51667, 'elev': 131.0, 'lat': 41.65000, 'network': 'icao', 'state': 'MA'},
'kfit': {'name': 'Fitchburg, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.75583, 'elev': 348.0, 'lat': 42.55194, 'network': 'icao', 'state': 'MA'},
'kmvy': {'name': 'Vineyard Haven, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -70.61500, 'elev': 68.0,  'lat': 41.39306, 'network': 'icao', 'state': 'MA'},
'kewb': {'name': 'New Bedford, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -70.95833, 'elev': 80.0,  'lat': 41.67639, 'network': 'icao', 'state': 'MA'},
'kcqx': {'name': 'Chatham, MA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -69.99333, 'elev': 68.0,  'lat': 41.68750, 'network': 'icao', 'state': 'MA'},
'kuuu': {'name': 'Newport, RI', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.28333, 'elev': 155.0, 'lat': 41.53333, 'network': 'icao', 'state': 'RI'},
'kpvd': {'name': 'Providence, RI', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -71.43333, 'elev': 60.0,  'lat': 41.71667, 'network': 'icao', 'state': 'RI'},
'kbdr': {'name': 'Bridgeport, CT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.12889, 'elev': 5.0, 'lat': 41.15833, 'network': 'icao', 'state': 'CT'},
'kdxr': {'name': 'Danbury, CT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -73.48278, 'elev': 457.0, 'lat': 41.37139, 'network': 'icao', 'state': 'CT'},
'kbdl': {'name': 'Hartford (Bradley AP), CT', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -72.68, 'elev': 190.0,  'lat': 41.94, 'network': 'icao', 'state': 'CT'},
'kcon': {'name': 'Concord, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 43.1953, 'lon': -71.5011, 'elev': 346, 'network': 'icao', 'state': 'NH'},
'keen': {'name': 'Keene, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 42.90, 'lon': -72.26667, 'elev': 487, 'network': 'icao', 'state': 'NH'},
'klci': {'name': 'Laconia, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 43.56667, 'lon': -71.43333, 'elev': 545, 'network': 'icao', 'state': 'NH'},
'kdaw': {'name': 'Rochester, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 43.2781, 'lon': -70.9222, 'elev': 323, 'network': 'icao', 'state': 'NH'},
'kbml': {'name': 'Berlin, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 44.5761, 'lon': -71.1786, 'elev': 1158, 'network': 'icao', 'state': 'NH'},
'kleb': {'name': 'Lebanon, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 43.6264, 'lon': -72.3047, 'elev': 598, 'network': 'icao', 'state': 'NH'},
'kash': {'name': 'Nashua, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 42.7824, 'lon': -71.5141, 'elev': 200, 'network': 'icao', 'state': 'NH'},
'kmht': {'name': 'Manchester, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 42.9333, 'lon': -71.4383, 'elev': 225, 'network': 'icao', 'state': 'NH'},
'kged': {'name': 'Georgetown, DE', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.6892, 'lon': -75.3592, 'elev': 51, 'network': 'icao', 'state': 'DE'},
'kdca': {'name': 'Washington, DC', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.8483, 'lon': -77.0342, 'elev': 10, 'network': 'icao', 'state': 'DC'},
'kbwi': {'name': 'Baltimore, MD', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 39.1667, 'lon': -76.6833, 'elev': 156, 'network': 'icao', 'state': 'MD'},
'ksby': {'name': 'Salisbury, MD', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.3406, 'lon': -75.5103, 'elev': 48, 'network': 'icao', 'state': 'MD'},
'kdlh': {'name': 'Diluth, MN', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 46.8369, 'lon': -92.1833, 'elev': 1433, 'network': 'icao', 'state': 'MN'},
'kmsp': {'name': 'Minneapolis, MN', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 44.8831, 'lon': -93.2289, 'elev': 872, 'network': 'icao', 'state': 'MN'},
'krst': {'name': 'Rochester, MN', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 43.9042, 'lon': -92.4917, 'elev': 1304, 'network': 'icao', 'state': 'MN'},
'kstc': {'name': 'St Cloud, MN', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 45.5433, 'lon': -94.0514, 'elev': 1032, 'network': 'icao', 'state': 'MN'},
'kgpz': {'name': 'Grand Rapids (Airport), MN', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 47.2111, 'lon': -93.5097, 'elev': 1355, 'network': 'icao', 'state': 'MN'},
'kfsd': {'name': 'Sioux Falls, SD', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 43.5778, 'lon': -96.7539, 'elev': 1428, 'network': 'icao', 'state': 'SD'},
'kovs': {'name': 'Boscobel, WI', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -90.6737, 'elev': 672.0,  'lat': 43.16085, 'network': 'icao', 'state': 'WI'},
'klse': {'name': 'La Crosse, WI', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 43.8789, 'lon': -91.2528, 'elev': 652, 'network': 'icao', 'state': 'WI'},
'koma': {'name': 'Omaha, NE', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -95.8992, 'elev': 982,  'lat': 41.3103, 'network': 'icao', 'state': 'NE'},
'klnk': {'name': 'Lincoln Airport, NE', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -96.7475, 'elev': 1190.0,  'lat': 40.8508, 'network': 'icao', 'state': 'NE'},
'kcid': {'name': 'Cedar Rapids, IA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -91.7167, 'elev': 868.0,  'lat': 41.8833, 'network': 'icao', 'state': 'IA'},
'kiow': {'name': 'Iowa City, IA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lon': -91.5431, 'elev': 650.0,  'lat': 41.6328, 'network': 'icao', 'state': 'IA'},
'krfd': {'name': 'Rockford, IL', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 42.1928, 'lon': -89.0931, 'elev': 730, 'network': 'icao', 'state': 'IL'},
'karr': {'name': 'Aurora, IL', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 41.7700, 'lon': -88.4814, 'elev': 710, 'network': 'icao', 'state': 'IL'},
'kstl': {'name': 'St. Louis, MO', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.7525, 'lon': -90.3736, 'elev': 531, 'network': 'icao', 'state': 'MO'},
'kavl': {'name': 'Asheville, NC', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 35.4319, 'lon': -82.5375, 'elev': 2117, 'network': 'icao', 'state': 'NC'},
'kclt': {'name': 'Charlotte, NC', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 35.2236, 'lon': -80.9553, 'elev': 728, 'network': 'icao', 'state': 'NC'},
'khky': {'name': 'Hickory, NC', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 35.7425, 'lon': -81.3819, 'elev': 1143, 'network': 'icao', 'state': 'NC'},
'khsv': {'name': 'Huntsville, AL', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 34.6439, 'lon': -86.7861, 'elev': 624, 'network': 'icao', 'state': 'AL'},
'kafn': {'name': 'Jaffrey, NH', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 42.8050, 'lon': -72.0036, 'elev': 1040, 'network': 'icao', 'state': 'NH'},
'kgsp': {'name': 'Greer, SC', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 34.8842, 'lon': -82.2208, 'elev': 943, 'network': 'icao', 'state': 'SC'},
'kmrb': {'name': 'Martinsburg, WV', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 39.4019, 'lon': -77.9844, 'elev': 534, 'network': 'icao', 'state': 'WV'},
'khgr': {'name': 'Hagerstown, MD', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 39.7078, 'lon': -77.7297, 'elev': 698, 'network': 'icao', 'state': 'MD'},
'kakq': {'name': 'Wakefield, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 36.9839, 'lon': -77.0072, 'elev': 109, 'network': 'icao', 'state': 'VA'},
'kdan': {'name': 'Danville, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 36.5728, 'lon': -79.3361, 'elev': 571, 'network': 'icao', 'state': 'VA'},
'khef': {'name': 'Manassas, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.72139, 'lon': -77.51528, 'elev': 192, 'network': 'icao', 'state': 'VA'},
'kiad': {'name': 'Dulles Airport, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.9408, 'lon': -77.4636, 'elev': 290, 'network': 'icao', 'state': 'VA'},
'klyh': {'name': 'Lynchburg, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 37.3208, 'lon': -79.2067, 'elev': 940, 'network': 'icao', 'state': 'VA'},
'kntu': {'name': 'Oceana, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 36.8167, 'lon': -76.0333, 'elev': 23, 'network': 'icao', 'state': 'VA'},
'knyg': {'name': 'Quantico, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.5000, 'lon': -77.3000, 'elev': 10, 'network': 'icao', 'state': 'VA'},
'korf': {'name': 'Norfolk, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 36.9033, 'lon': -76.1922, 'elev': 30, 'network': 'icao', 'state': 'VA'},
'kphf': {'name': 'Newport News, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 37.1319, 'lon': -76.4931, 'elev': 42, 'network': 'icao', 'state': 'VA'},
'kric': {'name': 'Richmond, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 37.5050, 'lon': -77.3203, 'elev': 164, 'network': 'icao', 'state': 'VA'},
'kroa': {'name': 'Roanoke, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 37.3169, 'lon': -79.9742, 'elev': 1175, 'network': 'icao', 'state': 'VA'},
'kshd': {'name': 'Staunton, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.26361, 'lon': -78.89639, 'elev': 1201, 'network': 'icao', 'state': 'VA'},
'kwal': {'name': 'Wallops Island, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 37.9372, 'lon': -75.4708, 'elev': 46, 'network': 'icao', 'state': 'VA'},
'kcho': {'name': 'Charlottesville (Arpt), VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.1386, 'lon': -78.4531, 'elev': 641, 'network': 'icao', 'state': 'VA'},
'kshd': {'name': 'Staunton, VA', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'srqual': 'ok', 'lat': 38.27, 'lon': -78.85, 'elev': 1188, 'network': 'icao', 'state': 'VA'}
}