stn_info = {'ew_epr': {'srqual': 'ok', 'state': 'MI', 'name': 'Eastport', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.1081, 'elev': 228, 'lon': -85.3247, 'network': 'miwx'},
'khtl': {'srqual': 'ok', 'state': 'MI', 'name': 'Houghton Lake (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.3592, 'elev': 1151, 'lon': -84.6739, 'network': 'icao'},
'ew_kbs': {'name': 'Hickory Corners (KBS)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -85.3736, 'state': 'MI', 'elev': 285.598, 'lat': 42.4081, 'network': 'miwx'},
'ew_pcc': {'srqual': 'ok', 'state': 'MI', 'name': 'Hastings', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.535, 'elev': 282.854, 'lon': -85.3019, 'network': 'miwx'},
'ew_old': {'srqual': 'ok', 'state': 'MI', 'name': 'Old Mission', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.932, 'elev': 219.456, 'lon': -85.4996, 'network': 'miwx'},
'ew_lpr': {'srqual': 'ok', 'state': 'MI', 'name': 'Lapeer', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.0761, 'elev': 251.765, 'lon': -83.3079, 'network': 'miwx'},
'ktvc': {'srqual': 'ok', 'state': 'MI', 'name': 'Traverse City (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.7408, 'elev': 618, 'lon': -85.5825, 'network': 'icao'},
'ew_scd': {'srqual': 'ok', 'state': 'MI', 'name': 'Scottdale', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.0242, 'elev': 204.216, 'lon': -86.4303, 'network': 'miwx'},
'ew_mgr': {'srqual': 'ok', 'state': 'MI', 'name': 'Munger', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.5617, 'elev': 171.907, 'lon': -83.7541, 'network': 'miwx'},
'ew_weo': {'srqual': 'ok', 'state': 'MI', 'name': 'West Olive', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.9715, 'elev': 194.442, 'lon': -86.0765, 'network': 'miwx'},
'ew_nwm': {'srqual': 'ok', 'state': 'MI', 'name': 'Traverse City (NWMHRS)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.8831, 'elev': 247.238, 'lon': -85.6777, 'network': 'miwx'},
'ew_cth': {'srqual': 'ok', 'state': 'MI', 'name': 'Chatham', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 46.3405, 'elev': 270, 'lon': -86.9273, 'network': 'miwx'},
'ew_flt': {'srqual': 'ok', 'state': 'MI', 'name': 'Flint', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.0241, 'elev': 228.6, 'lon': -83.6745, 'network': 'miwx'},
'ew_law': {'srqual': 'ok', 'state': 'MI', 'name': 'Lawton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.1606, 'elev': 251, 'lon': -85.8321, 'network': 'miwx'},
'ew_fev': {'srqual': 'ok', 'state': 'MI', 'name': 'Fennville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.5951, 'elev': 214.37, 'lon': -86.1561, 'network': 'miwx'},
'ew_bel': {'srqual': 'ok', 'state': 'MI', 'name': 'Belding', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.1125, 'elev': 256.52, 'lon': -85.3122, 'network': 'miwx'},
'ew_lin': {'srqual': 'ok', 'state': 'MI', 'name': 'Linwood', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.7199, 'elev': 188, 'lon': -84.0275, 'network': 'miwx'},
'ew_bbc': {'srqual': 'ok', 'state': 'MI', 'name': 'Bainbridge/Watervliet', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.1267, 'elev': 224.942, 'lon': -86.2677, 'network': 'miwx'},
'kfnt': {'srqual': 'ok', 'state': 'MI', 'name': 'Flint (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.9667, 'elev': 769, 'lon': -83.7494, 'network': 'icao'},
'kazo': {'srqual': 'ok', 'state': 'MI', 'name': 'Kalamazoo (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.2347, 'elev': 868, 'lon': -85.5519, 'network': 'icao'},
'ew_cnt': {'srqual': 'ok', 'state': 'MI', 'name': 'Constantine', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.8277, 'elev': 254, 'lon': -85.6616, 'network': 'miwx'},
'kbiv': {'srqual': 'ok', 'state': 'MI', 'name': 'Holland (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.7461, 'elev': 680, 'lon': -86.0967, 'network': 'icao'},
'ew_frm': {'srqual': 'ok', 'state': 'MI', 'name': 'Fremont', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.4225, 'elev': 233.003, 'lon': -85.9551, 'network': 'miwx'},
'ew_frl': {'srqual': 'ok', 'state': 'MI', 'name': 'Freeland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.5631, 'elev': 182, 'lon': -84.0233, 'network': 'miwx'},
'ew_htc': {'srqual': 'ok', 'state': 'MI', 'name': 'East Lansing (HTRC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.711, 'elev': 256.64, 'lon': -84.476, 'network': 'miwx'},
'ew_ver': {'srqual': 'ok', 'state': 'MI', 'name': 'Verona', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.8132, 'elev': 231.648, 'lon': -82.8455, 'network': 'miwx'},
'ew_pig': {'srqual': 'ok', 'state': 'MI', 'name': 'Pigeon', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.8992, 'elev': 187.603, 'lon': -83.2667, 'network': 'miwx'},
'kanj': {'srqual': 'ok', 'state': 'MI', 'name': 'Sault Ste Marie (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 46.4794, 'elev': 722, 'lon': -84.3572, 'network': 'icao'},
'ew_tpd': {'srqual': 'ok', 'state': 'MI', 'name': 'Lawrence/Teapot Dome', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.214, 'elev': 238.354, 'lon': -85.9596, 'network': 'miwx'},
'ew_grj': {'srqual': 'ok', 'state': 'MI', 'name': 'Grand Junction', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.402, 'elev': -9999, 'lon': -86.0731, 'network': 'miwx'},
'ew_cer': {'srqual': 'ok', 'state': 'MI', 'name': 'Ceresco', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.22, 'elev': 288.599, 'lon': -85.1526, 'network': 'miwx'},
'ew_rom': {'srqual': 'ok', 'state': 'MI', 'name': 'Romeo', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.7768, 'elev': 249, 'lon': -83.0211, 'network': 'miwx'},
'ew_cmc': {'srqual': 'ok', 'state': 'MI', 'name': 'Commerce Twp', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.5982, 'elev': 295, 'lon': -83.4964, 'network': 'miwx'},
'ew_haw': {'srqual': 'ok', 'state': 'MI', 'name': 'Hawks', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.2994, 'elev': 252.42, 'lon': -83.8528, 'network': 'miwx'},
'ew_has': {'srqual': 'ok', 'state': 'MI', 'name': 'Haslett', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.7703, 'elev': 281, 'lon': -84.3297, 'network': 'miwx'},
'ew_kct': {'srqual': 'ok', 'state': 'MI', 'name': 'Kent City', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.2463, 'elev': 289.56, 'lon': -85.7718, 'network': 'miwx'},
'ew_dow': {'srqual': 'ok', 'state': 'MI', 'name': 'Dowagiac', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.0249, 'elev': 241, 'lon': -86.171, 'network': 'miwx'},
'ew_fgv': {'srqual': 'ok', 'state': 'MI', 'name': 'Fairgrove', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.5276, 'elev': -9999, 'lon': -83.4864, 'network': 'miwx'},
'ew_spo': {'srqual': 'ok', 'state': 'MI', 'name': 'Sparta', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.1167, 'elev': 267, 'lon': -85.756, 'network': 'miwx'},
'kdtw': {'srqual': 'ok', 'state': 'MI', 'name': 'Detroit (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.2314, 'elev': 631, 'lon': -83.3308, 'network': 'icao'},
'ew_blk': {'name': 'Bear Lake', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -86.1627, 'state': 'MI', 'elev': 242, 'lat': 44.3719, 'network': 'miwx'},
'ew_clt': {'srqual': 'ok', 'state': 'MI', 'name': 'Charlotte', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.6509, 'elev': 284.683, 'lon': -84.916, 'network': 'miwx'},
'ew_hrt': {'srqual': 'ok', 'state': 'MI', 'name': 'Hart', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.7366, 'elev': 233.394, 'lon': -86.3594, 'network': 'miwx'},
'ew_shv': {'srqual': 'ok', 'state': 'MI', 'name': 'South Haven', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.3579, 'elev': 189, 'lon': -86.2894, 'network': 'miwx'},
'ew_clr': {'srqual': 'ok', 'state': 'MI', 'name': 'Clarksville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.8733, 'elev': 272.845, 'lon': -85.2604, 'network': 'miwx'},
'ew_cld': {'srqual': 'ok', 'state': 'MI', 'name': 'Coldwater', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.9348, 'elev': 293.218, 'lon': -85.1082, 'network': 'miwx'},
'ew_kzo': {'srqual': 'ok', 'state': 'MI', 'name': 'Kalamazoo', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.3538, 'elev': 268.224, 'lon': -85.5855, 'network': 'miwx'},
'ew_mml': {'srqual': 'ok', 'state': 'MI', 'name': 'McMillan/Newberry', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 46.3134, 'elev': 254.508, 'lon': -85.6487, 'network': 'miwx'},
'ew_elb': {'srqual': 'ok', 'state': 'MI', 'name': 'Elbridge/Hart', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.6793, 'elev': 276, 'lon': -86.1893, 'network': 'miwx'},
'ew_hfd': {'srqual': 'ok', 'state': 'MI', 'name': 'Hartford', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.2275, 'elev': 226, 'lon': -86.1403, 'network': 'miwx'},
'kmbs': {'srqual': 'ok', 'state': 'MI', 'name': 'Saginaw (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.5331, 'elev': 660, 'lon': -84.0797, 'network': 'icao'},
'ew_eld': {'srqual': 'ok', 'state': 'MI', 'name': 'East Leland', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.0301, 'elev': -9999, 'lon': -85.6743, 'network': 'miwx'},
'ew_elk': {'srqual': 'ok', 'state': 'MI', 'name': 'Elk Rapids', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.8448, 'elev': 198, 'lon': -85.4062, 'network': 'miwx'},
'ew_knd': {'srqual': 'ok', 'state': 'MI', 'name': 'Kinde', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.924, 'elev': 215.798, 'lon': -83.0121, 'network': 'miwx'},
'ew_swm': {'srqual': 'ok', 'state': 'MI', 'name': 'Benton Harbor (SWMREC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.0841, 'elev': 219.926, 'lon': -86.357, 'network': 'miwx'},
'kapn': {'srqual': 'ok', 'state': 'MI', 'name': 'Alpena (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 45.0717, 'elev': 692, 'lon': -83.5644, 'network': 'icao'},
'ew_alg': {'srqual': 'ok', 'state': 'MI', 'name': 'Allegan', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.4865, 'elev': 212, 'lon': -85.804, 'network': 'miwx'},
'ew_mct': {'srqual': 'ok', 'state': 'MI', 'name': 'Mecosta', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.5653, 'elev': 305.409, 'lon': -85.2449, 'network': 'miwx'},
'ew_alb': {'srqual': 'ok', 'state': 'MI', 'name': 'Albion', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.2619, 'elev': 289, 'lon': -84.7741, 'network': 'miwx'},
'ew_kal': {'srqual': 'ok', 'state': 'MI', 'name': 'Kalkaska', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.6555, 'elev': 351.434, 'lon': -85.0743, 'network': 'miwx'},
'ew_les': {'srqual': 'ok', 'state': 'MI', 'name': 'Leslie', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.4714, 'elev': 290.779, 'lon': -84.4575, 'network': 'miwx'},
'ew_mcb': {'srqual': 'ok', 'state': 'MI', 'name': 'McBain', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.1861, 'elev': 359.664, 'lon': -85.1251, 'network': 'miwx'},
'kjxn': {'srqual': 'ok', 'state': 'MI', 'name': 'Jackson (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.2667, 'elev': 1005, 'lon': -84.4667, 'network': 'icao'},
'ew_msu': {'srqual': 'ok', 'state': 'MI', 'name': 'East Lansing (MSU Hort)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.6734, 'elev': 264, 'lon': -84.487, 'network': 'miwx'},
'ew_rvl': {'srqual': 'ok', 'state': 'MI', 'name': 'Richville/Frankenmuth', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.3995, 'elev': -9999, 'lon': -83.698, 'network': 'miwx'},
'ew_ost': {'srqual': 'ok', 'state': 'MI', 'name': 'Oshtemo', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.295, 'elev': 292, 'lon': -85.7014, 'network': 'miwx'},
'ew_esc': {'srqual': 'ok', 'state': 'MI', 'name': 'Escanaba', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.8551, 'elev': 221.4, 'lon': -87.1844, 'network': 'miwx'},
'ew_bnz': {'srqual': 'ok', 'state': 'MI', 'name': 'Benzonia', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.5593, 'elev': 252.679, 'lon': -86.1172, 'network': 'miwx'},
'ew_arl': {'srqual': 'ok', 'state': 'MI', 'name': 'Arlene', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.3966, 'elev': 402.946, 'lon': -85.2935, 'network': 'miwx'},
'ew_nth': {'srqual': 'ok', 'state': 'MI', 'name': 'Northport', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.1356, 'elev': -9999, 'lon': -85.6508, 'network': 'miwx'},
'ew_bna': {'srqual': 'ok', 'state': 'MI', 'name': 'Benona/Shelby', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.6304, 'elev': 256, 'lon': -86.4931, 'network': 'miwx'},
'ew_ith': {'srqual': 'ok', 'state': 'MI', 'name': 'Ithaca', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.3154, 'elev': -9999, 'lon': -84.4884, 'network': 'miwx'},
'ew_hdn': {'srqual': 'ok', 'state': 'MI', 'name': 'Hudson', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.8729, 'elev': 265.481, 'lon': -84.2259, 'network': 'miwx'},
'ew_klr': {'srqual': 'ok', 'state': 'MI', 'name': 'Keeler', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.1769, 'elev': 245.364, 'lon': -86.18, 'network': 'miwx'},
'ew_drf': {'srqual': 'ok', 'state': 'MI', 'name': 'Deerfield/Blissfield', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.8626, 'elev': 207.5, 'lon': -83.7979, 'network': 'miwx'},
'ew_kwd': {'srqual': 'ok', 'state': 'MI', 'name': 'Kewadin', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.9526, 'elev': -9999, 'lon': -85.3347, 'network': 'miwx'},
'ew_ent': {'srqual': 'ok', 'state': 'MI', 'name': 'Entrican', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.3541, 'elev': 290, 'lon': -85.1791, 'network': 'miwx'},
'ew_brs': {'srqual': 'ok', 'state': 'MI', 'name': 'Berrien Springs', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.9352, 'elev': 228, 'lon': -86.3797, 'network': 'miwx'},
'ew_stn': {'srqual': 'ok', 'state': 'MI', 'name': 'Standale/Walker', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.9557, 'elev': 226, 'lon': -85.7521, 'network': 'miwx'},
'kmkg': {'srqual': 'ok', 'state': 'MI', 'name': 'Muskegon (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.1711, 'elev': 625, 'lon': -86.2367, 'network': 'icao'},
'ew_stv': {'srqual': 'ok', 'state': 'MI', 'name': 'Stephenson', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.4082, 'elev': -9999, 'lon': -87.6096, 'network': 'miwx'},
'kgrr': {'srqual': 'ok', 'state': 'MI', 'name': 'Grand Rapids (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.8825, 'elev': 803, 'lon': -85.5239, 'network': 'icao'},
'ew_men': {'srqual': 'ok', 'state': 'MI', 'name': 'Mendon', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.9833, 'elev': 256, 'lon': -85.4333, 'network': 'miwx'},
'ew_cas': {'srqual': 'ok', 'state': 'MI', 'name': 'Cassopolis', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.953, 'elev': 289.865, 'lon': -85.9902, 'network': 'miwx'},
'ew_emt': {'srqual': 'ok', 'state': 'MI', 'name': 'Emmett', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.9914, 'elev': 239.88, 'lon': -82.7598, 'network': 'miwx'},
'klan': {'srqual': 'ok', 'state': 'MI', 'name': 'Lansing (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.7803, 'elev': 871, 'lon': -84.5789, 'network': 'icao'},
'ew_gay': {'srqual': 'ok', 'state': 'MI', 'name': 'Gaylord', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.0315, 'elev': 434.34, 'lon': -84.8481, 'network': 'miwx'},
'kglr': {'srqual': 'ok', 'state': 'MI', 'name': 'Gaylord (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 45.0133, 'elev': 1335, 'lon': -84.7014, 'network': 'icao'},
'ew_ldt': {'srqual': 'ok', 'state': 'MI', 'name': 'Ludington', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.9043, 'elev': 199.683, 'lon': -86.3798, 'network': 'miwx'},
'ew_hvl': {'srqual': 'ok', 'state': 'MI', 'name': 'Hudsonville', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.8594, 'elev': -9999, 'lon': -85.8895, 'network': 'miwx'},
'kbtl': {'srqual': 'ok', 'state': 'MI', 'name': 'Battle Creek (AP)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.3075, 'elev': 956, 'lon': -85.2511, 'network': 'icao'},
'ew_sdk': {'srqual': 'ok', 'state': 'MI', 'name': 'Sandusky', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.4556, 'elev': 237, 'lon': -82.8375, 'network': 'miwx'},
}