stn_info = {'kmsp': {'srqual': 'ok', 'state': 'MN', 'name': 'Minneapolis', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 44.8831, 'elev': 872, 'lon': -93.2289, 'network': 'icao'},
'kstc': {'srqual': 'ok', 'state': 'MN', 'name': 'St Cloud', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 45.5433, 'elev': 1032, 'lon': -94.0514, 'network': 'icao'},
'mn_lkc': {'srqual': 'ok', 'state': 'MN', 'name': 'Lake City', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.420187, 'elev': 1140, 'lon': -92.227366, 'network': 'newa'},
'kdlh': {'srqual': 'ok', 'state': 'MN', 'name': 'Diluth', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 46.8369, 'elev': 1433, 'lon': -92.1833, 'network': 'icao'},
'mn_lac': {'srqual': 'ok', 'state': 'MN', 'name': 'La Crescent', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.858199, 'elev': 1231, 'lon': -91.318371, 'network': 'newa'},
'mn_aft': {'srqual': 'ok', 'state': 'MN', 'name': 'Afton', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.819, 'elev': 881, 'lon': -92.796, 'network': 'newa'},
'mn_cha': {'name': 'Chaska (Univ MN HRC)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lon': -93.634693, 'state': 'MN', 'elev': 1029, 'lat': 44.86252, 'network': 'newa'},
'krst': {'srqual': 'ok', 'state': 'MN', 'name': 'Rochester', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 43.9042, 'elev': 1304, 'lon': -92.4917, 'network': 'icao'},
'mn_buf': {'srqual': 'ok', 'state': 'MN', 'name': 'Buffalo', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.22, 'elev': 1015, 'lon': -93.84, 'network': 'newa'},
'mn_och': {'srqual': 'ok', 'state': 'MN', 'name': 'Worthington (Ocheda)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.56208, 'elev': 1594, 'lon': -95.573347, 'network': 'newa'},
'mn_pre': {'srqual': 'ok', 'state': 'MN', 'name': 'Preston', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 43.6825, 'elev': 1088, 'lon': -92.0761, 'network': 'newa'},
'mn_has': {'srqual': 'ok', 'state': 'MN', 'name': 'Hastings', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.7884, 'elev': 904, 'lon': -92.81677, 'network': 'newa'},
'mn_wbl': {'srqual': 'ok', 'state': 'MN', 'name': 'White Bear Lake', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.10632, 'elev': 955, 'lon': -92.955087, 'network': 'newa'},
'mn_sha': {'srqual': 'ok', 'state': 'MN', 'name': 'Shafer', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.352665, 'elev': 938, 'lon': -92.753021, 'network': 'newa'},
'kgpz': {'srqual': 'ok', 'state': 'MN', 'name': 'Grand Rapids (Airport)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 47.2111, 'elev': 1355, 'lon': -93.5097, 'network': 'icao'},
'mn_elg': {'srqual': 'ok', 'state': 'MN', 'name': 'Elgin', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 44.1364, 'elev': 1050, 'lon': -92.242435, 'network': 'newa'},
'mn_del': {'srqual': 'ok', 'state': 'MN', 'name': 'Delano (Apple Jack)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.0997, 'elev': 925, 'lon': -93.7902, 'network': 'newa'},
'mn_gra': {'srqual': 'ok', 'state': 'MN', 'name': 'Grand Rapids', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 47.24245, 'elev': 1289, 'lon': -93.492838, 'network': 'newa'},
'mn_alx': {'srqual': 'ok', 'state': 'MN', 'name': 'Alexandria', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 45.872756, 'elev': 1403, 'lon': -95.470478, 'network': 'newa'},
}