stn_info = {'pa_bre': {'srqual': 'ok', 'state': 'PA', 'name': 'Breinigsville (Grim)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.5433, 'elev': 470, 'lon': -75.6622, 'network': 'newa'},
'pa_lew': {'srqual': 'ok', 'state': 'PA', 'name': 'Lewisburg (Fero Vineyards)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.997036, 'elev': 565, 'lon': -76.886299, 'network': 'newa'},
'pa_ntr': {'srqual': 'ok', 'state': 'PA', 'name': 'New Tripoli (NWLHS)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.68263, 'elev': 738, 'lon': -75.724929, 'network': 'newa'},
'kbfd': {'srqual': 'ok', 'state': 'PA', 'name': 'Bradford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.80306, 'elev': 2117.0, 'lon': -78.64028, 'network': 'icao'},
'pa_big': {'srqual': 'ok', 'state': 'PA', 'name': 'Biglerville (Hollabaugh)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.946944, 'elev': 732, 'lon': -77.247222, 'network': 'newa'},
'pa_pin': {'srqual': 'ok', 'state': 'PA', 'name': 'Piney Mountain', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.977669, 'elev': 1217, 'lon': -77.339694, 'network': 'newa'},
'pa_ysp': {'srqual': 'ok', 'state': 'PA', 'name': 'York Springs (Lerew)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.038978, 'elev': 740, 'lon': -77.136408, 'network': 'newa'},
'pa_sco': {'srqual': 'ok', 'state': 'PA', 'name': 'Scott Township', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.572091, 'elev': 1750, 'lon': -75.593225, 'network': 'newa'},
'kpit': {'srqual': 'ok', 'state': 'PA', 'name': 'Pittsburgh', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.3547, 'elev': 1248, 'lon': -79.9217, 'network': 'icao'},
'kduj': {'srqual': 'ok', 'state': 'PA', 'name': 'DuBois', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.1783, 'elev': 1814, 'lon': -78.8989, 'network': 'icao'},
'pa_heg': {'srqual': 'ok', 'state': 'PA', 'name': 'Hegins (Schwalm)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.6568, 'elev': 237, 'lon': -76.4887, 'network': 'newa'},
'pa_hun': {'srqual': 'ok', 'state': 'PA', 'name': 'Hostetler Airport (StoneView)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.631244, 'elev': 741.8598, 'lon': -77.850166, 'network': 'newa'},
'kjst': {'srqual': 'ok', 'state': 'PA', 'name': 'Johnstown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.3161, 'elev': 2270, 'lon': -78.8339, 'network': 'icao'},
'kabe': {'srqual': 'ok', 'state': 'PA', 'name': 'Allentown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.6508, 'elev': 390, 'lon': -75.4492, 'network': 'icao'},
'kipt': {'srqual': 'ok', 'state': 'PA', 'name': 'Williamsport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.2433, 'elev': 520, 'lon': -76.9217, 'network': 'icao'},
'nee': {'srqual': 'ok', 'state': 'PA', 'name': 'North East Escarpment', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.18097, 'elev': 1029, 'lon': -79.8517, 'network': 'newa'},
'pa_cab': {'srqual': 'ok', 'state': 'PA', 'name': 'Cabot (Mathias Farm)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.7792, 'elev': 1330, 'lon': -79.7334, 'network': 'newa'},
'har': {'srqual': 'ok', 'state': 'PA', 'name': 'Harborcreek', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.1931232, 'elev': 742.0, 'lon': -79.9049196, 'network': 'newa'},
'kaoo': {'srqual': 'ok', 'state': 'PA', 'name': 'Altoona', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.2964, 'elev': 1480, 'lon': -78.3203, 'network': 'icao'},
'nel': {'srqual': 'ok', 'state': 'PA', 'name': 'North East Lab', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 42.22834, 'elev': 680, 'lon': -79.85432, 'network': 'newa'},
'krdg': {'srqual': 'ok', 'state': 'PA', 'name': 'Reading', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.3667, 'elev': 341, 'lon': -75.9667, 'network': 'icao'},
'kpne': {'srqual': 'ok', 'state': 'PA', 'name': 'NE Philadelphia', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.08, 'elev': 100, 'lon': -75.02, 'network': 'icao'},
'kphl': {'srqual': 'ok', 'state': 'PA', 'name': 'Philadelphia', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.88, 'elev': 63, 'lon': -75.25, 'network': 'icao'},
'kmdt': {'srqual': 'ok', 'state': 'PA', 'name': 'Middletown Harrisburg', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.1961, 'elev': 312, 'lon': -76.7725, 'network': 'icao'},
'pa_rsp': {'srqual': 'ok', 'state': 'PA', 'name': 'Rock Springs', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.713993, 'elev': 1213, 'lon': -77.948844, 'network': 'newa'},
'pa_npa': {'srqual': 'ok', 'state': 'PA', 'name': 'New Paris (Boyer)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.105321, 'elev': 1556, 'lon': -78.629474, 'network': 'newa'},
'kavp': {'srqual': 'ok', 'state': 'PA', 'name': 'Wilkes-Barre', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.3336, 'elev': 930, 'lon': -75.7269, 'network': 'icao'},
'keri': {'srqual': 'ok', 'state': 'PA', 'name': 'Erie', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 42.08, 'elev': 730.0, 'lon': -80.1825, 'network': 'icao'},
}