stn_info = {'nj_elk': {'srqual': 'ok', 'state': 'NJ', 'name': 'Elk Township', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.6664019, 'elev': 136, 'lon': -75.184658, 'network': 'newa'},
'ksmq': {'srqual': 'ok', 'state': 'NJ', 'name': 'Somerville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.62, 'elev': 105, 'lon': -74.67, 'network': 'icao'},
'kteb': {'srqual': 'ok', 'state': 'NJ', 'name': 'Teterboro', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.85, 'elev': 9.0, 'lon': -74.06139, 'network': 'icao'},
'1029': {'srqual': 'ok', 'state': 'NJ', 'name': 'Pequest', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.8383, 'elev': 135, 'lon': -74.9491, 'network': 'njwx'},
'k12n': {'srqual': 'bad', 'state': 'NJ', 'name': 'Andover', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.0089, 'elev': 583, 'lon': -74.7367, 'network': 'icao'},
'29': {'srqual': 'ok', 'state': 'NJ', 'name': 'South Harrison', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.712359, 'elev': 141, 'lon': -75.280754, 'network': 'njwx'},
'3531': {'srqual': 'ok', 'state': 'NJ', 'name': 'West Deptford', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.877742, 'elev': 14, 'lon': -75.1387889, 'network': 'njwx'},
'3530': {'srqual': 'ok', 'state': 'NJ', 'name': 'Fortescue', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.242525, 'elev': 4, 'lon': -75.177046, 'network': 'njwx'},
'3533': {'srqual': 'ok', 'state': 'NJ', 'name': 'Moorestown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.983344, 'elev': 71, 'lon': -74.895686, 'network': 'njwx'},
'3532': {'srqual': 'ok', 'state': 'NJ', 'name': 'Columbus', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.033403, 'elev': 47, 'lon': -74.732469, 'network': 'njwx'},
'111': {'name': 'Lyndhurst (NJMC)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.104617, 'state': 'NJ', 'elev': 0, 'lat': 40.784214, 'network': 'njwx'},
'3411': {'srqual': 'ok', 'state': 'NJ', 'name': 'Jersey City (LSC)', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.70877, 'elev': 1, 'lon': -74.053, 'network': 'njwx'},
'236': {'name': 'Cherry Hill III', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -75.0257, 'state': 'NJ', 'elev': 7, 'lat': 39.9098, 'network': 'njwx'},
'232': {'name': 'Egg Harbor', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.5421, 'state': 'NJ', 'elev': 12, 'lat': 39.4227, 'network': 'njwx'},
'kwwd': {'srqual': 'bad', 'state': 'NJ', 'name': 'Wildwood', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.02, 'elev': 23, 'lon': -74.92, 'network': 'icao'},
'nj_mil': {'srqual': 'ok', 'state': 'NJ', 'name': 'Milford', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.585858, 'elev': 123, 'lon': -75.157788, 'network': 'newa'},
'3552': {'srqual': 'ok', 'state': 'NJ', 'name': 'Pennsauken', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.985098, 'elev': 109, 'lon': -75.039108, 'network': 'njwx'},
'kblm': {'srqual': 'bad', 'state': 'NJ', 'name': 'Farmingdale', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.18, 'elev': 157, 'lon': -74.13, 'network': 'icao'},
'kewr': {'srqual': 'ok', 'state': 'NJ', 'name': 'Newark', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.6825, 'elev': 7.0, 'lon': -74.16944, 'network': 'icao'},
'3479': {'name': 'Hammonton 2', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.75, 'state': 'NJ', 'elev': 55, 'lat': 39.64, 'network': 'njwx'},
'289': {'srqual': 'ok', 'state': 'NJ', 'name': 'Pittstown', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.5612, 'elev': 183, 'lon': -74.961, 'network': 'njwx'},
'kvay': {'srqual': 'ok', 'state': 'NJ', 'name': 'Mount Holly', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.94, 'elev': 52, 'lon': -74.84, 'network': 'icao'},
'kcdw': {'srqual': 'ok', 'state': 'NJ', 'name': 'Fairfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.87639, 'elev': 173.0, 'lon': -74.28306, 'network': 'icao'},
'1032': {'srqual': 'ok', 'state': 'NJ', 'name': 'Berkeley Twp', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.92578, 'elev': 24, 'lon': -74.2981, 'network': 'njwx'},
'1033': {'srqual': 'ok', 'state': 'NJ', 'name': 'Haworth', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.9593, 'elev': 8, 'lon': -74.0135, 'network': 'njwx'},
'285': {'srqual': 'ok', 'state': 'NJ', 'name': 'Basking Ridge', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.6956, 'elev': 67, 'lon': -74.5198, 'network': 'njwx'},
'284': {'srqual': 'ok', 'state': 'NJ', 'name': 'Upper Deerfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.5243, 'elev': 33, 'lon': -75.2009, 'network': 'njwx'},
'1034': {'srqual': 'ok', 'state': 'NJ', 'name': 'Sicklerville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.7638, 'elev': 45, 'lon': -74.9785, 'network': 'njwx'},
'286': {'srqual': 'ok', 'state': 'NJ', 'name': 'High Point', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.305, 'elev': 422, 'lon': -74.666, 'network': 'njwx'},
'nj_pri': {'srqual': 'toolow', 'state': 'NJ', 'name': 'Princeton (Terhune)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.3218, 'elev': 186, 'lon': -74.7292, 'network': 'newa'},
'202': {'name': 'Bethel Mill Park', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -75.1138, 'state': 'NJ', 'elev': 30, 'lat': 39.7485, 'network': 'njwx'},
'knel': {'srqual': 'bad', 'state': 'NJ', 'name': 'Lakehurst NAS', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.03, 'elev': 112, 'lon': -74.35, 'network': 'icao'},
'kmiv': {'srqual': 'ok', 'state': 'NJ', 'name': 'Millville', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.37, 'elev': 70, 'lon': -75.07, 'network': 'icao'},
'3481': {'srqual': 'ok', 'state': 'NJ', 'name': 'Oceanport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.31126, 'elev': 16, 'lon': -74.01465, 'network': 'njwx'},
'317': {'srqual': 'ok', 'state': 'NJ', 'name': 'Oswego Lake', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.71539, 'elev': 15, 'lon': -74.5142, 'network': 'njwx'},
'kmmu': {'srqual': 'ok', 'state': 'NJ', 'name': 'Morristown', 'vars': ['temp', 'rhum', 'wspd', 'wdir'], 'lat': 40.8, 'elev': 187, 'lon': -74.42, 'network': 'icao'},
'3485': {'srqual': 'ok', 'state': 'NJ', 'name': 'Greenwich', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.441883, 'elev': 39, 'lon': -75.382315, 'network': 'njwx'},
'148': {'srqual': 'ok', 'state': 'NJ', 'name': 'Cape May Courthouse', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.1246, 'elev': 7, 'lon': -74.7873, 'network': 'njwx'},
'263': {'name': 'Piney Hollow', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.92, 'state': 'NJ', 'elev': 30, 'lat': 39.58, 'network': 'njwx'},
'3527': {'srqual': 'ok', 'state': 'NJ', 'name': 'Logan', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.804434, 'elev': 10, 'lon': -75.36564, 'network': 'njwx'},
'3403': {'name': 'Holmdel', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.18, 'state': 'NJ', 'elev': 48, 'lat': 40.3776, 'network': 'njwx'},
'3404': {'name': 'Wall Twp', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.072, 'state': 'NJ', 'elev': 7, 'lat': 40.1548, 'network': 'njwx'},
'3406': {'srqual': 'ok', 'state': 'NJ', 'name': 'Hamilton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.2244, 'elev': 28, 'lon': -74.6117, 'network': 'njwx'},
'3408': {'name': 'Toms River', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.2078, 'state': 'NJ', 'elev': 21, 'lat': 39.9553, 'network': 'njwx'},
'kwri': {'srqual': 'bad', 'state': 'NJ', 'name': 'McGuire AFB', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.02, 'elev': 148, 'lon': -74.6, 'network': 'icao'},
'3529': {'srqual': 'ok', 'state': 'NJ', 'name': 'Mannington', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.629444, 'elev': 49, 'lon': -75.359167, 'network': 'njwx'},
'nj_blu': {'srqual': 'ok', 'state': 'NJ', 'name': 'Blue Anchor (Sharrott Winery)', 'vars': ['temp', 'lwet', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.677, 'elev': 131, 'lon': -74.874, 'network': 'newa'},
'3526': {'srqual': 'ok', 'state': 'NJ', 'name': 'Hopewell Twp', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.35233, 'elev': 195, 'lon': -74.774986, 'network': 'njwx'},
'3397': {'name': 'Howell', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.1958, 'state': 'NJ', 'elev': 3, 'lat': 40.1922, 'network': 'njwx'},
'33': {'name': 'Dennis Twp', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.8923, 'state': 'NJ', 'elev': 5, 'lat': 39.2039, 'network': 'njwx'},
'3398': {'name': 'Mansfield', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.75, 'state': 'NJ', 'elev': 21, 'lat': 40.0778, 'network': 'njwx'},
'kttn': {'srqual': 'ok', 'state': 'NJ', 'name': 'Trenton', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 40.28, 'elev': 194, 'lon': -74.82, 'network': 'icao'},
'kfwn': {'srqual': 'bad', 'state': 'NJ', 'name': 'Sussex', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 41.20028, 'elev': 421.0, 'lon': -74.62306, 'network': 'icao'},
'261': {'name': 'West Cape May', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lon': -74.9441, 'state': 'NJ', 'elev': 5, 'lat': 38.9422, 'network': 'njwx'},
'471': {'srqual': 'ok', 'state': 'NJ', 'name': 'Charlotteburg', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 41.0299, 'elev': 232, 'lon': -74.4247, 'network': 'njwx'},
'kacy': {'srqual': 'ok', 'state': 'NJ', 'name': 'Atlantic City Airport', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir'], 'lat': 39.45, 'elev': 118, 'lon': -74.57, 'network': 'icao'},
'287': {'srqual': 'ok', 'state': 'NJ', 'name': 'Sea Girt', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.1203, 'elev': 2, 'lon': -74.0327, 'network': 'njwx'},
'1101': {'srqual': 'ok', 'state': 'NJ', 'name': 'New Brunswick', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.4727, 'elev': 21, 'lon': -74.4225, 'network': 'njwx'},
'296': {'srqual': 'ok', 'state': 'NJ', 'name': 'Woodbine', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 39.2202, 'elev': 10, 'lon': -74.7959, 'network': 'njwx'},
'295': {'srqual': 'ok', 'state': 'NJ', 'name': 'Cream Ridge', 'vars': ['temp', 'prcp', 'rhum', 'wspd', 'wdir', 'srad'], 'lat': 40.1185, 'elev': 36, 'lon': -74.5256, 'network': 'njwx'},
}