pest_status_management = { 
'pest_name': "Codling Moth",
'biofix_phenology': "First Trap Catch",
'biofix_abbrev': "cm",
'biofix2_phenology': "Second Generation Flight Start",
'biofix2_abbrev': None,
'basetemp': 50,

'pre_biofix': {
0: { 'ddlo':   0, 'ddhi': 272, 'altref': ["Dormant","Silver_Tip","Green_Tip","Half-Inch_Green","Tight_Cluster","Pink_Bud"],
                               'stage': "Overwintering in the pupae stage", 
                               'status': "No <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/cm/cm.asp' target='_blank'>codling moth</a> flight is expected.", 
                               'management': "Pheromone traps should be in place before the first apple blossoms open.  Mating disruption dispensers should also be put in the orchard before the first blossoms open for seasonal disruption programs." },
1: { 'ddlo': 273, 'ddhi': 611, 'altref': ["Bloom","Petal_Fall","Post_Petal_Fall"],
						       'stage': "1st generation moths emerge", 
                               'status': "First catch of <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/cm/cm_fig1.asp' target='_blank'>adults</a> from the overwintering generation is expected (usually coincides with first bloom of Delicious apples).",
                               'management': "No insecticides need to be applied until eggs begin to hatch." }  },
'post_biofix': {  
0: { 'ddlo':   0, 'ddhi': 219, 'altref': ["Post_0"],
						       'stage': "Moths flying & first eggs laid",
                               'status': "First <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/cm/cm_fig2.asp' target='_blank'>eggs</a> are laid at about 50 DD and the first eggs usually hatch after about 220 DD.",
                               'management': "Apply insecticides that need to be present before egg laying at about 50-75 DD.  Apply insecticides that target early egg laying period at 100-200 DD." ,
                               'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=24&GrowthStageID=12" },
1: { 'ddlo': 220, 'ddhi': 250, 'altref': ["Post_1"],
						       'stage': "Moth catches increasing and eggs begin to hatch",
                               'status': "Eggs usually begin to hatch about 220 DD after the first catch, and catches of adults should be increasing in pheromone traps.",
                               'management': "Apply the first spray for control of overwintering CM at 250 DD after first catch.  In some seasons, Plum curculio will still be active at this time and a broad spectrum material should be selected to control both of these pests at this time in high risk PC orchards.  If <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/cm/cm_fig5.asp' target='_blank'>internal worm damage</a> has been observed in past years in an orchard, CM populations may be resistant to organophosphate and synthetic pyrethroid insecticides and other classes of materials may be more effective." },
2: { 'ddlo': 251, 'ddhi': 600, 'altref': ["Post_2"],
						       'stage': "Moth flight peaks & majority of eggs hatch",
                               'status': "Adult flights are relatively heavy during this period and the majority of eggs are likely to hatch, so control is critical at this time.",
                               'management': "Apply a second spray 10-14 days after the initial spray that was timed at first hatch, to provide protection during this critical time period.  In high-pressure orchards, it may be particularly important to apply other classes of materials to replace organophosphates or synthetic pyrethroids.",
                               'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=24&GrowthStageID=12" },
3: { 'ddlo': 601, 'ddhi': 720, 'altref': ["Post_3"],
						       'stage': "1st moth flight over & egg hatch complete", 
                               'status': "Egg hatch of the first generation of CM is almost completed.",
                               'management': "It is too late to apply control sprays at this time because egg hatch is almost over and late sprays will not prevent fruit damage that has occurred earlier in the season.  If fruit has become infested with CM during the first generation, it will make subsequent control more difficult later in the season; most apples infested by larvae at this time will drop prematurely and will not be detected at harvest." },
4: { 'ddlo': 721, 'ddhi':1500, 'altref': ["Post_4"],
						       'stage': "2nd generation of moths emerge",
                               'status': "The flight of second generation CM usually starts during this time.", 
                               'management': "Insecticides should be applied when the eggs from the second generation of CM begin to hatch, which usually occurs about 250 DD after the moth flight begins.",
                               'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=24&GrowthStageID=12" }},
'post_biofix2': {  
0: { 'ddlo':   0, 'ddhi': 150, 'altref': ["Post_5"],
						       'stage': "Moths flying & egg hatch begins",
                               'status': "Eggs from the second generation of CM have started to hatch.", 
                               'management': "Apply insecticides to control newly hatching larvae.  In order to manage insecticide resistance, it is best to apply a different class of materials to control this second generation of CM than was used earlier in the season against the overwintering generation.  Insecticides applied at this time to control CM will also control the second generation of OFM.  The summer generation of OBLR may also be active at this time and materials should be applied that are active against both internal Lepidoptera and leafrollers." ,
                               'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=24&GrowthStageID=12" },
1: { 'ddlo': 151, 'ddhi': 350, 'altref': ["Post_6"],
						       'stage': "Moth flight near peak & majority of eggs hatch",
                               'status': "Moths from the second generation are actively flying and egg hatch is heavy.", 
                               'management': "Apply a second spray 10-14 days after the initial spray timed at the first hatch of the second generation.  OFM, summer OBLR, and AM may also be active during this time period so materials should also be selected that will control these pests if necessary." ,
                               'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=24&GrowthStageID=12" },
2: { 'ddlo': 351, 'ddhi': 500, 'altref': ["Post_7"],
						       'stage': "2nd moth flight & egg hatch almost over",
                               'status': "The flight of second generation CM is over and egg hatch is almost complete.", 
                               'management': "It is too late to apply a control spray to control fruit injury from the second generation of CM at this time.  However, a spray may be necessary if populations of OFM are high at this time." },
3: { 'ddlo': 501, 'ddhi': 950, 'altref': ["Post_8"],
						       'stage': "Third generation moths emerge",
                               'status': "The third generation of CM usually starts around mid-August and adults may continue to fly until September 10.  In normal years not enough heat units will accumulate in the fall to allow third generation eggs to hatch.",
                               'management': "Traditionally, NY growers have stopped spraying for CM from Aug. 15-30.  In most years it is not necessary to apply control sprays against the third generation, particularly when sprays have been timed properly against the first two generations.  However, in some orchards, sprays may be necessary at this time to control OFM in high-pressure orchards.",
                               'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=24&GrowthStageID=12" } } }