disease_cycle_management = { 
"dormant": {
	'cycle': "Shoot blight, rootstock blight and cankers contribute to overwintering inoculum. ", 
    'management': "Reduce primary inoculum sources by pruning out cankered limbs and branches during the dormant season. Prune and remove shoots killed by fire blight and cankered limbs. Cut shoots out 12 inches below the infected margin. Keep records of the fire blight history in your orchard blocks. Learn how to identify fire blight cankers. Scout orchards for active, oozing fire blight cankers." },

"early": { 
	'cycle': "Oozing cankers put bloom at risk. ",
	'management': "Learn how to identify fire blight cankers. Scout orchard blocks for active, oozing fire blight cankers. Determine and record each orchard blocks' fire blight history to use in the blossom blight tool, as shown: <br>--No fire blight in your neighborhood last year. <br>--Fire blight occured in your neighborhood last year (default). <br>--Fire blight is now active in your neighborhood. <br>At silver tip apply a copper spray to clean up inoculum on tree surfaces. <br>At bloom, apples and pears become susceptible to blossom blight infections. <br><a href='http://newatest.nrcc.cornell.edu/appfbnotes_pop.htm' target='_blank'>First blossom open</a> usually occurs once 230 to 440 degree days (DD) base 43F have accumulated from January 1. You are approximately xxxdddiffxxx degree days from first blossom open. The critical period for protection is during bloom, which is when blossom blight risk is calculated." },

"inseason": {
	'cycle': "Blossom blight. ",
	'management': "Blossom blight risk predictions begin at <a href='http://newatest.nrcc.cornell.edu/appfbnotes_pop.htm' target='_blank'>first blossom open</a>, which usually occurs once 230 to 440 degree days (DD) base 43F have accumulated from January 1. If bloom in your orchard has not yet occurred, continue to check fire blight risk predictions and monitor bloom daily. Infection cannot occur without open blossoms. <br>Most serious fire blight epidemics begin with infection during bloom. Certain antibiotics can effectively protect against blossom infections when applied shortly before or immediately after they occur. The Cougarblight and Infection Potential risk levels are based on the principle that <br>(a) a certain number of heat units must accumulate during bloom for a threshold level of inoculum to be reached; <br>(b) a wetting event is necessary after this point to wash the bacteria to their infection sites; and <br>(c) the average temperature is above 60F. <br><table><tr style='background-color:#00CC00;'><th>Low risk</th><td>If none of these conditions is met during bloom, risk is <b>'Low'</b> and bactericides are not needed.</td></tr> <tr style='background-color:yellow;'><th>Caution or Moderate risk</th><td>If only the heat units are met during bloom, Cougarblight risk is <b>'Caution'</b> and it is advisable to watch the forecast closely for continuing warm weather and rain. <br>If only one of these conditions is met during bloom, Infection Potential risk is <b>'Moderate'</b> and it is advisable to watch the forecast closely for continuing warm weather and rain.</td></tr> <tr style='background-color:#FF6600;'><th>High risk</th><td>If two conditions are met during bloom, risk is <b>'High'</b> and forecasted wetting events should be carefully considered and a bactericide applied just before (or after) a rain.</td></tr> <tr style='background-color:#FF0000;'><th>Extreme or Infection risk</th> <td>If all three conditions are met, risk is <b>'Extreme'</b> or <b>'Infection'</b> and an antibiotic should be applied just before (or after) a rain.</td></tr></table>" },

"late": {
	'cycle': "Shoot blight, rootstock blight and canker infections contribute to disease spread and overwintering inoculum.",
     'management': "The period of high risk of blossom blight infection (20% bloom to 80% petal fall) has passed. If bloom is still present in your orchard, recalculate blossom blight risk by entering a first blossom open date. 1-2 weeks after petal fall, scout orchards for shoot blight, including rootstock sucker infections. Prune and remove infected shoots 12 inches below the infected margin during cool, dry weather. Pruning is particularly useful when blossom blight is well controlled and canker blight infections are thus the main source of inoculum for disease spread during the summer. Pruning can help limit disease spread, but will be most effective if practiced rigorously during the first few weeks after bloom; pruning will do little to slow disease spread if delayed until a large number of infections are visible. Routine use of antibiotics to prevent shoot blight spread during the summer is not effective or recommended. However, applications to protect new wounds immediately following a hailstorm can be very beneficial; check current recommendations."},

"fall": { 
	'cycle': "Shoot blight, rootstock blight and canker infections contribute to overwintering inoculum.",
     'management': "Scout orchards for shoot blight and rootstock blight. Prune and remove infected shoots and limbs 12 inches below the infected margin during cool, dry weather. Routine use of antibiotics to prevent shoot blight spread during the summer is not effective or recommended. However, applications to protect new wounds immediately following a hailstorm can be very beneficial; check current recommendations. Learn how to identify fire blight cankers. Scout orchards for active, oozing fire blight cankers." },
}