pest_status_management = { 
'pest_name': "Obliquebanded Leafroller",
'biofix_phenology': "First Trap Catch",
'biofix_abbrev': "oblr",
'basetemp': 43,

'pre_biofix': {
0: { 'ddlo':   0, 'ddhi': 250, 'altref': ["Dormant","Silver_Tip","Green_Tip","Half-Inch_Green","Tight_Cluster"],
							   'stage': "Overwintering larvae emerge", 
                               'status': "Overwintering <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/oblr/oblr.asp' target='_blank'>OBLR</a> larvae usually begin to emerge at the half-inch green growth stage.", 
                               'management': "No control measures are recommended at this time because most overwintering larvae have not yet emerged and will escape residual effectiveness of most insecticides." },
1: { 'ddlo': 251, 'ddhi': 349, 'altref': "Pink_Bud",
					           'stage': "Overwintering larval emergence almost over", 
                               'status': "Almost all overwintering larvae have emerged by the end of the pink bud stage.",
                               'management': "Overwintering larvae can be <a href='http://www.nysipm.cornell.edu/publications/apple_man/files/oblr3.pdf' target='_blank'>sampled</a> starting at the pink bud stage. A control spray can be applied during pink if larval populations exceed threshold levels.",
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
2: { 'ddlo': 350, 'ddhi': 500, 'altref': "Bloom",
						       'stage': "Overwintering larvae complete emergence",
                               'status': "Emergence of overwintering larvae is completed by the end of bloom",
                               'management': "Larval populations can be monitored by sampling blossom clusters. <a href='http://www.nysipm.cornell.edu/publications/apple_man/files/oblr3.pdf' target='_blank'>Click here</a> for sampling form.  Bt can be applied during bloom if larval populations exceed threshold levels.  All other insecticides cannot be applied until petal fall." },
3: { 'ddlo': 501, 'ddhi': 750, 'altref': "Petal_Fall",
					           'stage': "Overwintering larvae feeding",
                               'status': "<a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/oblr/oblr_fig3.asp' target='_blank'>Overwintering larvae</a> begin to feed on developing fruit and may cause some <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/oblr/oblr_fig4.asp' target='_blank'>damage</a>, although many fruit damaged at this time will drop off of the tree prematurely and not result in fruit damage at harvest.  Fruit damage from overwintering larvae is usually relatively low (less than 5 percent).",
                               'management': "Apply a control spray as soon as possible after petal fall to control overwintering larvae.  Research studies in NY have shown that applying a single insecticide spray at either pink or petal fall is just as effective in controlling overwintering larvae and early fruit damage as applying two sprays (at pink and petal fall).  Most currently available insecticides usually only reduce fruit damage from overwintering larvae by 40-60%.  Usually, fruit injury from overwintering larvae is less than 5% at harvest, even if no control sprays are applied.  Some studies have shown that controlling the overwintering larvae will reduce numbers of subsequent summer generation larvae and the average damage from the summer generation is usually lower than when control of overwintering larvae is omitted, particularly when large areas are treated.  Plum curculio may also be a problem in some orchards at this time and many materials that are effective against OBLR do not control this pest effectively. Pheromone traps to monitor the first flight of OBLR should be deployed by June 1st.",
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
4: { 'ddlo': 751, 'ddhi':1212, 'altref': "Post_Petal_Fall",
						       'stage': "First generation moths emerge",
                               'status': "<a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/oblr/oblr_fig1.asp' target='_blank'>Adult</a> flight begins.  In western NY first flight usually occurs around the middle of June.",
                               'management': "No control measures are recommended for adults.  Sprays to control summer generation of larvae are timed to coincide with the first hatch of eggs." } },
'post_biofix': {  
0: { 'ddlo':   0, 'ddhi': 100, 'altref': ["Post_0"],
							   'stage': "First generation moths flying and laying eggs",
                               'status': "Adults are still flying and laying <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/oblr/oblr_fig2.asp' target='_blank'>eggs</a>. Peak flight usually occurs within two weeks after the first adult is captured.",
                               'management': "No control measures are recommended at this time, because eggs have not yet begun to hatch. It is also too early to sample growing terminals to estimate larval populations." },
1: { 'ddlo': 101, 'ddhi': 449, 'altref': ["Post_1"],
							   'stage': "Peak moth flight, first egg hatch",
                               'status': "First hatch of summer OBLR eggs.  Adult catches in pheromone traps are near peak numbers.",
                               'management': "In order to verify model predictions, monitor growing terminals at 600-700 DD base 43F after biofix to check for the detection of the first summer generation larvae.   It is too early now to monitor populations of summer larvae at this time to determine if control sprays are necessary because most eggs will hatch later during the summer.  However, applying protective sprays with the first spray timed to coincide with the first hatch of larvae at approximately 350 DD base 43F after biofix followed by a second spray 10-14 days later are recommended in orchards that have had a past history of severe OBLR fruit damage or if populations of overwintering larvae were high.",
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
2: { 'ddlo': 450, 'ddhi': 599, 'altref': ["Post_2"],
							   'stage': "Peak egg hatch", 
                               'status': "Peak egg hatch, approximately 25% of total eggs have hatched by this time.",
                               'management': "It is still too early to sample for larvae in orchards that are being monitored to determine if summer control sprays are necessary because most egg masses still have not hatched.  Residual activity from an initial protective spray will control hatching larvae at this time." }, 
3: { 'ddlo': 600, 'ddhi': 699, 'altref': ["Post_3"],
							   'stage': "Egg hatch half over",
                               'status': "Approximately half of egg masses have hatched at this time.", 
                               'management': "Summer larvae can be sampled in growing terminals at this time to determine if a control spray is necessary. (<a href='http://www.nysipm.cornell.edu/publications/apple_man/files/oblr3.pdf' target='_blank'>Click here</a> for Sampling Protocols).  Sampling at this time can determine the need for additional sprays if an initial protective spray has already been applied.",
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
4: { 'ddlo': 700, 'ddhi': 850, 'altref': ["Post_4"],
							   'stage': "Larvae damaging fruit",
                               'status': "<a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/oblr/oblr_fig6.asp' target='_blank'>Fruit damage</a> is starting now, and will rapidly increase if larvae have not been effectively controlled.", 
                               'management': "The second summer control spray should provide adequate control of the later hatching summer generation larvae.  A third spray may be recommended if earlier materials have not been effective and larvae populations are extremely high." ,
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
5: { 'ddlo': 851, 'ddhi':1334, 'altref': ["Post_5"],
							   'stage': "First adult flight almost over, large larvae",
                               'status': "Flight of the first summer generation of adults is now diminishing.", 
                               'management': "It is too late to apply control sprays for the summer generation of OBLR larvae.  If larvae have not been controlled by earlier treatments, fruit injury will already be substantial and remaining older larvae are less susceptible to insecticides."},
6: { 'ddlo':1335, 'ddhi':1741, 'altref': ["Post_6"],
							   'stage': "Second flight moths emerge",
                               'status': "Second flight of OBLR is now beginning.", 
                               'management': "Control of the second generation of OBLR larvae is not usually necessary if the first summer generation of larvae has been effectively controlled or if populations are low." },
7: { 'ddlo':1742, 'ddhi':2126, 'altref': ["Post_7"],
							   'stage': "Peak flight second generation moths",
                               'status': "Peak flight of the second generation of adults.  Larvae from the second generation are hatching and small larvae may be present.  These larvae will feed for a short period of time and then go into overwintering habitats.", 
                               'management': "Although no formal sampling protocols have been developed, fruit clusters can be inspected to determine if small larvae are present and fresh feeding has occurred.  If it appears that second generation larvae and fruit damage are prevalent, a treatment of any material that is effective against the first summer generation of larvae can be applied." ,
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
8: { 'ddlo':2127, 'ddhi':2575, 'altref': ["Post_8"],
							   'stage': "Second moth flight declining",
                               'status': "Flight of the second generation is diminishing.", 
                               'management': "It is too late to apply control sprays for the second generation of OBLR larvae at this time because many larvae have already stopped feeding and have gone into overwintering quarters." },
9: { 'ddlo':2576, 'ddhi':9999, 'altref': ["Post_9"],
							   'stage': "Moth flight over, larvae hibernation",
                               'status': "OBLR season is over.",
                               'management': "Control sprays are no longer necessary." } } }