pest_status_management = { 
'pest_name': "Phomopsis",
'messages': {
'page_dormant': { 'stages': ["dormant"],
                  'management': "Dead and diseased canes, arms, and pruning stubs should be pruned out to reduce inoculum. Dead canes and stubs can produce extremely high levels of Phomopsis spores over several years. In particular, growers seeking to minimize fungicide use should pay strict attention to the removal of infected wood from within the canopy."},
'get_ready':    { 'stages': ["early","bud_swell"],
                  'management': "In vineyards with heavy inoculum pressure (hedged vines, dead canes, pruning stubs), prepare to apply protective sprays as early as 1 inch shoot growth, ahead of infection events. Damage to shoots, leaves, clusters and fruit caused by Phomopsis is more prevalent when inoculum is allowed to build up on dead canes or pruning stubs in the vines and when early-season sprays for this disease are omitted."},
'start':        { 'stages': ["1in_shoot","3in_shoot"],
                  'management': "The early spray at around 3 inch shoot growth, when clusters first become visible, is most important for controlling rachis infections, shoot infections that serve as future sources of inoculum, and infections that move from berry stems into the fruit. A minimal spray program should include at least one application during this period to protect against infection events, especially in blocks with a history of Phomopsis and on <a href='http://newa.nrcc.cornell.edu/grapes/phomopsis_var_table.html' target='_blank'>highly susceptible varieties</a>."},
'peak_1':       { 'stages': ["10in_shoot","imm_prebloom"],
                  'management': "At this time, protect against rachis infections and prevent infections that move from berry stems into the fruit later in the season. Monitor infection events and maintain fungicide protection on <a href='http://newa.nrcc.cornell.edu/grapes/phomopsis_var_table.html' target='_blank'>susceptible varieties</a>, in hedged vineyards, or locations with a history of Phomopsis."},
'peak_2':       { 'stages': ["bloom","1st_postbloom"],
                  'management': "Fruit infections can occur from early bloom through the postbloom period, then remain dormant until severe fruit rot develops at harvest. Rachises also remain susceptible during this period. Monitor infection events and maintain fungicide protection, especially on <a href='http://newa.nrcc.cornell.edu/grapes/phomopsis_var_table.html' target='_blank'>susceptible varieties</a>, in hedged vineyards, or locations with a history of Phomopsis."},
'maintenance':  { 'stages': ["2nd_postbloom","bunch_closure"],
                  'management': "If the post bloom through pea-sized berry period is wet, you are growing <a href='http://newa.nrcc.cornell.edu/grapes/phomopsis_var_table.html' target='_blank'>susceptible varieties</a>, in hedged vineyards, or locations with a history of Phomopsis, and fungicidal protection is absent, then a final spray for Phomopsis may be needed. The risk of infection is low once berries become about pea-sized (~1/4 inch diam), since inoculum becomes scarce, unless the weather has been very dry for several weeks beforehand. Thus, Phomopsis sprays from this point forward probably are unnecessary in most vineyards."},
'passed':       { 'stages': ["veraison","harvest"],
                  'management': "Phomopsis fungicide sprays are no longer necessary."} } }