pest_status_management = { 
'pest_name': "Powdery Mildew",
'messages': {
'page_dormant': { 'stages': ["dormant"],
                  'management': "Powdery mildew overwinters as tiny fruiting bodies (cleistothecia) that form during late summer and autumn. The ascospores (primary inoculum) are discharged between bud break and bloom to initiate the disease. Therefore, disease pressure will be higher where powdery mildew control lapsed the previous summer, particularly if autumn weather was warm and frost-free. Sprays during the first few weeks of shoot growth in the following year are thus very important in controlling primary infections from the increased amount of overwintering inoculum."},
'get_ready':    { 'stages': ["early","bud_swell"],
                  'management': "A lot of powdery mildew the previous year =   More primary inoculum to cause infections this spring = A lot more secondary spores available when fruit are susceptible =   High disease pressure which can overwhelm your fungicide program. The model logs potential primary infection events. Be mindful of how much powdery mildew developed last year and, if there was a lot, keep track of the primary infection events logged and be prepared to protect vines in the early shoot growth stages (3-5 inch), particularly <a href='../grapes/pmildew_var_table.html' target='_blank'>highly susceptible varieties</a>."},
'start':        { 'stages': ["1in_shoot","3in_shoot"],
                  'management': "A lot of powdery mildew the previous year =  More primary inoculum to cause infections this spring. The model logs potential primary infection events. Consider <a href='http://ipmguidelines.org/grapes/' target='_blank'>early sprays</a> near the 3-5 inch shoot growth stage for <a href='../grapes/pmildew_var_table.html' target='_blank'>highly susceptible <i>V. vinifera</i> and hybrid varieties</a> in vineyards where powdery mildew was prevalent 30 days before leaf fall last year."},
'peak_1':       { 'stages': ["10in_shoot","imm_prebloom"],
                  'management': "A lot of powdery mildew the previous year =   More primary inoculum to cause infections this spring. The model logs potential primary infection events. <b>CAUTION:</b> Prolonged cloud cover (lack of sunshine), high RH (>60%) and warm (63-86F) weather significantly increases the risk of powdery mildew infections. <br>Do not delay sprays beyond the 10 inch shoot growth stage for <a href='../grapes/pmildew_var_table.html' target='_blank'>highly susceptible <i>V. vinifera</i> and hybrid varieties</a>. <br>Do not delay sprays beyond the immediate prebloom stage on Concord and other <a href='../grapes/pmildew_var_table.html' target='_blank'>moderately to slightly susceptible varieties</a>. <br>Fruit is extremely susceptible to powdery mildew from immediate prebloom through fruit set. This is the most critical period to protect from fruit infections. Management programs should be at their peak, emphasizing the use of <a href='http://ipmguidelines.org/grapes/' target='_blank'>effective fungicides</a>, full rates, appropriate spray intervals, and superior spray coverage."},
'peak_2':       { 'stages': ["bloom","1st_postbloom"],
                  'management': "The explosive secondary infection season has begun. Infections are favored when prolonged cloud cover, humid (>60% RH), <a href='../grapes/pm_table.html' target='_blank'>warm (63-86F)</a> days and nights prevail. <b>This is the most critical time of the year for control of cluster infections on all varieties.</b> <br>Management programs should be at their peak, emphasizing the use of <a href='http://ipmguidelines.org/grapes/' target='_blank'>effective fungicides</a>, full rates, appropriate spray intervals, and superior spray coverage."},
'maintenance':  { 'stages': ["2nd_postbloom","bunch_closure"],
                  'management': "Berries become highly resistant to infection about 2 weeks (Concord) to 4 weeks (<i>V. vinifera</i>) after fruit set. However, continued foliar protection on Concord (and other American varieties) may be beneficial for heavily-cropped vines or poor-ripening conditions. From this point on, management programs will depend on <a href='../grapes/pmildew_var_table.html' target='_blank'>varietal susceptibility</a>, market destination, ripening conditions, and conducive weather. Secondary infections are favored when cloudy, humid (85% RH), <a href='../grapes/pm_table.html' target='_blank'>warm (63-86F)</a> days and nights prevail; rain is not required for infection. <br>For <a href='../grapes/pmildew_var_table.html' target='_blank'><i>V. vinifera</i> and highly susceptible hybrid</a>, <a href='http://ipmguidelines.org/grapes/' target='_blank'>maintain protection</a> of the clusters through bunch closure to preclude bunch rots and/or wine spoilage. Maintain an appropriate level of control during the midsummer period to avoid poor ripening, premature defoliation, and reduced winter hardiness. <br>Concord fruit become resistant and no longer require protection. However, in conducive years, foliar protection on Concord and <a href='../grapes/pmildew_var_table.html' target='_blank'>other moderately susceptible varieties</a> may be beneficial for heavily-cropped vines or poor-ripening conditions. <br>Good management will decrease disease pressure next year, by limiting overwintering primary inoculum, reducing spring infection potential, and lowering the risk of cluster infections."},
'passed':       { 'stages': ["veraison","harvest"],
                  'management': "In some years and on some varieties, powdery mildew may cause defoliation after harvest. Premature defoliation, especially in early harvested varieties or winter-tender <i>V. vinifera</i>, predisposes the vines to winter injury and reduces bud survival the following spring. Good control of powdery mildew through August greatly reduces disease pressure during the early portion of the following year."} } }