pest_status_management = { 
'pest_name': "San Jose Scale",
'biofix_phenology': "First Trap Catch",
'biofix_abbrev': None,
'biofix2_phenology': "Second Generation Emergence",
'biofix2_abbrev': None,
'basetemp': 50,

'pre_biofix': {
0: { 'ddlo':   0, 'ddhi': 217, 'altref': ["Dormant","Silver_Tip","Green_Tip","Half-Inch_Green","Tight_Cluster","Pink_Bud"],
							   'stage': "Overwintering as immatures under scale covers", 
                               'status': "No <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/sjs/sjs.asp' target='_blank'>SJS</a> flight is expected.", 
                               'management': "An application of dormant oil or an effective insecticide directed against the overwintering immatures under the <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/sjs/sjs_fig6.asp' target='_blank'>'black cap' scale covers</a> on trunks and scaffold branches between the half-inch green and tight cluster stages will effectively reduce the potential for serious infestations later in the season. Prebloom sprays more effective if applied dilute, at high volume; for severe infestations, follow up with summer applications of appropriate materials. Suggested action threshold: 3-6 encrusted areas per tree.",
                               'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=39&GrowthStageID=7" },
1: { 'ddlo': 218, 'ddhi': 340, 'altref': ["Bloom","Petal_Fall","Post_Petal_Fall"],
							   'stage': "1st generation adults emerge", 
                               'status': "Predicted first catch of <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/sjs/sjs_fig1.asp' target='_blank'>SJS adults</a> from the overwintering generation is expected after approximately 200-350 degree days (base 50F) have accumulated.",
                               'management': "Pheromone traps should be in place in time to record the first adult male flight." } },
'post_biofix': {  
0: { 'ddlo':   0, 'ddhi': 259, 'altref': ['Post_0'],
							   'stage': "1st generation crawlers developing",
                               'status': "First generation crawlers are produced beneath female scale covers during this period.",
                               'management': "If monitoring for crawlers, double-sided sticky tape traps should be placed around tree limbs at this time."},
1: { 'ddlo': 260, 'ddhi': 360, 'altref': ["Post_1"],
							   'stage': "1st generation crawlers emerge, migrate and begin feeding", 
                               'status': "First generation crawler emergence is predicted to occur approximately 260-360 DD (base 50F) after biofix, or 500 DD after March 1. Prepare to start monitoring for the crawlers or, if SJS was a serious problem last season, begin treatment.",
                               'management': "Apply 2 sprays, against the first and peak (7-10 days later) activity of <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/sjs/sjs_fig5.asp' target='_blank'>crawlers</a> of the 1st generation.  If monitoring, suggested action threshold is 1-2 crawlers/trap (sticky tape trap around limb).",
                               'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=39&GrowthStageID=12" },
2: { 'ddlo': 361, 'ddhi': 778, 'altref': ["Post_2"],
							   'stage': "1st generation 'white caps'",
                               'status': "Nymphs secrete new scale covers and develop into adults.", 
                               'management': "Pheromone traps should be in place in time to record the second adult male flight."}, 
3: { 'ddlo': 779, 'ddhi':1057, 'altref': ["Post_3"],
							   'stage': "2nd generation adults emerge",
                               'status': "First catch of SJS 2nd generation adults usually occurs sometime around mid-July.", 
                               'management': "Note date of first capture of 2nd generation adults, to obtain biofix for predicting 2nd generation crawler emergence." } },
'post_biofix2': {  
0: { 'ddlo':   0, 'ddhi': 349, 'altref': ["Post_4"],
							   'stage': "2nd generation crawlers developing",
                               'status': "Second generation crawler emergence has not yet occurred.", 
                               'management': "No control measures are recommended at this time and it is too early to sample for second generation larvae." },
1: { 'ddlo': 350, 'ddhi': 450, 'altref': ["Post_5"],
							   'stage': "2nd generation crawlers emerge",
                               'status': "Second generation crawler emergence is predicted to occur approximately 350-450 DD (base 50F) after biofix of the 2nd generation, or 1450 DD after March 1. If SJS was a serious problem last season, begin treatment.", 
                               'management': "Apply 2 sprays, against the first and peak (7-10 days later) activity of <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/sjs/sjs_fig5.asp' target='_blank'>crawlers</a> of the 2nd generation.  If monitoring, suggested action threshold is 1-2 crawlers/trap (sticky tape trap around limb).",
							   'pesticide_link': "http://treefruitipm.info/PesticidesForPest.aspx?PestID=39&GrowthStageID=12"},
2: { 'ddlo': 451, 'ddhi':9999, 'altref': ["Post_6"],
							   'stage': "1st instar scales under 'black caps' on trunk and branches",
                               'status': "San Jose Scale management decisions are over for the season.", 
                               'management': "Control sprays are no longer needed." } } }