pest_status_management = { 
'pest_name': "Spotted Tentiform Leafminer",
'biofix_phenology': "First Trap Catch",
'biofix_abbrev': None,
'biofix2_phenology': "Second Generation Flight Start",
'biofix2_abbrev': 'stlm',
'basetemp': 43,

'pre_biofix': {
0: { 'ddlo':   0, 'ddhi': 114, 'altref': ["Dormant","Silver_Tip","Green_Tip"],
							   'stage': "Pupae overwintering", 
                               'status': "The first flight of <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/stlm/stlm.asp' target='_blank'>STLM</a> adults has not yet started.  First flight begins after 115 to 215 degree days have accumulated. Pheromone traps should be deployed for monitoring the adults.", 
                               'management': "No control measures are recommended at this time.  Pheromone traps for monitoring STLM adults should be deployed at the green-tip bud stage." },
1: { 'ddlo': 115, 'ddhi': 274, 'altref': ["Half-Inch_Green","Tight_Cluster","Pink_Bud"],
							   'stage': "Moth flight beginning", 
                               'status': "The first flight of STLM <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/stlm/stlm_fig1.asp' target='_blank'>adults</a> usually begins between the green tip and half-inch bud stage.",
                               'management': "No control measures are recommended against adults.  It is very difficult to predict larval infestation levels from adult catches in pheromone traps.  Sometimes catches may be very high, but if conditions are unfavorable for oviposition during the flight in the spring (cold, rainy, and windy weather), very few eggs are laid and subsequent larval populations will be low." } },
'post_biofix': {  
0: { 'ddlo':   0, 'ddhi': 266, 'altref': ['Post_0'],
							   'stage': "Moths flying and beginning to lay eggs",
                               'status': "First <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/stlm/stlm_fig2.asp' target='_blank'>eggs</a> are usually laid at early tight cluster on the first leaves to unfold. First generation adult STLM are actively flying and laying eggs from tight cluster until the end of the pink bud statge.",
                               'management': "No control should be applied at this time and it is too early to sample for STLM eggs because oviposition has just begun. No insecticidal control sprays are recommended against STLM adults.  Control sprays targeted against younger instars of larvae (<a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/stlm/stlm_fig4.asp' target='_blank'>sap feeding stages</a>) feeding in the leaves can be applied either at pink or shortly after petal fall.  To determine whether or not pink sprays are necessary, sample clusters for eggs at <a href='http://ipmguidelines.org/TreeFruits/content/CH07/default-4.asp' target='_blank'>pink</a> and if necessary apply insecticides before bloom.",
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
1: { 'ddlo': 267, 'ddhi': 547, 'altref': ["Post_1"],
							   'stage': "Eggs hatching and sap feeding mines appearing", 
                               'status': "The first generation of STLM eggs begin to hatch during bloom and hatch is almost completed by petal fall.  ",
                               'management': "Insecticides that are effective against STLM mines cannot be applied during bloom and it is too early to sample sap feeding mines because hatch will not be completed unitl the petal fall stage."},
2: { 'ddlo': 548, 'ddhi': 777, 'altref': ["Post_2"],
							   'stage': "Both sap and tissue feeding mines are present",
                               'status': "The first flight of STLM and egg hatch is over. Both younger sap feeding and older tissue mines are present.", 
                               'management': "If control sprays were not applied at the pink bud stage, sample fruit clusters for first generation <a href='http://nysipm.cornell.edu/factsheets/treefruit/pests/stlm/stlm_fig4.asp' target='_blank'>sap feeding mines</a> after <a href='http://ipmguidelines.org/TreeFruits/content/CH07/default-6.asp' target='_blank'>petal fall</a>, and apply insecticides if necessary.  Many other pests may also be active at this time, internal Lepidoptera, plum curculio, sawfly, and the first generation of white apple leafhoppers.  Compounds that are effective against STLM larvae may not provide adequate control of these other pests." ,
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" }, 
3: { 'ddlo': 778, 'ddhi': 977, 'altref': ["Post_3"],
							   'stage': "2nd generation of moths emerging",
                               'status': "The second flight of STLM is beginning", 
                               'management': "Pheromone traps should be checked frequently to determine the biofix of the second flight.  Usually, no treatments will be required to control the second generation of larvae if populations of first generation larvae are low or if effective control sprays have been applied against this generation. No control sprays are necessary against adults.  Monitoring and control sprays should be targeted for the appearance of sap feeding mines from the second generation of larvae on the undersides of terminal leaves." } },
'post_biofix2': {  
0: { 'ddlo':   0, 'ddhi': 689, 'altref': ["Post_4"],
							   'stage': "2nd generation moths flying & laying eggs",
                               'status': "Eggs from second generation of STLM will begin to hatch when 690 to 840 degree days have accumulated since the second generation flight start.", 
                               'management': "No control measures are recommended at this time and it is too early to sample for second generation larvae." },
1: { 'ddlo': 690, 'ddhi': 839, 'altref': ["Post_5"],
							   'stage': "2nd generation eggs hatch & sap feeding mines appear",
                               'status': "Small sap feeding mines are beginning to appear on the undersides of the terminal leaves.  Approximately 10% of eggs laid by the second generation of STLM have hatched.", 
                               'management': "Sample terminal leaves for sap feeding STLM <a href='http://ipmguidelines.org/TreeFruits/content/CH07/default-9.asp' target='_blank'>mines<a>.  Apply a control spray if mine counts are above the recommended threshold.  It may be necessary to sample again later at 840 DD post-biofix if initial counts of mines are in region 2 of the chart.",
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
2: { 'ddlo': 840, 'ddhi':1180, 'altref': ["Post_6"],
							   'stage': "2nd generation eggs & sap and tissue feeding mines on leaves",
                               'status': " Egg hatch is almost complete and numbers of sap feeding mines will not increase. Number of older tissue feeding mines are increasing and older larvae are beginning to pupate.", 
                               'management': "Sample terminal leaves for sap feeding STLM <a href='http://ipmguidelines.org/TreeFruits/content/CH07/default-9.asp' target='_blank'>mines</a> for the second time at 840 DD if no control spray were recommended after the first sample at 640 DD.  Apply a control spray if mine counts are above the recommended threshold.  It may be necessary to sample a third time at 1150 DD if mine counts are in region 2 of the sampling form.",
                               'pesticide_link': "http://www.dec.ny.gov/nyspad/products?0" },
3: { 'ddlo':1181, 'ddhi':1567, 'altref': ["Post_7"],
							   'stage': "2nd generation mines and pupae in leaves; 3rd generation of moths flying",
                               'status': "Second generation tissue feeding mines and pupae are present. The third generation of moths will emerage in mid to late August and continue to fly and lay eggs in September.", 
                               'management': "It is too late to apply a control spray for STLM.  Most second generation larvae are too old to control and maximum leaf damage from mines of this generation has already occurred.  Usually, mines from the third generation of STLM appear late in the season (late August and September), and late season leaf damage from these larvae will not affect the trees.  Also, late season sprays may disrupt the effects of parasites and predators, which reduce numbers of overwintering pupae that will emerge next season." },
4: { 'ddlo':1568, 'ddhi':2165, 'altref': ["Post_8"],
							   'stage': "3rd generation moths flying but starting to decline",
                               'status': "Eggs laid by this generation of moths will not affect the health of the tree or fruits, as leaf function is already declining because of normal senescence.", 
                               'management': "No further control measures are recommended at this time." },
5: { 'ddlo':2166, 'ddhi':9999, 'altref': ["Post_9"],
							   'stage': "Moth flight is over",
                               'status': "STLM seasonal activity has finished.", 
                               'management': "Control sprays are no longer necessary." } } }