disease_cycle_management = { 
"early": {
	'cycle': "The apple scab fungus overwinters in infected leaves that have fallen to the ground. In these leaves, from autumn to early spring, the fungus mates, resulting in the development of what are termed ascospores, which cause primary infections. <br>Ascospores mature as spring progresses with a few ascospores usually maturing by bud break (green tip). The proportion of ascospores maturing progresses slowly until about the tight cluster stage of blossom development.",
	'management': "Season-long control is difficult if primary infections develop. Even moderate numbers of primary lesions can produce an extremely large population of secondary spores, conidia, requiring an intensive fungicide program to protect fruit throughout the summer. Conversely, good control of primary infections allows use of fungicides to be reduced or omitted during the summer, once ascospores have been depleted and fruit become less susceptible. <br>Control of primary infections has traditionally begun at or shortly after green tip, when the first ascospores become mature. The percentage of spores that are mature at this time is low, and the actual number of mature spores may be insignificant during the early stages of bud development if very little leaf scab developed the previous year." },

"inseason": {
	'cycle': "Ascospores mature as spring progresses with a few ascospores usually maturing by bud break (green tip). The proportion of ascospores maturing progresses slowly until about the tight cluster stage of blossom development. From tight cluster through bloom the percentage of mature ascospores rapidly increases with most ascospores matured by the end of bloom. <br>Unusual weather conditions may contribute to significant ascospore discharges earlier than or later than the model predicts. <br>Mature ascospores begin to discharge into the air within 30 minutes during periods of rain. When rainfall begins at night, discharge may be delayed until daybreak. Ascospore discharge usually peaks from pink through bloom, and nearly all ascospores have been discharged within 1 or 2 weeks after petal fall.",
	'management': "Effective fungicide programs should be timed around infection events shown in the table above, inoculum availability, cultivar susceptibility, and specific characteristics of the available fungicides. <br>Season-long control is difficult if primary infections develop. Good control of primary infections allows use of fungicides to be reduced or omitted during the summer, once ascospores have been depleted and fruit become less susceptible. Control of primary infections has traditionally begun at or shortly after green tip, when the first ascospores become mature. <br>After ascospores are depleted, continue to monitor scab infection events and maintain spray coverage accordingly for at least two more weeks. Scout orchards for primary scab infections after this time. <br>Both ascospores and conidia infect at similar rates when tested at equivalent temperatures and inoculum doses. Therefore, the infection events tabulated can be used for both primary and secondary infections. <br>Standard apple cultivars vary widely in their susceptibility to scab, which will influence the intensity of the control program necessary for a particular variety. <br>Apple scab fungicides control disease in different ways. Protectants must be applied before infection occurs. Those with post-infection activity must be applied within a narrow time after the beginning of an infection event. Some fungicides can suppress production of conidia from recent infections or established lesions, presymptom and postsymptom activity, respectively. Understanding these activities and knowing which fungicides exhibit them is important for maximizing the efficiency of a fungicide program." },

"secondary": {
	'cycle': "Secondary scab season. Keep in mind that inoculum doses are generally much lower for ascospores than for conidia, so the severity of infection can be greater if secondary inoculum is present, as compared with early in the season, when only ascospores are present.",
     'management': "Season-long control is difficult if primary infections develop, which produce secondary inoculum placing orchards at risk for secondary, conidial infections. <br>After ascospores are depleted, continue to monitor scab infection events and maintain spray coverage accordingly for at least two more weeks, or until xxx14daysxxx. Scout orchards for primary scab infections after this time. <br>Focus on protecting trees from secondary scab infections as needed, based on infection events. <br>Both ascospores and conidia infect at similar rates when tested at equivalent temperatures and inoculum doses. Therefore, the infection events tabulated can be used for both primary and secondary infections. <br>Apple scab fungicides control disease in different ways. Protectants must be applied before infection occurs. Those with post-infection activity must be applied within a narrow time after the beginning of an infection event. Some fungicides can suppress production of conidia from recent infections or established lesions, presymptom and postsymptom activity, respectively. Understanding these activities and knowing which fungicides exhibit them is important for maximizing the efficiency of a fungicide program."},

"overwinter": { 
	'cycle': "The apple scab fungus overwinters in infected leaves that have fallen to the ground. In these leaves, from autumn to early spring, the fungus mates, resulting in the development of what are termed ascospores.",
     'management': "<b>Low inoculum orchards</b> - determining the potential ascospore dose (PAD) count. Before leaf drop in autumn, the number of apple scab infected leaves are counted on 600 shoots. If less than 53 leaves per 600 shoots have apple scab, the green tip spray can be omitted in most years. Never omit the green tip spray in orchards where PAD counts weren't done the previous autumn. <br><b>High carry-over inoculum is a major contributor to scab epidemics.</b> Orchard sanitation methods can reduce carry-over inoculum in orchards by 70&percnt; or more by using any one of the following methods: <br>(a) Apply 40 lb/A of urea fertilizer (mixed in 100 gal of water/A) sometime after winter but before bud break. Urea softens senescent and fallen leaves and stimulates their microbial breakdown, promoting faster removal by earthworms that feed on them. It may also directly suppress ascospore formation. Treat the entire orchard, including the ground cover in the row middles. Apply the spray using either an air blast sprayer with the upper nozzles turned off or a boom sprayer set up to spray both under the trees and the row middles. Reduce subsequent nitrogen fertilizer rates by the amount of N applied under the drip line of the tree rows. Ignore the amount of N applied to the row middles, as the ground cover will use this. Repeat after harvest during leaf drop following seasons with severe scab outbreaks. <br>(b) Shred overwintering leaves using a flail mower set low enough to contact the fallen leaves. Leaves must be raked or blown from under trees, or mower must be offset to reach them. Shredded leaves decay more quickly, and flail-mowing leaves in spring disorients many of the leaf pieces so they eject ascospores toward the soil instead of up into the air. Prunings can be chopped at the same time. However, the low mower settings required to effectively shred leaves may leave row middles so denuded as to be slippery or muddy at the time when early fungicide sprays are needed. <br>(c) Apply 2&frac12; ton/A of lime in early winter after leaves have fallen from trees. Lime raises the pH of fallen leaves enough to increase the rate of microbial breakdown of the fallen leaves." },
}