pest_status_management = { 
'pest_name': "Clubroot",
'time_concern': ["Pre plant","Seedling through harvest","Post harvest"],
'keychar_oc': "<i>Plasmodiophora brassicae </i><p><b>Key Characteristics: </b>",
'keychar_o':  "Clubroot attacks all brassicas. The fungus overwinters in the soil and causes large spindle-shaped galls to appear on roots; yellowing and wilting occurs on the aboveground portion. Surviving plants are stunted due to impaired root function. Although other pests cause similar symptoms (e.g. root maggot), abnormally large roots are diagnostic. Low pH favors this disease.</p>",
'keychar_c':  "Large spindle-shaped galls appear on roots; yellowing and wilting occurs on the above ground portion.</p>",
'help_links': [("Cornell fact sheet on Clubroot", "http://vegetablemdonline.ppath.cornell.edu/factsheets/Crucifers_Clubroot.htm")],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "<i>Plasmodiophora brassicae </i>may be in crop debris or soil as resting spores.",
                           'management_oc': "Seeds and transplants - This pathogen is not seed-borne. Affected transplants produced off farm are the main source of the pathogen. Purchase transplants certified to be free of clubroot. <p>Site selection - Land should be selected that has not produced cruciferous crops for seven years or longer. Avoid fields where crucifer plant waste has been discarded.  Avoid fields with potential for pathogen movement from an infested field in runoff or irrigation water or on animal feet.</p>",                          
                           'management_o': "Crop Rotation - Since resting clubroot spores can contaminate the soil for 7 to 10 years or longer, a minimum crop rotation of 7 years is recommended if clubroot has been observed. Rotate away from all cruciferous plants (see Appendix 1) including cover crops. During rotation, manage weeds (see specific weeds below). The high pH required to control this fungus may adversely affect other crops in the rotation.  Clubroot has declined more quickly where tomato, cucumber, snap bean and buckwheat are grown. Growing aromatic perennial herbs such as summer savory, peppermint, or garden thyme has provided effective control of clubroot when grown for 2 to 3 consecutive years. <ul><li><a href='http://calshort-lamp.cit.cornell.edu/bjorkman/covercrops/index.php' target='_blank'>Cover crops information</a> <li><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/McNabRotations.htm' target='_blank'>Crop rotation information</a></ul> <p>Some preliminary work indicates that incorporation of meadowfoam seedmeal can reduce incidence of clubroot while also suppressing some weeds. Once present on a farm, clubroot can be managed by adjusting the soil pH to 7.2 with ground limestone prior to the production season. Add limestone annually unless the soil pH exceeds 7.5.  This high pH may adversely affect other crops in the rotation.</p>",
                           'management_c': "Crop rotation - The clubbed roots disintegrate and contaminate the soil with resting spores for seven to ten years or longer. Minimum seven years without crucifer crops or cruciferous weeds which include wild mustard and wild radish. Avoid fields where crucifer plant waste has been dumped. <p>If treatment is necessary, apply Blocker at transplanting as a transplant solution, a band application or a broadcast application.</p> <p><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/FungicideResistance.html' target='_blank'>General guidelines for managing fungicide resistance.</a></p>"},
'Seedling through harvest': { 'datelo': (4,15,0), 'datehi': (11,14,23),
                           'status': "<i>Plasmodiophora brassicae </i>may be present in the field in infected plants.",
                           'management_oc': "",
                           'management_o': "Scouting - Examine transplants for symptoms; do not plant any if symptoms are seen. Examine fields weekly, especially during cool, wet conditions. Examine the roots for symptoms on cruciferous plants and weeds seen wilting in the heat of the day including weeds along field edges. Thresholds are not available for organic production, but record occurrence for field records.",
                           'management_c': "Scouting - Examine seedbeds and production fields weekly for clubroot. Record the occurrence of clubroot. No thresholds are available."},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "<i>Plasmodiophora brassicae </i>may be in crop debris",
                           'management_oc': "",
                           'management_o': "No management provided.",
                           'management_c': "Soil management - Adjust soil pH to 6.8 with ground limestone to manage clubroot. Broadcast and incorporate at least 1500 pounds per acre of hydrated lime at least six weeks before planting. The final pH should be about 7.2. Hydrated lime should be added each year unless the soil pH exceeds 7.5."}
} }