pest_status_management = { 
'pest_name': "Black Leg, Seed Decay",
'time_concern': ["Pre plant","Seedling through harvest","Post harvest"],
'keychar_oc': "<i>Phoma lingam </i> <p><b>Key Characteristics: </b>",
'keychar_o':  "Not available.</p>",
'keychar_c':  "Black leg causes dark, sunken cankers at the base of the stem or light brown circular leaf spots. Look for black, speck size, pycnidia on cankers and spots.</p>",
'help_links': [("Penn State fact sheet on crucifer disease ID","http://www.ppath.cas.psu.edu/EXTENSION/VEGDIS/VegDisases/Identification_files/crucifers.html")],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "<i>Phoma lingam </i>may be in crop debris or seed.",
                           'management_oc': "",
                           'management_o': "No organic techniques are available.",
                           'management_c': "<b>Crop rotation</b> - Minimum four years without crucifer crops or cruciferous weeds which include wild radish and wild mustard. Avoid fields where crucifer plant waste has been dumped. <ul><li><a href='http://calshort-lamp.cit.cornell.edu/bjorkman/covercrops/index.php' target='_blank'>Why use cover crops in vegetable rotations?</a> <li><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/McNabRotations.htm' target='_blank'>Do rotations matter within disease management programs?</a></ul> <p>Land for seedbeds and late-season crops should not be near those fields used for early-season crops to minimize the movement of pathogens from old to young plants.</p> <p><b>Seed selection/treatment</b> - Plant seed treated with captan or thiram. Hot water treatment kills the black leg fungi and is necessary only on infected seed lots. Soak broccoli, cauliflower, and Chinese cabbage seed for 20 minutes in 122&deg;F water, 25 minutes for Brussels sprouts and cabbage. This treatment may reduce germination and vigor and may not eradicate the disease from heavily infested lots.</p>"},
'Seedling through harvest': { 'datelo': (4,15,0), 'datehi': (11,14,23),
                           'status': "<i>Phoma lingam </i>may be present in the field.",
                           'management_oc': "",
                           'management_o': "No organic techniques are available.",
                           'management_c': "<b>Scouting/thresholds</b> - Record the occurrence and severity of black leg. No thresholds are available. <p>If treatment is necessary, apply Rovral 4F or Cabrio EG. <a href='http://vegcrops.cudss.org/PDS.aspx?PestID=25&Conventional=True' target='_blank'>Pesticide information</a>. </p> <p><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/FungicideResistance.html' target='_blank'>General guidelines for managing fungicide resistance</a></p>"},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "<i>Phoma lingam </i>may be in crop debris.",
                           'management_oc': "",
                           'management_o': "No organic techniques are available.",
                           'management_c': "Crop debris should be destroyed as soon as possible to remove this source of disease for other plantings and to initiate decomposition."},
} }