pest_status_management = { 
'pest_name': "Galinsoga",
'time_concern': ["Pre plant","Seedling","Mature Head","Post harvest"],
'keychar_oc': "Hairy galinsoga - <i>Galinsoga ciliata</i>, Small flowered galinsoga - <i>G. parviflora</i><p><b>Key Characteristics: </b>",
'keychar_o':  "",
'keychar_c':  "Annual flowering broadleaf weed. Produces 40,000 seeds per plant. Flowers 24-60 days after emergence, seeds released 11-14 days later. Grows best in full sun. Sensitive to frost and drought. Disperses short distances by wind. Few seeds survive in soil more than 3 years.</p>",
'help_links': [("Cornell Weed Ecology website",
				"http://weedecology.css.cornell.edu/"),
				("Virginia Tech fact sheet",  "http://www.ppws.vt.edu/scott/weed_id/galci.htm"),
				("Ontario, Canada fact sheet", "http://www.omafra.gov.on.ca/english/crops/facts/ontweeds/hairy_galinsoga.htm")],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "Galinsoga is overwintering in the soil as seed.",
                           'management_oc': "",
                           'management_o': "",
                           'management_c': "Scouting - Weeds may be unevenly distributed over a field. Localized areas of severe weed infestations or atypical conditions such as poorly drained areas, high spots, and field edges, may be recorded on a weed map. A weed map should be on file for each field. Make a rough sketch of the field, including landmarks, boundaries, crop row direction, compass directions, roads, planting date, date of map preparation, and any other important details. The following information should be indicated on the map: weed species, weed size, density of each species, and distribution of weeds.<p>Scout fields two to three weeks after direct seeding/transplanting to evaluate the success of the current season's program and at or near harvest to help predict weed control practices that will be necessary for the following year.</p><p><a href='http://nysipm.cornell.edu/scouting/weed_assmt.pdf' target='_blank'>Cornell Weed Assessment list</a><br/><a href='http://www.gov.mb.ca/agriculture/crops/weeds/fab01s00.html' target='_blank'>Manitoba, Canada weed scouting guide</a></p><p>Non-herbicide galinsoga management practices include:<ul><li>moldboard plow to move seed deep where it is less likely to germinate</li><li>plant to a competitive summer cover crop</li><li>rotate field into sod</li><li>summer fallow period with cultivation at 3-4 week intervals</li></ul> </p><p>If spraying is necessary choose from:<ul><li>Goal 2xl - PreTransplant</li><li>Goaltender -  PreTransplant</li><li>Dual Magnum (cabbage only) -  PreTransplant, PostTransplant,  PostEmergence</li><li>Stinger 3EC PostEmergence/li></ul></p>"},
'Seedling/transplant':  { 'datelo': (4,15,0), 'datehi': (5,14,23),
                           'status': "Galinsoga seeds are germinating and the weed is emerging; peak emergence in late spring and early summer.",
                           'management_oc': "",
                           'management_o': "",
                           'management_c': "Non-herbicide galinsoga management practices include:<ul><li>make the last cultivation before planting shallow in order to avoid bringing up new seeds</li><li>moldboard plow to move seed deep where it is less likely to germinate</li><li>plant to a competitive summer cover crop</li><li>rotate field into sod</li><li>summer fallow period with cultivation at 3-4 week intervals</li></ul> <p>If spraying is necessary choose from:<ul><li>Goal 2xl - PreTransplant</li><li>Goaltender -  PreTransplant</li><li>Dual Magnum (cabbage only) -  PreTransplant, PostTransplant,  PostEmergence</li><li>Stinger 3EC PostEmergence</li></ul></p>"},
'Through mature head': { 'datelo': (5,15,0), 'datehi': (11,14,23),
                           'status': "Galinsoga seeds are germinating and the weed is emerging; emergence ceases at frost.",
                           'management_oc': "",
                           'management_o': "",
                           'management_c': "Scouting - Weeds may be unevenly distributed over a field. Localized areas of severe weed infestations or atypical conditions such as poorly drained areas, high spots, and field edges, may be recorded on a weed map. A weed map should be on file for each field. Make a rough sketch of the field, including landmarks, boundaries, crop row direction, compass directions, roads, planting date, date of map preparation, and any other important details. The following information should be indicated on the map: weed species, weed size, density of each species, and distribution of weeds.<p>Scout fields two to three weeks after direct seeding/transplanting to evaluate the success of the current season's program and at or near harvest to help predict weed control practices that will be necessary for the following year.</p><p><a href='http://nysipm.cornell.edu/scouting/weed_assmt.pdf' target='_blank'>Cornell Weed Assessment list</a><br/><a href='http://www.gov.mb.ca/agriculture/crops/weeds/fab01s00.html' target='_blank'>Manitoba, Canada weed scouting guide</a></p><p>Non-herbicide galinsoga management practices include:<ul><li>make the last cultivation before planting shallow in order to avoid bringing up new seeds</li><li>moldboard plow to move seed deep where it is less likely to germinate</li><li>plant to a competitive summer cover crop</li><li>rotate field into sod</li><li>summer fallow period with cultivation at 3-4 week intervals</li></ul> </p>"},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "Galinsoga seeds have fallen from plants onto soil",
                           'management_oc': "",
                           'management_o': "",
                           'management_c': "Non-herbicide galinsoga management practices include:<ul><li>clean up galinsoga after harvest to reduce seed bank</li><li>moldboard plow to move seed deep where it is less likely to germinate</li></ul> </p>"}
} }