disease_vars = {#'alfalfa-weevil':     ['temp'],
				'apple-scab':         ['temp', 'lwet', 'prcp'],
				'apple-ascospore':    ['temp', 'prcp'],
				'apple-cougarblight': ['temp'],
				'apple-sootyblotch':  ['temp', 'lwet', 'prcp'],
				'apple-cm':           ['temp'],
				'apple-ofm':          ['temp'],
				'apple-oblr':         ['temp'],
				'apple-pc':           ['temp'],
				'apple-stlm':         ['temp'],
				'apple-maggot':       ['temp'],
				'apple-pet':          ['temp', 'wspd', 'rhum', 'srad'],
				'grape-powmildew':    ['temp', 'prcp'],
				'grape-phomopsis':    ['temp', 'lwet', 'prcp'],
				'grape-blackrot':     ['temp', 'lwet', 'prcp'],
				'grape-dowmildew':    ['temp', 'lwet', 'prcp', 'rhum'],
				'grape-berrymoth':	  ['temp'],
				'onion-blight':       ['temp', 'prcp', 'rhum'],
				'onion-modblight':    ['temp', 'prcp', 'rhum'],
				'onion-alternaria':   ['temp', 'prcp', 'rhum'],
				'onion-botrytis':     ['temp', 'prcp', 'rhum'],
				'onion-dowmildew':    ['temp', 'prcp', 'rhum'],
				'onion-maggot':       ['temp'],
				'potato-lateblight':  ['temp', 'prcp', 'rhum'],
				'potato-earlyblight': ['temp'],
				'cabbage-maggot':     ['temp'],
				'corn-swilt':         ['temp'],
				'tomato-tomcast':     ['temp', 'lwet', 'prcp'],
				'tomato-lateblight':  ['temp', 'prcp', 'rhum'],
				'wheat-scab': 		  ['temp', 'prcp', 'rhum'] }