# Title of pest model, basic url, and list of required variables (list least likely to be present first to improve speed)
pest_models = [ ('Apple Scab',                  'newaModel/apple_scab',              ['temp']),
				('Fire Blight',                 'newaModel/fire_blight',             ['temp']),
				('Sooty Blotch/Flyspeck',       'newaModel/sooty_blotch',            ['eslw', 'temp', 'prcp']),
				('Leaf Wetness Events',         'newaDisease/apple_lw',              ['eslw', 'temp']),
				('Spotted Tentiform Leafminer', 'newaModel/apple_pest/apple-stlm',   ['temp']),
				('Oriental Fruit Moth',         'newaModel/apple_pest/apple-ofm',    ['temp']),
				('Codling Moth',                'newaModel/apple_pest/apple-cm',     ['temp']),
				('Plum Curculio',               'newaModel/apple_pest/apple-pc',     ['temp']),
				('Obliquebanded Leafroller',    'newaModel/apple_pest/apple-oblr',   ['temp']),
				('Apple Maggot',                'newaModel/apple_pest/apple-maggot', ['temp']),
				('Grape Diseases',              'newaModel/grape_dis',               ['eslw', 'temp', 'prcp']),
				('Grapevine Downy Mildew',      'newaModel/dmcast',                  ['lwet', 'rhum', 'temp', 'prcp']),
				('Grape Berry Moth',            'newaModel/berry_moth',	             ['temp']),
#				('Alfalfa Weevil', 	            'newaDisease/alf_weev',              ['temp']),
				('Cabbage Maggot',              'newaDisease/cabbage_maggot',        ['temp']),
				('Onion Maggot',                'newaDisease/onion_maggot',          ['temp']),
				('Onion Disease Forecast',      'newaDisease/onion_dis',             ['rhum', 'temp', 'prcp']),
				('Onion Disease Log',           'newaDisease/onion_onlog',           ['rhum', 'temp', 'prcp']),
				('Onion Blight Alert',          'newaDisease/onion_sbalog',          ['rhum', 'temp', 'prcp']),
				('Onion Modified Blight Alert', 'newaDisease/onion_smbalog',         ['rhum', 'temp', 'prcp']),
				('Potato Early Blight',         'newaDisease/potato_pdays',          ['temp']),
				('Potato Late Blight Blitecast','newaDisease/potato_lb',             ['rhum', 'temp', 'prcp']),
				('Tomato Diseases, Tomcast',    'newaDisease/tomato_for',            ['eslw', 'temp', 'prcp']),
				('Late Blight Simcast',         'newaDisease/potato_simcast',        ['rhum', 'temp', 'prcp'])
				]