pest_status_management = { 
'pest_name': "Sugar Beet Cyst Nematode",
'time_concern': ["Pre plant","Seedling through harvest","Post harvest"],
'keychar_oc': "<i>Heterodera schachtii</i><p><b>Key Characteristics: </b>",
'keychar_o':  "Symptoms include stunted plants and small, loose heads. Roots branch excessively. The appearance of pearly-white, tan, or reddish bodies of female nematodes is common on the root surface. The leathery, lemon-shaped cysts are approximately 0.7 mm in length and can survive up to 7 to 8 years in soil in the absence of host plants.</p>",
'keychar_c':  "Symptoms include stunted plants that result in small, loose heads. Roots branch excessively. The appearance of pearly-white, tan, or reddish bodies of female nematodes is common on the root surface.</p>",
'help_links': [("Sugar beet cyst nematode fact sheet", "http://vegetablemdonline.ppath.cornell.edu/factsheets/SugarBeetNem.htm")],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "<i>Heterodera schachtii </i>may be in soil or crop or cruciferous weed debris.",
                           'management_oc': "",                          
                           'management_o': "Crop Rotation - Maintain a minimum of 3 years without brassica crops (especially beet), brassica cover crops, or susceptible weeds. Rotations with non-hosts such as alfalfa and sweet corn are better than rotations with soybean or wheat. <p><ul><li><a href='http://calshort-lamp.cit.cornell.edu/bjorkman/covercrops/index.php' target='_blank'>Why use cover crops in vegetable rotations?</a> <li><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/McNabRotations.htm' target='_blank'>Crop roatation information</a> <li><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/Crop_sequences.htm' target='_blank'>Cropping sequences and root health</a></ul></p> <p>Site selection - Choose soil with good tilth and no recent history of beet or cabbage production. Analyze for the presence of the nematode by collecting a representative soil sample. <ul><li><a href='http://www.nysipm.cornell.edu/grantspgm/projects/proj06/veg/gugino.asp' target='_blank'>On-farm method of assessing nematode population</a> <li><a href='http://www.nysaes.cornell.edu/recommends/Nemasoilsample.pdf' target='_blank'>&quot;How to&quot; instructions for soil sampling for nematode bioassays</a></ul></p> <p>Cultural practices - Nematodes only move a few inches per year on their own and are spread primarily by equipment and transplants moved from contaminated soils.  Cyst nematodes can be present for several seasons at numbers low enough to not cause symptoms, thus spread may occur from a field before infestations are noticed.</p> <p>Weeds - Control alternate weed hosts in the cabbage and beet families such as lambsquarters, shepherds purse, wild radish, mustard and dock.</p>",
                           'management_c': "Crop rotation - Minimum three years without crucifer crops, beets, or cruciferous weeds which include wild radish and wild mustard. Rotations with nonhosts such as alfalfa and sweet corn are better than rotations with soybean or wheat. <p>Site selection - Choose soil in good tilth, without recent history of beet or cabbage production and/or analyze for the presence of the nematode by collecting a representative soil sample.</p> <p>Sanitation - Control weeds in the cabbage and beet families, such as lambsquarter, because they are also hosts to this nematode.</p>"},
'Seedling through harvest': { 'datelo': (4,15,0), 'datehi': (11,14,23),
                           'status': "<i>Heterodera schachtii </i>may infect plants.",
                           'management_oc': "",
                           'management_o': "Scouting - Look for the presence of swollen immature females attached to the surface of roots about 4 to 6 weeks after planting.  Dig the plants carefully to prevent jarring the females loose from the roots. Threshold: 6 to 9 eggs per cubic centimeter. Contact the Cornell Plant Disease Diagnostic Clinic or the Michigan State University Diagnostic Services to determine egg numbers. <ul><li><a href='http://plantclinic.cornell.edu/' target='_blank'>Cornell Plant Disease Diagnostic Clinic</a> <li><a href='http://www.pestid.msu.edu/Default.aspx?tabid=109' target='_blank'>Michigan State Plant Parasitic Nematodes</a></ul> <p>If spraying is necessary only Nema-Q is labeled and approved.</p>",
                           'management_c': " Scouting - Record the occurrence of sugar beet cyst nematodes. The damaging level is six to nine eggs per cubic centimeter (cc) of soil."},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "<i>Heterodera schachtii </i>may be in soil or crop or cruciferous weed debris.",
                           'management_oc': "",
                           'management_o': "Postharvest - Destroy crop debris as soon as possible after harvest to stop further development on remaining roots and to initiate decomposition.",
                           'management_c': "Postharvest - Crop debris should be destroyed as soon as possible after harvest to stop further development of the nematode on roots and to initiate decomposition."}
} }