pest_status_management = { 
'pest_name': "Damping Off and Wire Stem",
'time_concern': ["Pre plant","Seedling through harvest","Post harvest"],
'keychar_oc': "<i>Pythium ultimum</i> and Wire stem caused by <i>Rhizoctonia solani.</i><p><b>Key Characteristics: </b>",
'keychar_o':  "Pythium can cause damping-off and seedling death in young plants. Depending on the time of onset, infection by <i>Rhizoctonia</i> most often is expressed as damping-off in seedlings, but can cause wirestem in young plants, bottom rot in midseason, and head rot as the heads mature. Wirestem is characterized by water-soaked or darkened constrictions on the stem near the soil line in young plants. It can also provide entry points along the soil line for secondary bacterial rot which ultimately rot the head. If plants survive, growth is stunted and the stem is black or brown. Bottom rot causes leaf margins to discolor. Plants may wilt, and gray-brown lesions may appear on the stem and lower side of leaves at the soil surface. Head rot causes a dark decay of the stem and base of heads, as well as spotted and wilted leaves at the center of the head.</p> <p><b>Relative risk: </b>This disease is most often seen in transplant production especially in cold greenhouses and wet soil.</p>",
'keychar_c':  "Depending on the time of onset, infection by these organisms may appear as seed decay, seedling damping-off, or root rot. Rhizoctonia infections may also result in wire-stem symptoms as well as foliar blight symptoms on top of the head and the outer leaves. Leaf margins discolor red to purple, and leaves die beginning at the tip and progressing toward the stem. Plants may wilt, and gray-brown lesions may appear on stems and lower leaves at the soil surface.</p> <p><b>Relative risk: </b>This disease is most often seen in transplant production especially in cold greenhouses and wet soil.</p>",
'help_links': [("Ontario, Canada fact sheet on crucifer fungal diseases", "http://www.omafra.gov.on.ca/english/crops/facts/85-043.htm")],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "<i>Pythium ultimum </i>and <i>Rhizoctonia solani. </i>may be in soil or crop or cruciferous weed debris.",
                           'management_oc': "",                          
                           'management_o': "Crop Rotation - Both Pythium and Rhizoctonia are common soil pathogens with a wide host range. For severe outbreaks, a minimum rotation of 3 years out of all vegetables may be necessary. A rotation with grain crops can reduce inoculum.  Potatoes, beans, lettuce, and cabbage are the most important host crops but other hosts include broccoli, kale, radish, turnip, carrot, cress, cucumber, eggplant, pepper, and tomato.<ul><li><a href='http://calshort-lamp.cit.cornell.edu/bjorkman/covercrops/index.php' target='_blank'>Cover crops information</a> <li><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/McNabRotations.htm' target='_blank'>Crop rotation information</a></ul> <p>Site selection - Plant on well-drained and light-textured soils.  Greenhouse sanitation is critical.</p> <p>Seed selection - These pathogens are generally not seed-borne; however hot water treatment could reduce the risk of pathogens present on the outside of the seed.</p>",
                           'management_c': " Crop rotation - Minimum three years out of vegetables. <p>Site selection - Plant on well-drained and light-textured soils.</p> <p>Seed treatment - Plant disease-free seed that has been treated with fungicides (Apron+Maxim).</p>"},
'Seedling through harvest': { 'datelo': (4,15,0), 'datehi': (11,14,23),
                           'status': "<i>Pythium ultimum </i>and <i>Rhizoctonia solani. </i>may infect plants.",
                           'management_oc': "",
                           'management_o': "Scouting - Remove flats with signs of damping off.  Disease spread will slow when the flats are allowed to dry out.  Field scouting and threshold information has not been established for organic production. <p>If spraying is necessary choose from among: Actino-Iron, Actinovate AG, Kodiak, MycoStop Mix, Mycostop, RootShield WP, RootShield Granules, T-22 HC.</p> <p>Transplants - Avoid overwatering in the greenhouse. Sanitize greenhouses and equipment where transplants are produced. Use the optimal seed planting depth, plant density, nutrition, growing medium, and watering methods. Do not plant transplants too deep.</p>",
                           'management_c': "Scouting - Record the occurrence and severity of root rot. No thresholds have been established. <p>If spraying is necessary choose from among: Quadris F, Endura, Ridomil Gold SL, Blocker 4, Cabrio.</p> <p><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/FungicideResistance.html' target='_blank'>General guidelines for managing fungicide resistance</a></p>"},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "<i>Pythium ultimum </i>and <i>Rhizoctonia solani. </i>may be in soil or crop or cruciferous weed debris.",
                           'management_oc': "",
                           'management_o': "Postharvest - Crop debris should be destroyed as soon as possible to remove inoculum for future plantings and to initiate decomposition. <p>Weeds - Several common weeds host Pythium species including wild-proso millet, shattercane, barnyardgrass, and quackgrass. Weeds hosting Rhizoctonia include annual bluegrass, barnyardgrass, common lambsquarters, common milkweed, common purslane, common ragweed, corn chamomile, eastern black medic, black nightshade, field bindweed, field horsetail, goosegrass, green foxtail, Italian ryegrass, kochia, large crabgrass, mouseear chickweed, perennial sowthistle, prickly lettuce, prostrate pigweed, redroot pigweed, shepherd&#39;s-purse, tumble pigweed, Venice mallow, wild buckwheat, wild mustard, and witchgrass.</p>",
                           'management_c': "Postharvest - If tillage system in use permits, crop debris should be destroyed as soon as possible to remove this source of inoculum for other plantings and to initiate decomposition."}
} }