pest_status_management = { 
'pest_name': "Cabbage Looper",
'time_concern': ["Pre plant","Seedling through mature head","Post harvest"],
'keychar_oc': "<i>Trichoplusia ni</i><p><b>Key Characteristics: </b>",
'keychar_o':  "Because adults are nocturnal, the gray, non-descript moths are seldom seen.  White, round eggs, the size of a pinhead, are laid on the undersides of leaves. Larvae are up to 1&frac12; inches long, light green with white strips along each side of the body and can be distinguished by the looping movement they use to travel.</p> <p><b>Relative risk:</b> Because cabbage looper does not overwinter in New York, infestations are variable and depend on weather fronts to move them in from areas further south.  Larvae feed on leaves and heads causing plant stress and contamination at harvest.</p>",
'keychar_c':  "White, round eggs the size of a pinhead are laid on the undersides of leaves. Larvae are light green with white strips along each side of the body. They may reach 1&frac12; inches in length.</p> <p><b>Relative risk:</b> Because cabbage looper does not overwinter in New York, infestations are variable and depend on weather fronts to move them in from areas further south.  Larvae feed on leaves and heads causing plant stress and contamination at harvest.</p>",
'help_links': [],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "<i>Trichoplusia ni </i>is arriving on transplants or migrating from more southern regions.",
                           'management_oc': "",                          
                           'management_o': "Resistant varieites - No resistant varieties are available. However, varieties do have different levels of susceptibility and should be scouted separately. <p>Crop barriers - Isolating the crop through growing tall barriers of a non-host crop such as sorghum Sudan or sweet corn, can reduce infestations from these low flying pests in small isolated plantings.</p> <p>Weeds - Cabbage looper feeds on many different weed species which may support the buildup of populations.</p>",
                           'management_c': "Resistant varieties - No resistant varieties are available. However, varieties have different susceptibilities and should be scouted separately."},
'Seedling through mature head': { 'datelo': (4,15,0), 'datehi': (11,14,23),
                           'status': "<i>Trichoplusia ni </i>can damage plants and reproduce on the crop.",
                           'management_oc': "",
                           'management_o': "Scouting - Use the same method and frequency as for diamondback moth, imported cabbageworm, thrips and aphids.  Examine plants for eggs and larvae from at least 10 randomly selected sites throughout the field. For fields less than five acres, examine two plants per site (20 plants total); for five to 25 acres, examine four plants per site (40 plants total); for each additional five acres, examine four plants at an additional site. Thresholds are in <strike>Table 14.5.1</strike> for products marked with a &quot;+&quot; in the pesticides list below. These thresholds were developed with conventional insecticides and may need to be adjusted for organic insecticides. <p>If spraying is necessary choose from: Agree WG*+, XenTari+, Biobit HP+, Deliver, Dipel DF+, Javelin WG+, Mycotrol O, Naturalis L, Entrust+,Azadirachtin, Aza-Direct, AzaGuard, Azahar, AzaMax, Ecozin Plus*, Neemix 4.5*, PyGanic EC 5.0, Garlic Barrier AG,Saf-T-Side, SuffOil-X, SucraShield.</p> <p>Transplants - Watch for CL if transplants were grown in southern states. </p> <p>Weeds - Cabbage looper feeds on many different weed species which may support the buildup of populations.</p> <p>Natural enemies - Natural enemies may help to control CL populations. Use Cornell's Guide to Natural Enemies in North America or Natural Enemies of Vegetable Insect Pests to identify natural enemies.</p> <ul><li><a href='http://www.biocontrol.entomology.cornell.edu/index.php' target='_blank'>More information on these natural enemies</a></ul>",
                           'management_c': "Scouting - Sample simultaneously with diamondback moth and imported cabbageworm. Examine plants at a minimum of ten randomly selected sites throughout the field. For five acres or less, examine two plants per site (20 plants total); for five to 25 acres, examine four plants per site (40 plants total); for each additional five acres, examine four plants at an additional site. Thresholds are given in <a href='http://www.nysaes.cals.cornell.edu/recommends/15cabbage.html#table15.4' target='_blank'>Table 15.6.1</a>. <p>If spraying is necessary choose from: XenTari, Agree WG, Biobit XL, Dipel DF, Javelin, *Baythroid XL, *Brigade 2EC, *Hero, *&#10013;&#916;Coragen, *&#10013;Voliam Xpress, *Proclaim 5WDG,  *Asana XL, *Leverage 2.7, Avaunt, *Warrior II with Zeon Technology, *Lannate LV, *Perm-Up 3.2 EC, Radiant SC, Entrust, *Mustang MAX.</p> <p>Insecticide resistance management - A classification of insecticides based on their mode of action is available in pdf format. This guide can be used to help avoid or delay the development of insecticide resistance, as well as manage populations that have developed resistance to a particular insecticide.<br /> <ul><li><a href='http://nysipm.cornell.edu/publications/res_mgmt/files/res_mgmt.pdf' target='_blank'>Classification of insecticides and acaracides for resistance management</a></li></ul></p> <p>Natural Enemies - Natural enemies may help to control CL populations. They can be preserved by using insecticides that are less harmful to them. Hyposoter exigua, Litomastix, Geocoris spp., nuclear polyhedrosis virus, Podisus maculiventris, Chrysoperla, Trichogramma pretiosum, Trichogramma ostriniae, Trichogramma exiguum, Bacillus thuringiensis var. kurstaki, Granulosis virus, Perillus bioculatus, Cotesia marginiventrus, Copidosoma floridanum, Phryxe vulgaris, Voria ruralis, Wintemia quadripustulata, Nomuraea rileyi, Vairimorpha necatrix.</p><ul><li><a href='http://www.biocontrol.entomology.cornell.edu/index.php' target='_blank'>More information on these natural enemies</a><li><a href='http://nativeplants.msu.edu/' target='_blank'>Enhancing Beneficial Insects with Native Plants (Michigan State)</a><li><a href='http://www.attra.org/attra-pub/farmscape.html' target='_blank'>Farmscaping to enhance biological control (ATTRA publication)</a></ul>"},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "<i>Trichoplusia ni </i>is NOT overwintering in plant debris and soil.",
                           'management_oc': "",
                           'management_o': "Postharvest - Plow down crop residues after harvest to destroy existing eggs and larvae which could build populations over the season.",
                           'management_c': "No management recommendations."}
} }