pest_status_management = { 
'pest_name': "Sclerotinia White Mold",
'time_concern': ["Pre plant","Seedling through harvest","Post harvest"],
'keychar_oc': "<i>Sclerotinia sclerotiorum</i><p><b>Key Characteristics: </b>",
'keychar_o':  "Sclerotinia white mold causes bleached, water-soaked spots that enlarge to irregular-shaped areas followed by rot on stems or entire head. Tissue becomes covered with fluffy, white fungal growth often producing black seed-like sclerotia the size of pea seeds, which remain in the soil and serve as inoculum for future years.</p> <p><b>Relative risk:  </b>White mold occurs annually on cabbage and Brussels sprouts but is uncommon on broccoli and cauliflower.</p>",
'keychar_c':  "Depending on the time of onset, infection by these organisms may appear as seed decay, seedling damping-off, or root rot. Rhizoctonia infections may also result in wire-stem symptoms as well as foliar blight symptoms on top of the head and the outer leaves. Leaf margins discolor red to purple, and leaves die beginning at the tip and progressing toward the stem. Plants may wilt, and gray-brown lesions may appear on stem and lower leaves at the soil surface.</p> <p><b>Relative risk:  </b>White mold occurs annually on cabbage and Brussels sprouts but is uncommon on broccoli and cauliflower.</p>", 'help_links': [("Sclerotinia fact sheet", "http://vegetablemdonline.ppath.cornell.edu/factsheets/Crucifers_Sclerotinia.htm"), ("Dillard lab Sclerotinia information", "http://www.nysaes.cornell.edu/pp/faculty/dillard/Sclerotinia.pdf")],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "<i>Sclerotinia sclerotiorum </i>may be in soil or crop or cruciferous weed debris.",
                           'management_oc': "",                          
                           'management_o': "Crop Rotation - The long list of alternate hosts makes the use of crop rotation a difficult method to control this long-lived fungus. Work to prevent inoculum buildup by maintaining a minimum of 3 years without brassica crops. In severe cases, 5 years may be necessary.  Other susceptible host crops include soybeans, beans, peas, tomatoes, eggplants, peppers, lettuce, carrots, and cucurbits. Rotations with non-hosts such as grains, sweet corn and sorghum are effective as long as brassica weed hosts are controlled.<ul><li><a href='http://calshort-lamp.cit.cornell.edu/bjorkman/covercrops/index.php' target='_blank'>Why use cover crops in vegetable rotations?</a> <li><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/McNabRotations.htm' target='_blank'>Crop roatation information</a></ul> <p>Site selection - Select a well drained field with good air flow to dry leaves and soil quickly. Growing on raised beds enhances air movement and soil drying for better disease control. Avoid fields with previous populations of alternate host weeds (see Weed section below). White mold spores are locally airborne. Plant upwind from previously infected fields.  Avoid fields where brassica plant waste has been discarded.</p> <p>Planting - Avoid over crowding and orient rows with the prevailing winds to quickly dry leaves and soil.</p> <p>Weeds - Maintain fields free of the many weeds that serve as an alternate host to Sclerotinia such as wild mustard, wild radish, shepherd&#39;s purse, ragweed, velvetleaf, dandelion, common lambsquarters, prickly lettuce, eastern black nightshade, field pennycress, redroot pigweed, common ragweed, shattercane, annual sowthistle, common sunflower, common chickweed, green foxtail, and Canada thistle.</p>",
                           'management_c': "Crop rotation - Minimum three years without crucifer crops, susceptible weeds (ragweed and velvetleaf), or other susceptible crops, such as beans and carrots. Rotations with nonhosts such as grains and sweet corn are recommended. Avoid fields where crucifer plant waste has been dumped. <p>Site selection - Select fields with good air and water drainage. Avoid weedy fields.</p>"},
'Seedling through harvest': { 'datelo': (4,15,0), 'datehi': (11,14,23),
                           'status': "<i>Sclerotinia sclerotiorum </i>may infect plants.",
                           'management_oc': "",
                           'management_o': "Scouting - Scout field prior to harvest to determine if a post-harvest treatment of Contans&reg; is necessary to reduce overwintering inoculum.  Record white mold incidence and severity in all fields. <p>If spraying is necessary choose from among: Actino-Iron, Actinovate AG, Contans WG, Cueva Fungicide Concentrate.</p>",
                           'management_c': "Scouting - Record the occurrence and severity of Sclerotinia white mold. No thresholds have been established. <p>If spraying is necessary choose from among: Endura 70 WDG, Contans WG.</p> <p><a href='http://vegetablemdonline.ppath.cornell.edu/NewsArticles/FungicideResistance.html' target='_blank'>General guidelines for managing fungicide resistance</a></p> <p>Fieldwork - Avoid mechanical damage to plants. Avoid weedy fields infested with ragweed and velvetleaf.</p>"},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "<i>Sclerotinia sclerotiorum </i>may be in soil or crop or cruciferous weed debris.",
                           'management_oc': "",
                           'management_o': "Harvest - Bruises and other mechanical injuries provide avenues of infection in storage. <p>Postharvest - Destroy crop debris by plowing or disking as soon as possible after harvest to manage this source of inoculum for future plantings and to initiate decomposition. If practical, dispose of infected debris off the farm. Composting waste will not effectively reduce inoculum, which even survives animal digestive tracts. If fields are badly infested, rotate to grains and treat with Contans&reg; immediately after harvest. Correct application of Contans&reg; is critical; see application details.</p>",
                           'management_c': "Postharvest - Crop debris should be destroyed as soon as possible after harvest to remove this source of disease for other plantings and to initiate decomposition."}
} }