pest_status_management = { 
'pest_name': "Nightshades",
'time_concern': ["Pre plant","Seedling","Mature Head","Post harvest"],
'keychar_oc': "Black nightshade - <i>Solanum nigrum</i>, Eastern black nightshade - <i>S. ptycanthum</i>, Hairy nightshade - <i>S. sarrachoides</i><p><b>Key Characteristics: </b>",
'keychar_o':  "",
'keychar_c':  "Annual broadleaf weeds in the <i>Solonacaae</i> family. Seeds can survive up to 39 years if undisturbed but decline in viability in tilled soil. Sensitive to light frost. Not drought tolerant. </p>",
'help_links': [("Cornell Weed Ecology website",
				"http://weedecology.css.cornell.edu/"),
				("Virginia Tech fact sheets (black nightshade)", "http://www.ppws.vt.edu/scott/weed_id/solni.htm"),
				("Virginia Tech fact sheets (eastern black nightshade)", "http://www.ppws.vt.edu/scott/weed_id/solpt.htm"),
				("Ontario, Canada fact sheets (eastern black nighshade)", "http://www.omafra.gov.on.ca/english/crops/facts/ontweeds/eblack_nightshade.htm"),
				("Ontario, Canada fact sheets (hairy nightshade)", "http://www.omafra.gov.on.ca/english/crops/facts/ontweeds/hairy_nightshade.htm")],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "Nightshades are overwintering as seed in soil.",
                           'management_oc': "",
                           'management_o': "",
                           'management_c': "Scouting - Weeds may be unevenly distributed over a field. Localized areas of severe weed infestations or atypical conditions such as poorly drained areas, high spots, and field edges, may be recorded on a weed map. A weed map should be on file for each field. Make a rough sketch of the field, including landmarks, boundaries, crop row direction, compass directions, roads, planting date, date of map preparation, and any other important details. The following information should be indicated on the map: weed species, weed size, density of each species, and distribution of weeds.<p>Scout fields two to three weeks after direct seeding/transplanting to evaluate the success of the current season's program and at or near harvest to help predict weed control practices that will be necessary for the following year.</p><p><a href='http://nysipm.cornell.edu/scouting/weed_assmt.pdf' target='_blank'>Cornell Weed Assessment list</a><br/><a href='http://www.gov.mb.ca/agriculture/crops/weeds/fab01s00.html' target='_blank'>Manitoba, Canada weed scouting guide</a></p><p>Non-herbicide nightshade management practices include:<ul><li>avoid excessive N fertilization</li><li>dense crop stands will shade out nightshades</li><li>seeds germinate in response to tillage so Cultivated Fallow can be used to manage nightshade</li><li>rogue escapes since nightshades harbor diseases of csolanaceous crops</li></ul> </p><p>If spraying is necessary choose from:<ul><li>Dual Magnum (cabbage only) -  PreT</li><li>Dual Magnum (cabbage only) - PostT</li><li>Dual Magnum (cabbage only)- PostE</li><li>Aim EW - hooded row middle</li></ul></p>"},
'Seedling/transplant':  { 'datelo': (4,15,0), 'datehi': (5,14,23),
                           'status': "Nightshades are germinating from seed.",
                           'management_oc': "",
                           'management_o': "",
                           'management_c': "Scouting - Weeds may be unevenly distributed over a field. Localized areas of severe weed infestations or atypical conditions such as poorly drained areas, high spots, and field edges, may be recorded on a weed map. A weed map should be on file for each field. Make a rough sketch of the field, including landmarks, boundaries, crop row direction, compass directions, roads, planting date, date of map preparation, and any other important details. The following information should be indicated on the map: weed species, weed size, density of each species, and distribution of weeds.<p>Scout fields two to three weeks after direct seeding/transplanting to evaluate the success of the current season's program and at or near harvest to help predict weed control practices that will be necessary for the following year.</p><p><a href='http://nysipm.cornell.edu/scouting/weed_assmt.pdf' target='_blank'>Cornell Weed Assessment list</a><br/><a href='http://www.gov.mb.ca/agriculture/crops/weeds/fab01s00.html' target='_blank'>Manitoba, Canada weed scouting guide</a></p><p>Non-herbicide nightshade management practices include:<ul><li>avoid excessive N fertilization</li><li>dense crop stands will shade out nightshades</li><li>seeds germinate in response to tillage so Cultivated Fallow can be used to manage nightshade</li><li>rogue escapes since nightshades harbor diseases of csolanaceous crops</li></ul> </p><p>If spraying is necessary choose from:<ul><li>Dual Magnum (cabbage only) -  PreT</li><li>Dual Magnum (cabbage only) - PostT</li><li>Dual Magnum (cabbage only)- PostE</li><li>Aim EW - hooded row middle</li></ul></p>"},
'Through mature head': { 'datelo': (5,15,0), 'datehi': (11,14,23),
                           'status': "Nightshades are germinating from seed.",
                           'management_oc': "",
                           'management_o': "",
                           'management_c': "Non-herbicide nightshade management practices include:<ul><li>avoid excessive N fertilization</li><li>dense crop stands will shade out nightshades</li><li>seeds germinate in response to tillage so Cultivated Fallow can be used to manage nightshade</li><li>rogue escapes since nightshades harbor diseases of csolanaceous crops</li></ul>"},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "Nightshades are overwintering as seed in soil.",
                           'management_oc': "",
                           'management_o': "",
                           'management_c': "Non-herbicide nightshade management practices include:<ul><li>avoid excessive N fertilization</li><li>dense crop stands will shade out nightshades</li><li>seeds germinate in response to tillage so Cultivated Fallow can be used to manage nightshade</li><li>rogue escapes since nightshades harbor diseases of csolanaceous crops</li></ul>"}
} }