pest_status_management = { 
'pest_name': "Flea Beetle",
'time_concern': ["Pre plant","Cotyledon through mature head","Post harvest"],
'keychar_oc': "<i>Phyllotreta striolata</i> and <i>P. cruciferae</i><p><b>Key Characteristics: </b>",
'keychar_o':  "Flea beetles are shiny, black, about 1/16 inch long, and jump when disturbed. Flea beetles overwinter as adults in brassica and non-brassica leaf litter and vegetation. Being excellent fliers, they can infest fields quickly from vegetation surrounding fields. In brassicas, the most common flea beetles are <i>P. cruciferae,</i> which feeds only on brassicas, and <i>P. striolata</i> which has a wider host range.  Eggs are laid in the soil near the plants. A second generation of adults emerges in late July or early August. </p> <p><b>Relative risk:</b> Flea beetles are a consistent annual problem for organic growers in the early spring and again in the fall. Beetles can damage the cosmetic quality and, with high populations, can stunt or kill small plants by chewing holes in the leaves especially during cool springs when plants cannot outgrow damage.</p>",
'keychar_c':  "Flea beetles are shiny and black, about 1/16 inch long, and jump when disturbed; they chew tiny holes in foliage.</p> <p><b>Relative risk:</b> Flea beetles are a consistent annual problem for organic growers in the early spring and again in the fall. Beetles can damage the cosmetic quality and, with high populations, can stunt or kill small plants by chewing holes in the leaves especially during cool springs when plants cannot outgrow damage.</p>",
'help_links': [],
'messages': {
'Pre plant':             { 'datelo': (1,1,0), 'datehi': (4,14,23),
                           'status': "<i>TPhyllotreta striolata</i> and <i>P. cruciferae </i>are overwintering as adults in brassica and non-brassica leaf litter and vegetation.",
                           'management_oc': "",                          
                           'management_o': "Resistant varieites - While no resistant varieties are available, varieties with shiny, dark green foliage are generally more attractive to flea beetle. <p>Exclusion - Spunbonded row covers can control flea beetles during the early seedling stage. Install row cover immediately after planting, and seal the edges to keep flea beetles out. This method is only effective in fields where brassicas were not recently grown since row covers can act to trap emerging flies from the previous crop. Yields may be reduced in cole crops grown under row covers.</p> <p>Site Selection - Rotate to a non-cole crop after harvest to reduce the buildup of damaging flea beetle populations. Hedgerows and woods can harbor overwintering flea beetles in fields with a history of infestation.</p> <p>Planting - Waiting until early July to plant brassicas will help break the reproductive cycle and avoid the heavy early season flea beetle activity allowing young plants to outgrow the damage.</p> <p>Trap cropping and trapping - Surrounding cole crop fields with Chinese giant mustard or glossy leaf collards, one to 2 weeks before planting, may help reduce migration into the field. It may be necessary to treat the trap crop to prevent movement of flea beetles to the cash crop.</p> <p>Mulching - Mulching with straw or other organic mulch appears to reduce flea beetle incidence. </p>",
                           'management_c': "Resistant varieties - No resistant varieties are available. &quot;Glossy&quot; varieties are generally much more attractive to the flea beetle. <p>Exclusion - Spunbonded row covers can control flea beetles. At time of sighting, place in the field and seal the edges to keep flea beetles out. The yields of late plantings may be reduced by row covers.</p>"},
'Cotyledon through mature head': { 'datelo': (4,15,0), 'datehi': (11,14,23),
                           'status': "<i>Phyllotreta striolata</i> and <i>P. cruciferae </i>adults invade fields and chew tiny holes in leaves.",
                           'management_oc': "",
                           'management_o': "Scouting - Scout fields at least weekly in the early season especially on direct-seeded fields. Flea beetles are most active in sunny weather. Reinfestations can occur rapidly. Treatment of cabbage is not usually necessary between six leaves and early headfill unless beetles begin to chew on heads bound for fresh market. Thresholds are not established for organic production. <p>If spraying is necessary choose from: Aza-Direct, AzaGuard, Azahar, AzaMax, Neemix 4.5, PyGanic EC 5.0, Entrust, Garlic Barrier, Glacial Spray Fluid, Golden Pest Spray Oil, Surround WP.</p> <p>Natural enemies - The effect of most natural enemies is not well known. Microcotonus vittage Muesebeck, a native braconid wasp, parasitizes and kills the adult flea beetle. Commercially available entomopathogenic nematodes have shown promise in reducing flea beetle larvae in some cases. See sources of commercial producers.</p> <ul><li><a href='http://www.biocontrol.entomology.cornell.edu/index.php' target='_blank'>More information on these natural enemies</a></ul>",
                           'management_c': "Scouting - Scout fields two to three times per week, especially during warm, sunny weather when beetles are most active. Thresholds: one beetle per plant at cotyledon or seedling stage since larger populations may kill or stunt plants. Systemic insecticides (e.g. imidacloprid and chlorantraniliprole) can provide longer term control against damage, although beetles may be present when scouting. With foliar sprays, even if good control was achieved, reinfestations can occur rapidly and require additional sprays. No treatment is usually necessary between six leaves and early headfill unless a flush of beetles begin to chew on the cabbage head bound for fresh market. <p>If spraying is necessary choose from: *Baythroid XL, *Brigade 2EC, *Hero, Sevin XLR Plus, *&#10013;Voliam Xpress, *Thionex 3 EC, *Leverage 2.7, *Warrior II with Zeon Technology, *Mustang MAX.</p> <p>Insecticide resistance management - A classification of insecticides based on their mode of action is available in pdf format. This guide can be used to help avoid or delay the development of insecticide resistance, as well as manage populations that have developed resistance to a particular insecticide. <br /> <ul><li><a href='http://nysipm.cornell.edu/publications/res_mgmt/files/res_mgmt.pdf' target='_blank'>Classification of insecticides and acaracides for resistance management</a></li></ul></p> <p>Natural Enemies - The species and effect of natural enemies are not known.</p><ul><li><a href='http://www.biocontrol.entomology.cornell.edu/index.php' target='_blank'>More information on these natural enemies</a><li><a href='http://nativeplants.msu.edu/' target='_blank'>Enhancing Beneficial Insects with Native Plants (Michigan State)</a><li><a href='http://www.attra.org/attra-pub/farmscape.html' target='_blank'>Farmscaping to enhance biological control (ATTRA publication)</a></ul>"},
'Post harvest':          { 'datelo': (11,15,0), 'datehi': (12,31,23),
                           'status': "<i>Phyllotreta striolata</i> and <i>P. cruciferae </i>are overwintering as adults in brassica and non-brassica leaf litter and vegetation.",
                           'management_oc': "",
                           'management_o': "Postharvest - Crop debris should be destroyed as soon as possible after harvest to kill larvae feeding on roots.",
                           'management_c': "No management recommendations."}
} }